Repository msupply-foundation/open-msupply, pull requests merged in 2022-09, with the labels that each got.

#547 469 fix query params
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Encounter/ListView/ListView.tsx
  client/packages/system/src/Encounter/api/api.ts
  client/packages/system/src/Encounter/api/operations.generated.ts
  client/packages/system/src/Encounter/api/operations.graphql
  client/packages/system/src/Patient/Encounter/ListView.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
  client/packages/system/src/Patient/api/api.ts
  client/packages/system/src/Patient/api/hooks/document/useEncounters.ts
  client/packages/system/src/Patient/api/hooks/document/useProgramEnrolments.ts
  client/packages/system/src/Patient/api/hooks/utils/usePatientApi.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  server/graphql/document/src/queries/patient.rs
  server/repository/src/db_diesel/name.rs
  server/service/src/document/patient/query.rs
Labels: front-end

#531 523 remove site id from sync settings input/mutations
  client/packages/common/src/types/schema.ts
  client/packages/host/src/Admin/SyncSettings.tsx
  client/packages/host/src/api/operations.generated.ts
  client/packages/host/src/api/operations.graphql
  client/packages/host/src/components/Initialise/Initialise.tsx
  client/packages/host/src/components/Initialise/InitialiseLayout.tsx
  client/packages/host/src/components/Initialise/InitialiseNumericInput.tsx
  client/packages/host/src/components/Initialise/hooks.ts
  server/configuration/example.yaml
  server/graphql/general/src/mutations/server_settings.rs
  server/graphql/general/src/queries/server_settings.rs
  server/graphql/tests/permissions.rs
  server/schema.graphql
  server/service/src/settings_service.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/test/integration/central_server_configurations.rs
Labels: front-end, back-end, sync v5

#556 487 array layout
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Array.tsx
  client/packages/common/src/ui/forms/JsonForms/components/CategorizationTabLayout.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Group.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Number.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Patient/JsonForms/components/EncounterLineChart.tsx
  server/service/src/sync/program_schemas/hiv_care_encounter.json
  server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Labels: front-end

#564 Make use of user permissions
  client/packages/common/src/authentication/AuthContext.tsx
  client/packages/common/src/authentication/api/api.ts
  client/packages/common/src/authentication/api/hooks/useUserDetails.ts
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.graphql
  client/packages/common/src/authentication/hooks/index.ts
  client/packages/common/src/authentication/hooks/usePermissionCheck.ts
  client/packages/common/src/authentication/index.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
  client/packages/host/src/Admin/Settings.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/components/AuthenticationAlert.tsx
  client/packages/host/src/components/Footer/StoreSelector.tsx
Labels: front-end

#568 Layout fixes
  client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
  client/packages/common/src/ui/forms/JsonForms/components/Array.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Boolean.tsx
  client/packages/common/src/ui/forms/JsonForms/components/CategorizationTabLayout.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Number.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Select.tsx
  client/packages/common/src/ui/forms/JsonForms/styleConstants.ts
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Patient/JsonForms/components/EncounterLineChart.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
  server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
  server/service/src/sync/program_schemas/hiv_testing_encounter_ui_schema.json
Labels: front-end

#573 Use correct keys as used in other api
  client/packages/system/src/Patient/api/hooks/utils/usePatientApi.ts
Labels: front-end

#546 #22 OmSupply windows installers
  build/omsupply_license_and_warranty.txt
  build/windows/adjustSUFs.js
  build/windows/installers-build.bat
  build/windows/omsupply-build.bat
  build/windows/omsupply-desktop-build.bat
  build/windows/omsupply-postgres-build.bat
  build/windows/omsupply-prepare.bat
  build/windows/omsupply-sqlite-build.bat
  build/windows/omsupply_desktop_server.suf
  build/windows/omsupply_desktop_server_upgrader.suf
  build/windows/omsupply_server.suf
  build/windows/omsupply_server_upgrader.suf
  server/Cargo.lock
  server/server/Cargo.toml
  server/server/omSupply.ico
  server/server/src/set_icon.rs
Labels: enhancement

#577 554 sync log
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/general/src/queries/sync_status.rs
  server/graphql/lib.rs
  server/repository/migrations/postgres/2022-08-31-235556_sync_log/down.sql
  server/repository/migrations/postgres/2022-08-31-235556_sync_log/up.sql
  server/repository/migrations/sqlite/2022-08-31-235605_sync_log/down.sql
  server/repository/migrations/sqlite/2022-08-31-235605_sync_log/up.sql
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/sync_log.rs
  server/repository/src/db_diesel/sync_log_row.rs
  server/service/src/service_provider.rs
  server/service/src/sync/central_data_synchroniser.rs
  server/service/src/sync/mod.rs
  server/service/src/sync/remote_data_synchroniser.rs
  server/service/src/sync/sync_status.rs
  server/service/src/sync/synchroniser.rs
Labels: back-end

#538 523 relocate query to get site id before going out of bootstrap mode
  client/packages/common/src/intl/locales/en/app.json
  client/packages/host/src/components/Initialise/hooks.ts
  server/Cargo.lock
  server/graphql/general/src/lib.rs
  server/graphql/general/src/mutations/server_settings.rs
  server/server/src/lib.rs
  server/service/Cargo.toml
  server/service/src/service_provider.rs
  server/service/src/sync/api/core.rs
  server/service/src/sync/api/error.rs
  server/service/src/sync/api/get_site_info.rs
  server/service/src/sync/api/mod.rs
  server/service/src/sync/mod.rs
  server/service/src/sync/remote_data_synchroniser.rs
  server/service/src/sync/site_info.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/test/integration/central_server_configurations.rs
Labels: front-end, back-end, sync v5

#600 Add confirmation alert for react router navigation
  client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
  client/packages/host/webpack.config.js
Labels: front-end

#616 613 fix request requistion inbound shipment link in transfers
  server/service/src/processors/transfer/mod.rs
  server/service/src/processors/transfer/requisition/mod.rs
  server/service/src/processors/transfer/shipment/create_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/link_outbound_shipment.rs
  server/service/src/processors/transfer/shipment/mod.rs
  server/service/src/processors/transfer/shipment/test.rs
  server/service/src/processors/transfer/shipment/update_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/update_outbound_shipment_status.rs
Labels: sync v5

#617 Processor driver to preserve order of processors
  server/service/src/processors/mod.rs
Labels: sync v5

#618 615 add concurrency tests to transfer tests
  server/Cargo.lock
  server/repository/src/mock/mod.rs
  server/repository/src/test_db.rs
  server/service/Cargo.toml
  server/service/src/processors/test_helpers.rs
  server/service/src/processors/transfer/requisition/test.rs
  server/service/src/processors/transfer/shipment/test.rs
  server/service/src/sync/test/integration/transfer/requisition.rs
  server/service/src/sync/test/integration/transfer/shipments.rs
  server/service/src/sync/test/mod.rs
  server/service/src/test_helpers.rs
Labels: sync v5

#621 Dynamic permission schema change + renaming in FE
  client/packages/common/src/authentication/AuthContext.tsx
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/hooks/usePermissionCheck.ts
  client/packages/common/src/types/schema.ts
  client/packages/host/src/Admin/Settings.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
Labels: front-end

#609 #593 dynamic permission table
  client/packages/common/src/authentication/AuthContext.tsx
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/hooks/usePermissionCheck.ts
  client/packages/common/src/types/schema.ts
  client/packages/host/src/Admin/Settings.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  server/graphql/types/src/types/permissions.rs
  server/repository/migrations/postgres/2022-03-25T14-30_create_user_permission_table/up.sql
  server/repository/migrations/sqlite/2022-03-25T14-30_create_user_permission_table/up.sql
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/mock/user_account.rs
  server/service/src/auth.rs
  server/service/src/login.rs
  server/service/src/user_account.rs
Labels: programs, back-end

#602 548 encounter list view
  client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
  client/packages/system/src/Encounter/DetailView/Footer.tsx
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
  client/packages/system/src/Encounter/ListView/ListView.tsx
  client/packages/system/src/Encounter/ListView/columns.ts
  client/packages/system/src/Encounter/index.ts
  client/packages/system/src/Encounter/utils.ts
  client/packages/system/src/Patient/Encounter/ListView.tsx
Labels: programs, front-end

#626 Create demo program patients
  server/service/src/sync/init_programs_data.rs
Labels: programs

#647 Fraction number of packs fe
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeDecimalCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PostiveNumberCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/index.ts
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
Labels: front-end

#605 604 tests for sync status
  server/Cargo.lock
  server/cli/src/refresh_dates.rs
  server/configuration/example.yaml
  server/graphql/general/src/mutations/server_settings.rs
  server/graphql/general/src/queries/sync_status.rs
  server/repository/migrations/postgres/2022-08-31-235556_sync_log/up.sql
  server/repository/migrations/sqlite/2022-08-31-235605_sync_log/up.sql
  server/repository/src/db_diesel/changelog/test.rs
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/db_diesel/location_row.rs
  server/repository/src/db_diesel/sync_log.rs
  server/repository/src/db_diesel/sync_log_row.rs
  server/server/src/lib.rs
  server/server/src/set_icon.rs
  server/service/Cargo.toml
  server/service/src/invoice/outbound_shipment/update/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/validate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/mod.rs
  server/service/src/service_provider.rs
  server/service/src/settings_service.rs
  server/service/src/sync/actor.rs
  server/service/src/sync/api/common_records.rs
  server/service/src/sync/api/get_central_records.rs
  server/service/src/sync/api/get_site_status.rs
  server/service/src/sync/api/mod.rs
  server/service/src/sync/api/post_queued_records.rs
  server/service/src/sync/central_data_synchroniser.rs
  server/service/src/sync/mod.rs
  server/service/src/sync/remote_data_synchroniser.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/site_info.rs
  server/service/src/sync/sync_status.rs
  server/service/src/sync/sync_status/logger.rs
  server/service/src/sync/sync_status/mod.rs
  server/service/src/sync/sync_status/status.rs
  server/service/src/sync/sync_status/test.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/test/integration/central_server_configurations.rs
  server/service/src/sync/test/integration/errors.rs
  server/service/src/sync/test/integration/mod.rs
  server/service/src/sync/test/test_data/master_list.rs
  server/service/src/sync/test/test_data/master_list_line.rs
  server/service/src/sync/test/test_data/master_list_name_join.rs
  server/service/src/sync/test/test_data/name_store_join.rs
  server/service/src/sync/test/test_data/report.rs
Labels: sync v5
