Repository msupply-foundation/open-msupply, pull requests merged in 2022-11, with the labels that each got.

#752 Add settings to actix server
  server/server/src/lib.rs
Labels: bug

#755 Cache selected language
  client/packages/common/src/intl/context/IntlContext.tsx
  client/packages/common/src/intl/context/browserLanguageDetector.ts
Labels: bug

#771 Use schema examples if there is a pattern error
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
  server/service/src/sync/program_schemas/hiv_care_encounter.json
  server/service/src/sync/program_schemas/patient.json
Labels: programs, v1.01

#769 370 translate restrict reorder enums
  client/packages/common/src/ui/forms/JsonForms/components/Select.tsx
  client/packages/common/src/ui/forms/JsonForms/index.ts
  client/packages/common/src/ui/forms/JsonForms/useZodOptionsValidation.test.ts
  client/packages/common/src/ui/forms/JsonForms/useZodOptionsValidation.ts
  client/packages/system/src/Patient/JsonForms/components/DispensedDuration.tsx
  client/packages/system/src/Patient/JsonForms/components/EncounterLineChart.tsx
  client/packages/system/src/Patient/JsonForms/components/EventTrigger.tsx
  client/packages/system/src/Patient/JsonForms/components/IdGenerator.tsx
  server/graphql/types/src/types/name.rs
  server/repository/migrations/postgres/2021-08-15T10-00_create_name_table/up.sql
  server/repository/migrations/sqlite/2021-08-15T10-00_create_name_table/up.sql
  server/repository/src/db_diesel/name_row.rs
  server/service/src/programs/patient/patient_updated.rs
  server/service/src/programs/schemas/patient.json
  server/service/src/sync/program_schemas/hiv_care_encounter.json
  server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
  server/service/src/sync/program_schemas/hiv_care_program.json
  server/service/src/sync/program_schemas/hiv_care_program_ui_schema.json
  server/service/src/sync/program_schemas/hiv_testing_encounter_ui_schema.json
  server/service/src/sync/program_schemas/hiv_testing_program_ui_schema.json
  server/service/src/sync/program_schemas/patient.json
  server/service/src/sync/program_schemas/patient_ui_schema.json
Labels: front-end

#776 655 patient registration 1
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
  client/packages/host/src/CommandK.tsx
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/program_schemas/patient_ui_schema.json
Labels: programs, v1.01

#763 Changing supplier/customer on shipments can cause strife for sync fe
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/OutboundShipment/api/api.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/document/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/document/useOutboundUpdateName.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/index.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
  server/schema.graphql
Labels: front-end, sync v5

#778 Fix regex utils ( new stocktake :: item search input )
  client/packages/common/src/utils/regex/RegexUtils.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: bug

#761 188 changing supplier/customer on shipments can cause strife for sync
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/OutboundShipment/api/api.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/document/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/document/useOutboundUpdateName.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/index.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
  server/graphql/invoice/src/lib.rs
  server/graphql/invoice/src/mutations/inbound_shipment/delete.rs
  server/graphql/invoice/src/mutations/inbound_shipment/update.rs
  server/graphql/invoice/src/mutations/outbound_shipment/delete.rs
  server/graphql/invoice/src/mutations/outbound_shipment/mod.rs
  server/graphql/invoice/src/mutations/outbound_shipment/update.rs
  server/graphql/invoice/src/mutations/outbound_shipment/update_name.rs
  server/schema.graphql
  server/service/src/invoice/inbound_shipment/add_from_master_list.rs
  server/service/src/invoice/inbound_shipment/delete/mod.rs
  server/service/src/invoice/inbound_shipment/delete/validate.rs
  server/service/src/invoice/inbound_shipment/update/validate.rs
  server/service/src/invoice/mod.rs
  server/service/src/invoice/outbound_shipment/add_from_master_list.rs
  server/service/src/invoice/outbound_shipment/delete/mod.rs
  server/service/src/invoice/outbound_shipment/delete/validate.rs
  server/service/src/invoice/outbound_shipment/mod.rs
  server/service/src/invoice/outbound_shipment/update/generate.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/invoice/outbound_shipment/update/validate.rs
  server/service/src/invoice/outbound_shipment/update_name/generate.rs
  server/service/src/invoice/outbound_shipment/update_name/mod.rs
  server/service/src/invoice/outbound_shipment/update_name/validate.rs
  server/service/src/invoice/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/delete/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/update/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/validate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/delete/validate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/validate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/update/validate.rs
  server/service/src/invoice_line/outbound_shipment_line/delete/validate.rs
  server/service/src/invoice_line/outbound_shipment_line/insert/validate.rs
  server/service/src/invoice_line/outbound_shipment_line/update/validate.rs
  server/service/src/invoice_line/outbound_shipment_line/validate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/delete/validate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/validate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/validate.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/delete.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/update.rs
  server/service/src/invoice_line/validate.rs
Labels: question, back-end, sync v5

#780 Fix Text option type and type validation
  client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
Labels: programs, v1.01

#807 Clear linked invoice id when changing name
  server/service/src/invoice/outbound_shipment/update_name/generate.rs
Labels: bug

#816 #809 Name change invoices don't have log
  server/service/src/invoice/outbound_shipment/update_name/generate.rs
  server/service/src/invoice/outbound_shipment/update_name/mod.rs
Labels: back-end

#819 #810 logging for stock line
  server/graphql/types/src/types/activity_log.rs
  server/repository/migrations/postgres/2022-11-16-021440_update_activity_log_type_v1.0.5/down.sql
  server/repository/migrations/postgres/2022-11-16-021440_update_activity_log_type_v1.0.5/up.sql
  server/repository/src/db_diesel/activity_log_row.rs
  server/service/src/stock_line/update.rs
Labels: back-end

#758 750 dynamic permission followup
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  server/graphql/core/src/loader/document.rs
  server/graphql/core/src/loader/document_registry.rs
  server/graphql/programs/src/mutations/delete_document.rs
  server/graphql/programs/src/mutations/encounter/insert.rs
  server/graphql/programs/src/mutations/encounter/update.rs
  server/graphql/programs/src/mutations/insert_document_registry.rs
  server/graphql/programs/src/mutations/patient/insert.rs
  server/graphql/programs/src/mutations/patient/update.rs
  server/graphql/programs/src/mutations/program_enrolment/insert.rs
  server/graphql/programs/src/mutations/program_enrolment/update.rs
  server/graphql/programs/src/mutations/undelete_document.rs
  server/graphql/programs/src/mutations/update_document.rs
  server/graphql/programs/src/queries/document.rs
  server/graphql/programs/src/queries/document_history.rs
  server/graphql/programs/src/queries/document_registry.rs
  server/graphql/programs/src/queries/encounter.rs
  server/graphql/programs/src/queries/encounter_fields.rs
  server/graphql/programs/src/queries/patient.rs
  server/graphql/programs/src/queries/patient_search.rs
  server/graphql/programs/src/queries/program_enrolment.rs
  server/graphql/programs/src/queries/program_event.rs
  server/graphql/programs/src/types/document.rs
  server/graphql/programs/src/types/document_registry.rs
  server/graphql/programs/src/types/encounter.rs
  server/graphql/programs/src/types/program_enrolment.rs
  server/graphql/types/src/types/permissions.rs
  server/repository/migrations/postgres/2022-03-25T14-30_create_user_permission_table/up.sql
  server/repository/migrations/sqlite/2022-03-25T14-30_create_user_permission_table/up.sql
  server/repository/src/db_diesel/document.rs
  server/repository/src/db_diesel/filter_restriction.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/mock/user_account.rs
  server/service/src/auth.rs
  server/service/src/document/document_registry/insert.rs
  server/service/src/document/document_registry/mod.rs
  server/service/src/document/document_registry/tests/insert.rs
  server/service/src/document/document_service.rs
  server/service/src/document/mod.rs
  server/service/src/login.rs
  server/service/src/programs/encounter/encounter_fields.rs
  server/service/src/programs/encounter/insert.rs
  server/service/src/programs/encounter/mod.rs
  server/service/src/programs/encounter/query.rs
  server/service/src/programs/encounter/update.rs
  server/service/src/programs/patient/update.rs
  server/service/src/programs/program_enrolment/mod.rs
  server/service/src/programs/program_enrolment/query.rs
  server/service/src/programs/program_enrolment/upsert.rs
  server/service/src/sync/init_programs_data.rs
Labels: programs

#826 #822 activity log event field
  server/graphql/types/src/types/activity_log.rs
  server/repository/migrations/postgres/2022-11-17-221434_update_activity_log_v1.0.5/down.sql
  server/repository/migrations/postgres/2022-11-17-221434_update_activity_log_v1.0.5/up.sql
  server/repository/migrations/sqlite/2022-11-17-221441_update_activity_log_v1.0.5/down.sql
  server/repository/migrations/sqlite/2022-11-17-221441_update_activity_log_v1.0.5/up.sql
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/mock/activity_log.rs
  server/repository/src/tests.rs
  server/service/src/activity_log.rs
  server/service/src/invoice/inbound_shipment/delete/mod.rs
  server/service/src/invoice/inbound_shipment/insert/mod.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice/outbound_shipment/delete/mod.rs
  server/service/src/invoice/outbound_shipment/insert/mod.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/login.rs
  server/service/src/requisition/request_requisition/delete.rs
  server/service/src/requisition/request_requisition/insert.rs
  server/service/src/requisition/request_requisition/update/mod.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/mod.rs
  server/service/src/requisition/response_requisition/update.rs
  server/service/src/stock_line/update.rs
  server/service/src/stocktake/delete.rs
  server/service/src/stocktake/insert.rs
  server/service/src/stocktake/update.rs
  server/service/src/sync/test/test_data/activity_log.rs
  server/service/src/sync/translations/activity_log.rs
Labels: back-end

#824 823 program events refactor
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/forms/JsonForms/components/CategorizationTabLayout.tsx
  client/packages/system/src/Encounter/ListView/columns.ts
  client/packages/system/src/Encounter/api/api.ts
  client/packages/system/src/Encounter/api/operations.generated.ts
  client/packages/system/src/Encounter/api/operations.graphql
  client/packages/system/src/Patient/JsonForms/components/DispensedDuration.tsx
  client/packages/system/src/Patient/JsonForms/components/EventTrigger.tsx
  client/packages/system/src/Patient/JsonForms/components/encounter_event.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/api.ts
  client/packages/system/src/Patient/api/api.ts
  client/packages/system/src/Patient/api/hooks/document/useProgramEnrolments.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  server/cli/src/refresh_dates.rs
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/mutations/encounter/insert.rs
  server/graphql/programs/src/queries/program_event.rs
  server/graphql/programs/src/types/encounter.rs
  server/graphql/programs/src/types/program_enrolment.rs
  server/graphql/programs/src/types/program_event.rs
  server/repository/migrations/postgres/2022-06-07T18-00_create_program_event_table/up.sql
  server/repository/migrations/sqlite/2022-06-07T18-00_create_program_event_table/up.sql
  server/repository/src/db_diesel/program_event.rs
  server/repository/src/db_diesel/program_event_row.rs
  server/schema.graphql
  server/service/src/programs/ProgramEvents.md
  server/service/src/programs/Programs.md
  server/service/src/programs/encounter/encounter_updated.rs
  server/service/src/programs/encounter/insert.rs
  server/service/src/programs/encounter/update.rs
  server/service/src/programs/program_event.rs
  server/service/src/programs/schemas/encounter.json
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/program_schemas/hiv_care_encounter.json
  server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
  server/service/src/sync/program_schemas/hiv_testing_encounter.json
Labels: programs

#829 655 conditional text input
  client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Autocomplete.tsx
  client/packages/common/src/ui/forms/JsonForms/components/ConditionalSelect.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
  client/packages/common/src/ui/forms/JsonForms/components/index.ts
  client/packages/system/src/Patient/JsonForms/useJsonForms.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  server/service/src/sync/program_schemas/patient_ui_schema.json
Labels: programs, v1.01

#869 Fix infinity bug for bmi
  client/packages/system/src/Patient/JsonForms/components/BMI.tsx
Labels: programs

#853 #779 Document owner:group (permissions)
  server/graphql/programs/src/mutations/update_document.rs
  server/graphql/programs/src/queries/document.rs
  server/repository/migrations/postgres/2022-04-27T13-00_create_document_table/up.sql
  server/repository/migrations/sqlite/2022-04-27T13-00_create_document_table/up.sql
  server/repository/src/db_diesel/document.rs
  server/repository/src/mock/document.rs
  server/service/src/document/document_service.rs
  server/service/src/document/raw_document.rs
  server/service/src/programs/encounter/insert.rs
  server/service/src/programs/encounter/update.rs
  server/service/src/programs/patient/update.rs
  server/service/src/programs/program_enrolment/program_enrolment_updated.rs
  server/service/src/programs/program_enrolment/upsert.rs
Labels: programs

#839 #644(1) HIV Care and treatment enrolment updates
  .gitignore
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/program_schemas/hiv_care_program.json
  server/service/src/sync/program_schemas/hiv_care_program_ui_schema.json
  server/service/src/sync/program_schemas/patient.json
  server/service/src/sync/program_schemas/patient_ui_schema.json
Labels: programs
