Repository msupply-foundation/open-msupply, pull requests merged in 2022-06, with the labels that each got.

#59 51 patients query
  server/Cargo.lock
  server/graphql/core/src/loader/document.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/document/Cargo.toml
  server/graphql/document/src/lib.rs
  server/graphql/document/src/mutations/mod.rs
  server/graphql/document/src/mutations/patient/insert.rs
  server/graphql/document/src/mutations/patient/mod.rs
  server/graphql/document/src/mutations/update_document.rs
  server/graphql/document/src/queries/mod.rs
  server/graphql/document/src/queries/patient.rs
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/names.rs
  server/graphql/general/src/queries/tests/names.rs
  server/graphql/types/src/types/name.rs
  server/repository/migrations/postgres/2022-03-25T14-30_create_user_permission_table/up.sql
  server/repository/migrations/sqlite/2022-03-25T14-30_create_user_permission_table/up.sql
  server/repository/src/db_diesel/document.rs
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/db_diesel/name.rs
  server/repository/src/db_diesel/name_row.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/service/src/auth.rs
  server/service/src/document/document_service.rs
  server/service/src/document/mod.rs
  server/service/src/document/patient/insert.rs
  server/service/src/document/patient/mod.rs
  server/service/src/document/patient/patient_document_update.rs
  server/service/src/document/patient/patient_schema.rs
  server/service/src/document/patient/query.rs
  server/service/src/document/raw_document.rs
  server/service/src/document/update_trigger.rs
  server/service/src/lib.rs
  server/service/src/login.rs
Labels: programs, back-end

#55 54 export and import initialisation
  server/Cargo.lock
  server/Cargo.toml
  server/README.md
  server/cli/Cargo.toml
  server/cli/src/cli.rs
  server/cli/src/lib.rs
  server/cli/src/refresh_dates.rs
  server/data/reference1/export.json
  server/data/reference1/users.txt
  server/demo/src/main.rs
  server/graphql/Cargo.toml
  server/graphql/batch_mutations/Cargo.toml
  server/graphql/core/Cargo.toml
  server/graphql/general/Cargo.toml
  server/graphql/general/src/mutations/server_settings.rs
  server/graphql/general/src/queries/login.rs
  server/graphql/general/src/queries/server_settings.rs
  server/graphql/invoice/Cargo.toml
  server/graphql/invoice_line/Cargo.toml
  server/graphql/location/Cargo.toml
  server/graphql/reports/Cargo.toml
  server/graphql/requisition/Cargo.toml
  server/graphql/requisition_line/Cargo.toml
  server/graphql/stocktake/Cargo.toml
  server/graphql/stocktake_line/Cargo.toml
  server/graphql/types/Cargo.toml
  server/repository/migrations/postgres/2022-02-11T15-00_create_key_value_store/up.sql
  server/repository/src/db_diesel/key_value_store.rs
  server/server/Cargo.toml
  server/server/src/cli.rs
  server/server/src/lib.rs
  server/server/src/sync/actor.rs
  server/server/src/sync/central_data_synchroniser.rs
  server/server/src/sync/integration_tests/remote_sync_integration_test.rs
  server/server/src/sync/mod.rs
  server/server/src/sync/remote_data_synchroniser.rs
  server/server/src/sync/sync_api_v5.rs
  server/server/src/sync/synchroniser.rs
  server/service/Cargo.toml
  server/service/src/apis/login_v4.rs
  server/service/src/login.rs
  server/service/src/service_provider.rs
  server/service/src/settings_service.rs
  server/service/src/sync_settings.rs
  server/service/src/user_account.rs
Labels: back-end

#93 Improve logging when unable to connect to database
  server/server/src/sync/central_data_synchroniser.rs
Labels: back-end

#108 Fix stock filter
  .gitignore
  .vscode/launch.json.example
  client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts
  client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
  client/packages/common/src/utils/regex/RegexUtils.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: bug

#106 Android printing
  client/packages/android/app/src/main/java/org/openmsupply/client/MainActivity.java
  client/packages/android/app/src/main/java/org/openmsupply/client/RemoteServer.java
  client/packages/common/src/intl/context/IntlContext.tsx
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/system/src/Report/api/api.ts
  client/packages/system/src/Report/api/hooks/utils/usePrintReport.ts
  client/packages/system/src/Report/api/operations.generated.ts
  client/packages/system/src/Report/api/operations.graphql
  server/android/src/android.rs
  server/cli/src/cli.rs
  server/graphql/reports/src/lib.rs
  server/graphql/reports/src/printing.rs
  server/schema.graphql
  server/server/src/sync/sync_api_v5.rs
  server/server/src/sync/synchroniser.rs
  server/service/Cargo.toml
  server/service/src/report/report_service.rs
  server/service/src/settings_service.rs
Labels: front-end, back-end

#105 #101 Patients to use "patient" API
  client/codegen.yml
  client/package.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Patient/DetailModal/DetailModal.tsx
  client/packages/system/src/Patient/api/api.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  server/schema.graphql
Labels: front-end

#115 Postgres compilation
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/document.rs
  server/repository/src/db_diesel/json_schema.rs
Labels: bug, programs, back-end

#110 #109 Separate errors for Timeout and Unauthenticated
  client/packages/common/src/authentication/AuthContext.tsx
  client/packages/common/src/intl/locales/en/app.json
  client/packages/host/src/components/AuthenticationAlert.tsx
Labels: bug, front-end

#133 Add reference support to the report builder
  server/report_builder/README.md
  server/report_builder/src/build.rs
Labels: back-end, [report printing]

#135 #132 Remove invoice id from line mutations
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/hooks/line/useDeleteInboundLines.ts
  client/packages/invoices/src/OutboundShipment/api/api.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/line/useOutboundDeleteLines.ts
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/delete.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/delete.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/delete.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/delete.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/update.rs
  server/graphql/tests/permissions.rs
  server/schema.graphql
  server/service/src/invoice/inbound_shipment/delete/mod.rs
  server/service/src/invoice/outbound_shipment/delete/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/delete/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/delete/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/update/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/update/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/update/validate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/delete/mod.rs
  server/service/src/invoice_line/inbound_shipment_service_line/delete/validate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/update/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/update/mod.rs
  server/service/src/invoice_line/inbound_shipment_service_line/update/validate.rs
  server/service/src/invoice_line/outbound_shipment_line/delete/mod.rs
  server/service/src/invoice_line/outbound_shipment_line/delete/validate.rs
  server/service/src/invoice_line/outbound_shipment_line/update/mod.rs
  server/service/src/invoice_line/outbound_shipment_line/update/validate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/delete/mod.rs
  server/service/src/invoice_line/outbound_shipment_service_line/delete/validate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/mod.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/validate.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/allocate/generate.rs
Labels: front-end, back-end

#169 Add to shipment from master list (f/e)
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/common/src/intl/locales/fr/replenishment.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/DetailView/AddFromMasterListButton.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/OutboundShipment/api/api.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/useAddFromMasterList.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
  server/service/src/invoice/outbound_shipment/add_from_master_list.rs
Labels: front-end

#178 177 number table sync adjustments
  server/README.md
  server/server/src/sync/integration_tests/mod.rs
  server/server/src/sync/integration_tests/name.rs
  server/server/src/sync/integration_tests/remote_sync_integration_test.rs
  server/server/src/sync/remote_data_synchroniser.rs
  server/server/src/sync/translation_remote/number.rs
  server/server/src/sync/translation_remote/test_data/number.rs
Labels: front-end, back-end

#184 136 patients endpoint
  server/graphql/core/src/loader/document.rs
  server/graphql/core/src/loader/document_registry.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/document/src/lib.rs
  server/graphql/document/src/mutations/patient/insert.rs
  server/graphql/document/src/mutations/patient/update.rs
  server/graphql/document/src/queries/document.rs
  server/graphql/document/src/queries/patient.rs
  server/graphql/document/src/types/document.rs
  server/graphql/document/src/types/encounter.rs
  server/graphql/document/src/types/mod.rs
  server/graphql/document/src/types/program.rs
  server/repository/src/db_diesel/document.rs
  server/repository/src/db_diesel/filter_sort_pagination.rs
  server/repository/src/diesel_macros.rs
  server/service/src/document/document_registry/mod.rs
  server/service/src/document/patient/mod.rs
  server/service/src/document/patient/query.rs
  server/service/src/document/patient/update.rs
Labels: programs, back-end

#212 Fix patients total count
  server/graphql/document/src/queries/patient.rs
  server/service/src/document/patient/mod.rs
  server/service/src/document/patient/patient_document_update.rs
  server/service/src/document/patient/query.rs
  server/service/src/document/patient/update.rs
Labels: bug, back-end

#187 #155 basic logging
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/log.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/general/src/queries/tests/logs.rs
  server/graphql/general/src/queries/tests/mod.rs
  server/graphql/types/src/types/log.rs
  server/graphql/types/src/types/mod.rs
  server/repository/migrations/postgres/2022-03-25T14-30_create_user_permission_table/up.sql
  server/repository/migrations/postgres/2022-06-21-013225_create_log_table/down.sql
  server/repository/migrations/postgres/2022-06-21-013225_create_log_table/up.sql
  server/repository/migrations/sqlite/2022-03-25T14-30_create_user_permission_table/up.sql
  server/repository/migrations/sqlite/2022-06-21-013232_create_log_table/down.sql
  server/repository/migrations/sqlite/2022-06-21-013232_create_log_table/up.sql
  server/repository/src/db_diesel/log.rs
  server/repository/src/db_diesel/log_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/mock/log.rs
  server/repository/src/mock/mod.rs
  server/repository/src/tests.rs
  server/service/src/auth.rs
  server/service/src/invoice/inbound_shipment/delete/mod.rs
  server/service/src/invoice/inbound_shipment/insert/mod.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice/outbound_shipment/insert/mod.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/lib.rs
  server/service/src/log.rs
  server/service/src/login.rs
Labels: back-end

#194 171 default program data
  server/graphql/document/src/mutations/patient/insert.rs
  server/graphql/document/src/mutations/patient/update.rs
  server/repository/src/mock/form_schema.rs
  server/repository/src/mock/mod.rs
  server/server/src/sync/init_programs_data.rs
  server/server/src/sync/mod.rs
  server/server/src/sync/synchroniser.rs
  server/service/src/document/document_service.rs
  server/service/src/document/patient/update.rs
Labels: programs, back-end
