Repository msupply-foundation/open-msupply, pull requests merged in 2022-10, with the labels that each got.

#685 656 manual sync
  client/packages/common/src/intl/locales/en/common.json
  client/packages/host/src/Site.tsx
  client/packages/host/src/api/api.ts
  client/packages/host/src/api/hooks/index.ts
  client/packages/host/src/api/hooks/utils/index.ts
  client/packages/host/src/api/hooks/utils/useHostApi.ts
  client/packages/host/src/api/hooks/utils/useSyncInfo.ts
  client/packages/host/src/api/operations.generated.ts
  client/packages/host/src/api/operations.graphql
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/components/Sync/Sync.tsx
  client/packages/host/src/components/Sync/index.tsx
  client/packages/host/src/components/SyncProgress/SyncProgress.tsx
Labels: front-end, sync v5, v1.01

#687 Support custom errors, update the format of some physical exam elements
  client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/program_schemas/hiv_care_encounter.json
  server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Labels: programs, v1.01

#689 Body Mass Index calculation
  client/packages/host/public/medical-icons.css
  client/packages/system/src/Patient/JsonForms/components/BMI.tsx
  client/packages/system/src/Patient/JsonForms/useJsonForms.tsx
  server/service/src/sync/program_schemas/hiv_care_encounter.json
  server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Labels: programs, v1.01

#690 update layout
  client/packages/common/src/ui/forms/JsonForms/components/CategorizationTabLayout.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Group.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Label.tsx
  client/packages/system/src/Patient/JsonForms/components/EncounterLineChart.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
  server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Labels: programs, v1.01

#693 Rename log
  client/codegen.yml
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Log/Components/ListView.tsx
  client/packages/system/src/Log/api/api.ts
  client/packages/system/src/Log/api/hooks/document/useLogsByRecord.ts
  client/packages/system/src/Log/api/hooks/utils/useLogApi.ts
  client/packages/system/src/Log/api/index.ts
  client/packages/system/src/Log/api/operations.generated.ts
  client/packages/system/src/Log/api/operations.graphql
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/activity_log.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/general/src/queries/tests/activity_log.rs
  server/graphql/general/src/queries/tests/mod.rs
  server/graphql/types/src/types/activity_log.rs
  server/graphql/types/src/types/log.rs
  server/graphql/types/src/types/mod.rs
  server/repository/migrations/postgres/2022-06-21-013225_create_log_table/down.sql
  server/repository/migrations/postgres/2022-06-21-013225_create_log_table/up.sql
  server/repository/migrations/sqlite/2022-06-21-013232_create_log_table/down.sql
  server/repository/migrations/sqlite/2022-06-21-013232_create_log_table/up.sql
  server/repository/src/db_diesel/activity_log.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/log.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/mock/activity_log.rs
  server/repository/src/mock/mod.rs
  server/repository/src/tests.rs
  server/schema.graphql
  server/service/src/activity_log.rs
  server/service/src/invoice/inbound_shipment/delete/mod.rs
  server/service/src/invoice/inbound_shipment/insert/mod.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice/outbound_shipment/delete/mod.rs
  server/service/src/invoice/outbound_shipment/insert/mod.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/lib.rs
  server/service/src/login.rs
  server/service/src/processors/transfer/requisition/create_response_requisition.rs
  server/service/src/processors/transfer/requisition/update_request_requisition_status.rs
  server/service/src/processors/transfer/shipment/create_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/delete_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/update_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/update_outbound_shipment_status.rs
  server/service/src/requisition/request_requisition/delete.rs
  server/service/src/requisition/request_requisition/insert.rs
  server/service/src/requisition/request_requisition/update/mod.rs
  server/service/src/requisition/request_requisition/update/test.rs
  server/service/src/requisition/response_requisition/update.rs
  server/service/src/stocktake/delete.rs
  server/service/src/stocktake/insert.rs
  server/service/src/stocktake/update.rs
Labels: front-end, back-end

#707 Store display settings in db
  client/packages/common/src/localStorage/keys.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/TextInput/PasswordTextInput.tsx
  client/packages/host/src/Admin/Settings.tsx
  client/packages/host/src/Admin/SyncSettings.tsx
  client/packages/host/src/api/api.ts
  client/packages/host/src/api/hooks/index.ts
  client/packages/host/src/api/hooks/settings/index.ts
  client/packages/host/src/api/hooks/settings/useDisplaySettings.ts
  client/packages/host/src/api/hooks/settings/useSyncSettings.ts
  client/packages/host/src/api/hooks/settings/useUpdateDisplaySettings.ts
  client/packages/host/src/api/hooks/utils/index.ts
  client/packages/host/src/api/hooks/utils/useHostApi.ts
  client/packages/host/src/api/operations.generated.ts
  client/packages/host/src/api/operations.graphql
  client/packages/host/src/components/Initialise/hooks.ts
  client/packages/host/src/components/Login/Login.tsx
  client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  server/graphql/general/src/lib.rs
  server/graphql/general/src/mutations/display_settings.rs
  server/graphql/general/src/mutations/mod.rs
  server/graphql/general/src/queries/display_settings.rs
  server/graphql/general/src/queries/mod.rs
  server/repository/migrations/postgres/2022-02-11T15-00_create_key_value_store/up.sql
  server/repository/migrations/postgres/2022-10-11T100-22_v102/down.sql
  server/repository/migrations/postgres/2022-10-11T100-22_v102/up.sql
  server/repository/src/db_diesel/key_value_store.rs
  server/schema.graphql
  server/server/src/lib.rs
  server/service/src/display_settings_service.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
  server/service/src/settings.rs
Labels: v1.01

#695 661 sync logs
  server/graphql/general/src/queries/tests/activity_log.rs
  server/repository/migrations/postgres/2022-01-27T08-00_create_changelog_table/up.sql
  server/repository/migrations/postgres/2022-06-21-013225_create_activity_log_table/down.sql
  server/repository/migrations/postgres/2022-06-21-013225_create_activity_log_table/up.sql
  server/repository/migrations/postgres/2022-10-10-220020_activity_log_trigger/down.sql
  server/repository/migrations/postgres/2022-10-10-220020_activity_log_trigger/up.sql
  server/repository/migrations/sqlite/2022-06-21-013232_create_activity_log_table/down.sql
  server/repository/migrations/sqlite/2022-06-21-013232_create_activity_log_table/up.sql
  server/repository/migrations/sqlite/2022-10-10-220028_activity_log_trigger/down.sql
  server/repository/migrations/sqlite/2022-10-10-220028_activity_log_trigger/up.sql
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/mock/activity_log.rs
  server/service/src/sync/sync_buffer.rs
  server/service/src/sync/test/integration/remote/activity_log.rs
  server/service/src/sync/test/integration/remote/mod.rs
  server/service/src/sync/test/integration/remote/test.rs
  server/service/src/sync/test/mod.rs
  server/service/src/sync/test/pull_and_push.rs
  server/service/src/sync/test/test_data/activity_log.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translation_and_integration.rs
  server/service/src/sync/translations/activity_log.rs
  server/service/src/sync/translations/mod.rs
Labels: back-end, sync v5, v1.01

#711 708 consistent dashboard button navigation
  client/packages/dashboard/src/widgets/StockWidget.tsx
  client/packages/invoices/src/InboundShipment/Dashboard/Widget.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/document/useInsertInbound.ts
  client/packages/invoices/src/OutboundShipment/Dashboard/Widget.tsx
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useInsertRequest.ts
Labels: front-end

#719 712 issues with requisitions part 01
  client/packages/common/src/intl/locales/en/common.json
  client/packages/requisitions/src/RequestRequisition/DetailView/ContentArea.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/requisitions/src/types.ts
  client/packages/requisitions/src/utils.ts
  server/service/src/requisition/request_requisition/generate.rs
  server/service/src/requisition/request_requisition/update/generate.rs
  server/service/src/requisition/request_requisition/update/mod.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/mod.rs
Labels: bug, front-end, back-end

#727 Check date validity
  client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx
Labels: programs, v1.01

#728 Create patient modal
  client/packages/common/src/intl/locales/en/patients.json
  client/packages/common/src/ui/components/steppers/HorizontalStepper/HorizontalStepper.tsx
  client/packages/common/src/ui/components/steppers/WizardStepper/WizardStepper.tsx
  client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
  client/packages/system/src/Patient/CreatePatientModal/PatientPanel.tsx
  client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
Labels: programs, v1.01
