Repository msupply-foundation/open-msupply, pull requests merged in 2022-07, with the labels that each got.

#213 #193 stocktake and requisition logging
  server/graphql/general/src/queries/log.rs
  server/graphql/requisition/src/mutations/request_requisition/update.rs
  server/graphql/types/src/types/log.rs
  server/repository/migrations/postgres/2022-06-21-013225_create_log_table/up.sql
  server/repository/migrations/sqlite/2022-06-21-013232_create_log_table/up.sql
  server/repository/src/db_diesel/log.rs
  server/repository/src/db_diesel/log_row.rs
  server/repository/src/mock/log.rs
  server/repository/src/tests.rs
  server/service/src/invoice/inbound_shipment/delete/mod.rs
  server/service/src/invoice/inbound_shipment/insert/mod.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice/outbound_shipment/delete/mod.rs
  server/service/src/invoice/outbound_shipment/insert/mod.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/login.rs
  server/service/src/requisition/request_requisition/insert.rs
  server/service/src/requisition/request_requisition/update/mod.rs
  server/service/src/requisition/request_requisition/update/test.rs
  server/service/src/requisition/response_requisition/update.rs
  server/service/src/stocktake/insert.rs
  server/service/src/stocktake/update.rs
Labels: back-end

#276 Stocktake show lines
  client/packages/common/src/localStorage/keys.ts
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/CheckboxCell/EnabledCheckboxCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/CheckboxCell/index.ts
  client/packages/common/src/ui/layout/tables/context/hooks/useIsGrouped.ts
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Labels: bug, front-end

#294 Only mount CreatePatientModal when it suppose to be shown
  client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
  client/packages/system/src/Patient/ListView/AppBarButtons.tsx
  client/packages/system/src/Patient/hooks/useCreatePatientStore.ts
Labels: programs, front-end

#259 #215 deletion logging
  server/service/src/invoice/outbound_shipment/delete/mod.rs
  server/service/src/requisition/request_requisition/delete.rs
  server/service/src/stocktake/delete.rs
  server/service/src/sync/remote_data_synchroniser.rs
Labels: back-end

#288 265 Don't change sort direction when useUrlQueryParam mounts
  client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
Labels: bug, front-end

#283 #272 Rewrite graphql invoice deletion tests
  server/graphql/invoice/src/mutations/inbound_shipment/delete.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/delete.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/delete.rs
Labels: back-end

#289 #285 rewrite graphql invoice insert tests
  server/graphql/invoice/src/mutations/inbound_shipment/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
  server/service/src/invoice/inbound_shipment/insert/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/mod.rs
Labels: back-end

#282 Return a patient search connector from the patient search endpoint
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Patient/api/api.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  server/graphql/document/src/lib.rs
  server/graphql/document/src/queries/patient_search.rs
Labels: programs, front-end

#258 #217 remove total after tax from mutations
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/useServiceLineColumns.tsx
  client/packages/invoices/src/OutboundShipment/api/api.ts
  client/packages/invoices/src/utils.ts
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/update.rs
  server/graphql/tests/permissions.rs
  server/schema.graphql
  server/service/src/invoice/common.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/update/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/mod.rs
  server/service/src/invoice_line/inbound_shipment_service_line/update/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/update/mod.rs
  server/service/src/invoice_line/outbound_shipment_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_line/insert/mod.rs
  server/service/src/invoice_line/outbound_shipment_line/update/generate.rs
  server/service/src/invoice_line/outbound_shipment_line/update/mod.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/mod.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/mod.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/allocate/generate.rs
Labels: front-end, back-end

#316 Create postgres database if it doesn't exist
  server/repository/src/database_settings.rs
Labels: back-end

#311 #290 rewrite graphql update invoice tests
  server/graphql/invoice/src/mutations/inbound_shipment/update.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/update/mod.rs
Labels: back-end

#314 Specify tokio features in service
  server/android/Cargo.toml
  server/repository/Cargo.toml
  server/service/Cargo.toml
Labels: back-end

#235 234 consolidate sync test data
  server/service/src/sync/test/integration/invoice.rs
  server/service/src/sync/test/integration/location.rs
  server/service/src/sync/test/integration/mod.rs
  server/service/src/sync/test/integration/number.rs
  server/service/src/sync/test/integration/remote_sync_integration_test.rs
  server/service/src/sync/test/integration/requisition.rs
  server/service/src/sync/test/integration/stock_line.rs
  server/service/src/sync/test/integration/stocktake.rs
  server/service/src/sync/test/mod.rs
  server/service/src/sync/test/pull_and_push.rs
  server/service/src/sync/test/test_data/item.rs
  server/service/src/sync/test/test_data/location.rs
  server/service/src/sync/test/test_data/master_list.rs
  server/service/src/sync/test/test_data/master_list_line.rs
  server/service/src/sync/test/test_data/master_list_name_join.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/name.rs
  server/service/src/sync/test/test_data/name_store_join.rs
  server/service/src/sync/test/test_data/number.rs
  server/service/src/sync/test/test_data/report.rs
  server/service/src/sync/test/test_data/requisition.rs
  server/service/src/sync/test/test_data/requisition_line.rs
  server/service/src/sync/test/test_data/stock_line.rs
  server/service/src/sync/test/test_data/stocktake.rs
  server/service/src/sync/test/test_data/stocktake_line.rs
  server/service/src/sync/test/test_data/store.rs
  server/service/src/sync/test/test_data/trans_line.rs
  server/service/src/sync/test/test_data/transact.rs
  server/service/src/sync/test/test_data/unit.rs
  server/service/src/sync/translation_central/test_data/master_list.rs
  server/service/src/sync/translation_central/test_data/master_list_line.rs
  server/service/src/sync/translation_central/test_data/master_list_name_join.rs
  server/service/src/sync/translation_central/test_data/mod.rs
  server/service/src/sync/translation_central/test_data/unit.rs
  server/service/src/sync/translation_remote/test_data/location.rs
  server/service/src/sync/translation_remote/test_data/mod.rs
  server/service/src/sync/translation_remote/test_data/name.rs
  server/service/src/sync/translation_remote/test_data/name_store_join.rs
Labels: sync v5

#237 236 consolidate sync buffer integration
  server/cli/src/cli.rs
  server/repository/src/db_diesel/sync_buffer.rs
  server/repository/src/mock/mod.rs
  server/server/src/lib.rs
  server/service/src/sync/actor.rs
  server/service/src/sync/central_data_synchroniser.rs
  server/service/src/sync/mod.rs
  server/service/src/sync/remote_data_synchroniser.rs
  server/service/src/sync/sync_api_v5.rs
  server/service/src/sync/sync_buffer.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/translation_and_integration.rs
  server/service/src/sync/translation_remote/pull.rs
  server/service/src/sync/translation_remote/push.rs
Labels: sync v5

#242 241 reinstate sync integration transaction and errors
  server/Cargo.lock
  server/cli/Cargo.toml
  server/cli/src/cli.rs
  server/repository/src/db_diesel/unit_row.rs
  server/server/Cargo.toml
  server/server/src/main.rs
  server/service/Cargo.toml
  server/service/src/sync/central_data_synchroniser.rs
  server/service/src/sync/remote_data_synchroniser.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/test/pull_and_push.rs
  server/service/src/sync/translation_and_integration.rs
  server/util/Cargo.toml
  server/util/src/lib.rs
  server/util/src/logger.rs
Labels: sync v5

#342 Log auth error & update messaging
  client/packages/common/src/authentication/api/api.ts
  client/packages/common/src/authentication/api/hooks/useAuthApi.ts
  client/packages/common/src/intl/locales/en/app.json
Labels: front-end

#248 246 handle sync remote data deletes
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/name_store_join.rs
  server/repository/src/db_diesel/sync_buffer.rs
  server/service/src/sync/mod.rs
  server/service/src/sync/test/mod.rs
  server/service/src/sync/test/pull_and_push.rs
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/name_store_join.rs
  server/service/src/sync/test/test_data/requisition.rs
  server/service/src/sync/test/test_data/requisition_line.rs
  server/service/src/sync/translation_and_integration.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/name_store_join.rs
  server/service/src/sync/translations/requisition.rs
  server/service/src/sync/translations/requisition_line.rs
Labels: sync v5

#251 250 name is customer and supplier to reflect in name store join
  server/repository/src/db_diesel/name_store_join.rs
  server/repository/src/db_diesel/sync_buffer.rs
  server/repository/src/mock/mod.rs
  server/service/src/sync/test/mod.rs
  server/service/src/sync/test/pull_and_push.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/number.rs
  server/service/src/sync/test/test_data/special/mod.rs
  server/service/src/sync/test/test_data/special/name_to_name_store_join.rs
  server/service/src/sync/test/test_data/store.rs
  server/service/src/sync/translation_and_integration.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/special/mod.rs
  server/service/src/sync/translations/special/name_to_name_store_join.rs
Labels: sync v5

#323 #312 update service tests for inbound invoice
  server/graphql/invoice/src/mutations/inbound_shipment/delete.rs
  server/repository/src/mock/invoice.rs
  server/service/src/invoice/inbound_shipment/delete/mod.rs
  server/service/src/invoice/inbound_shipment/insert/mod.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice/mod.rs
Labels: back-end

#256 255 update existing sync integraiton tests
  server/service/Cargo.toml
  server/service/src/lib.rs
  server/service/src/sync/central_data_synchroniser.rs
  server/service/src/sync/sync_api_v3.rs
  server/service/src/sync/sync_api_v5.rs
  server/service/src/sync/test/integration/central_server_configurations.rs
  server/service/src/sync/test/integration/invoice.rs
  server/service/src/sync/test/integration/location.rs
  server/service/src/sync/test/integration/mod.rs
  server/service/src/sync/test/integration/number.rs
  server/service/src/sync/test/integration/remote_sync_integration_test.rs
  server/service/src/sync/test/integration/requisition.rs
  server/service/src/sync/test/integration/stock_line.rs
  server/service/src/sync/test/integration/stocktake.rs
  server/service/src/sync/test/mod.rs
Labels: sync v5

#328 165 v5 push
  server/repository/src/db_diesel/changelog_row.rs
  server/service/src/sync/api/common_records.rs
  server/service/src/sync/api/core.rs
  server/service/src/sync/api/error.rs
  server/service/src/sync/api/get_central_records.rs
  server/service/src/sync/api/get_queued_records.rs
  server/service/src/sync/api/get_site_status.rs
  server/service/src/sync/api/mod.rs
  server/service/src/sync/api/post_acknowledged_records.rs
  server/service/src/sync/api/post_initialise.rs
  server/service/src/sync/api/post_queued_records.rs
  server/service/src/sync/central_data_synchroniser.rs
  server/service/src/sync/mod.rs
  server/service/src/sync/remote_data_synchroniser.rs
  server/service/src/sync/sync_api_v3.rs
  server/service/src/sync/sync_api_v5.rs
  server/service/src/sync/synchroniser.rs
Labels: back-end, sync v5

#329 #324 update tests for service -> outbound shipments
  server/graphql/batch_mutations/src/batch_outbound_shipment.rs
  server/graphql/invoice/src/mutations/outbound_shipment/update.rs
  server/repository/src/mock/invoice.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice/outbound_shipment/delete/mod.rs
  server/service/src/invoice/outbound_shipment/insert/mod.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/invoice/outbound_shipment/update/validate.rs
Labels: back-end

#315 Add android ID
  server/android/src/android.rs
  server/server/Cargo.toml
  server/server/src/lib.rs
  server/service/src/settings.rs
Labels: platform: android

#306 #260 update mutations that affect price
  server/graphql/core/src/generic_inputs.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/update.rs
  server/schema.graphql
  server/service/src/invoice_line/inbound_shipment_line/insert/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/update/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/update/mod.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/mod.rs
  server/service/src/invoice_line/inbound_shipment_service_line/update/mod.rs
  server/service/src/invoice_line/outbound_shipment_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_line/insert/mod.rs
  server/service/src/invoice_line/outbound_shipment_line/update/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/mod.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/allocate/generate.rs
Labels: back-end

#362 Quantity allocation
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/utils.ts
Labels: outbound

#359 358 fix bug with reduction of total number of packs in outbound shipment status change
  server/graphql/invoice/src/mutations/outbound_shipment/add_from_master_list.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/unallocated_line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/unallocated_line/update.rs
  server/graphql/location/src/mutations/delete.rs
  server/graphql/types/src/types/invoice_line.rs
  server/repository/src/db_diesel/invoice_line.rs
  server/service/src/invoice/outbound_shipment/update/generate.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
Labels: bug, back-end

#377 Move the name table update trigger to patient service
  server/graphql/document/src/mutations/update_document.rs
  server/service/src/document/document_service.rs
  server/service/src/document/mod.rs
  server/service/src/document/patient/patient_document_update.rs
  server/service/src/document/patient/update.rs
  server/service/src/document/update_trigger.rs
Labels: back-end

#367 Update patient and program schemas
  server/graphql/document/src/mutations/update_document.rs
  server/service/src/document/document_service.rs
  server/service/src/document/encounter/insert.rs
  server/service/src/document/encounter/update.rs
  server/service/src/document/mod.rs
  server/service/src/document/patient/patient_document_update.rs
  server/service/src/document/patient/update.rs
  server/service/src/document/program/upsert.rs
  server/service/src/document/schemas/patient.json
  server/service/src/document/schemas/program.json
  server/service/src/document/update_trigger.rs
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/program_schemas/patient.json
  server/service/src/sync/program_schemas/patient_ui_schema.json
Labels: programs

#382 376 program table
  server/graphql/document/src/lib.rs
  server/graphql/document/src/mutations/program/insert.rs
  server/graphql/document/src/mutations/program/update.rs
  server/graphql/document/src/mutations/update_document.rs
  server/graphql/document/src/queries/mod.rs
  server/graphql/document/src/queries/patient.rs
  server/graphql/document/src/queries/program.rs
  server/graphql/document/src/types/program.rs
  server/repository/migrations/postgres/2022-06-07T16-00_create_program_table/down.sql
  server/repository/migrations/postgres/2022-06-07T16-00_create_program_table/up.sql
  server/repository/migrations/sqlite/2022-06-07T16-00_create_program_table/down.sql
  server/repository/migrations/sqlite/2022-06-07T16-00_create_program_table/up.sql
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/program.rs
  server/repository/src/db_diesel/program_row.rs
  server/service/src/auth.rs
  server/service/src/document/patient/mod.rs
  server/service/src/document/patient/patient_updated.rs
  server/service/src/document/patient/query.rs
  server/service/src/document/patient/update.rs
  server/service/src/document/program/mod.rs
  server/service/src/document/program/program_updated.rs
  server/service/src/document/program/query.rs
  server/service/src/document/program/upsert.rs
Labels: back-end

#332 327 central sync integration test
  server/service/src/sync/test/integration/central/master_list.rs
  server/service/src/sync/test/integration/central/mod.rs
  server/service/src/sync/test/integration/central/name_and_store_and_name_store_join.rs
  server/service/src/sync/test/integration/central/report.rs
  server/service/src/sync/test/integration/central/test.rs
  server/service/src/sync/test/integration/central/unit_and_item.rs
  server/service/src/sync/test/integration/central_server_configurations.rs
  server/service/src/sync/test/integration/errors.rs
  server/service/src/sync/test/integration/mod.rs
  server/service/src/sync/test/test_data/item.rs
  server/service/src/sync/translations/item.rs
  server/util/src/json.rs
  server/util/src/lib.rs
Labels: sync v5

#334 330 remote integration tests for deletes
  server/service/src/sync/test/integration/invoice.rs
  server/service/src/sync/test/integration/location.rs
  server/service/src/sync/test/integration/number.rs
  server/service/src/sync/test/integration/remote/invoice.rs
  server/service/src/sync/test/integration/remote/location.rs
  server/service/src/sync/test/integration/remote/mod.rs
  server/service/src/sync/test/integration/remote/number.rs
  server/service/src/sync/test/integration/remote/requisition.rs
  server/service/src/sync/test/integration/remote/stock_line.rs
  server/service/src/sync/test/integration/remote/stocktake.rs
  server/service/src/sync/test/integration/remote/test.rs
  server/service/src/sync/test/integration/remote_sync_integration_test.rs
  server/service/src/sync/test/integration/requisition.rs
  server/service/src/sync/test/integration/stock_line.rs
  server/service/src/sync/test/integration/stocktake.rs
Labels: sync v5

#335 333 documenation for sync integration tests
  server/Cargo.lock
  server/README.md
  server/repository/src/db_diesel/invoice_line_row.rs
  server/repository/src/db_diesel/number_row.rs
  server/repository/src/db_diesel/report_row.rs
  server/repository/src/db_diesel/requisition/requisition_row.rs
  server/repository/src/db_diesel/stock_line_row.rs
  server/repository/src/db_diesel/stocktake_line_row.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/login.rs
  server/service/src/requisition_line/request_requisition_line/insert.rs
  server/service/src/sync/test/integration/README.MD
  server/service/src/sync/test/integration/central/mod.rs
  server/service/src/sync/test/integration/central/test.rs
  server/service/src/sync/test/integration/central_server_configurations.rs
  server/service/src/sync/test/integration/errors.rs
  server/service/src/sync/test/integration/mod.rs
  server/service/src/sync/test/integration/remote/mod.rs
  server/service/src/sync/test/integration/remote/test.rs
  server/service/src/sync/test/mod.rs
  server/service/src/sync/test/pull_and_push.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/stock_line.rs
  server/service/src/sync/translation_and_integration.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/location.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/number.rs
  server/service/src/sync/translations/requisition.rs
  server/service/src/sync/translations/requisition_line.rs
  server/service/src/sync/translations/stock_line.rs
  server/service/src/sync/translations/stocktake.rs
  server/service/src/sync/translations/stocktake_line.rs
  server/service/src/sync/translations/store.rs
  server/service/src/token.rs
  server/service/src/user_account.rs
  server/util/Cargo.toml
  server/util/src/test_helpers.rs
Labels: sync v5

#386 378 encounter table
  server/cli/src/refresh_dates.rs
  server/graphql/document/src/lib.rs
  server/graphql/document/src/mutations/encounter/insert.rs
  server/graphql/document/src/mutations/encounter/update.rs
  server/graphql/document/src/queries/encounter.rs
  server/graphql/document/src/queries/mod.rs
  server/graphql/document/src/types/encounter.rs
  server/graphql/document/src/types/program.rs
  server/repository/migrations/postgres/2022-06-07T17-00_create_encounter_table/down.sql
  server/repository/migrations/postgres/2022-06-07T17-00_create_encounter_table/up.sql
  server/repository/migrations/sqlite/2022-06-07T17-00_create_encounter_table/down.sql
  server/repository/migrations/sqlite/2022-06-07T17-00_create_encounter_table/up.sql
  server/repository/src/db_diesel/encounter.rs
  server/repository/src/db_diesel/encounter_row.rs
  server/repository/src/db_diesel/mod.rs
  server/service/src/auth.rs
  server/service/src/document/encounter/encounter_updated.rs
  server/service/src/document/encounter/insert.rs
  server/service/src/document/encounter/mod.rs
  server/service/src/document/encounter/query.rs
  server/service/src/document/encounter/update.rs
  server/service/src/document/patient/mod.rs
  server/service/src/document/patient/query.rs
  server/service/src/document/program/upsert.rs
  server/service/src/document/schemas/encounter.json
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/program_schemas/encounter.json
Labels: back-end

#389 Form submit
  client/packages/common/src/ui/components/loading/BasicSpinner/BasicSpinner.tsx
  client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Array.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
  client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx
Labels: front-end

#364 Inbound batches
  client/packages/common/src/ui/layout/tables/DataTable.tsx
  client/packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditPanel.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Labels: inbound

#366 #347 store id not being checked against invoices
  server/graphql/invoice/src/mutations/outbound_shipment/delete.rs
  server/graphql/invoice/src/mutations/outbound_shipment/update.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/delete.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/delete.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/unallocated_line/delete.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/unallocated_line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/unallocated_line/update.rs
  server/repository/src/mock/full_invoice.rs
  server/repository/src/mock/invoice.rs
  server/repository/src/mock/name.rs
  server/repository/src/mock/test_name_store_id.rs
  server/repository/src/mock/test_unallocated_line.rs
  server/service/src/invoice/inbound_shipment/batch.rs
  server/service/src/invoice/inbound_shipment/delete/mod.rs
  server/service/src/invoice/inbound_shipment/delete/validate.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice/inbound_shipment/update/validate.rs
  server/service/src/invoice/outbound_shipment/delete/mod.rs
  server/service/src/invoice/outbound_shipment/delete/validate.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/invoice/outbound_shipment/update/validate.rs
  server/service/src/invoice/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/delete/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/delete/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/update/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/update/validate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/delete/mod.rs
  server/service/src/invoice_line/inbound_shipment_service_line/delete/validate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/mod.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/validate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/update/mod.rs
  server/service/src/invoice_line/inbound_shipment_service_line/update/validate.rs
  server/service/src/invoice_line/outbound_shipment_line/delete/mod.rs
  server/service/src/invoice_line/outbound_shipment_line/delete/validate.rs
  server/service/src/invoice_line/outbound_shipment_line/insert/mod.rs
  server/service/src/invoice_line/outbound_shipment_line/insert/validate.rs
  server/service/src/invoice_line/outbound_shipment_line/update/mod.rs
  server/service/src/invoice_line/outbound_shipment_line/update/validate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/delete/mod.rs
  server/service/src/invoice_line/outbound_shipment_service_line/delete/validate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/mod.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/validate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/mod.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/validate.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/delete.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/update.rs
Labels: back-end

#405 date of birth control
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
  client/packages/common/src/ui/forms/JsonForms/components/DateOfBirth.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
  client/packages/common/src/ui/forms/JsonForms/components/index.ts
  client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx
  client/packages/system/src/Patient/DetailView/DetailView.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
  server/service/src/sync/program_schemas/patient_ui_schema.json
Labels: front-end

#409 355 improve patient creation modal
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx
  client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
  client/packages/system/src/Patient/DetailView/DetailView.tsx
  client/packages/system/src/Patient/hooks/useCreatePatientStore.ts
  server/graphql/document/src/queries/patient_search.rs
  server/service/src/document/patient/query.rs
  server/service/src/document/patient/search.rs
Labels: front-end, back-end
