Repository msupply-foundation/open-msupply, pull requests merged in 2022-05, with the labels that each got.

#44 update schema
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Name/DetailModal/DetailModal.tsx
  client/packages/system/src/Name/api/operations.generated.ts
  client/packages/system/src/Name/api/operations.graphql
Labels: front-end

#45 Patients columns
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/host/src/routers/PatientRouter.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
  client/packages/system/src/Patient/api/api.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  client/packages/system/src/Patient/utils.ts
  server/docs/content/docs/M1/how_to_m1.md
  server/graphql/types/src/types/name.rs
Labels: enhancement, programs, front-end

#34 #2 URL query parameters
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/useQueryParams/index.ts
  client/packages/common/src/hooks/useQueryParams/useQueryParams.test.tsx
  client/packages/common/src/hooks/useQueryParams/useQueryParamsStore.ts
  client/packages/common/src/hooks/useUrlQuery/index.ts
  client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts
  client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
  client/packages/common/src/ui/layout/tables/context/TableContext.tsx
  client/packages/host/src/Host.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
  client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx
  client/packages/inventory/src/Stocktake/ListView/ListView.tsx
  client/packages/inventory/src/Stocktake/api/hooks/document/useStocktakes.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/document/useInbounds.ts
  client/packages/invoices/src/InboundShipment/api/hooks/line/useInboundRows.ts
  client/packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/OutboundShipment/api/hooks/document/useOutbounds.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/line/useOutboundRows.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/ContentArea.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
  client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/Toolbar.tsx
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useRequests.ts
  client/packages/requisitions/src/RequestRequisition/api/hooks/line/useRequestLines.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useResponses.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useResponseLines.ts
  client/packages/system/src/Item/ListView/ListView.tsx
  client/packages/system/src/Item/api/hooks/useItems/useItems.ts
  client/packages/system/src/Location/ListView/ListView.tsx
  client/packages/system/src/Location/api/hooks/document/useLocations.ts
  client/packages/system/src/MasterList/DetailView/DetailView.tsx
  client/packages/system/src/MasterList/DetailView/columns.ts
  client/packages/system/src/MasterList/ListView/ListView.tsx
  client/packages/system/src/MasterList/ListView/Toolbar.tsx
  client/packages/system/src/MasterList/api/hooks/document/useMasterLists.ts
  client/packages/system/src/Name/ListView/ListView.tsx
  client/packages/system/src/Name/api/hooks/document/useNames.ts
  client/packages/system/src/Stock/Components/Toolbar.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/api/hooks/document/useStockLines.ts
Labels: front-end

#53 Don't duplicate stock lines
  LICENSE
  README.md
  client/README.md
  server/service/src/invoice/inbound_shipment/update/generate.rs
Labels: back-end

#39 26 server to host client
  client/.gitignore
  client/packages/host/dist/.gitignore
  client/packages/host/package.json
  client/packages/host/webpack.config.js
  package.json
  server/Cargo.lock
  server/README.md
  server/android/src/android.rs
  server/configuration/base.yaml
  server/server/Cargo.toml
  server/server/src/cors.rs
  server/server/src/discovery.rs
  server/server/src/lib.rs
  server/server/src/self_signed_certs.rs
  server/server/src/serve_frontend.rs
  server/server/src/test_utils.rs
  server/service/src/settings.rs
Labels: back-end

#41 38 resolve server url rlative to window.url
  client/README.md
  client/codegen.yml
  client/package.json
  client/packages/config/src/config.ts
  client/packages/config/src/index.ts
  client/packages/host/package.json
  client/packages/host/public/config.js
  client/packages/host/public/config.local.js
  client/packages/host/public/index.html
  client/packages/host/webpack.config.js
  server/report_builder/README.md
  server/server/src/lib.rs
  server/server/src/serve_frontend.rs
Labels: front-end, back-end
