Repository msupply-foundation/open-msupply, pull requests merged in 2022-12, with the labels that each got.

#882 #861 Highlight current Text box
  client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
  client/packages/common/src/ui/components/inputs/Select/Select.tsx
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
Labels: programs

#885 818 sync translation handle empty datetime strings
  server/service/src/sync/sync_serde.rs
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/test/test_data/requisition.rs
  server/service/src/sync/test/test_data/requisition_line.rs
  server/service/src/sync/test/test_data/stocktake.rs
  server/service/src/sync/translations/activity_log.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/name.rs
  server/service/src/sync/translations/report.rs
  server/service/src/sync/translations/requisition.rs
  server/service/src/sync/translations/requisition_line.rs
  server/service/src/sync/translations/stock_line.rs
  server/service/src/sync/translations/stocktake.rs
  server/service/src/sync/translations/stocktake_line.rs
Labels: back-end, sync v5

#887 #860 Unify visuals of multi select (EnumArrayComponent) and single Select components
  client/packages/common/src/ui/forms/JsonForms/components/Array.tsx
Labels: programs

#902 868 Calendar select color
  client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
Labels: programs

#879 862 search list order of search results
  client/packages/common/package.json
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Array.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Select.tsx
  client/yarn.lock
Labels: programs

#922 682 programs patient registration form layout
  server/service/src/programs/schemas/patient.json
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/program_schemas/patient.json
  server/service/src/sync/program_schemas/patient_ui_schema.json
Labels: programs

#849 704.2 template migration examples and doc
  client/package.json
  client/packages/host/src/components/AppVersion.tsx
  package.json
  server/Cargo.lock
  server/cli/src/refresh_dates.rs
  server/repository/Cargo.toml
  server/repository/migrations/postgres/2022-10-27T09-15_v103/up.sql
  server/repository/src/db_diesel/key_value_store.rs
  server/repository/src/lib.rs
  server/repository/src/migrations/README.md
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/templates/add_data_from_sync_buffer/mod.rs
  server/repository/src/migrations/templates/adding_table/mod.rs
  server/repository/src/migrations/templates/data_and_schema/mod.rs
  server/repository/src/migrations/templates/data_migration/mod.rs
  server/repository/src/migrations/templates/mod.rs
  server/repository/src/migrations/types.rs
  server/repository/src/migrations/v1_00_04/mod.rs
  server/repository/src/migrations/version.rs
  server/repository/src/test_db.rs
  server/repository/src/test_db/mod.rs
  server/repository/src/test_db/postgres.rs
  server/repository/src/test_db/sqlite.rs
  server/server/src/lib.rs
Labels: enhancement

#925 #863 history button location
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
  client/packages/system/src/Patient/PatientView/Footer.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
Labels: programs

#935 834 Remove code from Program Selector UI
  client/packages/system/src/Patient/Components/EncounterSearchInput/EncounterSearchInput.tsx
  client/packages/system/src/Program/Components/ProgramOptionRenderer.tsx
Labels: programs

#933 843 arv medication section 2
  client/packages/common/src/intl/locales/en/common.json
  client/packages/programs/src/JsonForms/components/QuantityPrescribed.tsx
  client/packages/programs/src/JsonForms/useJsonForms.tsx
Labels: programs

#802 743 use dns sd with electron client
  client/packages/common/src/api/hooks/index.ts
  client/packages/common/src/api/hooks/useInitialisationStatus.ts
  client/packages/common/src/api/operations.generated.ts
  client/packages/common/src/api/operations.graphql
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/useElectronClient/index.ts
  client/packages/common/src/hooks/useElectronClient/useElectronClient.ts
  client/packages/common/src/hooks/useNativeClient/index.ts
  client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/discovery/DiscoveredServers.tsx
  client/packages/common/src/ui/discovery/ServerDiscovery.tsx
  client/packages/common/src/ui/discovery/index.ts
  client/packages/common/src/ui/index.ts
  client/packages/electron/package.json
  client/packages/electron/src/discovery/DiscoveredServers.tsx
  client/packages/electron/src/electron.ts
  client/packages/electron/src/home.tsx
  client/packages/electron/src/preload.ts
  client/packages/electron/src/shared.ts
  client/packages/host/src/api/api.ts
  client/packages/host/src/api/hooks/index.ts
  client/packages/host/src/api/hooks/utils/index.ts
  client/packages/host/src/api/hooks/utils/useHostApi.ts
  client/packages/host/src/api/hooks/utils/useInitialisationStatus.ts
  client/packages/host/src/api/operations.generated.ts
  client/packages/host/src/api/operations.graphql
  client/packages/host/src/components/Initialise/Initialise.tsx
  client/packages/host/src/components/Initialise/InitialiseLayout.tsx
  client/packages/host/src/components/Initialise/hooks.ts
  client/packages/host/src/components/Login/Login.tsx
  client/packages/host/src/components/Login/LoginLayout.tsx
  client/packages/host/src/components/Login/hooks.ts
  client/packages/host/src/components/SiteInfo.tsx
  client/yarn.lock
  server/Cargo.lock
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/initialisation_status.rs
  server/server/Cargo.toml
  server/server/src/cors.rs
  server/server/src/discovery.rs
  server/server/src/lib.rs
  server/service/src/service_provider.rs
  server/service/src/settings_service.rs
  server/service/src/sync/sync_status/status.rs
  server/service/src/sync/sync_status/test.rs
Labels: Blocked

#945 909 number input fixes
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx
  client/packages/common/src/utils/numbers/NumUtils.ts
  client/packages/programs/src/JsonForms/components/AdherenceStatus.tsx
Labels: programs

#959 Fix sync status tests
  server/cli/src/refresh_dates.rs
  server/service/src/sync/sync_serde.rs
  server/service/src/sync/sync_status/status.rs
  server/service/src/sync/sync_status/test.rs
Labels: bug, back-end

#949 947 adherenc status warning
  client/packages/common/src/intl/locales/en/programs.json
  client/packages/common/src/intl/locales/index.ts
  client/packages/programs/src/JsonForms/components/AdherenceStatus.tsx
  client/packages/programs/src/JsonForms/components/PreviousEncounterField.tsx
  client/packages/programs/src/JsonForms/components/PreviousEncounterText.tsx
  client/packages/programs/src/JsonForms/useJsonForms.tsx
  server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Labels: programs

#969 #777 Tab indicator correctly moves when Details panel is opened
  client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
Labels: bug, front-end

#964 #910 Timestamp fixes
  server/graphql/general/src/queries/tests/activity_log.rs
  server/graphql/types/src/types/activity_log.rs
Labels: bug

#966 841 remove graphql request logging
  server/README.md
  server/graphql/lib.rs
Labels: bug

#930 Add program practitioners KDD
  decisions/2022-12-12_programs_practitioners.md
Labels: KDD
