Repository msupply-foundation/open-msupply, pull requests merged in 2022-08, with the labels that each got.

#339 338 PR review changes up to 333
  server/repository/migrations/postgres/2021-11-05T10-00_create_sync_buffer_table/up.sql
  server/repository/src/db_diesel/changelog_row.rs
  server/service/src/sync/api/core.rs
  server/service/src/sync/remote_data_synchroniser.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/test/mod.rs
  server/service/src/sync/translation_and_integration.rs
Labels: back-end, sync v5

#503 476 encounter extract fields api
  server/graphql/document/src/lib.rs
  server/graphql/document/src/queries/encounter.rs
  server/graphql/document/src/queries/encounter_extract_field.rs
  server/graphql/document/src/queries/mod.rs
  server/service/src/document/encounter/extract_encounter_fields.rs
  server/service/src/document/encounter/extract_fields.rs
  server/service/src/document/encounter/mod.rs
Labels: back-end

#507 425 enrol patient
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/patients.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
  client/packages/common/src/ui/forms/JsonForms/components/DateTime.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Text.tsx
  client/packages/common/src/ui/forms/JsonForms/useJsonForms.tsx
  client/packages/system/src/Patient/Encounter/DetailModal.tsx
  client/packages/system/src/Patient/Encounter/ListView.tsx
  client/packages/system/src/Patient/PatientView/AddButton.tsx
  client/packages/system/src/Patient/PatientView/index.ts
  client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/index.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/api.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/hooks/document/index.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/hooks/document/useProgramEnrolments.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/index.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/operations.generated.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/operations.graphql
  client/packages/system/src/Patient/ProgramEnrolment/index.ts
  client/packages/system/src/Patient/hooks/usePatientModalStore.ts
  client/packages/system/src/Patient/index.ts
  client/packages/system/src/Program/Components/ProgramSearchModal/ProgramOptionRenderer.tsx
  client/packages/system/src/Program/Components/ProgramSearchModal/ProgramSearchModal.tsx
  client/packages/system/src/Program/Components/ProgramSearchModal/index.ts
  client/packages/system/src/Program/Components/index.ts
  client/packages/system/src/Program/api/api.ts
  client/packages/system/src/Program/api/hooks/document/index.ts
  client/packages/system/src/Program/api/hooks/document/usePrograms.ts
  client/packages/system/src/Program/api/hooks/index.ts
  client/packages/system/src/Program/api/hooks/utils/index.ts
  client/packages/system/src/Program/api/hooks/utils/useProgramApi.ts
  client/packages/system/src/Program/api/index.ts
  client/packages/system/src/Program/api/operations.generated.ts
  client/packages/system/src/Program/api/operations.graphql
  client/packages/system/src/Program/utils.ts
Labels: front-end

#504 File logging
  .gitignore
  client/packages/host/src/components/Login/Login.tsx
  server/.gitignore
  server/Cargo.lock
  server/README.md
  server/android/src/android.rs
  server/cli/Cargo.toml
  server/cli/src/cli.rs
  server/configuration/example.yaml
  server/server/Cargo.toml
  server/server/src/main.rs
  server/service/src/settings.rs
Labels: documentation, back-end, v1

#506 477 line chart control
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
  client/packages/common/src/ui/forms/JsonForms/components/index.ts
  client/packages/common/src/ui/forms/JsonForms/index.ts
  client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
  client/packages/system/src/Patient/Encounter/DetailModal.tsx
  client/packages/system/src/Patient/JsonForms/api/api.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/document/index.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/document/useAllocateNumber.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/document/useDocument.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/document/useDocumentRegistryByContext.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/document/useEncounterFields.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/index.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/utils/index.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/utils/useAllocateNumberApi.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/utils/useDocumentApi.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/utils/useDocumentRegistryApi.ts
  client/packages/system/src/Patient/JsonForms/api/index.ts
  client/packages/system/src/Patient/JsonForms/api/operations.generated.ts
  client/packages/system/src/Patient/JsonForms/api/operations.graphql
  client/packages/system/src/Patient/JsonForms/components/DateOfBirth.tsx
  client/packages/system/src/Patient/JsonForms/components/EncounterLineChart.tsx
  client/packages/system/src/Patient/JsonForms/components/IdGenerator.tsx
  client/packages/system/src/Patient/JsonForms/index.ts
  client/packages/system/src/Patient/JsonForms/useDocumentLoader.ts
  client/packages/system/src/Patient/JsonForms/useJsonForms.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
  client/packages/system/src/Patient/hooks/usePatientCreateStore.ts
  client/packages/system/src/Patient/hooks/usePatientModalStore.ts
  server/graphql/document/src/lib.rs
  server/graphql/document/src/queries/encounter_fields.rs
  server/graphql/document/src/queries/mod.rs
  server/service/src/document/encounter/encounter_fields.rs
  server/service/src/document/encounter/encounter_updated.rs
  server/service/src/document/encounter/extract_fields.rs
  server/service/src/document/encounter/insert.rs
  server/service/src/document/encounter/mod.rs
  server/service/src/document/encounter/update.rs
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Labels: front-end

#510 Create encounter: part 1
  client/packages/system/src/Patient/Components/ProgramSearchInput/ProgramSearchInput.tsx
  client/packages/system/src/Patient/Components/ProgramSearchInput/index.ts
  client/packages/system/src/Patient/Components/index.ts
  client/packages/system/src/Patient/Encounter/DetailModal.tsx
  client/packages/system/src/Patient/Encounter/api/api.ts
  client/packages/system/src/Patient/Encounter/api/operations.generated.ts
  client/packages/system/src/Patient/Encounter/api/operations.graphql
  client/packages/system/src/Patient/PatientView/AddButton.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
  client/packages/system/src/Patient/ProgramEnrolment/api/api.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/hooks/document/index.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/hooks/index.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/index.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/operations.generated.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/operations.graphql
  client/packages/system/src/Patient/api/api.ts
  client/packages/system/src/Patient/api/hooks/document/index.ts
  client/packages/system/src/Patient/api/hooks/document/usePrograms.ts
  client/packages/system/src/Patient/api/hooks/index.ts
  client/packages/system/src/Patient/api/index.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  client/packages/system/src/Patient/hooks/usePatientModalStore.ts
  client/packages/system/src/Program/Components/ProgramOptionRenderer.tsx
  client/packages/system/src/Program/Components/ProgramSearchModal/ProgramSearchModal.tsx
  client/packages/system/src/Program/Components/index.ts
  client/packages/system/src/Program/api/api.ts
  client/packages/system/src/Program/api/hooks/document/usePrograms.ts
  client/packages/system/src/Program/api/index.ts
  client/packages/system/src/Program/api/operations.generated.ts
  client/packages/system/src/Program/api/operations.graphql
  client/packages/system/src/Program/index.ts
  client/packages/system/src/Program/utils.ts
Labels: front-end

#511 Create encounter: part 2
  client/packages/common/src/intl/locales/en/patients.json
  client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
  client/packages/system/src/Patient/Encounter/DetailModal.tsx
  client/packages/system/src/Patient/Encounter/api/api.ts
  client/packages/system/src/Patient/Encounter/api/hooks/document/index.ts
  client/packages/system/src/Patient/Encounter/api/hooks/document/useUpsertEncounter.ts
  client/packages/system/src/Patient/Encounter/api/hooks/index.ts
  client/packages/system/src/Patient/Encounter/api/hooks/registry/index.ts
  client/packages/system/src/Patient/Encounter/api/hooks/registry/useRegistryByProgram.ts
  client/packages/system/src/Patient/Encounter/api/operations.generated.ts
  client/packages/system/src/Patient/Encounter/api/operations.graphql
  client/packages/system/src/Patient/JsonForms/useDocumentLoader.ts
  client/packages/system/src/Patient/PatientView/AddButton.tsx
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  client/packages/system/src/Program/Components/ProgramOptionRenderer.tsx
Labels: front-end

#525 516 control options validation
  client/.github/workflows/bundle-size-diff.yaml
  client/package.json
  client/packages/host/package.json
  client/packages/host/webpack.config.js
  client/packages/system/package.json
  client/packages/system/src/Patient/JsonForms/components/DispensedDuration.tsx
  client/packages/system/src/Patient/JsonForms/components/EncounterLineChart.tsx
  client/packages/system/src/Patient/JsonForms/components/IdGenerator.tsx
  client/packages/system/src/Patient/JsonForms/useJsonForms.tsx
  client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.test.ts
  client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.ts
  client/yarn.lock
  server/Cargo.toml
  server/server/src/lib.rs
Labels: front-end

#520 514 missed encounters
  client/.github/workflows/bundle-size-diff.yaml
  client/package.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/host/package.json
  client/packages/host/webpack.config.js
  client/packages/system/package.json
  client/packages/system/src/Patient/Encounter/ListView.tsx
  client/packages/system/src/Patient/JsonForms/api/operations.generated.ts
  client/packages/system/src/Patient/JsonForms/api/operations.graphql
  client/packages/system/src/Patient/JsonForms/components/DispensedDuration.tsx
  client/packages/system/src/Patient/JsonForms/components/EncounterLineChart.tsx
  client/packages/system/src/Patient/JsonForms/components/IdGenerator.tsx
  client/packages/system/src/Patient/JsonForms/useJsonForms.tsx
  client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.test.ts
  client/packages/system/src/Patient/JsonForms/useZodOptionsValidation.ts
  client/yarn.lock
  server/Cargo.toml
  server/server/src/lib.rs
Labels: front-end

#521 179 document deletion
  server/graphql/document/src/lib.rs
  server/graphql/document/src/mutations/delete_document.rs
  server/graphql/document/src/mutations/mod.rs
  server/graphql/document/src/mutations/undelete_document.rs
  server/graphql/document/src/mutations/update_document.rs
  server/repository/migrations/postgres/2022-04-27T13-00_create_document_table/up.sql
  server/repository/migrations/sqlite/2022-04-27T13-00_create_document_table/up.sql
  server/repository/src/db_diesel/document.rs
  server/repository/src/mock/document.rs
  server/repository/src/mock/mod.rs
  server/service/src/document/document_service.rs
  server/service/src/document/encounter/insert.rs
  server/service/src/document/encounter/update.rs
  server/service/src/document/patient/update.rs
  server/service/src/document/program/upsert.rs
  server/service/src/document/raw_document.rs
Labels: programs, back-end

#533 Encounter details tabs
  client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Boolean.tsx
  client/packages/common/src/ui/forms/JsonForms/components/CategorizationTabLayout.tsx
  client/packages/common/src/ui/forms/JsonForms/components/index.ts
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/host/public/medical-icons.css
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/Footer.tsx
  server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Labels: front-end

#524 447 encounter details 1
  client/packages/common/src/authentication/api/hooks/useUserDetails.ts
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/patients.json
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/TimePickers/TimePickerInput/TimePickerInput.tsx
  client/packages/common/src/ui/components/inputs/TimePickers/TimePickerInput/index.ts
  client/packages/common/src/ui/components/inputs/TimePickers/index.ts
  client/packages/common/src/ui/components/inputs/index.ts
  client/packages/common/src/ui/forms/JsonForms/JsonForm.tsx
  client/packages/common/src/ui/forms/JsonForms/components/Boolean.tsx
  client/packages/common/src/ui/forms/JsonForms/components/CategorizationTabLayout.tsx
  client/packages/common/src/ui/forms/JsonForms/components/index.ts
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/config/src/routes.ts
  client/packages/host/public/medical-icons.css
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/components/Navigation/DispensaryNav.tsx
  client/packages/host/src/components/Navigation/index.ts
  client/packages/host/src/routers/DispensaryRouter.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/Footer.tsx
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
  client/packages/system/src/Encounter/DetailView/index.ts
  client/packages/system/src/Encounter/ListView/ListView.tsx
  client/packages/system/src/Encounter/ListView/index.ts
  client/packages/system/src/Encounter/Service/Service.tsx
  client/packages/system/src/Encounter/Service/index.ts
  client/packages/system/src/Encounter/api/api.ts
  client/packages/system/src/Encounter/api/hooks/document/index.ts
  client/packages/system/src/Encounter/api/hooks/document/useEncounter.ts
  client/packages/system/src/Encounter/api/hooks/document/useEncounters.ts
  client/packages/system/src/Encounter/api/hooks/document/useInsertEncounter.ts
  client/packages/system/src/Encounter/api/hooks/document/useUpdateEncounter.ts
  client/packages/system/src/Encounter/api/hooks/document/useUpsertEncounter.ts
  client/packages/system/src/Encounter/api/hooks/index.ts
  client/packages/system/src/Encounter/api/hooks/registry/index.ts
  client/packages/system/src/Encounter/api/hooks/registry/useRegistryByProgram.ts
  client/packages/system/src/Encounter/api/hooks/utils/index.ts
  client/packages/system/src/Encounter/api/hooks/utils/useEncounterApi.ts
  client/packages/system/src/Encounter/api/hooks/utils/useEncounterId.ts
  client/packages/system/src/Encounter/api/index.ts
  client/packages/system/src/Encounter/api/operations.generated.ts
  client/packages/system/src/Encounter/api/operations.graphql
  client/packages/system/src/Encounter/index.ts
  client/packages/system/src/Patient/Encounter/DetailModal.tsx
  client/packages/system/src/Patient/Encounter/ListView.tsx
  client/packages/system/src/Patient/Encounter/api/hooks/document/useEncounters.ts
  client/packages/system/src/Patient/Encounter/api/index.ts
  client/packages/system/src/Patient/api/hooks/document/index.ts
  client/packages/system/src/Patient/api/hooks/document/useEncounters.ts
  client/packages/system/src/Patient/api/hooks/index.ts
  client/packages/system/src/Patient/api/index.ts
  client/packages/system/src/Program/api/hooks/document/usePrograms.ts
  server/graphql/document/src/queries/encounter.rs
  server/graphql/document/src/types/encounter.rs
  server/repository/src/db_diesel/encounter.rs
  server/service/src/sync/program_schemas/hiv_care_encounter_ui_schema.json
Labels: front-end

#541 Query encounter fields by patient id
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Patient/JsonForms/api/api.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/document/useEncounterFields.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/utils/useDocumentApi.ts
  client/packages/system/src/Patient/JsonForms/api/operations.generated.ts
  client/packages/system/src/Patient/JsonForms/api/operations.graphql
  client/packages/system/src/Patient/JsonForms/components/EncounterLineChart.tsx
Labels: front-end

#537 Allow custom numbers for Programs
  server/repository/migrations/postgres/2021-12-10T10-00_number_table/up.sql
  server/repository/migrations/sqlite/2021-12-10T10-00_number_table/up.sql
  server/repository/src/db_diesel/number_row.rs
  server/repository/src/mock/number.rs
  server/service/src/number.rs
  server/service/src/sync/integration_tests/number.rs
  server/service/src/sync/translation_remote/number.rs
  server/service/src/sync/translation_remote/test_data/mod.rs
  server/service/src/sync/translation_remote/test_data/number.rs
Labels: back-end

#536 132 serial numbers postgres
  server/repository/migrations/postgres/2021-12-10T10-00_number_table/up.sql
  server/repository/migrations/sqlite/2021-12-10T10-00_number_table/up.sql
  server/repository/src/db_diesel/number_row.rs
  server/repository/src/mock/number.rs
  server/service/Cargo.toml
  server/service/src/number.rs
  server/service/src/sync/integration_tests/number.rs
  server/service/src/sync/translation_remote/number.rs
  server/service/src/sync/translation_remote/test_data/mod.rs
  server/service/src/sync/translation_remote/test_data/number.rs
Labels: v1

#544 Create encounter modal
  client/packages/common/src/intl/locales/en/patients.json
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/api/api.ts
  client/packages/system/src/Encounter/api/hooks/document/index.ts
  client/packages/system/src/Encounter/api/hooks/document/useEncounter.ts
  client/packages/system/src/Encounter/api/hooks/document/useUpsertEncounter.ts
  client/packages/system/src/Encounter/api/hooks/index.ts
  client/packages/system/src/Encounter/api/operations.generated.ts
  client/packages/system/src/Encounter/api/operations.graphql
  client/packages/system/src/Patient/Encounter/DetailModal.tsx
  client/packages/system/src/Patient/ProgramEnrolment/api/api.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/operations.generated.ts
  client/packages/system/src/Patient/ProgramEnrolment/api/operations.graphql
  server/graphql/document/src/mutations/encounter/insert.rs
  server/graphql/document/src/mutations/encounter/update.rs
  server/graphql/document/src/mutations/program_enrolment/insert.rs
  server/graphql/document/src/mutations/program_enrolment/update.rs
  server/graphql/document/src/queries/encounter.rs
  server/graphql/document/src/queries/patient.rs
  server/graphql/document/src/queries/program_enrolment.rs
  server/graphql/document/src/types/program_enrolment.rs
  server/service/src/document/encounter/mod.rs
  server/service/src/document/encounter/query.rs
  server/service/src/document/program/mod.rs
  server/service/src/document/program/query.rs
Labels: front-end

#550 451 use program number service
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Patient/JsonForms/api/api.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/document/useAllocateNumber.ts
  client/packages/system/src/Patient/JsonForms/api/hooks/utils/useAllocateNumberApi.ts
  client/packages/system/src/Patient/JsonForms/api/operations.generated.ts
  client/packages/system/src/Patient/JsonForms/api/operations.graphql
  server/graphql/document/src/lib.rs
  server/graphql/document/src/mutations/allocate_number.rs
  server/service/src/auth.rs
Labels: back-end
