Repository msupply-foundation/open-msupply, pull requests merged in 2023-02, with the labels that each got.

#1106 1059 rename context2 to sub context
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Report/api/hooks/document/useReports.ts
  client/packages/system/src/Report/api/operations.generated.ts
  client/packages/system/src/Report/api/operations.graphql
  client/packages/system/src/Report/components/ReportSelector.tsx
  server/graphql/reports/src/reports.rs
  server/repository/migrations/postgres/2023-01-16T10-00_report_secondary_context_and_arg_schema_v1.0.5/up.sql
  server/repository/migrations/sqlite/2023-01-16T10-00_report_secondary_context_and_arg_schema_v1.0.5/up.sql
  server/repository/src/db_diesel/report.rs
  server/repository/src/db_diesel/report_row.rs
  server/service/src/report/report_service.rs
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/test/test_data/report.rs
  server/service/src/sync/translations/report.rs
Labels: programs, Priority: High

#1102 Update information for stock line when updated in stocktake
  server/service/src/stocktake/update.rs
Labels: bug, Priority: Normal

#1103 #1051 when entering a new shipment line, alert if mandatory fields are not filled in, rather than just closing the window
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
  client/packages/common/src/ui/layout/tables/columns/types.ts
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeIntegerCell.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
Labels: enhancement, Priority: Normal

#1098 1077 UI changes for stocktake reasons
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
  client/packages/common/src/ui/layout/tables/DataTable.tsx
  client/packages/common/src/utils/arrays/ArrayUtils.ts
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts
  client/packages/inventory/src/Stocktake/api/api.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeSaveLines.ts
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/inventory/src/Stocktake/api/operations.graphql
  client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx
  client/packages/system/src/InventoryAdjustmentReason/Components/index.ts
  client/packages/system/src/InventoryAdjustmentReason/api/api.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/document/index.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/document/useInventoryAdjustmentReason.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/index.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/utils/index.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/utils/useInventoryAdjustmentReasonApi.ts
  client/packages/system/src/InventoryAdjustmentReason/api/index.ts
  client/packages/system/src/InventoryAdjustmentReason/api/operations.generated.ts
  client/packages/system/src/InventoryAdjustmentReason/api/operations.graphql
  client/packages/system/src/InventoryAdjustmentReason/index.ts
  client/packages/system/src/index.ts
Labels: front-end

#1115 Update OS placeholder
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
Labels: bug

#1130 Text inputs in table lose focus when typing
  client/packages/common/src/intl/locales/fr/dashboard.json
  client/packages/common/src/ui/components/inputs/Autocomplete/utils.tsx
  client/packages/common/src/ui/layout/tables/DataTable.tsx
  client/packages/common/src/ui/layout/tables/columns/CommentPopoverColumn/CommentPopoverColumn.tsx
  client/packages/common/src/ui/layout/tables/columns/ExpiryDateInput/ExpiryDateInput.tsx
  client/packages/common/src/ui/layout/tables/columns/NameAndColorColumn.tsx
  client/packages/common/src/ui/layout/tables/columns/NotePopoverColumn/NotePopoverColumn.tsx
  client/packages/common/src/ui/layout/tables/columns/types.ts
  client/packages/common/src/ui/layout/tables/components/Cells/CheckCell/CheckCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/CheckboxCell/CheckboxCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell/CurrencyCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/CurrencyInputCell/CurrencyInputCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/ExpiryDateCell/ExpiryDateCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeDecimalCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeIntegerCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PositiveNumberInputCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PostiveNumberCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
  client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.stories.tsx
  client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.test.tsx
  client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
  client/packages/common/src/ui/layout/tables/components/index.tsx
  client/packages/common/src/utils/arrays/ArrayUtils.ts
  client/packages/host/src/Site.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/useServiceLineColumns.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/useServiceLineColumns.tsx
  client/packages/system/src/Location/Components/LocationInputColumn.tsx
Labels: Priority: Normal

#1125 1107 enforce item visibility by master list for store
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useNextItem.test.tsx
  client/packages/system/src/Item/api/api.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Name/api/operations.generated.ts
  client/packages/system/src/Name/api/operations.graphql
  server/graphql/core/src/loader/item.rs
  server/graphql/core/src/loader/stock_line.rs
  server/graphql/general/src/queries/item.rs
  server/graphql/general/src/queries/tests/items.rs
  server/graphql/stock_line/src/lib.rs
  server/graphql/types/src/types/item.rs
  server/repository/migrations/postgres/2021-12-05T10-00_create_item_is_visible_view/down.sql
  server/repository/migrations/postgres/2021-12-05T10-00_create_item_is_visible_view/up.sql
  server/repository/migrations/sqlite/2021-12-05T10-00_create_item_is_visible_view/down.sql
  server/repository/migrations/sqlite/2021-12-05T10-00_create_item_is_visible_view/up.sql
  server/repository/src/db_diesel/diesel_schema.rs
  server/repository/src/db_diesel/item.rs
  server/repository/src/db_diesel/item_row.rs
  server/repository/src/db_diesel/stock_line.rs
  server/repository/src/migrations/v1_01_02/mod.rs
  server/repository/src/tests.rs
  server/service/src/dashboard/item_count.rs
  server/service/src/dashboard/stock_expiry_count.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/mod.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/validate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/mod.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/validate.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/allocate/generate.rs
  server/service/src/item.rs
  server/service/src/location/delete.rs
  server/service/src/location/tests/delete.rs
  server/service/src/requisition_line/request_requisition_line/insert.rs
  server/service/src/requisition_line/response_line_stats/response_line_stats.rs
  server/service/src/stock_line/mod.rs
  server/service/src/stock_line/query.rs
  server/service/src/stock_line/tests/query.rs
  server/service/src/stocktake_line/insert.rs
  server/service/src/stocktake_line/validate.rs
Labels: Priority: High

#1127 1073 add item performance back end
  server/graphql/core/src/loader/item_stock_on_hand.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/types/src/types/item.rs
Labels: Priority: High

#1135 #1120 If you group rows by item, the unit quantity of each batch shows the total for item rather than the batch
  client/packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
Labels: bug

#1088 Add KDD for store preferences
  decisions/store-preferences.md
Labels: Priority: High, KDD

#1112 Add option 4 to versioning KDD
  decisions/version-compatibility.md
Labels: KDD

#1129 1128 add clinician id to encounter table + graphql updates
  server/graphql/clinician/src/query.rs
  server/graphql/core/src/loader/clinician.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/programs/src/mutations/encounter/insert.rs
  server/graphql/programs/src/mutations/encounter/update.rs
  server/graphql/programs/src/queries/encounter.rs
  server/graphql/programs/src/types/encounter.rs
  server/graphql/types/src/types/clinician.rs
  server/graphql/types/src/types/mod.rs
  server/repository/migrations/postgres/2022-04-01T10-00_create_clinician_table/down.sql
  server/repository/migrations/postgres/2022-04-01T10-00_create_clinician_table/up.sql
  server/repository/migrations/postgres/2022-04-01T11-00_create_clinician_store_join_table/down.sql
  server/repository/migrations/postgres/2022-04-01T11-00_create_clinician_store_join_table/up.sql
  server/repository/migrations/postgres/2022-04-01T12-00_create_clinician_trigger/down.sql
  server/repository/migrations/postgres/2022-04-01T12-00_create_clinician_trigger/up.sql
  server/repository/migrations/postgres/2022-04-01T13-00_create_clinician_store_join_trigger/down.sql
  server/repository/migrations/postgres/2022-04-01T13-00_create_clinician_store_join_trigger/up.sql
  server/repository/migrations/postgres/2022-06-07T17-00_create_encounter_table/up.sql
  server/repository/migrations/sqlite/2022-04-01T10-00_create_clinician_table/down.sql
  server/repository/migrations/sqlite/2022-04-01T10-00_create_clinician_table/up.sql
  server/repository/migrations/sqlite/2022-04-01T11-00_create_clinician_store_join_table/down.sql
  server/repository/migrations/sqlite/2022-04-01T11-00_create_clinician_store_join_table/up.sql
  server/repository/migrations/sqlite/2022-04-01T12-00_create_clinician_trigger/down.sql
  server/repository/migrations/sqlite/2022-04-01T12-00_create_clinician_trigger/up.sql
  server/repository/migrations/sqlite/2022-04-01T13-00_create_clinician_store_join_trigger/down.sql
  server/repository/migrations/sqlite/2022-04-01T13-00_create_clinician_store_join_trigger/up.sql
  server/repository/migrations/sqlite/2022-06-07T17-00_create_encounter_table/up.sql
  server/repository/migrations/sqlite/2023-01-25T12-00_create_clinician_trigger/up.sql
  server/repository/src/db_diesel/clinician.rs
  server/repository/src/db_diesel/clinician_row.rs
  server/repository/src/db_diesel/encounter.rs
  server/repository/src/db_diesel/encounter_row.rs
  server/service/src/programs/encounter/encounter_schema.rs
  server/service/src/programs/encounter/encounter_updated.rs
  server/service/src/programs/encounter/insert.rs
  server/service/src/programs/encounter/update.rs
  server/service/src/programs/encounter/validate_misc.rs
  server/service/src/programs/schemas/encounter.json
  server/service/src/sync/program_schemas/hiv_care_encounter.json
  server/service/src/sync/program_schemas/hiv_testing_encounter.json
  server/service/src/sync/test/integration/central/report.rs
  server/service/src/sync/test/integration/remote/clinician.rs
  server/service/src/sync/translations/clinician.rs
Labels: programs

#1126 680 hiv testing encounter update
  client/packages/common/src/intl/locales/en/common.json
  client/packages/programs/src/JsonForms/common/components/Array/EnumArray.tsx
  client/packages/programs/src/JsonForms/common/components/Boolean.tsx
  client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/program_schemas/hiv_care_program.json
  server/service/src/sync/program_schemas/hiv_testing_encounter.json
  server/service/src/sync/program_schemas/hiv_testing_encounter_ui_schema.json
  server/service/src/sync/program_schemas/hiv_testing_program.json
  server/service/src/sync/program_schemas/hiv_testing_program_ui_schema.json
Labels: programs, Priority: High

#1156 1133 encounter created datetime
  client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
  server/graphql/programs/src/queries/encounter.rs
  server/graphql/programs/src/types/encounter.rs
  server/repository/migrations/postgres/2022-06-07T17-00_create_encounter_table/up.sql
  server/repository/migrations/sqlite/2022-06-07T17-00_create_encounter_table/up.sql
  server/repository/src/db_diesel/encounter.rs
  server/repository/src/db_diesel/encounter_row.rs
  server/service/src/programs/encounter/encounter_schema.rs
  server/service/src/programs/encounter/encounter_updated.rs
  server/service/src/programs/encounter/update.rs
  server/service/src/programs/encounter/validate_misc.rs
  server/service/src/programs/schemas/encounter.json
  server/service/src/programs/schemas/patient.json
  server/service/src/programs/schemas/program_enrolment.json
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/program_schemas/hiv_care_encounter.json
  server/service/src/sync/program_schemas/hiv_care_program.json
  server/service/src/sync/program_schemas/hiv_testing_encounter.json
  server/service/src/sync/program_schemas/hiv_testing_program.json
  server/service/src/sync/program_schemas/patient.json
  server/service/src/sync/program_schemas/routine_immunisation_3month_encounter.json
  server/service/src/sync/program_schemas/routine_immunisation_5month_encounter.json
  server/service/src/sync/program_schemas/routine_immunisation_6weeks_encounter.json
Labels: programs, Priority: High

#1157 676 add user node
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  server/graphql/programs/src/types/document.rs
Labels: programs, Priority: High

#1148 Some Ux issues from mobile testing
  client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/SearchBar/SearchBar.tsx
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useNextItem.test.tsx
  client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/utils.ts
  client/packages/system/src/Item/ListView/ListView.tsx
  client/packages/system/src/Item/ListView/Toolbar.tsx
  client/packages/system/src/Item/api/api.ts
  client/packages/system/src/Item/api/hooks/useItems/useItems.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/api/api.ts
  server/graphql/location/src/mutations/delete.rs
  server/graphql/stock_line/src/lib.rs
  server/graphql/stock_line/src/mutations/update.rs
  server/repository/src/db_diesel/stock_line.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/allocate/test.rs
Labels: Priority: Low

#1163 #1154 Spacer component
  client/packages/programs/src/JsonForms/common/JsonForm.tsx
  client/packages/programs/src/JsonForms/common/components/Spacer.tsx
  client/packages/programs/src/JsonForms/common/components/index.ts
  server/service/src/sync/program_schemas/hiv_testing_encounter_ui_schema.json
Labels: programs

#1168 Delete inactive name store joins
  server/service/src/sync/test/test_data/name_store_join.rs
  server/service/src/sync/translations/name_store_join.rs
Labels: bug, good first issue, back-end, sync v5, Priority: High

#1132 Enable discovery in windows server
  server/Cargo.lock
  server/README.md
  server/server/Cargo.toml
  server/server/src/discovery.rs
  server/server/src/lib.rs
Labels: programs, Priority: Normal

#1162 Improve the JSONForms rule for the testing encounter
  server/service/src/sync/program_schemas/hiv_testing_encounter_ui_schema.json
Labels: programs, Priority: High

#1149 976 remove transaction from sync initialisation integration
  server/cli/src/cli.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/test/pull_and_push.rs
  server/service/src/sync/translation_and_integration.rs
Labels: back-end, Priority: High

#1160 976 2 integration tests
  server/repository/src/database_settings.rs
  server/service/src/processors/transfer/shipment/test.rs
  server/service/src/sync/sync_buffer.rs
  server/service/src/sync/test/integration/central/inventory_adjustment_reason.rs
  server/service/src/sync/test/integration/central/mod.rs
  server/service/src/sync/test/integration/central/test.rs
  server/service/src/sync/test/integration/remote/invoice.rs
  server/service/src/sync/test/integration/remote/stock_line.rs
  server/service/src/sync/test/integration/remote/stocktake.rs
  server/service/src/sync/test/integration/remote/test.rs
  server/service/src/sync/test/test_data/stock_line.rs
  server/service/src/sync/translations/stock_line.rs
Labels: back-end, Priority: High

#1161 1155 encounter enrolment node
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/Encounter/utils.ts
  client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/ListView.tsx
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/program_enrolment.rs
  server/graphql/programs/src/mutations/program_enrolment/insert.rs
  server/graphql/programs/src/mutations/program_enrolment/update.rs
  server/graphql/programs/src/queries/program_enrolment.rs
  server/graphql/programs/src/types/encounter.rs
  server/graphql/programs/src/types/program_enrolment.rs
  server/repository/migrations/postgres/2022-06-07T16-00_create_program_enrolment_table/up.sql
  server/repository/migrations/sqlite/2022-06-07T16-00_create_program_enrolment_table/up.sql
  server/repository/src/db_diesel/program_enrolment.rs
  server/repository/src/db_diesel/program_enrolment_row.rs
  server/service/src/programs/program_enrolment/program_enrolment_updated.rs
  server/service/src/programs/program_enrolment/query.rs
  server/service/src/programs/program_enrolment/upsert.rs
Labels: programs

#1159 676(1) Encounter headers and side panel
  client/packages/common/src/hooks/useQueryParams/types.ts
  client/packages/common/src/intl/locales/en/patients.json
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/Encounter/DetailView/AppBarButtons.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/SidePanel.tsx
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
  server/service/src/sync/init_programs_data.rs
  server/service/src/sync/program_schemas/hiv_care_encounter.json
  server/service/src/sync/program_schemas/hiv_testing_encounter.json
Labels: programs, Priority: High

#1167 973 pack to one preference
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  server/service/src/invoice_line/inbound_shipment_line/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/update/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/update/mod.rs
  server/service/src/processors/transfer/shipment/common.rs
  server/service/src/processors/transfer/shipment/create_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/update_inbound_shipment.rs
Labels: needs details/discussion

#1186 Create stocktake from location
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
  client/packages/system/src/MasterList/api/operations.generated.ts
  client/packages/system/src/MasterList/api/operations.graphql
  server/graphql/stocktake/src/mutations/insert.rs
  server/service/src/stocktake/insert.rs
Labels: enhancement, Priority: Normal
