Repository msupply-foundation/open-msupply, pull requests merged in 2024-04, with the labels that each got.

#3217 3143 fetching patient from central
  client/packages/system/src/Patient/CreatePatientModal/FetchPatientModal.tsx
  client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
  client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts
  client/packages/system/src/Patient/ListView/AppBarButtons.tsx
  client/packages/system/src/Patient/api/hooks/utils/usePatientApi.ts
  client/packages/system/src/Sync/api/hooks/index.ts
  client/packages/system/src/Sync/api/hooks/utils/index.ts
  client/packages/system/src/Sync/api/hooks/utils/useSyncStatus.ts
  server/service/src/programs/patient/search_central.rs
Labels: bug, Team Tauhou, Severity: High

#3484 3458 Fix receiving stock more than once in the stock transfer
  client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
  server/repository/src/db_diesel/invoice_line_row.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
Labels: bug, Severity: Hotfix, Severity: High

#3512 Unable to load Inbound shipments list view
  client/packages/common/src/intl/currency/currency.ts
  client/packages/common/src/intl/number/IntlNumber.ts
  client/packages/common/src/intl/utils/index.ts
Labels: bug, Severity: Hotfix

#3508 3242 Outbound shipment line edit modal truncating important column values, over crowded with horizontal scroll
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
Labels: bug, Severity: Normal, docs: done

#3510 3441 ensure sync buffer merge records don't override upserts/delete
  server/service/src/sync/api/common_records.rs
Labels: bug, Team Tauhou, Severity: High

#3513 Correct hook implementation
  client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureTooltipLayout.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx
  client/packages/coldchain/src/Sensor/Components/SensorLineForm.tsx
  client/packages/coldchain/src/Sensor/ListView/ListView.tsx
  client/packages/coldchain/src/common/utils.ts
Labels: bug, Severity: Normal

#3516 #3308 Implement disabling of completed returns
  client/packages/invoices/src/Returns/InboundListView/ListView.tsx
  client/packages/invoices/src/Returns/OutboundListView/ListView.tsx
  client/packages/invoices/src/utils.ts
Labels: enhancement, Team Ruru 🦉, feature: returns

#3530 3525 Outbound shipment status is automatically switching back to New in case of stock-transfer (to desktop-store)
  server/service/src/processors/transfer/shipment/update_outbound_shipment_status.rs
Labels: bug, Team Tauhou, Severity: Hotfix

#3454 Upload documents for status logs
  client/packages/coldchain/src/Equipment/Components/AssetLogPanel.tsx
  client/packages/coldchain/src/Equipment/DetailView/StatusTab.tsx
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/coldchain/src/Equipment/DetailView/UploadTab.tsx
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/inputs/Upload/Upload.tsx
  client/packages/common/src/ui/icons/File.tsx
  client/packages/common/src/ui/icons/FileUpload.tsx
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/config/src/config.ts
Labels: Team Piwakawaka, feature: CCEI

#3429 3139 import asset from spreadsheet
  client/packages/coldchain/src/Equipment/Components/AssetLogPanel.tsx
  client/packages/coldchain/src/Equipment/DetailView/StatusTab.tsx
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/coldchain/src/Equipment/DetailView/UploadTab.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/ImportPanel.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/ImportReviewDataTable.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/ImportTab.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/ReviewTab.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/index.ts
  client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetInsert.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetUpdate.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/package.json
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
  client/packages/common/src/ui/components/inputs/Upload/Upload.tsx
  client/packages/common/src/ui/components/inputs/Upload/index.ts
  client/packages/common/src/ui/components/inputs/index.ts
  client/packages/common/src/ui/components/loading/InlineProgress/InlineProgress.tsx
  client/packages/common/src/ui/components/loading/InlineProgress/index.ts
  client/packages/common/src/ui/components/loading/index.ts
  client/packages/common/src/ui/components/steppers/ClickableStepper/ClickableStepper.test.tsx
  client/packages/common/src/ui/components/steppers/ClickableStepper/ClickableStepper.tsx
  client/packages/common/src/ui/components/steppers/ClickableStepper/index.ts
  client/packages/common/src/ui/components/steppers/index.ts
  client/packages/common/src/ui/icons/File.tsx
  client/packages/common/src/ui/icons/FileUpload.tsx
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/config/src/config.ts
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
  client/packages/system/src/Asset/api/operations.generated.ts
  client/packages/system/src/Asset/api/operations.graphql
  client/yarn.lock
  server/graphql/asset/src/lib.rs
  server/graphql/asset/src/mutations/insert.rs
  server/graphql/asset/src/types.rs
  server/graphql/core/src/simple_generic_errors.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/migrations/v1_08_00/assets/asset.rs
  server/repository/src/migrations/v1_08_00/assets/asset_catalogue_item.rs
  server/repository/src/mock/asset.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/tests/insert.rs
  server/service/src/asset/tests/update.rs
  server/service/src/asset/update.rs
  server/service/src/asset/validate.rs
  server/service/src/sync/test/test_data/asset.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3545 3543 Fix outbound shipment not including service charge in total
  server/service/src/invoice/outbound_shipment/update/generate.rs
Labels: bug, needs triage, Severity: Hotfix

#3505 3017.5 fix clippy warnings
  server/graphql/core/src/loader/asset_location.rs
  server/repository/src/db_diesel/assets/asset_internal_location.rs
  server/repository/src/db_diesel/assets/asset_log_row.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/server/src/print/label.rs
  server/server/src/print/mod.rs
  server/service/src/asset/delete.rs
  server/service/src/asset/location.rs
  server/service/src/asset/tests/update.rs
  server/service/src/asset/update.rs
  server/service/src/asset/validate.rs
  server/service/src/plugin/validation.rs
  server/service/src/plugin_data/insert.rs
  server/service/src/print/label.rs
  server/service/src/processors/mod.rs
  server/service/src/processors/transfer/requisition/create_response_requisition.rs
  server/service/src/processors/transfer/requisition/mod.rs
  server/service/src/processors/transfer/requisition/test.rs
  server/service/src/processors/transfer/requisition/update_request_requisition_status.rs
  server/service/src/processors/transfer/shipment/common.rs
  server/service/src/processors/transfer/shipment/create_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/mod.rs
  server/service/src/processors/transfer/shipment/test.rs
  server/service/src/processors/transfer/shipment/update_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/update_outbound_shipment_status.rs
  server/service/src/programs/contact_trace/query.rs
  server/service/src/programs/contact_trace/upsert.rs
  server/service/src/programs/encounter/encounter_fields.rs
  server/service/src/programs/encounter/extract_fields.rs
  server/service/src/programs/encounter/insert.rs
  server/service/src/programs/encounter/query.rs
  server/service/src/programs/patient/insert_patient.rs
  server/service/src/programs/patient/patient_updated.rs
  server/service/src/programs/patient/update_patient.rs
  server/service/src/programs/patient/upsert_program_patient.rs
Labels: needs architecture/solution, Priority: Should have, refactor, Team Tauhou, Tooling

#3533 #3212 Pack variants in Returns
  client/packages/common/src/utils/arrays/ArrayUtils.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/Returns/InboundDetailView/columns.ts
  client/packages/invoices/src/Returns/OutboundDetailView/columns.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/system/src/Item/Components/PackVariant/PackVariantCell.tsx
  client/packages/system/src/Item/Components/PackVariant/PackVariantEntryCell.tsx
Labels: enhancement, Team Ruru 🦉, feature: returns

#3539 3496 inventory adjustment view stock tab
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentDirectionSearchInput.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentForm.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/index.ts
  client/packages/system/src/Stock/Components/StockLineEditModal.tsx
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/Components/StyledInputRow.tsx
  client/packages/system/src/Stock/api/hooks/index.ts
  client/packages/system/src/Stock/api/hooks/keys.ts
  client/packages/system/src/Stock/api/hooks/useInventoryAdjustment.ts
  client/packages/system/src/Stock/api/hooks/utils/useStockApi.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  client/packages/system/src/Stock/api/useStockGraphQL.ts
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/inventory_adjustment/Cargo.toml
  server/graphql/inventory_adjustment/lib.rs
  server/graphql/inventory_adjustment/mutations/insert.rs
  server/graphql/inventory_adjustment/mutations/mod.rs
  server/graphql/lib.rs
Labels: Team Ruru 🦉, feature: inventory adjustments

#3557 3498 pt 1 inventory adjustment permissions
  server/graphql/inventory_adjustment/mutations/insert.rs
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v1_08_00/inventory_adjustment_permissions.rs
  server/repository/src/migrations/v1_08_00/mod.rs
  server/service/src/auth.rs
  server/service/src/login.rs
Labels: Team Ruru 🦉, feature: inventory adjustments

#3566 Rename ver from 1.8 -> 2.0
  package.json
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_00_00/activity_log_add_zero_line.rs
  server/repository/src/migrations/v2_00_00/add_source_site_id.rs
  server/repository/src/migrations/v2_00_00/assets/activity_log.rs
  server/repository/src/migrations/v2_00_00/assets/asset.rs
  server/repository/src/migrations/v2_00_00/assets/asset_catalogue_data.rs
  server/repository/src/migrations/v2_00_00/assets/asset_catalogue_item.rs
  server/repository/src/migrations/v2_00_00/assets/asset_log.rs
  server/repository/src/migrations/v2_00_00/assets/label_printer.rs
  server/repository/src/migrations/v2_00_00/assets/latest_asset_log.rs
  server/repository/src/migrations/v2_00_00/assets/mod.rs
  server/repository/src/migrations/v2_00_00/assets/reference_data.rs
  server/repository/src/migrations/v2_00_00/assets/sync_triggers_central.rs
  server/repository/src/migrations/v2_00_00/central_omsupply.rs
  server/repository/src/migrations/v2_00_00/inventory_adjustment_permissions.rs
  server/repository/src/migrations/v2_00_00/linked_shipment.rs
  server/repository/src/migrations/v2_00_00/mod.rs
  server/repository/src/migrations/v2_00_00/pack_variant.rs
  server/repository/src/migrations/v2_00_00/returns/mod.rs
  server/repository/src/migrations/v2_00_00/returns/return_context_types.rs
  server/repository/src/migrations/v2_00_00/returns/return_invoice_types.rs
  server/repository/src/migrations/v2_00_00/returns/return_permissions.rs
  server/repository/src/migrations/v2_00_00/returns/return_reasons.rs
  server/repository/src/migrations/v2_00_00/store_add_created_date.rs
  server/repository/src/migrations/v2_00_00/sync_file_reference.rs
  server/repository/src/migrations/v2_00_00/user_change_last_synced_to_optional.rs
  server/server/src/print/label.rs
Labels: Priority: Must Have, refactor, Team Tauhou

#3541 Put store at the top of asset creation on central server!
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
Labels: Priority: Should have, Team Piwakawaka, feature: CCEI

#3423 Support multiple SQL report queries
  server/graphql/reports/src/printing.rs
  server/report_builder/src/build.rs
  server/report_builder/src/lib.rs
  server/repository/src/db_diesel/report_query.rs
  server/service/src/report/definition.rs
  server/service/src/report/mod.rs
  server/service/src/report/report_service.rs
  server/service/src/report/string_or_vec.rs
Labels: enhancement, Team Tauhou

#3569 'Code' column title is not visible under Replenishment -> Suppliers #3477
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
  client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx
  client/packages/system/src/Name/Components/CustomerSearchInput/CustomerSearchInput.tsx
  client/packages/system/src/Name/ListView/ListView.tsx
Labels: bug, Team Tauhou, Severity: Normal

#3518 Add program relate report views
  server/repository/src/migrations/v2_00_00/mod.rs
  server/repository/src/migrations/v2_00_00/report_views.rs
Labels: enhancement, Team Tauhou

#3548 Improve/fix SnapshotCountCurrentCountMismatch error
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
Labels: bug, Migrating Existing Mobile, Migrate Existing Desktop, Team Tauhou, Severity: Normal, needs design, docs: external

#3570 Show CCE in sensor list view
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Sensor/Components/SensorLineForm.tsx
  client/packages/coldchain/src/Sensor/ListView/ListView.tsx
  client/packages/coldchain/src/Sensor/api/operations.generated.ts
  client/packages/coldchain/src/Sensor/api/operations.graphql
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  server/Cargo.lock
  server/graphql/asset/src/lib.rs
  server/graphql/asset/src/types.rs
  server/graphql/cold_chain/Cargo.toml
  server/graphql/cold_chain/src/types/sensor.rs
  server/graphql/core/src/loader/asset.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/types/src/types/location.rs
  server/repository/src/db_diesel/location.rs
  server/service/src/location/tests/query.rs
Labels: bug, Priority: Should have, Team Piwakawaka, feature: CCEI, docs: external

#3573 Hide make/model for non-catalogue assets
  client/packages/coldchain/src/Equipment/DetailView/Toolbar.tsx
Labels: bug, Team Piwakawaka, Severity: Low, feature: CCEI

#3571 3465 create new asset catalogue items via import spreadsheet
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Asset/ImportCatalogueItem/CatalogueItemImportModal.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/ImportPanel.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/ImportReviewDataTable.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/ImportTab.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/ReviewTab.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/index.ts
  client/packages/system/src/Asset/ListView/AppBarButtons.tsx
  client/packages/system/src/Asset/ListView/ListView.tsx
  client/packages/system/src/Asset/ListView/Toolbar.tsx
  client/packages/system/src/Asset/api/api.ts
  client/packages/system/src/Asset/api/hooks/document/index.ts
  client/packages/system/src/Asset/api/hooks/document/useAssetItemInsert.ts
  client/packages/system/src/Asset/api/hooks/document/useAssets.ts
  client/packages/system/src/Asset/api/hooks/document/useAssetsDelete.ts
  client/packages/system/src/Asset/api/hooks/index.ts
  client/packages/system/src/Asset/api/hooks/line/useAssets/index.ts
  client/packages/system/src/Asset/api/operations.generated.ts
  client/packages/system/src/Asset/api/operations.graphql
  client/packages/system/src/Asset/utils.ts
  server/Cargo.lock
  server/graphql/asset_catalogue/Cargo.toml
  server/graphql/asset_catalogue/src/asset_catalogue_item_queries.rs
  server/graphql/asset_catalogue/src/lib.rs
  server/graphql/asset_catalogue/src/mutations/delete_catalogue_item.rs
  server/graphql/asset_catalogue/src/mutations/insert_catalogue_item.rs
  server/graphql/asset_catalogue/src/mutations/mod.rs
  server/graphql/asset_catalogue/src/types/asset_catalogue_item.rs
  server/graphql/lib.rs
  server/graphql/types/src/types/activity_log.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/assets/asset_catalogue_item.rs
  server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs
  server/repository/src/migrations/v2_00_00/assets/asset_catalogue_data.rs
  server/repository/src/migrations/v2_00_00/assets/asset_catalogue_item.rs
  server/service/src/catalogue/delete.rs
  server/service/src/catalogue/insert.rs
  server/service/src/catalogue/mod.rs
  server/service/src/catalogue/tests/insert.rs
  server/service/src/catalogue/tests/mod.rs
  server/service/src/sync/test/test_data/asset_catalogue_item.rs
Labels: enhancement, Priority: Must Have, Team Piwakawaka, feature: CCEI, docs: external

#3586 Store filter and status log entry on create
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetInsert.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
  client/packages/coldchain/src/Equipment/api/hooks/log/useAssetLogInsert.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
  client/packages/inventory/src/utils.ts
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/utils.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/SidePanel.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/AdditionalInfoSection.tsx
  client/packages/requisitions/src/utils.ts
  client/packages/system/src/Asset/api/api.ts
  server/graphql/asset/src/types.rs
  server/repository/src/db_diesel/assets/asset.rs
Labels: bug, Team Piwakawaka, feature: CCEI, docs: external

#3572 #3498 Inventory adjustment back-end
  server/graphql/inventory_adjustment/mutations/insert.rs
  server/graphql/types/src/types/activity_log.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/migrations/v2_00_00/inventory_adjustment_logtype.rs
  server/repository/src/migrations/v2_00_00/linked_shipment.rs
  server/repository/src/migrations/v2_00_00/mod.rs
  server/service/src/invoice/inventory_adjustment/generate.rs
  server/service/src/invoice/inventory_adjustment/insert.rs
  server/service/src/invoice/inventory_adjustment/mod.rs
  server/service/src/invoice/inventory_adjustment/validate.rs
  server/service/src/invoice/mod.rs
Labels: Team Ruru 🦉, feature: inventory adjustments

#3582 3500 add new stock line UI
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/system/src/Item/Components/PackVariant/PackVariantInput.tsx
  client/packages/system/src/Item/Components/PackVariant/index.ts
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentForm.tsx
  client/packages/system/src/Stock/Components/NewStockLineModal.tsx
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/Components/StyledInputRow.tsx
  client/packages/system/src/Stock/ListView/AppBarButtons.tsx
  client/packages/system/src/Stock/api/hooks/index.ts
  client/packages/system/src/Stock/api/hooks/useInventoryAdjustment.ts
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/graphql/stock_line/src/lib.rs
  server/graphql/stock_line/src/mutations/insert.rs
  server/graphql/stock_line/src/mutations/mod.rs
Labels: Team Ruru 🦉, feature: inventory adjustments, docs: external

#3594 3503 mass reduce to zero
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationWithChildrenModal.tsx
  client/packages/common/src/ui/components/modals/ConfirmationModal/index.ts
  client/packages/inventory/src/Stocktake/DetailView/ChangeLocationModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/ReduceLinesToZeroModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts
  client/packages/inventory/src/Stocktake/api/hooks/index.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/index.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useChangeLinesLocation.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeSaveLines.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useZeroStocktakeLines.ts
  client/packages/inventory/src/Stocktake/api/hooks/utils/index.ts
  client/packages/inventory/src/Stocktake/api/hooks/utils/useSelectedRows.ts
Labels: Team Ruru 🦉, feature: inventory adjustments, docs: external

#3590 Update doc links #3589
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/system/src/Clinician/ClinicianSearchInput.tsx
  client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx
Labels: enhancement, Team Tauhou

#3610 Handle invoice status "FN" and "fn"
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/translations/invoice.rs
Labels: Team Tauhou

#3578 Handle requisition status "nw"
  server/service/src/sync/translations/requisition.rs
Labels: Team Tauhou

#3603 3457 returns ok next follow table sort
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalLayout.tsx
  client/packages/common/src/ui/components/modals/ConfirmationModal/index.ts
  client/packages/inventory/src/Stocktake/DetailView/ChangeLocationModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/ReduceLinesToZeroModal.tsx
  client/packages/invoices/src/Returns/InboundDetailView/DetailView.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/DetailView.tsx
  client/packages/invoices/src/utils.test.ts
  client/packages/invoices/src/utils.ts
Labels: Team Ruru 🦉, feature: returns

#3599 #3496(2) Adjustment tab query update
  .github/pull_request_template.md
  client/packages/inventory/src/Stocktake/DetailView/ReduceLinesToZeroModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentDirectionSearchInput.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentForm.tsx
  client/packages/system/src/Stock/Components/NewStockLineModal.tsx
  client/packages/system/src/Stock/Components/StockLineEditModal.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/api/hooks/useInventoryAdjustment.ts
Labels: Team Ruru 🦉, feature: inventory adjustments

#3615 Add inventory adjustments feature flag for v2.0.0
  client/README.md
  client/package.json
  client/packages/config/src/config.ts
  client/packages/host/webpack.config.js
  client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
  client/packages/system/src/Stock/Components/StockLineEditModal.tsx
  client/packages/system/src/Stock/ListView/AppBarButtons.tsx
Labels: Team Ruru 🦉, feature: inventory adjustments, docs: done

#3577 Fix parsing pref records
  server/service/src/sync/translations/store_preference.rs
Labels: Team Tauhou

#3593 Add infinite scroll to catalogue items autocomplete
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/coldchain/src/Equipment/api/hooks/document/useAsset.ts
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/usePagination.ts
  client/packages/common/src/hooks/useStringFilter.ts
  client/packages/common/src/index.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/arrays/ArrayUtils.ts
  client/packages/host/src/QueryErrorHandler.tsx
  client/packages/system/src/Asset/api/hooks/document/index.ts
  client/packages/system/src/Asset/api/hooks/document/useAsset.ts
  client/packages/system/src/Asset/api/hooks/document/useInfiniteAssets.ts
  client/packages/system/src/Asset/api/hooks/index.ts
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
  client/packages/system/src/Item/api/hooks/useItem/useItem.ts
  client/packages/system/src/Item/api/hooks/useItemStockOnHand/useItemStockOnHand.tsx
  client/packages/system/src/Item/api/hooks/usePackVariants/usePackVariants.ts
  client/packages/system/src/Log/api/hooks/document/useLogContentsByFileName.ts
  client/packages/system/src/Log/api/hooks/document/useLogFileNames.ts
  client/packages/system/src/Log/api/hooks/document/useLogLevel.ts
  server/graphql/asset_catalogue/src/asset_catalogue_item_queries.rs
  server/repository/src/db_diesel/assets/asset_catalogue_item.rs
Labels: bug, Team Piwakawaka, feature: CCEI

#3612 Ignore bad optionID = "0" when translating invoice_lines
  server/cli/src/refresh_dates.rs
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/translations/invoice_line.rs
Labels: Team Tauhou

#3622 Internal docs for returns
  server/service/src/processors/transfer/shipment/README.md
  server/service/src/processors/transfer/shipment/doc/omSupply_return_transfer.drawio.png
Labels: Team Ruru 🦉, feature: returns, docs: done

#3507 3398 file sync upload to central server
  server/Cargo.lock
  server/Cargo.toml
  server/cli/src/cli.rs
  server/cli/src/refresh_dates.rs
  server/graphql/core/src/lib.rs
  server/graphql/general/src/queries/login.rs
  server/graphql/general/src/sync_api_error.rs
  server/repository/src/db_diesel/assets/asset_log_row.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/sync_file_reference_row.rs
  server/repository/src/migrations/v2_00_00/sync_file_reference.rs
  server/server/Cargo.toml
  server/server/src/lib.rs
  server/server/src/static_files.rs
  server/server/src/sync_on_central/mod.rs
  server/service/Cargo.toml
  server/service/src/static_files.rs
  server/service/src/sync/api_v6/download_file.rs
  server/service/src/sync/api_v6/mod.rs
  server/service/src/sync/file_sync_driver.rs
  server/service/src/sync/file_synchroniser.rs
  server/service/src/sync/mod.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/sync_on_central/mod.rs
  server/service/src/sync/sync_status/logger.rs
  server/service/src/sync/synchroniser_driver.rs
  server/service/src/sync/test/test_data/sync_file_reference.rs
  server/service/src/test_helpers.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3629 3620 validate location barcode ids
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/stock_line.rs
  server/service/src/sync/translations/stocktake_line.rs
  server/service/src/sync/translations/utils.rs
Labels: Migrate Existing Desktop, Team Tauhou

#3651 Nothing sent to query when creating Internal Order #3534
  client/packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx
Labels: bug, Team Tauhou, Severity: High

#3632 Central server indication
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/ui/components/portals/AppFooter/AppFooter.tsx
  client/packages/common/src/ui/icons/Central.tsx
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/components/Footer/Footer.tsx
Labels: enhancement, Team Piwakawaka

#3638 Stop infinite reloading
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
Labels: bug, Team Piwakawaka, Severity: Normal, feature: CCEI

#3616 3601 authorisation required for sync file endpoints
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Documents.tsx
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  server/Cargo.lock
  server/Cargo.toml
  server/server/Cargo.toml
  server/server/src/authentication.rs
  server/server/src/lib.rs
  server/server/src/print/label.rs
  server/server/src/print/mod.rs
  server/server/src/static_files.rs
  server/server/src/support/mod.rs
  server/server/src/sync_on_central/mod.rs
  server/service/Cargo.toml
  server/service/src/sync/api_v6/mod.rs
  server/service/src/sync/api_v6/upload_file.rs
  server/service/src/sync/file_sync_driver.rs
  server/service/src/sync/file_synchroniser.rs
  server/service/src/sync/sync_on_central/mod.rs
  server/util/Cargo.toml
  server/util/src/file.rs
Labels: bug, Team Piwakawaka

#3520 KDD central server codebase
  decisions/2024-03-18_central_server_code_base.md
Labels: Team Ruru 🦉

#3646 3556 after merging items, should oms retain previous merged item name on invoices, requisitions etc.
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/utils.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/useDraftServiceLines.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/StockOut/hooks/usePackSizeController.test.tsx
  client/packages/invoices/src/StockOut/operations.generated.ts
  client/packages/invoices/src/StockOut/operations.graphql
  client/packages/invoices/src/StockOut/utils.test.ts
  client/packages/invoices/src/StockOut/utils.tsx
  client/packages/invoices/src/utils.ts
Labels: bug, Team Tauhou, Severity: High

#3648 3502 new stocktake from expired
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
  server/graphql/stocktake/src/mutations/insert.rs
  server/service/Cargo.toml
  server/service/src/stocktake/insert.rs
Labels: Team Ruru 🦉, feature: inventory adjustments

#3626 Display catalogue item properties
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/coldchain/src/Equipment/types.ts
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  server/graphql/asset/src/types.rs
  server/graphql/core/src/loader/asset_catalogue_item_property.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/repository/src/db_diesel/assets/asset_catalogue_item_property.rs
  server/repository/src/db_diesel/assets/asset_catalogue_property.rs
  server/server/src/logging.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI, docs: external

#3657 3644 Fix Storybook with Feature Flags/Numeric Text fix
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/common/src/ui/components/portals/AppFooter/AppFooter.test.tsx
  client/packages/config/src/config.ts
Labels: bug, Team Ruru 🦉

#3633 Rename asset_type table to asset_catalogue_type
  server/repository/src/db_diesel/assets/asset.rs
  server/repository/src/db_diesel/assets/asset_catalogue_item.rs
  server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/db_diesel/assets/asset_type.rs
  server/repository/src/db_diesel/assets/asset_type_row.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/migrations/v2_00_00/assets/asset.rs
  server/repository/src/migrations/v2_00_00/assets/asset_catalogue_data.rs
  server/repository/src/migrations/v2_00_00/assets/asset_catalogue_item.rs
  server/repository/src/migrations/v2_00_00/assets/reference_data.rs
  server/repository/src/migrations/v2_00_00/assets/sync_triggers_central.rs
  server/service/Cargo.toml
  server/service/src/static_files.rs
  server/service/src/sync/test/test_data/asset_type.rs
  server/service/src/sync/translations/asset_type.rs
Labels: bug, Team Piwakawaka, Severity: Normal

#3661 Fix spelling
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/utils.rs
Labels: enhancement, Priority: Should have, feature: merging

#3653 3652 file sync pr review updates
  client/packages/coldchain/src/Monitoring/ListView/AppBarButtons.tsx
  server/Cargo.lock
  server/server/Cargo.toml
  server/server/src/static_files.rs
  server/server/src/sync_on_central/mod.rs
  server/server/src/upload_fridge_tag.rs
  server/service/Cargo.toml
  server/service/src/lib.rs
  server/service/src/static_files.rs
  server/service/src/sync/api_v6/core.rs
  server/service/src/sync/api_v6/download_file.rs
  server/service/src/sync/api_v6/mod.rs
  server/service/src/sync/api_v6/upload_file.rs
  server/service/src/sync/file_sync_driver.rs
  server/service/src/sync/file_synchroniser.rs
  server/service/src/sync/sync_on_central/mod.rs
Labels: enhancement, Team Ruru 🦉, feature: CCEI

#3583 3118 central server config through m supply central
  server/README.md
  server/graphql/asset/src/mutations/insert.rs
  server/graphql/general/src/lib.rs
  server/graphql/lib.rs
  server/server/src/lib.rs
  server/server/src/middleware/central_server_only.rs
  server/server/src/static_files.rs
  server/service/src/sync/README.md
  server/service/src/sync/api/get_site_info.rs
  server/service/src/sync/api_v6/core.rs
  server/service/src/sync/central_data_synchroniser_v6.rs
  server/service/src/sync/file_sync_driver.rs
  server/service/src/sync/file_synchroniser.rs
  server/service/src/sync/mod.rs
  server/service/src/sync/remote_data_synchroniser.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/sync_on_central/mod.rs
  server/service/src/sync/sync_status/logger.rs
  server/service/src/sync/sync_status/test.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/test/integration/README.md
  server/service/src/sync/test/integration/central/currency.rs
  server/service/src/sync/test/integration/omsupply_central/mod.rs
  server/service/src/sync/test/integration/remote/invoice.rs
  server/service/src/sync/test/integration/remote/mod.rs
  server/service/src/sync/test/integration/remote/stocktake.rs
  server/service/src/sync/test/pull_and_push.rs
  server/util/src/lib.rs
Labels: docs: internal, enhancement, Team Ruru 🦉, feature: central server, docs: external

#3643 3119 omsupply central sync steps
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/host/src/components/SyncProgress/SyncProgress.tsx
  client/packages/system/src/Sync/api/api.ts
  client/packages/system/src/Sync/api/operations.generated.ts
  client/packages/system/src/Sync/api/operations.graphql
  server/graphql/general/src/sync_api_error.rs
  server/repository/src/db_diesel/sync_log_row.rs
  server/repository/src/migrations/v2_00_00/assets/mod.rs
  server/repository/src/migrations/v2_00_00/assets/sync_error_codes.rs
  server/service/src/sync/api_v6/core.rs
  server/service/src/sync/sync_status/logger.rs
  server/service/src/sync/synchroniser.rs
Labels: enhancement, feature: pack variant, Team Ruru 🦉, docs: external

#3623 Use Upsert for soft delete
  server/repository/src/db_diesel/sync_file_reference_row.rs
Labels: bug

#3655 3645 add item name column to requisition line
  client/packages/common/src/intl/locales/pt/app.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/utils.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/useDraftServiceLines.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/StockOut/hooks/usePackSizeController.test.tsx
  client/packages/invoices/src/StockOut/operations.generated.ts
  client/packages/invoices/src/StockOut/operations.graphql
  client/packages/invoices/src/StockOut/utils.test.ts
  client/packages/invoices/src/StockOut/utils.tsx
  client/packages/invoices/src/utils.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/hooks.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  server/graphql/requisition/src/query_tests/requisition_loaders.rs
  server/graphql/types/src/types/requisition_line.rs
  server/repository/src/db_diesel/requisition_line/requisition_line_row.rs
  server/repository/src/db_diesel/stock_on_hand.rs
  server/repository/src/migrations/v2_00_00/mod.rs
  server/repository/src/migrations/v2_00_00/requisition_line_add_item_name.rs
  server/repository/src/migrations/v2_00_00/stock_on_hand_add_item_name.rs
  server/repository/src/mock/test_requisition_queries.rs
  server/service/src/item_stats.rs
  server/service/src/processors/transfer/requisition/create_response_requisition.rs
  server/service/src/report/default_queries.rs
  server/service/src/requisition/request_requisition/generate.rs
  server/service/src/sync/test/test_data/requisition_line.rs
  server/service/src/sync/translations/requisition_line.rs
Labels: enhancement, feature: merging, Team Tauhou

#3664 Performance improvements
  client/packages/common/src/intl/context/IntlContext.tsx
  client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
  client/packages/common/src/ui/layout/tables/components/index.tsx
  client/packages/host/public/index.html
  client/packages/host/webpack.config.js
  server/server/src/serve_frontend.rs
Labels: enhancement, Priority: Should have, Team Piwakawaka

#3678 3522 Shortcut key for master list g+m will logged you out
  client/packages/host/src/CommandK.tsx
Labels: bug, Team Tauhou, Severity: High

#3676 Change Outbound Shipment list default sort from "Created" to "Number"? #3092
  client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
Labels: enhancement, Priority: Should have, Team Tauhou

#3673 3647 add item name column to stocktake line
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/utils.ts
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/inventory/src/Stocktake/api/operations.graphql
  server/graphql/stocktake_line/src/mutations/insert.rs
  server/graphql/stocktake_line/src/mutations/update.rs
  server/graphql/types/src/types/stocktake_line.rs
  server/repository/src/db_diesel/stocktake_line_row.rs
  server/repository/src/migrations/v2_00_00/mod.rs
  server/repository/src/migrations/v2_00_00/stocktake_line_add_item_name.rs
  server/repository/src/mock/stocktake_line.rs
  server/service/src/stocktake/insert.rs
  server/service/src/stocktake_line/insert.rs
  server/service/src/stocktake_line/update.rs
  server/service/src/sync/test/test_data/stocktake_line.rs
  server/service/src/sync/translations/stocktake_line.rs
Labels: enhancement, feature: merging, Team Tauhou

#3671 Move requisition create shipment button
  client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/CreateShipmentButton.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/Footer.tsx
Labels: enhancement, Team Piwakawaka, needs design, docs: external

#3685 tidy confirmation message
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/common/src/intl/strings/IntlStrings.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/StatusChangeButton.tsx
Labels: enhancement, Team Piwakawaka, needs design

#3698 Default to local server
  client/package.json
Labels: refactor, Team Piwakawaka

#3619 #3618 decimal pack size kdd
  decisions/2024-04-15_decimal_pack_size.md
Labels: KDD, Team Tauhou

#3707 3531 Translations breaking
  client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
Labels: bug, Severity: Low

#3710 3581 code required on patient creation but there is no indication
  client/packages/programs/src/JsonForms/components/IdGenerator.tsx
  client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
Labels: bug, Severity: High, docs: external

#3694 3568 Current patient selection modal makes it seem like the store has 0 patients
  client/packages/system/src/Patient/Components/PatientSearchModal/PatientSearchModal.tsx
Labels: bug, Priority: Must Have, Team Tauhou

#3712 3428 remove breadcrums from supplier modal
  client/packages/system/src/Name/DetailModal/DetailModal.tsx
Labels: bug, Severity: High

#3693 Soft Delete for Asset Catalogue Items
  server/repository/src/db_diesel/assets/asset_catalogue_item.rs
  server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs
  server/repository/src/migrations/v2_00_00/assets/asset_catalogue_item.rs
  server/service/src/catalogue/delete.rs
  server/service/src/catalogue/insert.rs
  server/service/src/sync/test/test_data/asset_catalogue_item.rs
Labels: bug, Team Piwakawaka, Severity: High, feature: CCEI

#3720 advance v6 push cursor after initialisation
  server/service/src/sync/remote_data_synchroniser.rs
Labels: bug, Team Ruru 🦉, Severity: High
