Repository msupply-foundation/open-msupply, pull requests merged in 2024-02, with the labels that each got.

#2863 Rename item_link_id for requisition lines
  server/graphql/core/src/loader/requisition_line.rs
  server/graphql/core/src/loader/requisition_supply_status.rs
  server/graphql/requisition/src/mutations/request_requisition/add_from_master_list.rs
  server/graphql/requisition/src/mutations/request_requisition/use_suggested_quantity.rs
  server/graphql/requisition/src/mutations/response_requisition/supply_requested_quantity.rs
  server/graphql/requisition/src/query_tests/requisition_loaders.rs
  server/graphql/requisition_line/src/mutations/request_requisition_line/insert.rs
  server/graphql/requisition_line/src/mutations/request_requisition_line/update.rs
  server/graphql/requisition_line/src/mutations/response_requisition_line/update.rs
  server/graphql/types/src/types/requisition_line.rs
  server/repository/src/db_diesel/changelog/test.rs
  server/repository/src/db_diesel/requisition_line/requisition_line.rs
  server/repository/src/db_diesel/requisition_line/requisition_line_row.rs
  server/repository/src/mock/test_remaining_to_supply.rs
  server/repository/src/mock/test_requisition_line_repository.rs
  server/repository/src/mock/test_requisition_queries.rs
  server/repository/src/mock/test_requisition_service.rs
  server/service/src/item_stats.rs
  server/service/src/processors/transfer/requisition/create_response_requisition.rs
  server/service/src/processors/transfer/requisition/test.rs
  server/service/src/requisition/request_requisition/add_from_master_list.rs
  server/service/src/requisition/request_requisition/generate.rs
  server/service/src/requisition/requisition_supply_status.rs
  server/service/src/requisition_line/chart/mod.rs
  server/service/src/requisition_line/request_requisition_line/insert.rs
  server/service/src/requisition_line/response_line_stats/mod.rs
  server/service/src/requisition_line/response_line_stats/response_line_stats.rs
  server/service/src/sync/test/test_data/requisition_line.rs
  server/service/src/sync/translations/requisition_line.rs
Labels: back-end, Priority: Should have, merging

#2879 Add option for login layout background image size
  client/packages/common/src/styles/theme.ts
  client/packages/host/src/components/Login/LoginLayout.tsx
Labels: enhancement

#2864 Rename item_link_id for stocktake lines
  server/graphql/stocktake_line/src/mutations/insert.rs
  server/graphql/stocktake_line/src/mutations/update.rs
  server/graphql/stocktake_line/src/stocktake_line_queries.rs
  server/graphql/types/src/types/stocktake_line.rs
  server/repository/src/db_diesel/stocktake_line_row.rs
  server/repository/src/mock/stocktake_line.rs
  server/repository/src/mock/test_stocktake.rs
  server/service/src/stocktake/insert.rs
  server/service/src/stocktake/update.rs
  server/service/src/stocktake_line/delete.rs
  server/service/src/stocktake_line/insert.rs
  server/service/src/stocktake_line/update.rs
  server/service/src/stocktake_line/validate.rs
  server/service/src/sync/test/test_data/stocktake_line.rs
  server/service/src/sync/translations/stocktake_line.rs
Labels: merging

#2869 2840 link column rename encounter
  server/graphql/types/src/types/program/encounter.rs
  server/repository/src/db_diesel/encounter.rs
  server/repository/src/db_diesel/encounter_row.rs
  server/service/src/programs/encounter/encounter_fields.rs
  server/service/src/programs/encounter/encounter_updated.rs
  server/service/src/programs/encounter/update.rs
  server/service/src/sync/integrate_document.rs
Labels: merging

#2870 Rename patient_link_id for ProgramEnrolmentRow
  server/graphql/core/src/loader/program_enrolment.rs
  server/graphql/types/src/types/program/program_enrolment.rs
  server/repository/src/db_diesel/patient.rs
  server/repository/src/db_diesel/program_enrolment.rs
  server/repository/src/db_diesel/program_enrolment_row.rs
  server/service/src/programs/encounter/insert.rs
  server/service/src/programs/program_enrolment/program_enrolment_updated.rs
  server/service/src/programs/program_enrolment/upsert.rs
  server/service/src/sync/integrate_document.rs
Labels: merging

#2872 Rename supplier_link_id for StockLineRow
  server/repository/src/db_diesel/stock_line_row.rs
  server/repository/src/mock/stock_line.rs
  server/repository/src/mock/test_item_stats.rs
  server/repository/src/mock/test_requisition_queries.rs
  server/repository/src/mock/test_stocktake.rs
  server/repository/src/mock/test_stocktake_line.rs
  server/repository/src/tests.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/generate.rs
  server/service/src/repack/insert.rs
  server/service/src/stocktake/insert.rs
  server/service/src/stocktake/update.rs
  server/service/src/sync/test/test_data/stock_line.rs
  server/service/src/sync/translations/stock_line.rs
Labels: merging

#2874 Rename manufacturer_link_id for BarcodeRow
  server/graphql/types/src/types/barcode.rs
  server/repository/src/db_diesel/barcode_row.rs
  server/repository/src/mock/barcode.rs
  server/service/src/sync/test/test_data/barcode.rs
  server/service/src/sync/translations/barcode.rs
Labels: merging

#2875 Rename clinician_link_id for ClinicianStoreJoinRow
  server/repository/src/db_diesel/clinician.rs
  server/repository/src/db_diesel/clinician_store_join_row.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/sync/translations/clinician_store_join.rs
Labels: merging

#2889 2776 cannot select and delete internal orders
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useDeleteSelectedRequisitions.ts
Labels: bug, Section: Internal Order

#2888 2859 prevent IS changing from new message when status not new
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/common/src/intl/locales/es/replenishment.json
  client/packages/common/src/intl/locales/fr/replenishment.json
  client/packages/common/src/intl/locales/pt/replenishment.json
  client/packages/common/src/intl/locales/tet/replenishment.json
  client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
Labels: bug

#2887 UI tweaks
  client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx
  client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
Labels: bug

#2894 2895 add set up steps for msupply remote site
  client/README.md
  server/README.md
Labels: bug, needs triage

#2901 Add logging on Temperature Logs and Temperature Breaches API Errors
  server/server/src/cold_chain/sensor.rs
  server/server/src/cold_chain/temperature_breach.rs
  server/server/src/cold_chain/temperature_log.rs
Labels: bug, module: coldchain, Team Piwakawaka

#2913 2720 cold chain missing data create temporary breaches
  server/server/src/cold_chain/temperature_log.rs
Labels: bug, module: coldchain, Team Piwakawaka

#2914 2812 gql codegen unrunnable code
  client/codegen.yml
  client/package.json
  client/packages/invoices/src/StockOut/operations.generated.ts
  client/packages/invoices/src/StockOut/operations.graphql
Labels: bug, refactor, Team Ruru 🦉

#2924 Make final column auto-width
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
Labels: bug, Team Ruru 🦉

#2899 2290 sqlite db config
  server/android/src/android.rs
  server/repository/src/database_settings.rs
  server/repository/src/test_db/postgres.rs
  server/repository/src/test_db/sqlite.rs
Labels: enhancement, Priority: Should have

#2916 2885 merging fix integration tests
  server/repository/Cargo.toml
  server/repository/src/database_settings.rs
  server/repository/src/db_diesel/unit_row.rs
  server/repository/src/migrations/v1_07_00/mod.rs
  server/repository/src/migrations/v1_07_00/unit_add_is_active.rs
  server/repository/src/mock/unit.rs
  server/service/src/processors/transfer/shipment/test.rs
  server/service/src/sync/test/integration/README.md
  server/service/src/sync/test/integration/central/master_list.rs
  server/service/src/sync/test/integration/central/name_and_store_and_name_store_join.rs
  server/service/src/sync/test/integration/central/unit_and_item.rs
  server/service/src/sync/test/integration/mod.rs
  server/service/src/sync/test/integration/remote/clinician.rs
  server/service/src/sync/test/integration/remote/invoice.rs
  server/service/src/sync/test/integration/remote/location_movement.rs
  server/service/src/sync/test/integration/remote/mod.rs
  server/service/src/sync/test/integration/remote/patient_name_and_store_and_name_store_join.rs
  server/service/src/sync/test/integration/remote/program_requisition.rs
  server/service/src/sync/test/integration/remote/requisition.rs
  server/service/src/sync/test/integration/remote/stock_line.rs
  server/service/src/sync/test/integration/remote/stocktake.rs
  server/service/src/sync/test/integration/transfer/shipments.rs
  server/service/src/sync/test/mod.rs
  server/service/src/sync/test/test_data/unit.rs
  server/service/src/sync/translations/unit.rs
Labels: back-end, Priority: Should have, merging, Team Tauhou

#2880 Outbound shipment allocation - unable to type multi digit quantities
  client/packages/common/src/hooks/useDebounce/useDebouncedValueCallback.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
Labels: bug, Priority: Should have

#2907 2572 ok next short cuts
  client/packages/common/src/hooks/useDialog/useDialog.tsx
  client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useDraftStocktakeLines.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
Labels: enhancement, needs details/discussion, Priority: Should have, make omSupply delightful, Team Ruru 🦉

#2794 #1440 #2491 Number component refactor
  client/packages/common/src/intl/currency/currency.ts
  client/packages/common/src/intl/number/IntlNumber.ts
  client/packages/common/src/ui/components/inputs/Filters/NumberFilter.tsx
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/TextInput.stories.tsx
  client/packages/common/src/ui/components/inputs/TextInput/index.ts
  client/packages/common/src/ui/components/inputs/TextInput/numeric/NonNegativeIntegerInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/numeric/NonNegativeNumberInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/numeric/NumericTextInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/numeric/PositiveNumberInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/numeric/index.ts
  client/packages/common/src/ui/components/modals/InputModal/InputModal.stories.tsx
  client/packages/common/src/ui/components/modals/InputModal/InputModal.tsx
  client/packages/common/src/ui/components/modals/InputModal/NonNegativeNumberInputModal.tsx
  client/packages/common/src/ui/components/modals/InputModal/index.ts
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeDecimalCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NonNegativeIntegerCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/PositiveNumberInputCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/index.ts
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTabs.tsx
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/useServiceLineColumns.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/TaxEdit.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/useServiceLineColumns.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/modals/TaxEdit.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditTable.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/StockOut/utils.tsx
  client/packages/programs/src/JsonForms/common/components/Number.tsx
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
  client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEditForm.tsx
  client/packages/system/src/Item/DetailView/Tabs/General.tsx
  client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx
Labels: front-end, Priority: Nice to Have, refactor

#2922 2912 add timezone agnostic date time for picker
  client/packages/common/package.json
  client/packages/common/src/intl/utils/DateUtils.test.ts
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/common/src/utils/formatters/formatters.test.ts
  client/packages/programs/src/JsonForms/common/components/Date.tsx
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
  client/yarn.lock
Labels: Urgency: Hotfix

#2892 Add some more docs about the used backend layers
  server/architecture.md
Labels: enhancement

#2927 Improve stocktake detail view speed
  client/packages/common/src/hooks/useEditModal/useEditModal.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
  client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
  client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx
  client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx
  client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
  client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useDraftStocktakeLines.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useNextItem.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts
  client/packages/inventory/src/Stocktake/api/api.ts
  client/packages/inventory/src/Stocktake/api/hooks/document/useStocktakeFields.ts
  client/packages/inventory/src/Stocktake/api/hooks/index.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/index.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeDeleteSelectedLines.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeItems.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeLines.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts
  client/packages/inventory/src/Stocktake/api/hooks/utils/useStocktakeApi.ts
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/inventory/src/Stocktake/api/operations.graphql
  client/packages/system/src/Item/ListView/ListView.tsx
  server/graphql/core/src/loader/stocktake_lines.rs
  server/graphql/stocktake_line/src/stocktake_line_queries.rs
  server/repository/src/db_diesel/stock_line.rs
  server/repository/src/db_diesel/stocktake_line.rs
  server/service/src/stocktake/delete.rs
  server/service/src/stocktake/insert.rs
  server/service/src/stocktake/update.rs
  server/service/src/stocktake/validate.rs
  server/service/src/stocktake_line/delete.rs
  server/service/src/stocktake_line/insert.rs
  server/service/src/stocktake_line/mod.rs
  server/service/src/stocktake_line/query.rs
  server/service/src/stocktake_line/update.rs
Labels: Urgency: Hotfix

#2928 2921 select lines from inbound
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/index.ts
  client/packages/invoices/src/Returns/api/hooks/line/index.ts
  client/packages/invoices/src/Returns/api/hooks/line/useNewSupplierReturnLines.ts
  client/packages/invoices/src/Returns/api/hooks/utils/index.ts
  client/packages/invoices/src/Returns/api/hooks/utils/useReturnsApi.ts
  client/packages/invoices/src/Returns/api/index.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/index.ts
  client/packages/invoices/src/Returns/modals/NewReturnItems/NewReturnItems.tsx
  client/packages/invoices/src/Returns/modals/NewReturnItems/ReturnQuantitiesTable.tsx
  client/packages/invoices/src/Returns/modals/NewReturnItems/index.ts
  client/packages/invoices/src/Returns/modals/NewReturnItems/useDraftNewReturnLines.ts
  client/packages/invoices/src/Returns/modals/index.ts
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/general/src/queries/new_supplier_return.rs
  server/graphql/invoice/src/invoice_queries.rs
  server/graphql/types/src/types/invoice_query.rs
Labels: enhancement, Team Ruru 🦉

#2919 2658 patient list add filter for program enrollments
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/Filters/FilterMenu.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
  client/packages/system/src/Patient/ListView/Toolbar.tsx
  server/graphql/types/src/types/program/patient.rs
  server/repository/src/db_diesel/patient.rs
Labels: enhancement, programs, Priority: Nice to Have, Team Tauhou

#2943 #2912 hot fix
  client/packages/common/package.json
  client/packages/common/src/intl/utils/DateUtils.test.ts
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/common/src/utils/formatters/formatters.test.ts
  client/packages/programs/src/JsonForms/common/components/Date.tsx
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
  client/yarn.lock
Labels: bug, Team Piwakawaka, Urgency: Hotfix

#2946 Move migrations to correct folder
  server/repository/src/migrations/v1_06_00/indexes.rs
  server/repository/src/migrations/v1_06_00/mod.rs
  server/repository/src/migrations/v1_06_00/patient_id_indices.rs
  server/repository/src/migrations/v1_07_00/changelog_add_name_link_id.rs
  server/repository/src/migrations/v1_07_00/mod.rs
  server/repository/src/migrations/v1_07_00/sync_log.rs
Labels: bug, Team Tauhou, Urgency: High

#2995 2994 New program enrolment name is breaking build
  server/repository/src/db_diesel/patient.rs
Labels: bug, Team Tauhou, Urgency: High

#2934 2929 add reason step
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/index.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInsertSupplierReturn.ts
  client/packages/invoices/src/Returns/api/hooks/index.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/modals/NewReturnItems/NewReturnItems.tsx
  client/packages/invoices/src/Returns/modals/NewReturnItems/ReturnQuantitiesTable.tsx
  client/packages/invoices/src/Returns/modals/NewReturnItems/ReturnReasonsTable.tsx
  client/packages/invoices/src/Returns/modals/NewReturnItems/useDraftNewReturnLines.ts
  client/packages/invoices/src/Returns/modals/NewReturnItems/useDraftReturnLines.ts
  client/packages/system/src/ReturnReason/Components/ReturnReasonSearchInput.tsx
  client/packages/system/src/ReturnReason/Components/index.ts
  client/packages/system/src/ReturnReason/api/api.ts
  client/packages/system/src/ReturnReason/api/hooks/document/index.ts
  client/packages/system/src/ReturnReason/api/hooks/document/useReturnReasons.ts
  client/packages/system/src/ReturnReason/api/hooks/index.ts
  client/packages/system/src/ReturnReason/api/hooks/utils/index.ts
  client/packages/system/src/ReturnReason/api/hooks/utils/useReturnReasonApi.ts
  client/packages/system/src/ReturnReason/api/index.ts
  client/packages/system/src/ReturnReason/api/operations.generated.ts
  client/packages/system/src/ReturnReason/api/operations.graphql
  client/packages/system/src/ReturnReason/index.ts
  client/packages/system/src/index.ts
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/general/src/queries/new_supplier_return.rs
  server/graphql/general/src/queries/return_reason.rs
  server/graphql/invoice/src/lib.rs
  server/graphql/invoice/src/mutations/mod.rs
  server/graphql/invoice/src/mutations/supplier_return/insert.rs
  server/graphql/invoice/src/mutations/supplier_return/mod.rs
Labels: Team Ruru 🦉

#2954 #2920 Outbound returns detail view - skeleton
  client/packages/common/src/intl/locales/en/app.json
  client/packages/config/src/routes.ts
  client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
  client/packages/host/src/routers/ReplenishmentRouter.tsx
  client/packages/invoices/src/InvoiceService.tsx
  client/packages/invoices/src/Returns/DetailView/DetailView.tsx
  client/packages/invoices/src/Returns/DetailView/index.ts
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/index.ts
  client/packages/invoices/src/Returns/api/hooks/document/useOutboundReturn.ts
  client/packages/invoices/src/Returns/api/hooks/index.ts
  client/packages/invoices/src/Returns/api/hooks/utils/useReturnsApi.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/index.ts
Labels: Team Ruru 🦉

#2930 Remove openssl as a dependency (to fix Android build on Macs)
  server/Cargo.lock
  server/Cargo.toml
  server/cli/Cargo.toml
  server/graphql/form_schema/Cargo.toml
  server/graphql/plugin/Cargo.toml
  server/graphql/programs/Cargo.toml
  server/report_builder/Cargo.toml
  server/server/Cargo.toml
  server/service/Cargo.toml
Labels: enhancement, Team Tauhou

#2997 2953 supplier return list view
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/common/src/types/schema.ts
  client/packages/config/src/routes.ts
  client/packages/invoices/src/InvoiceService.tsx
  client/packages/invoices/src/Returns/ListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/ListView/ListView.tsx
  client/packages/invoices/src/Returns/ListView/Toolbar.tsx
  client/packages/invoices/src/Returns/ListView/index.ts
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/index.ts
  client/packages/invoices/src/Returns/api/hooks/document/useOutboundDeleteRows.ts
  client/packages/invoices/src/Returns/api/hooks/document/useOutbounds.ts
  client/packages/invoices/src/Returns/api/hooks/document/useOutboundsAll.ts
  client/packages/invoices/src/Returns/api/hooks/index.ts
  client/packages/invoices/src/Returns/api/hooks/utils/useReturnsApi.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/index.ts
  client/packages/invoices/src/utils.ts
  server/graphql/invoice/src/invoice_queries.rs
  server/graphql/invoice/src/lib.rs
  server/graphql/invoice/src/mutations/supplier_return/delete.rs
  server/graphql/invoice/src/mutations/supplier_return/mod.rs
Labels: enhancement, Team Ruru 🦉

#2878 2669 throw error on failure to delete inbound shipment line
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/InboundShipment/api/hooks/line/useDeleteSelectedLines.ts
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/delete.rs
  server/repository/src/mock/invoice_line.rs
  server/repository/src/mock/item.rs
  server/service/src/invoice/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/delete/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/delete/validate.rs
  server/service/src/invoice_line/validate.rs
Labels: bug

#3004 2998 inbound returns list view
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/common/src/types/schema.ts
  client/packages/config/src/routes.ts
  client/packages/host/src/components/Navigation/DistributionNav.tsx
  client/packages/host/src/routers/DistributionRouter.tsx
  client/packages/invoices/src/InvoiceService.tsx
  client/packages/invoices/src/Returns/InboundListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/InboundListView/ListView.tsx
  client/packages/invoices/src/Returns/InboundListView/Toolbar.tsx
  client/packages/invoices/src/Returns/InboundListView/index.ts
  client/packages/invoices/src/Returns/OutboundListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/OutboundListView/ListView.tsx
  client/packages/invoices/src/Returns/OutboundListView/Toolbar.tsx
  client/packages/invoices/src/Returns/OutboundListView/index.ts
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/index.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInboundDeleteRows.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInbounds.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInboundsAll.ts
  client/packages/invoices/src/Returns/api/hooks/index.ts
  client/packages/invoices/src/Returns/api/hooks/utils/useReturnsApi.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/index.ts
  client/packages/invoices/src/utils.ts
  server/graphql/invoice/src/invoice_queries.rs
  server/graphql/invoice/src/lib.rs
  server/graphql/invoice/src/mutations/customer_return/delete.rs
  server/graphql/invoice/src/mutations/customer_return/mod.rs
  server/graphql/invoice/src/mutations/mod.rs
  server/graphql/types/src/types/invoice_query.rs
Labels: enhancement, Team Ruru 🦉

#3016 3005 Remove constraint on barcode manufacturer link id
  server/repository/src/migrations/v1_07_00/barcode_add_manufacturer_link_id.rs
  server/service/src/sync/translations/barcode.rs
Labels: bug

#3007 Update the "Add" SplitButton dependent on the active tab
  client/packages/system/src/Patient/PatientView/AddButton.tsx
Labels: enhancement, programs, Priority: Nice to Have, Team Tauhou

#2891 Add support to build Android with ndk 26 and Rust 1.76
  client/packages/android/build_remote_server_libs.sh
  server/Cargo.lock
  server/Cargo.toml
  server/cli/Cargo.toml
  server/graphql/form_schema/Cargo.toml
  server/graphql/plugin/Cargo.toml
  server/graphql/programs/Cargo.toml
  server/report_builder/Cargo.toml
  server/server/Cargo.toml
  server/service/Cargo.toml
Labels: enhancement, Team Tauhou

#3034 Fix cargo warnings
  server/graphql/general/src/mutations/update_user.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/general/src/queries/sync_status.rs
  server/graphql/general/src/queries/temperature_chart.rs
  server/graphql/invoice/src/query_tests/invoices.rs
  server/graphql/types/src/types/activity_log.rs
  server/graphql/types/src/types/invoice_query.rs
  server/graphql/types/src/types/name.rs
  server/graphql/types/src/types/program/contact_trace.rs
  server/graphql/types/src/types/program/encounter.rs
  server/graphql/types/src/types/program/program_enrolment.rs
  server/graphql/types/src/types/program/program_event.rs
  server/graphql/types/src/types/repack.rs
  server/graphql/types/src/types/requisition.rs
  server/graphql/types/src/types/sensor.rs
  server/graphql/types/src/types/stocktake.rs
  server/graphql/types/src/types/temperature_breach.rs
  server/graphql/types/src/types/temperature_log.rs
  server/graphql/types/src/types/temperature_notification.rs
  server/repository/src/database_settings.rs
  server/repository/src/db_diesel/activity_log.rs
  server/repository/src/db_diesel/barcode.rs
  server/repository/src/db_diesel/document.rs
  server/repository/src/db_diesel/inventory_adjustment_reason.rs
  server/repository/src/db_diesel/location.rs
  server/repository/src/db_diesel/location_movement.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/plugin_data.rs
  server/repository/src/db_diesel/sensor.rs
  server/repository/src/db_diesel/stock_line.rs
  server/repository/src/db_diesel/stocktake_line.rs
  server/repository/src/db_diesel/temperature_breach.rs
  server/repository/src/db_diesel/temperature_breach_config.rs
  server/repository/src/db_diesel/temperature_log.rs
  server/repository/src/mock/document.rs
  server/server/src/support/database.rs
  server/service/src/document/document_service.rs
  server/service/src/programs/contact_trace/upsert.rs
  server/service/src/programs/program_enrolment/upsert.rs
  server/service/src/sync/integrate_document.rs
  server/service/src/sync/translations/document.rs
  server/util/src/lib.rs
Labels: bug, chore

#3024 3008 create outbound return from list view
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/invoices/src/Returns/OutboundListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInsertSupplierReturn.ts
Labels: enhancement, Team Ruru 🦉

#3037 3014 add new inbound return from list view
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/invoices/src/Returns/InboundListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInsertInboundReturn.ts
Labels: enhancement, Team Ruru 🦉

#3039 3038 map to stock line ids
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/utils/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/utils/useSelectedStockLineIds.ts
  client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/OutboundShipment/api/hooks/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/useSelectedStockLineIds.ts
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/line/useInboundReturnLines.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/utils.ts
  server/graphql/general/src/queries/generate_inbound_return_lines.rs
  server/graphql/general/src/queries/generate_outbound_return_lines.rs
Labels: refactor, Team Ruru 🦉

#3036 Add catalogue table
  server/repository/src/db_diesel/assets/asset_catalogue_item.rs
  server/repository/src/db_diesel/assets/asset_catalogue_item_row.rs
  server/repository/src/db_diesel/assets/mod.rs
  server/repository/src/migrations/v1_08_00/assets/asset_catalogue_item.rs
  server/repository/src/migrations/v1_08_00/assets/mod.rs
Labels: enhancement, Team Piwakawaka, module: CCEI

#3046 Fix barcode tests
  server/service/src/sync/test/test_data/barcode.rs
Labels: bug, Team Piwakawaka, Urgency: High

#2893 2865 update invoice and invoice line mutations to save currency
  server/graphql/invoice/src/mutations/inbound_shipment/update.rs
  server/graphql/invoice/src/mutations/outbound_shipment/error.rs
  server/graphql/invoice/src/mutations/outbound_shipment/update.rs
  server/graphql/types/src/types/invoice_line.rs
  server/graphql/types/src/types/invoice_query.rs
  server/repository/src/db_diesel/currency.rs
  server/repository/src/db_diesel/invoice_line.rs
  server/repository/src/db_diesel/invoice_line_row.rs
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/migrations/v1_07_00/invoice_add_currency_fields.rs
  server/repository/src/mock/invoice_line.rs
  server/repository/src/mock/test_outbound_shipment_update.rs
  server/repository/src/mock/test_requisition_queries.rs
  server/repository/src/mock/test_requisition_service.rs
  server/repository/src/mock/test_unallocated_line.rs
  server/repository/src/tests.rs
  server/service/src/invoice/common.rs
  server/service/src/invoice/inbound_shipment/generate.rs
  server/service/src/invoice/inbound_shipment/insert/generate.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice/inbound_shipment/update/validate.rs
  server/service/src/invoice/outbound_shipment/generate.rs
  server/service/src/invoice/outbound_shipment/insert/generate.rs
  server/service/src/invoice/outbound_shipment/update/generate.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/invoice/outbound_shipment/update/validate.rs
  server/service/src/invoice/prescription/insert/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/update/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/mod.rs
  server/service/src/invoice_line/inbound_shipment_service_line/update/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/update/mod.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/mod.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/update/mod.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/processors/transfer/shipment/common.rs
  server/service/src/processors/transfer/shipment/create_inbound_shipment.rs
  server/service/src/report/default_queries.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/update.rs
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/invoice_line.rs
Labels: back-end, currency, Team Tauhou

#3049 2972 create asset tables
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/assets/asset.rs
  server/repository/src/db_diesel/assets/asset_catalogue_item.rs
  server/repository/src/db_diesel/assets/asset_internal_location_row.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/db_diesel/assets/mod.rs
  server/repository/src/migrations/v1_08_00/assets/asset.rs
  server/repository/src/migrations/v1_08_00/assets/mod.rs
  server/repository/src/mock/mod.rs
Labels: enhancement, Team Piwakawaka, module: CCEI

#3061 Fix stocktake detail cache invalidation
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeLines.ts
  client/packages/inventory/src/Stocktake/api/hooks/utils/useStocktakeApi.ts
Labels: bug, Team Piwakawaka, Urgency: High

#3065 3035 populate class category and type reference data as a migration1(data tidy)
  server/repository/src/migrations/v1_08_00/assets/asset_catalogue_data.rs
Labels: enhancement, Team Piwakawaka, module: CCEI

#3053 3043 generate outbound return lines
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/modals/OutboundReturn/ReturnQuantitiesTable.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/useDraftOutboundReturnLines.ts
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/generate_outbound_return_lines.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/outbound_return_line.rs
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/service/src/auth.rs
  server/service/src/invoice/mod.rs
  server/service/src/invoice/outbound_return/generate_outbound_return_lines.rs
  server/service/src/invoice/outbound_return/mod.rs
  server/service/src/login.rs
Labels: enhancement, Team Ruru 🦉

#3058 3056 schema changes for returns
  server/graphql/types/src/types/invoice_query.rs
  server/repository/src/db_diesel/invoice_line_row.rs
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/number_row.rs
  server/repository/src/db_diesel/return_reason_row.rs
  server/repository/src/migrations/v1_07_00/mod.rs
  server/repository/src/migrations/v1_07_00/return_reasons.rs
  server/repository/src/migrations/v1_07_00/return_types.rs
  server/repository/src/mock/invoice_line.rs
  server/repository/src/mock/test_outbound_shipment_update.rs
  server/repository/src/mock/test_requisition_queries.rs
  server/repository/src/mock/test_requisition_service.rs
  server/repository/src/mock/test_unallocated_line.rs
  server/repository/src/tests.rs
  server/service/src/invoice/inbound_shipment/generate.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice/outbound_shipment/generate.rs
  server/service/src/invoice/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/number.rs
  server/service/src/processors/transfer/shipment/common.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/update.rs
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/invoice_line.rs
Labels: enhancement, Team Ruru 🦉

#3062 3035 populate class category and type reference data as a migration
  server/repository/src/migrations/v1_08_00/assets/asset_catalogue_data.rs
  server/repository/src/migrations/v1_08_00/assets/mod.rs
Labels: enhancement, Team Piwakawaka, module: CCEI

#3047 2960 map temperature log datetimes to local
  server/service/src/sensor/berlinger.rs
Labels: bug, Priority: Should have, Team Piwakawaka

#3069 3068 remove item id from stock out line inputs
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/api/api.ts
  client/packages/invoices/src/Prescriptions/api/api.ts
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/prescription_line/insert.rs
  server/graphql/invoice_line/src/mutations/prescription_line/update.rs
  server/graphql/tests/permissions.rs
  server/service/src/invoice/outbound_shipment/batch.rs
  server/service/src/invoice/prescription/batch.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/allocate/generate.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/insert/mod.rs
  server/service/src/invoice_line/stock_out_line/insert/validate.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
  server/service/src/invoice_line/stock_out_line/update/validate.rs
Labels: refactor, Team Ruru 🦉

#3080 Remove all om_* fields from transfered generated in mSupply
  server/service/src/sync/translations/invoice.rs
Labels: bug, Priority: Must Have, Migrating Existing Mobile, Team Tauhou

#3077 3059 insert outbound return
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/modals/InboundReturn/useDraftInboundReturnLines.ts
  client/packages/invoices/src/Returns/modals/OutboundReturn/useDraftOutboundReturnLines.ts
  client/packages/invoices/src/Returns/modals/ReturnReasonsTable.tsx
  client/packages/system/src/ReturnReason/Components/ReturnReasonSearchInput.tsx
  client/packages/system/src/ReturnReason/api/api.ts
  client/packages/system/src/ReturnReason/api/operations.generated.ts
  client/packages/system/src/ReturnReason/api/operations.graphql
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/generate_inbound_return_lines.rs
  server/graphql/general/src/queries/return_reason.rs
  server/graphql/invoice/src/invoice_queries.rs
  server/graphql/invoice/src/lib.rs
  server/graphql/invoice/src/mutations/inbound_return/insert.rs
  server/graphql/invoice/src/mutations/outbound_return/insert.rs
  server/graphql/types/src/types/invoice_line.rs
  server/graphql/types/src/types/invoice_query.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/outbound_return_line.rs
  server/graphql/types/src/types/return_reason.rs
  server/repository/src/db_diesel/invoice_line_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/return_reason.rs
  server/repository/src/mock/invoice.rs
  server/repository/src/mock/invoice_line.rs
  server/repository/src/mock/mod.rs
  server/service/src/invoice/mod.rs
  server/service/src/invoice/outbound_return/generate_outbound_return_lines.rs
  server/service/src/invoice/outbound_return/insert/generate.rs
  server/service/src/invoice/outbound_return/insert/mod.rs
  server/service/src/invoice/outbound_return/insert/validate.rs
  server/service/src/invoice/outbound_return/mod.rs
  server/service/src/invoice_line/mod.rs
  server/service/src/invoice_line/stock_out_line/mod.rs
  server/service/src/invoice_line/update_return_reason_id/mod.rs
  server/service/src/invoice_line/update_return_reason_id/validate.rs
  server/service/src/lib.rs
  server/service/src/return_reason.rs
Labels: enhancement, Team Ruru 🦉

#3102 KDD: File Sync
  decisions/2024-02-28_file_sync.md
  decisions/media/file_sync.png
Labels: enhancement, Priority: Must Have, Team Piwakawaka, feature: CCEI

#3095 2967 Create, Update, Delete and & Query Assets
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/asset/Cargo.toml
  server/graphql/asset/src/lib.rs
  server/graphql/asset/src/mutations/delete.rs
  server/graphql/asset/src/mutations/insert.rs
  server/graphql/asset/src/mutations/mod.rs
  server/graphql/asset/src/mutations/update.rs
  server/graphql/asset/src/types.rs
  server/graphql/core/src/generic_inputs.rs
  server/graphql/lib.rs
  server/repository/src/db_diesel/assets/asset.rs
  server/repository/src/migrations/v1_08_00/assets/asset.rs
  server/repository/src/mock/asset.rs
  server/repository/src/mock/mod.rs
  server/service/src/asset/delete.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/mod.rs
  server/service/src/asset/query.rs
  server/service/src/asset/tests/insert.rs
  server/service/src/asset/tests/mod.rs
  server/service/src/asset/tests/query.rs
  server/service/src/asset/tests/update.rs
  server/service/src/asset/update.rs
  server/service/src/asset/validate.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3067 2963 add service layer and graphql for queries of assets, catalogues and types
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/catalogue/Cargo.toml
  server/graphql/catalogue/src/asset_catalogue_item_queries.rs
  server/graphql/catalogue/src/asset_category_queries.rs
  server/graphql/catalogue/src/asset_class_queries.rs
  server/graphql/catalogue/src/asset_type_queries.rs
  server/graphql/catalogue/src/lib.rs
  server/graphql/lib.rs
  server/graphql/types/src/types/asset_catalogue_item.rs
  server/graphql/types/src/types/asset_category.rs
  server/graphql/types/src/types/asset_class.rs
  server/graphql/types/src/types/asset_type.rs
  server/graphql/types/src/types/mod.rs
  server/repository/src/db_diesel/assets/asset_catalogue_item.rs
  server/repository/src/db_diesel/assets/asset_category.rs
  server/repository/src/db_diesel/assets/asset_class.rs
  server/repository/src/db_diesel/assets/asset_type.rs
  server/repository/src/db_diesel/mod.rs
  server/service/src/catalogue/mod.rs
  server/service/src/catalogue/query_catalogue_item.rs
  server/service/src/catalogue/query_category.rs
  server/service/src/catalogue/query_class.rs
  server/service/src/catalogue/query_type.rs
  server/service/src/catalogue/tests/mod.rs
  server/service/src/catalogue/tests/query_catalogue_item.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3096 3052 Cannot choose the time correctly in date-time picker
  client/packages/common/src/intl/utils/IntlUtils.ts
  client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
  client/packages/programs/src/JsonForms/common/components/DateTime.tsx
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
Labels: bug, feature: programs, Team Tauhou, Severity: High

#3082 #2932 Number fixes
  client/packages/common/src/intl/currency/currency.test.tsx
  client/packages/common/src/intl/number/IntlNumber.ts
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/programs/src/JsonForms/components/EncounterLineChart.tsx
  client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx
Labels: bug, Team Ruru 🦉, Severity: High

#2902 2830 currency selection for inbound shipment
  client/packages/common/src/intl/currency/currency.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell/CurrencyCell.tsx
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/system/src/Currency/Components/CurrencyModal.tsx
  client/packages/system/src/Currency/Components/CurrencySearchInput.tsx
  client/packages/system/src/Currency/Components/index.ts
  client/packages/system/src/Currency/api/api.ts
  client/packages/system/src/Currency/api/hooks/document/index.ts
  client/packages/system/src/Currency/api/hooks/document/useCurrencies.ts
  client/packages/system/src/Currency/api/hooks/index.ts
  client/packages/system/src/Currency/api/hooks/utils/index.ts
  client/packages/system/src/Currency/api/hooks/utils/useCurrencyApi.ts
  client/packages/system/src/Currency/api/index.ts
  client/packages/system/src/Currency/api/operations.generated.ts
  client/packages/system/src/Currency/api/operations.graphql
  client/packages/system/src/Currency/index.ts
  client/packages/system/src/index.ts
  server/graphql/invoice/src/mutations/inbound_shipment/update.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice/inbound_shipment/update/validate.rs
Labels: enhancement, feature: currency, Team Tauhou
