Repository msupply-foundation/open-msupply, pull requests merged in 2024-12, with the labels that each got.

#5651 Allow editing of asset number
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  server/graphql/asset/src/mutations/update.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/update.rs
  server/service/src/asset/validate.rs
Labels: enhancement, Priority: Must Have, Team Piwakawaka, feature: CCEI, feature: GAPS

#5668 5591 fix integration tests
  server/service/src/processors/transfer/requisition/test.rs
  server/service/src/sync/central_data_synchroniser.rs
  server/service/src/sync/test/integration/README.md
  server/service/src/sync/test/integration/remote/invoice.rs
  server/service/src/sync/test/integration/remote/location.rs
  server/service/src/sync/test/integration/remote/location_movement.rs
  server/service/src/sync/test/integration/remote/mod.rs
  server/service/src/sync/test/integration/remote/requisition.rs
  server/service/src/sync/test/integration/remote/stock_line.rs
  server/service/src/sync/test/integration/remote/stocktake.rs
  server/service/src/sync/test/integration/transfer/requisition.rs
  server/service/src/sync/test/integration/transfer/returns.rs
  server/service/src/sync/test/integration/transfer/shipments.rs
  server/service/src/sync/test/test_data/item.rs
  server/service/src/sync/translations/item.rs
Labels: bug, Team Ruru 🦉, Severity: High

#5657 5584 Updated program icons/styles
  client/packages/common/src/styles/theme.ts
  client/packages/host/public/medical-icons.css
  client/packages/host/webpack.config.js
  client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx
  client/packages/programs/src/icons/Contraceptive.tsx
  client/packages/programs/src/icons/Docs.tsx
  client/packages/programs/src/icons/GenderBasedViolence.tsx
  client/packages/programs/src/icons/Gynaecological.tsx
  client/packages/programs/src/icons/Haemotology.tsx
  client/packages/programs/src/icons/Heart.tsx
  client/packages/programs/src/icons/Immunization.tsx
  client/packages/programs/src/icons/IndexTesting.tsx
  client/packages/programs/src/icons/Liver.tsx
  client/packages/programs/src/icons/Lungs.tsx
  client/packages/programs/src/icons/LungsVirus.tsx
  client/packages/programs/src/icons/MedicalBag.tsx
  client/packages/programs/src/icons/MedicalChart.tsx
  client/packages/programs/src/icons/MedicalHistory.tsx
  client/packages/programs/src/icons/Medication.tsx
  client/packages/programs/src/icons/Microscope.tsx
  client/packages/programs/src/icons/Nutrition.tsx
  client/packages/programs/src/icons/Pregnancy.tsx
  client/packages/programs/src/icons/Referrals.tsx
  client/packages/programs/src/icons/Stethoscope.tsx
  client/packages/programs/src/icons/TestTube.tsx
  client/packages/programs/src/icons/Virus.tsx
  client/packages/programs/src/icons/VisitType.tsx
  client/packages/programs/src/icons/_gradient.tsx
  client/packages/programs/src/icons/index.ts
  client/packages/programs/src/index.ts
  client/packages/system/src/ContactTrace/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  project-words.txt
Labels: enhancement, feature: programs, Team Piwakawaka

#5653 5600 move docs link to help page
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/navigation/ExternalNavLink.tsx
  client/packages/host/src/Admin/UserGuide.tsx
  client/packages/host/src/Help/Help.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
Labels: feature: GEDSI, Team Korimako

#5698 Only one story and straight to bed!
  client/packages/common/src/ui/components/charts/NewValueBar/NewValueBar.stories.tsx
Labels: bug

#5707 Add R&R form tetum translations
  client/packages/common/src/intl/locales/tet/replenishment.json
Labels: bug, Team Piwakawaka, Severity: Hotfix

#5708 5659 CIV 2.5 emergency order configs
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/charts/NewValueBar/NewValueBar.stories.tsx
  client/packages/common/src/ui/icons/Emergency.tsx
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/Footer/StatusChangeButton.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/ProgramRequisitionOptions.tsx
  client/packages/requisitions/src/RequestRequisition/api/api.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/StatusChangeButton.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ProgramRequisitionOptions.tsx
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  server/graphql/core/src/simple_generic_errors.rs
  server/graphql/requisition/src/mutations/request_requisition/update.rs
  server/graphql/requisition/src/mutations/response_requisition/update.rs
  server/graphql/requisition/src/program_settings.rs
  server/repository/src/db_diesel/program_requisition/program.rs
  server/repository/src/db_diesel/program_requisition/program_requisition_order_type_row.rs
  server/repository/src/db_diesel/program_requisition/program_requisition_settings.rs
  server/repository/src/migrations/v2_05_00/add_emergency_orders.rs
  server/repository/src/migrations/v2_05_00/mod.rs
  server/repository/src/mock/program_order_types.rs
  server/service/src/requisition/common.rs
  server/service/src/requisition/request_requisition/update/mod.rs
  server/service/src/requisition/request_requisition/update/validate.rs
  server/service/src/requisition/response_requisition/update.rs
  server/service/src/sync/sync_serde.rs
  server/service/src/sync/test/test_data/program_requisition_settings.rs
  server/service/src/sync/translations/program_requisition_settings.rs
Labels: enhancement, Team Ruru 🦉, feature: CIV

#5714 Add comments for FE filter
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorsTab.tsx
Labels: enhancement, Team Ruru 🦉, feature: CIV

#5680 5601 add feedback form inputs
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/icons/Mail.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/host/src/Help/FeedbackForm.tsx
  client/packages/host/src/Help/FeedbackSection.tsx
  client/packages/host/src/Help/Help.tsx
  client/packages/host/src/api/hooks/help/useFeedbackForm.ts
Labels: feature: GEDSI, Team Korimako

#5716 5599 adjust settings page permissions
  client/packages/host/src/Admin/DisplaySettings.tsx
  client/packages/host/src/Admin/SettingTextArea.tsx
  client/packages/host/src/Admin/Settings.tsx
  client/packages/host/src/Admin/SettingsSection.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
Labels: feature: GEDSI, Team Korimako

#5726 5691 Encounter delete fix
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
Labels: bug, feature: programs, Team Piwakawaka, Severity: High

#5715 5643(2) Re-use usePatchState hook
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/usePatchState/index.ts
  client/packages/common/src/hooks/usePatchState/usePatchState.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescription.ts
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/programs/src/api/hooks/useVaccineCourse.ts
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
Labels: Team Piwakawaka, feature: dispensing

#5700 5643 refactor prescription hooks
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/usePatchState/index.ts
  client/packages/common/src/hooks/usePatchState/usePatchState.ts
  client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
  client/packages/invoices/src/Prescriptions/DetailView/ContentArea.tsx
  client/packages/invoices/src/Prescriptions/DetailView/DetailView.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/hooks/useDraftPrescriptionLines.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/hooks/useNextItem.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/ListView/AppBarButtons.tsx
  client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
  client/packages/invoices/src/Prescriptions/ListView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/api/api.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/index.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescription.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionById.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionDelete.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionDeleteRows.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionFields.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionInsert.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionUpdate.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptions.ts
  client/packages/invoices/src/Prescriptions/api/hooks/index.ts
  client/packages/invoices/src/Prescriptions/api/hooks/keys.ts
  client/packages/invoices/src/Prescriptions/api/hooks/line/index.ts
  client/packages/invoices/src/Prescriptions/api/hooks/line/usePrescriptionDeleteLines.ts
  client/packages/invoices/src/Prescriptions/api/hooks/line/usePrescriptionItems.ts
  client/packages/invoices/src/Prescriptions/api/hooks/line/usePrescriptionLine.ts
  client/packages/invoices/src/Prescriptions/api/hooks/line/usePrescriptionRows.ts
  client/packages/invoices/src/Prescriptions/api/hooks/line/usePrescriptionSaveLines.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescription.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionDelete.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionLines.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionList.ts
  client/packages/invoices/src/Prescriptions/api/hooks/utils.ts
  client/packages/invoices/src/Prescriptions/api/hooks/utils/index.ts
  client/packages/invoices/src/Prescriptions/api/hooks/utils/usePrescriptionApi.ts
  client/packages/invoices/src/Prescriptions/api/hooks/utils/usePrescriptionIsDisabled.ts
  client/packages/invoices/src/Prescriptions/api/hooks/utils/usePrescriptionNumber.ts
  client/packages/invoices/src/Prescriptions/api/index.ts
  client/packages/invoices/src/Prescriptions/api/usePrescriptionGraphQL.ts
  client/packages/invoices/src/Prescriptions/api/utils/index.ts
  client/packages/invoices/src/Prescriptions/api/utils/usePrescriptionApi.ts
  client/packages/invoices/src/Prescriptions/api/utils/usePrescriptionIsDisabled.ts
  client/packages/invoices/src/Prescriptions/api/utils/usePrescriptionNumber.ts
  client/packages/programs/src/JsonForms/components/Prescription/Prescription.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/programs/src/api/hooks/useVaccineCourse.ts
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
Labels: Team Piwakawaka, feature: dispensing

#5684 5602 create feedback form table
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/contact_form.rs
  server/repository/src/db_diesel/contact_form_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_05_00/add_contact_form_table.rs
  server/repository/src/migrations/v2_05_00/mod.rs
Labels: feature: GEDSI, Team Korimako

#5719 5548 refactor internal orders column sorting
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
  client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/RequestRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  server/graphql/requisition/src/requisition_queries.rs
  server/repository/src/db_diesel/requisition/mod.rs
  server/repository/src/db_diesel/requisition/requisition.rs
Labels: bug, enhancement, good first issue, Severity: Low, Team Korimako

#5727 Fix queries on item usage report
  server/graphql/types/src/types/item_stats.rs
  server/reports/item-usage/2_3_0/convert_data_js/input.json
  server/reports/item-usage/2_3_0/convert_data_js/output.json
  server/reports/item-usage/2_3_0/convert_data_js/src/utils.js
  server/reports/item-usage/2_3_0/convert_data_js/src/utils.test.ts
  server/reports/item-usage/2_3_0/src/expiringInSixMonths.postgres.sql
  server/reports/item-usage/2_3_0/src/expiringInSixMonths.sqlite.sql
  server/reports/item-usage/2_3_0/src/expiringInTwelveMonths.postgres.sql
  server/reports/item-usage/2_3_0/src/expiringInTwelveMonths.sqlite.sql
  server/reports/item-usage/2_3_0/src/query.graphql
  server/reports/item-usage/2_3_0/src/stockOnOrder.sql
  server/service/src/item_stats.rs
Labels: bug, Team Ruru 🦉, Severity: High

#5728 Update export csv to map data to correct headings
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/src/intl/locales/en/common.json
Labels: bug, good first issue, Severity: High, feature: CCEI, feature: GAPS, Team Korimako

#5732 Update to use getNaiveDate instead of getDateOrNull
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
Labels: bug, good first issue, Severity: Low, Team Korimako

#5734 5733 remove numeric input mode for number inputs
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
Labels: bug, Severity: High, Team Korimako

#5703 5098 a single processor error blocks all future processor events
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/system_log_row.rs
  server/repository/src/migrations/v2_04_01/mod.rs
  server/repository/src/migrations/v2_04_01/system_log_table.rs
  server/service/src/activity_log.rs
  server/service/src/processors/transfer/invoice/mod.rs
  server/service/src/processors/transfer/invoice/update_outbound_invoice_status.rs
  server/service/src/processors/transfer/mod.rs
  server/service/src/processors/transfer/requisition/mod.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/system_log.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/system_log.rs
Labels: bug, Migrate Existing Desktop, Team Piwakawaka, Severity: High, Needs Investigation

#5742 5645 abbreviations table
  server/repository/src/db_diesel/abbreviation.rs
  server/repository/src/db_diesel/abbreviation_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_05_00/abbreviation_create_table.rs
  server/repository/src/migrations/v2_05_00/mod.rs
  server/service/src/sync/test/test_data/abbreviation.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/abbreviation.rs
  server/service/src/sync/translations/mod.rs
Labels: enhancement, Team Piwakawaka, feature: dispensing

#5752 5646 item direction table
  server/repository/src/db_diesel/item_direction.rs
  server/repository/src/db_diesel/item_direction_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_05_00/item_direction_create_table.rs
  server/repository/src/migrations/v2_05_00/mod.rs
  server/service/src/sync/test/test_data/item_direction.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/item_direction.rs
  server/service/src/sync/translations/mod.rs
Labels: Team Piwakawaka, feature: dispensing

#5744 5603 service layer contact
  server/Cargo.lock
  server/repository/src/db_diesel/contact_form_row.rs
  server/service/Cargo.toml
  server/service/src/contact_form/insert/generate.rs
  server/service/src/contact_form/insert/mod.rs
  server/service/src/contact_form/insert/test.rs
  server/service/src/contact_form/insert/validate.rs
  server/service/src/contact_form/mod.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
Labels: feature: GEDSI, Team Korimako

#5760 5604 graphql layer contact
  client/packages/common/src/types/schema.ts
  client/packages/host/src/Help/FeedbackForm.tsx
  client/packages/host/src/Help/FeedbackSection.tsx
  client/packages/host/src/Help/Help.tsx
  client/packages/host/src/api/hooks/help/useFeedbackForm.ts
  client/packages/host/src/api/hooks/help/useFeedbackFormGraphQL.ts
  client/packages/host/src/api/operations.generated.ts
  client/packages/host/src/api/operations.graphql
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/contact_form/Cargo.toml
  server/graphql/contact_form/src/lib.rs
  server/graphql/contact_form/src/mutations/insert.rs
  server/graphql/contact_form/src/mutations/mod.rs
  server/graphql/lib.rs
  server/service/src/auth.rs
  server/service/src/contact_form/mod.rs
Labels: feature: GEDSI, Team Korimako

#5765 Add cost price columns to the view stock page
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: enhancement, good first issue, Team Korimako

#5755 Vagabond/#5578
  client/packages/programs/src/JsonForms/index.ts
  client/packages/programs/src/JsonForms/useJsonFormsHandler.tsx
  client/packages/system/src/ContactTrace/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
Labels: good first issue, Priority: Nice to Have, refactor, Effort: small

#5786 add XOF currency
  client/packages/common/src/intl/currency/currency.ts
Labels: enhancement, good first issue, Priority: Must Have, Team Korimako

#5767 remove contact forms side id
  .github/workflows/server-cargo-clean.yaml
  .github/workflows/server-tests.yaml
  server/graphql/contact_form/src/mutations/insert.rs
  server/repository/src/db_diesel/contact_form_row.rs
  server/repository/src/migrations/v2_05_00/mod.rs
  server/repository/src/migrations/v2_05_00/remove_contact_form_site_id.rs
  server/service/src/contact_form/insert/generate.rs
  server/service/src/contact_form/insert/mod.rs
  server/service/src/contact_form/insert/test.rs
  server/service/src/contact_form/mod.rs
Labels: feature: GEDSI, Team Korimako

#5725 5537 paginated autocomplete
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.stories.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
  client/packages/system/src/Asset/api/hooks/document/useInfiniteAssets.ts
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
  client/packages/system/src/Item/api/hooks/useItemStockOnHand/useItemStockOnHand.tsx
  client/packages/system/src/Store/components/StoreSearchInput/StoreSearchInput.tsx
Labels: bug, Severity: High, Team Korimako

#5759 Update inbound shipment generate.rs to use default item packsize
  server/service/src/invoice/inbound_shipment/add_from_master_list.rs
  server/service/src/invoice/inbound_shipment/generate.rs
Labels: bug, Severity: High, Team Korimako

#5782 5774 revert schema changes
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  server/reports/expiring-items/2_3_0/convert_data_js/src/utils.js
Labels: bug, Team Ruru 🦉, Severity: High

#5796 actions footer component
  client/packages/common/src/ui/components/footer/ActionsFooter.tsx
  client/packages/common/src/ui/components/footer/index.ts
  client/packages/common/src/ui/components/index.ts
  client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
Labels: feature: GEDSI, Team Korimako

#5809 change tooltip placement to top
  client/packages/common/src/ui/layout/tables/components/tooltipPlacement.ts
Labels: bug, good first issue, front-end, Severity: High, Team Korimako

#5547 5182 add logging to reports
  server/cli/src/cli.rs
  server/report_builder/README.md
Labels: enhancement, Priority: Must Have, Team Ruru 🦉, feature: reports

#5816 5690 create email queue table
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/contact_form.rs
  server/repository/src/db_diesel/email_queue_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_05_00/add_email_queue_table.rs
  server/repository/src/migrations/v2_05_00/mod.rs
  server/service/src/invoice/inbound_shipment/add_from_master_list.rs
  server/service/src/invoice/inbound_shipment/generate.rs
Labels: feature: GEDSI, Team Korimako

#5720 5650 dispensing redesigned item add & edit page view
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/InvoiceService.tsx
  client/packages/invoices/src/Prescriptions/DetailView/ContentArea.tsx
  client/packages/invoices/src/Prescriptions/DetailView/DetailView.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/hooks/index.ts
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/hooks/useNextItem.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/AppBarButtons.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/Footer.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PageLayout.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditTable.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/columns.ts
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/index.ts
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/useDraftPrescriptionLines.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/usePrescriptionLineEditRows.ts
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/usePreviousNextItem.ts
  client/packages/invoices/src/Prescriptions/LineEditView/index.ts
  client/packages/programs/src/JsonForms/components/Prescription/Prescription.tsx
  client/packages/system/src/Item/Components/ListItems/ListItems.tsx
Labels: Team Piwakawaka, feature: dispensing

#5815 Sync and repo for diagnosis
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/diagnosis.rs
  server/repository/src/db_diesel/diagnosis_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_05_00/diagnosis_create_table.rs
  server/repository/src/migrations/v2_05_00/mod.rs
  server/service/src/sync/test/test_data/diagnosis.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/diagnosis.rs
  server/service/src/sync/translations/mod.rs
Labels: Team Piwakawaka, feature: dispensing

#5822 5650(2) Dispensing Line Edit UI additional changes
  client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/DetailView/DetailView.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/Footer.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/NavBar.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/useDraftPrescriptionLines.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionLines.ts
  client/packages/programs/src/JsonForms/components/Prescription/Prescription.tsx
  client/packages/programs/src/JsonForms/useJsonForms.tsx
  client/packages/system/src/Item/Components/ListItems/ListItems.tsx
Labels: Team Piwakawaka, feature: dispensing

#5788 Move selection to be first column in list view tables
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx
  client/packages/inventory/src/Stocktake/ListView/ListView.tsx
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/columns.ts
  client/packages/invoices/src/Returns/CustomerListView/ListView.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/columns.ts
  client/packages/invoices/src/Returns/SupplierListView/ListView.tsx
  client/packages/programs/src/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
  client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
  client/packages/system/src/Asset/AssetLogReasons/ListView.tsx
  client/packages/system/src/Asset/ListView/ListView.tsx
  client/packages/system/src/Location/ListView/ListView.tsx
Labels: feature: GEDSI, Team Korimako

#5769 5739 move logout to footer user
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/popover/ClickPopover/ClickPopover.tsx
  client/packages/common/src/ui/forms/Detail/TextWithLabelRow.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/components/Footer/Footer.tsx
  client/packages/host/src/components/Footer/UserDetails.tsx
  client/packages/system/src/utils.ts
Labels: feature: GEDSI, Team Korimako

#5811 5737 validate inputs contact form frontend
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/utils/regex/RegexUtils.test.ts
  client/packages/common/src/utils/regex/RegexUtils.tsx
  client/packages/host/src/Help/ContactForm.tsx
  client/packages/host/src/Help/ContactFormSection.tsx
  client/packages/host/src/Help/Help.tsx
  client/packages/host/src/api/hooks/help/useContactForm.ts
  client/packages/host/src/api/hooks/help/useContactFormGraphQL.ts
  client/packages/host/src/api/hooks/help/useFeedbackForm.ts
  client/packages/host/src/api/hooks/help/useFeedbackFormGraphQL.ts
Labels: feature: GEDSI, Team Korimako

#5845 change portuguese translation of log
  client/packages/common/src/intl/locales/pt/common.json
Labels: bug, good first issue, Severity: High, Team Korimako

#5843 5763 print qr code label
  client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr-DJ/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
Labels: bug, good first issue, Team Korimako

#5853 fix typo
  client/packages/common/src/intl/locales/en/common.json
Labels: bug, good first issue, Team Korimako

#5533 4791 add report versioning
  server/cli/src/cli.rs
  server/graphql/reports/src/lib.rs
  server/graphql/reports/src/reports.rs
  server/report_builder/README.md
  server/repository/src/db_diesel/report.rs
  server/repository/src/db_diesel/report_row.rs
  server/repository/src/migrations/version.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/reports.rs
  server/service/src/report/report_service.rs
  server/service/src/standard_reports.rs
Labels: enhancement, Priority: Must Have, Team Ruru 🦉, feature: reports

#5535 5524 add pick list reports
  client/packages/common/src/intl/locales/en/common.json
  server/cli/src/cli.rs
  server/reports/inbound/2_3_0/manifest.json
  server/reports/inbound/2_3_0/src/footer.html
  server/reports/inbound/2_3_0/src/header.html
  server/reports/inbound/2_3_0/src/inbound.graphql
  server/reports/inbound/2_3_0/src/style.css
  server/reports/inbound/2_3_0/src/template.html
  server/reports/outbound-invoice-landscape-with-logo/2_3_0/manifest.json
  server/reports/outbound-invoice-landscape-with-logo/2_3_0/src/footer.html
  server/reports/outbound-invoice-landscape-with-logo/2_3_0/src/header.html
  server/reports/outbound-invoice-landscape-with-logo/2_3_0/src/outbound.graphql
  server/reports/outbound-invoice-landscape-with-logo/2_3_0/src/style.css
  server/reports/outbound-invoice-landscape-with-logo/2_3_0/src/template.html
  server/reports/outbound-invoice-portrait-with-logo/2_3_0/manifest.json
  server/reports/outbound-invoice-portrait-with-logo/2_3_0/src/footer.html
  server/reports/outbound-invoice-portrait-with-logo/2_3_0/src/header.html
  server/reports/outbound-invoice-portrait-with-logo/2_3_0/src/picklist.graphql
  server/reports/outbound-invoice-portrait-with-logo/2_3_0/src/style.css
  server/reports/outbound-invoice-portrait-with-logo/2_3_0/src/template.html
  server/reports/repack/2_3_0/manifest.json
  server/reports/repack/2_3_0/src/footer.html
  server/reports/repack/2_3_0/src/header.html
  server/reports/repack/2_3_0/src/repack.graphql
  server/reports/repack/2_3_0/src/style.css
  server/reports/repack/2_3_0/src/template.html
  server/reports/requisition/2_3_0/manifest.json
  server/reports/requisition/2_3_0/src/footer.html
  server/reports/requisition/2_3_0/src/header.html
  server/reports/requisition/2_3_0/src/requisition.css
  server/reports/requisition/2_3_0/src/requisitionQuery.graphql
  server/reports/requisition/2_3_0/src/template.html
  server/reports/stock-take-variance/2_3_0/manifest.json
  server/reports/stock-take-variance/2_3_0/src/StockVarianceQuery.graphql
  server/reports/stock-take-variance/2_3_0/src/header.html
  server/reports/stock-take-variance/2_3_0/src/style.css
  server/reports/stock-take-variance/2_3_0/src/template.html
  server/reports/stock-take-with-quantity/2_3_0/manifest.json
  server/reports/stock-take-with-quantity/2_3_0/src/footer.html
  server/reports/stock-take-with-quantity/2_3_0/src/header.html
  server/reports/stock-take-with-quantity/2_3_0/src/stocktake.css
  server/reports/stock-take-with-quantity/2_3_0/src/template.html
  server/reports/stock-take-without-quantity/2_3_0/manifest.json
  server/reports/stock-take-without-quantity/2_3_0/src/footer.html
  server/reports/stock-take-without-quantity/2_3_0/src/header.html
  server/reports/stock-take-without-quantity/2_3_0/src/stocktake.css
  server/reports/stock-take-without-quantity/2_3_0/src/template.html
  server/service/src/report/report_service.rs
Labels: enhancement, Priority: Must Have, feature: reports

#5851 5605 sync contact form
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/contact_form_row.rs
  server/repository/src/mock/contact_form.rs
  server/repository/src/mock/mod.rs
  server/service/src/contact_form/insert/test.rs
  server/service/src/sync/test/test_data/contact_form.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/contact_form.rs
  server/service/src/sync/translations/mod.rs
Labels: feature: GEDSI, Team Korimako

#5754 Handle optional gs1 warranty dates
  server/service/src/asset/parse.rs
Labels: Team Piwakawaka

#5878 Update FP translations
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/programs/src/JsonForms/components/Prescription/StockLineTable.tsx
  client/packages/programs/src/icons/Contraceptive.tsx
  client/packages/programs/src/icons/Liver.tsx
  client/packages/programs/src/icons/LungsVirus.tsx
  client/packages/programs/src/icons/MedicalBag.tsx
  client/packages/programs/src/icons/Referrals.tsx
  client/packages/programs/src/icons/_gradient.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: enhancement

#5855 5223 add permission check for update status
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/common/src/intl/locales/en/common.json
Labels: bug, Severity: High, feature: CCEI, Team Korimako

#5839 add permission check to scan button
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/coldchain/src/Equipment/ListView/AddFromScannerButton.tsx
  client/packages/common/src/intl/locales/en/common.json
Labels: bug, Severity: High, feature: CCEI, Team Korimako

#5856 Add switch for item packs
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/hooks.tsx
Labels: bug, enhancement, Team Ruru 🦉, Severity: High, feature: manual requisition

#5864 modify the tooltips of table column headers
  client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
Labels: bug, good first issue, Severity: Low, Team Korimako

#5790 Requisition info alert modal
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.stories.tsx
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.tsx
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalContext.ts
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalProvider.tsx
  client/packages/common/src/ui/components/modals/ConfirmationModal/useConfirmationModal.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/StatusChangeButton.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar/Toolbar.tsx
Labels: good first issue, Priority: Should have, Effort: small, Team Korimako

#5867 remove currentItem loading check
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
Labels: bug, Severity: Hotfix, Team Korimako

#5840 5805 support option on contact form
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/host/src/Help/ContactForm.tsx
  client/packages/host/src/api/hooks/help/useContactForm.ts
  server/graphql/contact_form/Cargo.toml
  server/graphql/contact_form/src/mutations/insert.rs
  server/service/src/contact_form/insert/generate.rs
  server/service/src/contact_form/insert/mod.rs
  server/service/src/contact_form/insert/test.rs
Labels: feature: GEDSI, Team Korimako

#5887 5806 change button orange text on white to black text
  client/packages/common/src/ui/components/buttons/FlatButton/FlatButton.tsx
  client/packages/common/src/ui/components/buttons/standard/BaseButton.tsx
Labels: feature: GEDSI, Team Korimako

#5905 autofocus first input in add variant modal
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
Labels: bug, feature: GAPS, Team Korimako

#5904 add link to create new variant if none
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
Labels: bug, feature: GAPS, Team Korimako
