Repository msupply-foundation/open-msupply, pull requests merged in 2024-10, with the labels that each got.

#4927 4901 Bug fix - call hook out of function with default id
  client/packages/invoices/src/Returns/CustomerDetailView/Toolbar.tsx
Labels: bug, Severity: Hotfix

#4919 Show Average unit price in prescriptions
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Labels: bug, Severity: High, feature: dispensing

#4911 4900 improve stock numbers backdated
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/hooks/useDraftPrescriptionLines.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/StockOut/utils.tsx
Labels: bug, Priority: Must Have, HUNCHY FUNCHY

#4938 4765 outbound shipment unit price incorrect, when multiple lines are grouped
  client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
Labels: bug, Team Ruru 🦉, Severity: High, docs: external

#4931 #4884 Vax config age range improvement
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
Labels: bug, Team Piwakawaka, Severity: High, feature: vaccine card

#4896 4015 allow filtering view stock page by master list
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/system/src/Patient/Components/ChipTableCell.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/ListView/Toolbar.tsx
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
  client/packages/system/src/Stock/api/hooks/useStockList.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/master_list.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/master_list.rs
  server/graphql/general/src/queries/master_list_line.rs
  server/graphql/stock_line/src/lib.rs
  server/graphql/types/src/types/master_list.rs
  server/graphql/types/src/types/stock_line.rs
  server/repository/src/db_diesel/master_list_line.rs
  server/repository/src/db_diesel/stock_line.rs
  server/service/src/pricing/item_price.rs
  server/service/src/stock_line/tests/query.rs
  server/service/src/sync/test/test_data/master_list_line.rs
Labels: enhancement, Priority: Nice to Have, Team Ruru 🦉

#4942 4941 inbound shipment crashes when status changed to delivered
  client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
Labels: bug, Severity: Hotfix

#4961 4831 dose age labels
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/common/src/types/schema.ts
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
  client/packages/programs/src/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/programs/src/api/hooks/useImmunisationProgram.ts
  client/packages/programs/src/api/hooks/useVaccineCourse.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Patient/PatientView/AddButton.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Patient/VaccinationCard/DetailView.tsx
  client/packages/system/src/Vaccination/Components/SelectBatch.tsx
  client/packages/system/src/Vaccination/Components/SelectItemAndBatch.tsx
  client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/graphql/lib.rs
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/mutations/immunisation/mod.rs
  server/graphql/programs/src/mutations/immunisation/update.rs
  server/graphql/programs/src/mutations/mod.rs
  server/graphql/types/src/types/program/vaccination_card.rs
  server/graphql/types/src/types/vaccine_course_dose.rs
  server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/update_vaccine_course.rs
  server/repository/src/db_diesel/vaccination_card.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_dose_row.rs
  server/repository/src/migrations/v2_03_00/add_vaccine_course_dose_custom_age_label.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/repository/src/migrations/views/mod.rs
  server/service/src/sync/test/test_data/vaccine_course_dose.rs
  server/service/src/vaccine_course/update.rs
Labels: enhancement, Priority: Must Have, Team Piwakawaka, feature: vaccine card

#4914 4900 backdated datetime
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  server/graphql/invoice/src/mutations/prescription/update.rs
  server/graphql/types/src/types/invoice_query.rs
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/migrations/v2_03_00/add_backdated_datetime.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/service/src/invoice/customer_return/insert/generate.rs
  server/service/src/invoice/inbound_shipment/insert/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/outbound_shipment/insert/generate.rs
  server/service/src/invoice/prescription/insert/generate.rs
  server/service/src/invoice/prescription/update/generate.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/invoice/prescription/update/validate.rs
  server/service/src/invoice/supplier_return/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/insert/mod.rs
  server/service/src/invoice_line/stock_out_line/mod.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
  server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/update.rs
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/vaccination/generate.rs
Labels: bug, Priority: Must Have, HUNCHY FUNCHY

#4903 Adds localised links to docs
  client/packages/config/src/routes.ts
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
Labels: bug, Severity: Normal

#4983 4977 Spanish currency crash
  client/packages/common/src/intl/currency/currency.ts
Labels: bug, Team Piwakawaka, Severity: Hotfix

#4976 delete doses on course delete
  server/service/src/vaccine_course/delete.rs
  server/service/src/vaccine_course/test/delete.rs
Labels: bug, Team Piwakawaka, feature: vaccine card

#4982 Add PT option
  client/packages/common/src/intl/utils/IntlUtils.ts
Labels: enhancement, Team Ruru 🦉, docs: external

#4986 4912 Can't create/edit patients with a Date of Birth
  client/packages/system/src/Patient/PatientView/PatientView.tsx
Labels: bug, Team Ruru 🦉, Severity: High

#5008 4997 Notification prefs wording fix
  client/packages/common/src/intl/locales/en/common.json
Labels: bug, Team Ruru 🦉, Severity: High, docs: external

#4988 4963 demographic permissions
  client/packages/common/src/types/schema.ts
  client/packages/system/src/IndicatorsDemographics/api/api.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/utils/useDemographicApi.ts
  client/packages/system/src/IndicatorsDemographics/api/operations.generated.ts
  client/packages/system/src/IndicatorsDemographics/api/operations.graphql
  server/graphql/demographic/src/lib.rs
Labels: bug, Team Ruru 🦉, Severity: High

#5011 4916 batches with <1 doses remaining are showing as 0
  client/packages/system/src/Vaccination/Components/SelectBatch.tsx
Labels: bug, Team Piwakawaka, Severity: Normal, feature: vaccine card

#5013 4992 expiring items report is not translated
  client/packages/common/src/intl/locales/en/common.json
  client/packages/reports/src/ListView/SidePanel.tsx
  server/reports/expiring-items/2_3_0/src/template.html
  server/reports/generated/standard_reports.json
  server/reports/stock-status/2_3_0/src/template.html
Labels: bug, Team Ruru 🦉, Severity: Normal

#5010 4996 inventory adjustment modal height fix
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
Labels: bug, Team Piwakawaka, Severity: High

#5012 #4999 soft delete vaccine course item
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Vaccination/Components/SelectItemAndBatch.tsx
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/graphql/types/src/types/stock_line.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_item.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_item_row.rs
  server/repository/src/migrations/v2_03_00/add_vaccine_course_item_deleted_datetime.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/repository/src/mock/vaccine_course.rs
  server/service/src/sync/test/test_data/vaccine_course_item.rs
  server/service/src/vaccine_course/update.rs
Labels: bug, Team Piwakawaka, Severity: High, feature: vaccine card

#4939 4591 group by item hides batch even if only one line present
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx
  client/packages/common/src/utils/numbers/NumUtils.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditTable.tsx
  client/packages/system/src/Item/Components/PackVariant/PackVariantQuantityCell.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal, Severity: Low

#5019 4891 Update stocktake price column headers
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
Labels: bug, Team Ruru 🦉, Severity: High, docs: external

#5024 Fix intermittent test failure for transfers
  server/service/src/processors/transfer/requisition/test.rs
Labels: bug, Team Ruru 🦉, Severity: High, Needs Investigation

#5027 5014 can give wrong vaccinations on new site
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  server/graphql/types/src/types/program/vaccination_card.rs
  server/repository/src/db_diesel/program_enrolment_row.rs
  server/repository/src/migrations/v2_03_00/add_store_id_to_program_enrolment.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/repository/src/mock/form_schema.rs
  server/service/src/programs/program_enrolment/program_enrolment_updated.rs
  server/service/src/programs/program_enrolment/program_schema.rs
  server/service/src/programs/schemas/program_enrolment.json
  server/service/src/sync/integrate_document.rs
Labels: bug, Team Piwakawaka, Severity: Normal, feature: vaccine card

#4724 4658 reduce central record sync volume kdd
  decisions/2024-04-12_central_server_ui.md
  decisions/2024-08-30_central_sync_queue_pull_reduction.md
Labels: bug, Priority: Must Have, KDD, Needs Investigation

#5044 Fix tests
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/patient.rs
Labels: bug

#5039 5003 months years input fix
  client/packages/common/src/intl/locales/en/programs.json
  client/packages/common/src/ui/layout/tables/components/Cells/MultiNumberInputCell/MultiNumberInputCell.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
Labels: bug, Team Piwakawaka, Severity: Normal, feature: vaccine card

#5030 4808 update login error component
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/styles/theme.ts
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/host/src/components/Login/Login.tsx
  client/packages/host/src/components/Login/LoginError.tsx
Labels: enhancement, Priority: Must Have, Team Ruru 🦉

#5048 Add log on panic to 2.2
  package.json
  server/Cargo.lock
  server/Cargo.toml
  server/android/Cargo.toml
  server/server/Cargo.toml
  server/server/src/main.rs
  server/windows/Cargo.toml
  server/windows/src/windows.rs
Labels: enhancement, Team Ruru 🦉, Severity: Hotfix

#4954 Add standard reports docs
  server/report_builder/README.md
Labels: enhancement, Epic, Team Ruru 🦉

#5038 4991 add report loading messages for rc
  client/packages/common/src/intl/locales/en/common.json
  client/packages/reports/src/DetailView/DetailView.tsx
  client/packages/reports/src/ListView/ListView.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#5040 Use invoice status to adjustStockLines
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/hooks/useDraftPrescriptionLines.tsx
  client/packages/invoices/src/StockOut/hooks/usePackSizeController.test.tsx
  client/packages/invoices/src/StockOut/utils.test.ts
  client/packages/invoices/src/StockOut/utils.tsx
Labels: bug, Team Ruru 🦉, Severity: High

#5020 Fix broken report id urls
  server/cli/src/cli.rs
  server/reports/generated/standard_reports.json
  server/repository/src/migrations/v2_03_00/mod.rs
  server/repository/src/migrations/v2_03_00/remove_stops_from_report_ids.rs
Labels: bug, Team Ruru 🦉, Severity: High

#5054 5053-Store-hardware-id-in-memory
  package.json
  server/server/src/lib.rs
  server/service/src/app_data.rs
Labels: enhancement, needs triage, Severity: Hotfix

#5059 5007 Improve sort order for stock details report
  server/reports/generated/standard_reports.json
  server/reports/stock-detail/2_3_0/src/query.graphql
Labels: bug, Severity: Normal, feature: reports

#5073 Update default log level to Info
  build/windows/omsupply_server.suf
  build/windows/omsupply_standalone.suf
Labels: enhancement

#5076 5056 report descriptions
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/reports/src/DetailView/DetailView.tsx
  client/packages/reports/src/DetailView/Toolbar.tsx
  client/packages/system/src/Report/api/operations.generated.ts
  client/packages/system/src/Report/api/operations.graphql
  server/graphql/reports/src/reports.rs
Labels: enhancement, Team Ruru 🦉, docs: external, feature: reports

#5045 4766 When migrating a finalised stocktake there's no finalised date
  server/service/src/sync/translations/stocktake.rs
Labels: bug, Migrate Existing Desktop, Severity: Low

#5116 5022 fix ledger issues in backdated prescriptions
  server/service/src/invoice_line/outbound_shipment_unallocated_line/allocate/test.rs
  server/service/src/invoice_line/stock_out_line/insert/validate.rs
  server/service/src/invoice_line/stock_out_line/mod.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
  server/service/src/invoice_line/stock_out_line/update/validate.rs
  server/service/src/invoice_line/validate.rs
  server/service/src/stock_line/historical_stock.rs
Labels: bug, Team Ruru 🦉, Severity: Hotfix, HUNCHY FUNCHY

#5110 5055 fix integration tests
  server/Cargo.lock
  server/service/Cargo.toml
  server/service/src/sync/test/integration/central/master_list.rs
  server/service/src/sync/test/integration/central/report.rs
  server/service/src/sync/test/integration/central/unit_and_item.rs
  server/service/src/sync/test/integration/central_server_configurations.rs
  server/service/src/sync/test/integration/errors.rs
  server/service/src/sync/test/integration/remote/invoice.rs
  server/service/src/sync/test/integration/remote/program_requisition.rs
Labels: enhancement, Priority: Must Have, Team Piwakawaka

#5127 clean repository crate on server tests
  .github/workflows/server-tests.yaml
  server/README.md
Labels: bug, Severity: High

#5065 5064 translations for report print / export
  client/packages/system/src/Report/api/hooks/usePrintReport.ts
  server/graphql/reports/src/print.rs
  server/report_builder/src/print.rs
  server/reports/expiring-items/2_3_0/src/style.css
  server/reports/generated/standard_reports.json
  server/reports/stock-status/2_3_0/src/style.css
  server/service/src/report/report_service.rs
  server/service/src/standard_reports.rs
Labels: bug, Team Ruru 🦉, feature: reports

#5126 4147 gaps demographics must be linked to year 2.3.1
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/programs/src/api/hooks/useVaccineCourse.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/IndicatorsDemographics/api/api.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/index.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographics.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/index.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/utils/useDemographicApi.ts
  client/packages/system/src/IndicatorsDemographics/api/operations.generated.ts
  client/packages/system/src/IndicatorsDemographics/api/operations.graphql
  package.json
  server/graphql/core/src/loader/demographic.rs
  server/graphql/core/src/loader/demographic_indicator.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/demographic/src/lib.rs
  server/graphql/demographic/src/types.rs
  server/graphql/types/src/types/demographic.rs
  server/graphql/types/src/types/demographic_indicator.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/update_vaccine_course.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/demographic.rs
  server/repository/src/db_diesel/demographic_indicator_row.rs
  server/repository/src/db_diesel/demographic_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_row.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_03_01/add_demographic_table.rs
  server/repository/src/migrations/v2_03_01/mod.rs
  server/repository/src/migrations/v2_03_01/move_vaccine_course_to_demographic.rs
  server/repository/src/mock/demographic.rs
  server/repository/src/mock/mod.rs
  server/service/src/demographic/insert_demographic_indicator.rs
  server/service/src/demographic/mod.rs
  server/service/src/demographic/query_demographic_indicator.rs
  server/service/src/demographic/validate.rs
  server/service/src/sync/test/test_data/demographic.rs
  server/service/src/sync/test/test_data/demographic_indicator.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/vaccine_course.rs
  server/service/src/sync/translations/demographic.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/vaccine_course.rs
  server/service/src/vaccine_course/insert.rs
  server/service/src/vaccine_course/test/delete.rs
  server/service/src/vaccine_course/test/insert.rs
  server/service/src/vaccine_course/test/query.rs
  server/service/src/vaccine_course/test/update.rs
  server/service/src/vaccine_course/update.rs
Labels: bug, Team Piwakawaka, Severity: High, feature: GAPS

#5140 add side panel to R&R
  client/packages/requisitions/src/RnRForms/DetailView/AppBarButtons.tsx
  client/packages/requisitions/src/RnRForms/DetailView/DetailView.tsx
  client/packages/requisitions/src/RnRForms/DetailView/SidePanel.tsx
Labels: enhancement, Team Piwakawaka, feature: R&R

#5160 Update diagram
  README.md
  doc/architecture.drawio.svg
  doc/architecture.svg
Labels: enhancement

#5143 5081 requisition line variance option (backend implementation)
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/inventory_adjustment_reason.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/general/src/queries/reason_option.rs
  server/graphql/general/src/queries/return_reason.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/reason_option.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/reason_option.rs
  server/repository/src/db_diesel/reason_option_row.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_04_00/add_reason_option_table.rs
  server/repository/src/migrations/v2_04_00/mod.rs
  server/service/src/auth.rs
  server/service/src/lib.rs
  server/service/src/reason_option.rs
  server/service/src/sync/translations/reason.rs
Labels: enhancement, back-end, Build Tested: Dev, Team Ruru 🦉, feature: manual requisition

#5144 4726 add rnr reference
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RnRForms/DetailView/DetailView.tsx
  client/packages/requisitions/src/RnRForms/DetailView/SidePanel.tsx
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts
  client/packages/requisitions/src/RnRForms/api/operations.generated.ts
  client/packages/requisitions/src/RnRForms/api/operations.graphql
  server/graphql/programs/src/mutations/rnr_form/update.rs
  server/graphql/types/src/types/program/rnr_form.rs
  server/repository/src/db_diesel/rnr_form_row.rs
  server/repository/src/migrations/v2_03_01/add_reference_and_comment_to_rnr_form.rs
  server/repository/src/migrations/v2_03_01/mod.rs
  server/repository/src/mock/rnr_form.rs
  server/service/src/rnr_form/finalise.rs
  server/service/src/rnr_form/insert.rs
  server/service/src/rnr_form/tests/finalise.rs
  server/service/src/rnr_form/tests/update.rs
  server/service/src/rnr_form/update.rs
  server/service/src/sync/test/test_data/rnr_form.rs
Labels: enhancement, Priority: Should have, Team Piwakawaka, docs: external, feature: R&R

#5161 Don't allow changing backdated date with lines assigned.
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/index.ts
  client/packages/invoices/src/Prescriptions/api/hooks/line/index.ts
  client/packages/invoices/src/Prescriptions/api/hooks/line/usePrescriptionDeleteLines.ts
  package.json
  server/graphql/invoice/src/mutations/prescription/update.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/invoice/prescription/update/validate.rs
Labels: bug, Team Piwakawaka, Severity: Hotfix

#5176 Asset Property for lifespan, Default existing assets to 10 years
  server/repository/src/migrations/constants.rs
  server/repository/src/migrations/v2_04_00/add_expected_lifespan_to_assets.rs
  server/repository/src/migrations/v2_04_00/mod.rs
Labels: Team Piwakawaka, feature: GAPS

#5174 #4759 Add new equipment status: "Unserviceable"
  client/packages/coldchain/src/Equipment/Components/Status.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/styles/theme.ts
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Asset/utils.ts
  server/graphql/asset/src/types/asset_log.rs
  server/repository/src/db_diesel/assets/asset_log_row.rs
  server/repository/src/migrations/v2_04_00/add_unserviceable_status_to_asset_status_enum.rs
  server/repository/src/migrations/v2_04_00/mod.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#5163 4768 full screen rnr
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/useHostContext/FullScreen.tsx
  client/packages/common/src/hooks/useHostContext/index.ts
  client/packages/common/src/hooks/useHostContext/useHostContext.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
  client/packages/common/src/ui/components/portals/AppFooter/AppFooter.tsx
  client/packages/common/src/ui/icons/Maximise.tsx
  client/packages/common/src/ui/icons/Minimise.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/host/src/components/AppBar/AppBar.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/requisitions/src/RnRForms/DetailView/AppBarButtons.tsx
  client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
Labels: enhancement, Priority: Nice to Have, Team Piwakawaka, docs: external, feature: R&R

#5180 4810 new rnr columns
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts
  client/packages/requisitions/src/RnRForms/api/operations.generated.ts
  client/packages/requisitions/src/RnRForms/api/operations.graphql
  server/graphql/programs/src/mutations/rnr_form/update.rs
  server/graphql/types/src/types/program/rnr_form_line.rs
  server/repository/src/db_diesel/rnr_form_line_row.rs
  server/repository/src/migrations/v2_03_01/add_rnr_columns.rs
  server/repository/src/migrations/v2_03_01/mod.rs
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/update.rs
  server/service/src/rnr_form/update.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
Labels: enhancement, Team Piwakawaka, feature: R&R

#5178 5088 manual requisition line new fields
  server/graphql/types/src/types/requisition_line.rs
  server/repository/src/db_diesel/name.rs
  server/repository/src/db_diesel/requisition_line/requisition_line_row.rs
  server/repository/src/migrations/v2_04_00/add_manual_requisition_line_fields.rs
  server/repository/src/migrations/v2_04_00/mod.rs
  server/repository/src/mock/common.rs
  server/repository/src/mock/mod.rs
  server/service/src/auth.rs
  server/service/src/processors/transfer/requisition/create_response_requisition.rs
  server/service/src/requisition/request_requisition/generate.rs
  server/service/src/rnr_form/finalise.rs
  server/service/src/sync/test/mod.rs
  server/service/src/sync/test/test_data/requisition_line.rs
  server/service/src/sync/translations/requisition_line.rs
Labels: enhancement, back-end, Build Tested: Dev, Team Ruru 🦉, feature: manual requisition

#5092 5057 add extism
  server/Cargo.lock
  server/cli/src/backup/restore.rs
  server/cli/src/cli.rs
  server/graphql/reports/src/print.rs
  server/report_builder/Cargo.toml
  server/report_builder/README.md
  server/report_builder/src/build.rs
  server/report_builder/src/lib.rs
  server/reports/.gitignore
  server/repository/src/db_diesel/mod.rs
  server/service/Cargo.toml
  server/service/src/report/definition.rs
  server/service/src/report/report_service.rs
  server/service/src/standard_reports.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#5168 4979 when backdating an invoice to today the dates arent correct
  server/service/src/invoice/prescription/update/generate.rs
Labels: Priority: Should have, Team Piwakawaka

#5166 5118 add service + endpoint to create a response requisition
  server/graphql/requisition/src/lib.rs
  server/graphql/requisition/src/mutations/response_requisition/insert.rs
  server/graphql/requisition/src/mutations/response_requisition/mod.rs
  server/service/src/requisition/mod.rs
  server/service/src/requisition/response_requisition/insert.rs
  server/service/src/requisition/response_requisition/mod.rs
Labels: enhancement, back-end, Build Tested: Dev, Team Ruru 🦉, feature: manual requisition

#5188 4370 add stock safety buffer to name properties
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
Labels: enhancement, Team Piwakawaka, feature: CCEI, feature: GAPS

#5186 4367(1) Cold storage type (location type) table
  server/graphql/location/src/lib.rs
  server/graphql/location/src/mutations/insert.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/cold_storage_type.rs
  server/repository/src/db_diesel/cold_storage_type_row.rs
  server/repository/src/db_diesel/location_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_04_00/add_cold_storage_type_table.rs
  server/repository/src/migrations/v2_04_00/mod.rs
  server/repository/src/mock/location.rs
  server/service/src/location/insert.rs
  server/service/src/location/tests/insert.rs
  server/service/src/sync/test/test_data/location.rs
  server/service/src/sync/translations/location.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI, feature: GAPS

#5183 5171.1 response program requisition
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RequestRequisition/ListView/ProgramRequisitionOptions.tsx
  client/packages/requisitions/src/RequestRequisition/api/api.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  server/graphql/requisition/src/lib.rs
  server/graphql/requisition/src/mutations/errors.rs
  server/graphql/requisition/src/mutations/request_requisition/insert_program.rs
  server/graphql/requisition/src/program_settings.rs
  server/repository/src/db_diesel/program_requisition/mod.rs
  server/repository/src/db_diesel/program_requisition/program_customer.rs
  server/repository/src/db_diesel/program_requisition/requisitions_in_period.rs
  server/repository/src/migrations/views/mod.rs
  server/service/src/requisition/mod.rs
  server/service/src/requisition/program_settings/common.rs
  server/service/src/requisition/program_settings/customer_program_settings/map.rs
  server/service/src/requisition/program_settings/customer_program_settings/mod.rs
  server/service/src/requisition/program_settings/customer_program_settings/prepare.rs
  server/service/src/requisition/program_settings/map.rs
  server/service/src/requisition/program_settings/mod.rs
  server/service/src/requisition/program_settings/supplier_program_settings/map.rs
  server/service/src/requisition/program_settings/supplier_program_settings/mod.rs
  server/service/src/requisition/program_settings/supplier_program_settings/prepare.rs
  server/service/src/requisition/request_requisition/insert_program.rs
Labels: enhancement, Build Tested: Dev, Team Ruru 🦉, feature: manual requisition

#5197 4761 fix CI bundle diff
  .github/workflows/client-bundle-size-diff.yaml
Labels: bug, Build Tested: Dev, Team Piwakawaka, Severity: High, Tooling

#5191 5119 allow user to create manual requisitions
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/ResponseRequisition/ListView/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/index.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useInsertResponse.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/index.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  server/service/src/requisition/response_requisition/insert.rs
Labels: enhancement, front-end, Team Ruru 🦉, feature: manual requisition

#5185 5141 database changes for item variants gaps
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/item_variant/item_variant_row.rs
  server/repository/src/db_diesel/item_variant/mod.rs
  server/repository/src/db_diesel/item_variant/packaging_variant_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_04_00/item_variant.rs
  server/repository/src/migrations/v2_04_00/mod.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#5196 4789 item variant UI (PT 1)
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Item/DetailView/DetailView.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemPackagingVariantsTable.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/index.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/item_variant.rs
  server/graphql/types/src/types/mod.rs
Labels: enhancement, Team Piwakawaka, needs design, feature: GAPS

#5199 5190 endpoint to create response requisition lines
  client/packages/common/src/types/schema.ts
  server/graphql/requisition_line/src/lib.rs
  server/graphql/requisition_line/src/mutations/errors.rs
  server/graphql/requisition_line/src/mutations/request_requisition_line/insert.rs
  server/graphql/requisition_line/src/mutations/response_requisition_line/insert.rs
  server/graphql/requisition_line/src/mutations/response_requisition_line/mod.rs
  server/graphql/requisition_line/src/mutations/response_requisition_line/update.rs
  server/repository/src/mock/test_requisition_repository.rs
  server/service/src/requisition_line/mod.rs
  server/service/src/requisition_line/response_requisition_line/insert/generate.rs
  server/service/src/requisition_line/response_requisition_line/insert/mod.rs
  server/service/src/requisition_line/response_requisition_line/insert/validate.rs
  server/service/src/requisition_line/response_requisition_line/mod.rs
  server/service/src/requisition_line/response_requisition_line/update.rs
Labels: enhancement, Team Ruru 🦉, feature: manual requisition

#5224 5211 program indicators
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/program_indicator.rs
  server/repository/src/db_diesel/program_indicator_row.rs
  server/repository/src/migrations/v2_04_00/mod.rs
  server/repository/src/migrations/v2_04_00/program_indicator_create_table.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/program_indicator.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/program_indicator.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/program_indicator.rs
Labels: enhancement, back-end, Team Ruru 🦉, feature: manual requisition

#5227 4789 item variant UI pt2
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemPackagingVariantsTable.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/Item/api/hooks/index.ts
  client/packages/system/src/Item/api/hooks/useItemApi/index.ts
  client/packages/system/src/Item/api/hooks/useItemApi/useItemGraphQL.ts
  client/packages/system/src/Item/api/hooks/useItemVariant/index.ts
  client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariant.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Name/Components/ManufacturerSearchInput/ManufacturerSearchInput.tsx
  client/packages/system/src/Name/Components/ManufacturerSearchInput/index.ts
  client/packages/system/src/Name/Components/index.ts
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/item_variant/Cargo.toml
  server/graphql/item_variant/src/lib.rs
  server/graphql/item_variant/src/mutations/delete.rs
  server/graphql/item_variant/src/mutations/mod.rs
  server/graphql/item_variant/src/mutations/upsert.rs
  server/graphql/lib.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/item_variant.rs
Labels: enhancement, Team Piwakawaka, needs design, feature: GAPS

#5232 5208 gaps item variant service layer
  server/graphql/types/src/types/item_variant.rs
  server/repository/src/db_diesel/item_variant/item_variant.rs
  server/repository/src/db_diesel/item_variant/item_variant_row.rs
  server/repository/src/db_diesel/item_variant/mod.rs
  server/repository/src/db_diesel/item_variant/packaging_variant.rs
  server/repository/src/db_diesel/item_variant/packaging_variant_row.rs
  server/repository/src/migrations/v2_04_00/item_variant.rs
  server/service/src/barcode.rs
  server/service/src/item/item.rs
  server/service/src/item/item_variant/delete.rs
  server/service/src/item/item_variant/mod.rs
  server/service/src/item/item_variant/query.rs
  server/service/src/item/item_variant/test/mod.rs
  server/service/src/item/item_variant/upsert.rs
  server/service/src/item/item_variant/validate.rs
  server/service/src/item/mod.rs
  server/service/src/item/packaging_variant/delete.rs
  server/service/src/item/packaging_variant/mod.rs
  server/service/src/item/packaging_variant/query.rs
  server/service/src/item/packaging_variant/test/mod.rs
  server/service/src/item/packaging_variant/upsert.rs
  server/service/src/requisition_line/request_requisition_line/insert.rs
  server/service/src/service_provider.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#5229 3917 add packaging level to facility properties
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
Labels: Team Piwakawaka, feature: GAPS

#5236 5228 add item variant
  server/cli/src/test_connection.rs
  server/graphql/invoice/src/mutations/customer_return/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/stock_line/src/mutations/insert.rs
  server/repository/src/db_diesel/invoice_line_row.rs
  server/repository/src/db_diesel/stock_line_row.rs
  server/repository/src/migrations/v2_04_00/add_item_variant_id_to_stock_line_and_invoice_line.rs
  server/repository/src/migrations/v2_04_00/mod.rs
  server/repository/src/mock/invoice_line.rs
  server/repository/src/mock/test_outbound_shipment_update.rs
  server/repository/src/mock/test_requisition_queries.rs
  server/repository/src/mock/test_requisition_service.rs
  server/repository/src/mock/test_stocktake.rs
  server/repository/src/mock/test_stocktake_line.rs
  server/repository/src/mock/test_unallocated_line.rs
  server/repository/src/tests.rs
  server/service/src/invoice/customer_return/insert/generate.rs
  server/service/src/invoice/customer_return/mod.rs
  server/service/src/invoice/customer_return/update_lines/generate.rs
  server/service/src/invoice/inbound_shipment/generate.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/insert.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/outbound_shipment/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
  server/service/src/invoice_line/stock_in_line/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
  server/service/src/invoice_line/stock_in_line/update/mod.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/processors/transfer/invoice/common.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/insert/generate.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/test/test_data/stock_line.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/stock_line.rs
  server/service/src/vaccination/update/generate.rs
Labels: Team Piwakawaka, feature: GAPS

#5240 Fix compilation and tidy warnings
  server/graphql/item_variant/src/mutations/delete.rs
  server/graphql/item_variant/src/mutations/upsert.rs
  server/graphql/types/src/types/item.rs
Labels: bug

#5231 4367(2) Cold storage display
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/coldchain/src/Sensor/api/operations.generated.ts
  client/packages/coldchain/src/Sensor/api/operations.graphql
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Location/Components/LocationSearchInput.tsx
  client/packages/system/src/Location/ListView/ListView.tsx
  client/packages/system/src/Location/api/operations.generated.ts
  client/packages/system/src/Location/api/operations.graphql
  client/packages/system/src/Stock/api/operations.generated.ts
  server/graphql/core/src/loader/cold_storage_type.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/types/src/types/cold_storage_type.rs
  server/graphql/types/src/types/location.rs
  server/graphql/types/src/types/mod.rs
  server/repository/src/db_diesel/cold_storage_type.rs
  server/repository/src/migrations/v2_04_00/add_cold_storage_type_table.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI, feature: GAPS

#5246 5208 gaps item variant graphql
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Item/DetailView/DetailView.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemPackagingVariantsTable.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariant.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  server/graphql/core/src/loader/item_variant.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/packaging_variant.rs
  server/graphql/item_variant/src/mutations/delete.rs
  server/graphql/item_variant/src/mutations/upsert.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/item_variant.rs
  server/repository/src/db_diesel/item_variant/item_variant.rs
  server/service/src/item/item_variant/mod.rs
  server/service/src/item/item_variant/test/mod.rs
  server/service/src/item/item_variant/upsert.rs
  server/service/src/item/mod.rs
  server/service/src/item/packaging_variant/test/mod.rs
  server/service/src/item/packaging_variant/upsert.rs
Labels: enhancement, Build Tested: None, Team Piwakawaka, feature: GAPS

#5252 5248 gaps manufacturer list
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Name/Components/ManufacturerSearchInput/ManufacturerSearchInput.tsx
  client/packages/system/src/Name/api/api.ts
  client/packages/system/src/Name/api/hooks/document/index.ts
  client/packages/system/src/Name/api/hooks/document/useManufacturers.ts
  client/packages/system/src/Name/api/hooks/index.ts
  server/graphql/general/src/queries/names.rs
  server/graphql/general/src/queries/tests/names.rs
  server/repository/src/db_diesel/name.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#5261 5225 delete item variant
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/Item/api/hooks/useItemVariant/index.ts
  client/packages/system/src/Item/api/hooks/useItemVariant/useDeleteItemVariant.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
Labels: enhancement, Team Piwakawaka, feature: GAPS

#5255 5145 item variant on all incoming stock
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/modals/CustomerReturn/ReturnQuantitiesTable.tsx
  client/packages/invoices/src/Returns/modals/CustomerReturn/useDraftCustomerReturnLines.ts
  client/packages/system/src/Item/Components/ItemVariantSearchInput/ItemVariantInputCell.tsx
  client/packages/system/src/Item/Components/ItemVariantSearchInput/ItemVariantSearchInput.tsx
  client/packages/system/src/Item/Components/ItemVariantSearchInput/index.ts
  client/packages/system/src/Item/Components/index.ts
  client/packages/system/src/Item/api/hooks/useItemVariant/index.ts
  client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariants.ts
  client/packages/system/src/Item/api/keys.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/stock_line/src/mutations/update.rs
  server/graphql/types/src/types/customer_return_line.rs
  server/graphql/types/src/types/invoice_line.rs
  server/graphql/types/src/types/stock_line.rs
  server/service/src/invoice/customer_return/generate_lines.rs
  server/service/src/invoice/customer_return/update_lines/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/insert/validate.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
  server/service/src/invoice_line/stock_in_line/update/mod.rs
  server/service/src/invoice_line/stock_in_line/update/validate.rs
  server/service/src/item/item_variant/mod.rs
  server/service/src/item/item_variant/validate.rs
  server/service/src/item/packaging_variant/upsert.rs
  server/service/src/lib.rs
  server/service/src/stock_line/tests/update.rs
  server/service/src/stock_line/update.rs
Labels: Team Piwakawaka, feature: GAPS

#5260 Cold storage type selection for Item Variant
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Item/Components/ColdStorageTypeInput/ColdStorageTypeInput.tsx
  client/packages/system/src/Item/Components/ColdStorageTypeInput/index.ts
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/Item/api/hooks/useColdStorageTypes/index.ts
  client/packages/system/src/Item/api/hooks/useColdStorageTypes/useColdStorageTypes.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  project-words.txt
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/cold_storage_type.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/types/src/types/item_variant.rs
  server/service/src/cold_storage_type.rs
  server/service/src/lib.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI, feature: GAPS

#5276 #5247 Naive date fix
  client/packages/common/src/intl/utils/DateUtils.test.ts
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx
  client/packages/programs/src/JsonForms/common/components/Date.tsx
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
  client/packages/system/src/Patient/PatientView/PatientSummary.tsx
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: bug, Team Piwakawaka, Severity: High

#5271 5206 item variant packaging variant sync
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/test/test_data/item_variant.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/packaging_variant.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/item_variant.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/packaging_variant.rs
  server/service/src/sync/translations/stock_line.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#5275 5259 gaps sync translation for location type cold storage type
  server/service/src/sync/test/test_data/cold_storage_type.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/cold_storage_type.rs
  server/service/src/sync/translations/item_variant.rs
  server/service/src/sync/translations/mod.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#5281 5274 back button not confirming when form dirty
  client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
  client/packages/common/src/index.ts
  client/packages/host/src/Host.tsx
  package.json
Labels: bug, Severity: High
