Repository msupply-foundation/open-msupply, pull requests merged in 2024-06, with the labels that each got.

#4021 3863 custom fields api
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Name/api/api.ts
  client/packages/system/src/Name/api/operations.generated.ts
  client/packages/system/src/Name/api/operations.graphql
  server/graphql/asset/src/types/asset_property.rs
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/general/src/queries/name_property.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/property.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/name_property.rs
  server/repository/src/db_diesel/name_property_row.rs
  server/repository/src/db_diesel/property_row.rs
  server/repository/src/migrations/v2_01_00/mod.rs
  server/repository/src/migrations/v2_01_00/name_properties/mod.rs
  server/repository/src/migrations/v2_01_00/name_properties/name_property.rs
  server/repository/src/migrations/v2_01_00/name_properties/name_property_data.rs
  server/repository/src/migrations/v2_01_00/property.rs
  server/service/src/lib.rs
  server/service/src/name_property.rs
Labels: Team Piwakawaka, feature: GAPS

#4023 4014 You can query patient data without View Patients permission (via name query)
  server/repository/src/db_diesel/name.rs
  server/service/src/name.rs
Labels: bug, Team Tauhou, Severity: High

#4008 3656 (2) Stock page -- repack and adjustment functionality
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentForm.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/index.ts
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
  client/packages/system/src/Stock/Components/index.ts
  client/packages/system/src/Stock/DetailView/AppBarButtons.tsx
  client/packages/system/src/Stock/DetailView/DetailView.tsx
  client/packages/system/src/Stock/DetailView/Footer.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/api/hooks/keys.ts
  client/packages/system/src/Stock/api/hooks/useRepack.ts
Labels: Priority: Should have, refactor, Team Ruru 🦉, docs: external

#3961 #3656 (1) Stock line page
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/common/src/ui/icons/BarChart2.tsx
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentForm.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/index.ts
  client/packages/system/src/Stock/Components/Ledger/LedgerTable.tsx
  client/packages/system/src/Stock/Components/Ledger/index.ts
  client/packages/system/src/Stock/Components/NewStockLineModal.tsx
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
  client/packages/system/src/Stock/Components/StockLineEditModal.tsx
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/Components/index.ts
  client/packages/system/src/Stock/DetailView/AppBarButtons.tsx
  client/packages/system/src/Stock/DetailView/DetailView.tsx
  client/packages/system/src/Stock/DetailView/Footer.tsx
  client/packages/system/src/Stock/DetailView/index.ts
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/Service/Service.tsx
  client/packages/system/src/Stock/api/hooks/keys.ts
  client/packages/system/src/Stock/api/hooks/useRepack.ts
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
Labels: Priority: Should have, refactor, Team Ruru 🦉, docs: external

#4033 3989 Outbound shipment detail view column headers not fixed #4025
  client/packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/ContentArea.tsx
Labels: bug, Team Tauhou, Severity: High, HUNCHY FUNCHY

#4026 3823 Syncing user causes store to swap to default store
  client/packages/common/src/authentication/AuthContext.tsx
Labels: bug, Team Tauhou, Severity: Normal

#4037 Add patient creation json schema
  client/packages/programs/src/JsonForms/common/JsonForm.tsx
  client/packages/programs/src/JsonForms/index.ts
  client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
  client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientSchema.json
  client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json
  client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx
  client/packages/system/src/Patient/PatientView/DefaultPatientSchema.json
  client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
  client/packages/system/src/Patient/PatientView/PatientView.tsx
Labels: bug, Team Tauhou, Severity: High, docs: external

#4044 default lang version to app version if not defined
  client/packages/common/src/intl/context/IntlContext.tsx
Labels: bug, Severity: High

#4002 3844 add front end UI pop data entry
  client/package.json
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/catalogue.json
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/strings/IntlStrings.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/arrays/ArrayUtils.ts
  client/packages/config/src/config.ts
  client/packages/config/src/routes.ts
  client/packages/host/src/components/Navigation/CatalogueNav.tsx
  client/packages/host/src/routers/CatalogueRouter.tsx
  client/packages/host/webpack.config.js
  client/packages/system/src/Asset/ListView/EditableInput.tsx
  client/packages/system/src/Asset/ListView/ListView.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/AppBarButtons.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/Footer.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/GrowthRow.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/NameColumn.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/PercentageColumn.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/PopulationColumn.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/utils.test.ts
  client/packages/system/src/IndicatorsDemographics/DetailView/utils.tsx
  client/packages/system/src/IndicatorsDemographics/Service/Service.tsx
  client/packages/system/src/IndicatorsDemographics/Service/index.ts
  client/packages/system/src/IndicatorsDemographics/api/api.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/index.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicator.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicatorInsert.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicatorUpdate.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicators.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjection.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjectionInsert.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjectionUpdate.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjections.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/index.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/utils/index.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/utils/useDemographicApi.ts
  client/packages/system/src/IndicatorsDemographics/api/index.ts
  client/packages/system/src/IndicatorsDemographics/api/operations.generated.ts
  client/packages/system/src/IndicatorsDemographics/api/operations.graphql
  client/packages/system/src/IndicatorsDemographics/index.ts
  client/packages/system/src/IndicatorsDemographics/types.ts
  client/packages/system/src/Item/context/usePackVariant.ts
  client/packages/system/src/index.ts
  server/graphql/demographic/src/types.rs
  server/service/src/demographic/insert_demographic_indicator.rs
  server/service/src/demographic/update_demographic_indicator.rs
  server/service/src/demographic/validate.rs
Labels: Priority: Must Have, Team Piwakawaka, feature: CCEI, feature: GAPS

#4030 3911 gaps immunisation program back end query
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/lib.rs
  server/graphql/types/src/types/activity_log.rs
  server/graphql/types/src/types/permissions.rs
  server/graphql/vaccine_course/Cargo.toml
  server/graphql/vaccine_course/src/lib.rs
  server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/mod.rs
  server/graphql/vaccine_course/src/types/mod.rs
  server/graphql/vaccine_course/src/types/vaccine_course.rs
  server/graphql/vaccine_course/src/vaccine_course_queries.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/db_diesel/vaccine_course/mod.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_item.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_item_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_schedule.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_schedule_row.rs
  server/repository/src/migrations/v2_01_00/activity_log.rs
  server/repository/src/migrations/v2_01_00/mod.rs
  server/repository/src/migrations/v2_01_00/vaccine_course.rs
  server/repository/src/mock/demographic.rs
  server/repository/src/mock/mod.rs
  server/service/src/auth.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
  server/service/src/vaccine_course/insert.rs
  server/service/src/vaccine_course/mod.rs
  server/service/src/vaccine_course/query.rs
  server/service/src/vaccine_course/test/mod.rs
  server/service/src/vaccine_course/test/query.rs
  server/service/src/vaccine_course/validate.rs
Labels: Team Piwakawaka, feature: GAPS

#4051 3913 gaps immunisation programs backend
  client/packages/common/src/types/schema.ts
  server/graphql/lib.rs
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/mutations/immunisation/insert.rs
  server/graphql/programs/src/mutations/immunisation/mod.rs
  server/graphql/programs/src/mutations/mod.rs
  server/graphql/programs/src/queries/mod.rs
  server/graphql/programs/src/queries/program.rs
  server/graphql/programs/src/types/mod.rs
  server/graphql/programs/src/types/program.rs
  server/graphql/types/src/types/activity_log.rs
  server/graphql/types/src/types/program/program_node.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/master_list.rs
  server/repository/src/db_diesel/program_requisition/program.rs
  server/repository/src/db_diesel/program_requisition/program_requisition_settings.rs
  server/repository/src/db_diesel/program_requisition/program_row.rs
  server/repository/src/db_diesel/program_requisition/program_supplier.rs
  server/repository/src/db_diesel/program_requisition/requisitions_in_period.rs
  server/repository/src/migrations/v2_01_00/mod.rs
  server/repository/src/migrations/v2_01_00/program.rs
  server/repository/src/mock/program.rs
  server/service/src/lib.rs
  server/service/src/master_list/tests/query.rs
  server/service/src/missing_program.rs
  server/service/src/program/insert_immunisation.rs
  server/service/src/program/mod.rs
  server/service/src/program/query.rs
  server/service/src/program/test/insert.rs
  server/service/src/program/test/mod.rs
  server/service/src/program/test/query.rs
  server/service/src/program/validate.rs
  server/service/src/requisition/program_settings/mod.rs
  server/service/src/requisition/request_requisition/insert_program.rs
  server/service/src/service_provider.rs
  server/service/src/sync/test/test_data/program_requisition_settings.rs
  server/service/src/sync/translations/program_requisition_settings.rs
Labels: Team Piwakawaka, feature: GAPS

#4032 3915 add immunisation program list view
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/config/src/routes.ts
  client/packages/host/src/Site.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/components/Navigation/ProgramsNav.tsx
  client/packages/host/src/components/Navigation/index.ts
  client/packages/host/src/routers/ProgramsRouter.tsx
  client/packages/host/src/routers/index.ts
  client/packages/system/src/Immunisation/ListView/AppBarButtons.tsx
  client/packages/system/src/Immunisation/ListView/ImmunisationProgramCreateModal.tsx
  client/packages/system/src/Immunisation/ListView/ListView.tsx
  client/packages/system/src/Immunisation/ListView/Toolbar.tsx
  client/packages/system/src/Immunisation/ListView/index.ts
  client/packages/system/src/Immunisation/ProgramView/ProgramView.tsx
  client/packages/system/src/Immunisation/ProgramView/Toolbar/Toolbar.tsx
  client/packages/system/src/Immunisation/ProgramView/Toolbar/index.ts
  client/packages/system/src/Immunisation/ProgramView/index.ts
  client/packages/system/src/Immunisation/Service/Service.tsx
  client/packages/system/src/Immunisation/Service/index.ts
  client/packages/system/src/Immunisation/index.ts
  client/packages/system/src/index.ts
Labels: Team Piwakawaka, feature: GAPS

#4050 swallow keep awake errors
  client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
Labels: bug, platform: android, Severity: High

#4052 Use uuid v7 instead of v4
  client/packages/common/package.json
  client/packages/common/src/utils/functions/FnUtils.ts
  client/yarn.lock
  server/Cargo.lock
  server/util/Cargo.toml
  server/util/src/uuid.rs
Labels: needs architecture/solution, Priority: Nice to Have, refactor

#4071 Fix programs table migration
  server/repository/src/migrations/v2_01_00/program.rs
Labels: bug, needs triage, Team Tauhou, Severity: Hotfix, needs daily triage

#4084 Fix report name column width + fix warnings
  client/packages/system/src/Report/ListView/ListView.tsx
Labels: bug, Team Tauhou

#3979 3909 display structured errors for edit inbound shipment lines
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/line/useSaveInboundLines.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
Labels: bug, Team Ruru 🦉, Severity: Normal

#4065 3865 store custom name fields
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Name/ListView/Facilities/FacilityEditModal.tsx
  client/packages/system/src/Name/api/api.ts
  client/packages/system/src/Name/api/hooks/document/index.ts
  client/packages/system/src/Name/api/hooks/document/useUpdateProperties.ts
  client/packages/system/src/Name/api/hooks/index.ts
  client/packages/system/src/Name/api/operations.generated.ts
  client/packages/system/src/Name/api/operations.graphql
  server/graphql/core/src/loader/name.rs
  server/graphql/general/src/lib.rs
  server/graphql/general/src/mutations/mod.rs
  server/graphql/general/src/mutations/update_name_properties.rs
  server/graphql/general/src/queries/names.rs
  server/graphql/general/src/queries/tests/names.rs
  server/graphql/types/src/types/name.rs
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/name.rs
  server/repository/src/db_diesel/name_row.rs
  server/repository/src/db_diesel/program_requisition/program_supplier.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v2_01_00/name_properties/name_property.rs
  server/service/src/auth.rs
  server/service/src/login.rs
  server/service/src/name/mod.rs
  server/service/src/name/query.rs
  server/service/src/name/update.rs
  server/service/src/name/validate.rs
  server/service/src/requisition/program_settings/mod.rs
  server/service/src/service_provider.rs
Labels: Team Piwakawaka, feature: GAPS

#4098 Change translation from status log to status history
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
Labels: enhancement, Priority: Nice to Have, feature: CCEI, docs: external

#4007 4000 ignore soft deleted master lists
  server/repository/src/db_diesel/master_list_row.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/master_list.rs
Labels: bug, Migrate Existing Desktop, Team Tauhou

#4080 Add immunisation detail view
  client/packages/common/src/intl/locales/en/catalogue.json
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/AppBarButtons.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/VaccineCourseCreateModal.tsx
  client/packages/system/src/Immunisation/Service/Service.tsx
  client/packages/system/src/Immunisation/VaccineCourseView/DescriptionColumn.tsx
  client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseView.tsx
  client/packages/system/src/Immunisation/VaccineCourseView/index.ts
Labels: Team Piwakawaka, feature: GAPS

#4114 4062 add vaccine course detail view api
  client/packages/common/src/intl/locales/en/catalogue.json
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/AppBarButtons.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/VaccineCourseCreateModal.tsx
  client/packages/system/src/Immunisation/api/hooks/keys.ts
  client/packages/system/src/Immunisation/api/hooks/useVaccineCourse.ts
  client/packages/system/src/Immunisation/api/hooks/useVaccineCourseList.ts
  client/packages/system/src/Immunisation/api/operations.generated.ts
  client/packages/system/src/Immunisation/api/operations.graphql
  server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
  server/graphql/vaccine_course/src/types/vaccine_course.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_row.rs
  server/repository/src/migrations/v2_01_00/vaccine_course.rs
  server/service/src/vaccine_course/insert.rs
  server/service/src/vaccine_course/test/query.rs
Labels: enhancement, needs triage, Team Piwakawaka, feature: GAPS

#4099 3992 unable to see full description of a master list in item master list or in master list page
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/system/src/Item/DetailView/Tabs/MasterLists.tsx
  client/packages/system/src/MasterList/ListView/ListView.tsx
  server/repository/src/db_diesel/requisition_line/requisition_line_row.rs
Labels: bug, Team Tauhou, Severity: Low

#4119 4093 create vaccine course loaders
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/system/src/Immunisation/ListView/ListView.tsx
  client/packages/system/src/Immunisation/api/operations.generated.ts
  client/packages/system/src/Immunisation/api/operations.graphql
  server/graphql/core/src/loader/demographic_indicator.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/vaccine_course_by_program.rs
  server/graphql/core/src/loader/vaccine_course_item_by_vaccine_course.rs
  server/graphql/core/src/loader/vaccine_course_schedule_by_vaccine_course.rs
  server/graphql/demographic/src/mutations/insert_indicator.rs
  server/graphql/demographic/src/mutations/update_indicator.rs
  server/graphql/demographic/src/types.rs
  server/graphql/types/src/types/demographic.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/program/program_node.rs
  server/graphql/types/src/types/vaccine_course.rs
  server/graphql/types/src/types/vaccine_course_item.rs
  server/graphql/types/src/types/vaccine_course_schedule.rs
  server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
  server/graphql/vaccine_course/src/types/vaccine_course.rs
  server/graphql/vaccine_course/src/vaccine_course_queries.rs
  server/service/src/vaccine_course/test/query.rs
  server/service/src/vaccine_course/validate.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#4049 Remove unused endpoint
  client/packages/common/src/types/schema.ts
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/mutations/mod.rs
  server/graphql/programs/src/mutations/update_document.rs
Labels: good first issue, feature: programs, refactor, Team Tauhou

#4103 3862 custom name data edit on remote site
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.graphql
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/types/schema.ts
  client/packages/host/src/components/Footer/Footer.tsx
  client/packages/system/src/Name/ListView/Facilities/FacilityEditModal.tsx
  client/packages/system/src/Name/ListView/index.ts
  server/graphql/types/src/types/user.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/name_row.rs
  server/repository/src/migrations/helpers.rs
  server/repository/src/migrations/v2_01_00/name_properties/name_property.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/name_oms_fields.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/name_oms_fields.rs
Labels: Team Piwakawaka, feature: CCEI, feature: GAPS

#3933 3883 use stock in abstraction
  server/graphql/batch_mutations/src/batch_inbound_shipment.rs
  server/graphql/inventory_adjustment/mutations/insert.rs
  server/graphql/invoice/src/mutations/inbound_shipment/delete.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/delete.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/delete.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/prescription_line/insert.rs
  server/graphql/stocktake/src/mutations/update.rs
  server/service/src/invoice/inbound_shipment/batch.rs
  server/service/src/invoice/inbound_shipment/delete/mod.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/insert.rs
  server/service/src/invoice/inventory_adjustment/mod.rs
  server/service/src/invoice/outbound_return/insert/generate.rs
  server/service/src/invoice/outbound_return/update_lines/generate.rs
  server/service/src/invoice/outbound_shipment/batch.rs
  server/service/src/invoice/prescription/batch.rs
  server/service/src/invoice_line/inbound_shipment_line/delete/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/delete/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/insert/validate.rs
  server/service/src/invoice_line/inbound_shipment_line/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/update/generate.rs
  server/service/src/invoice_line/inbound_shipment_line/update/mod.rs
  server/service/src/invoice_line/inbound_shipment_line/update/validate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/delete/mod.rs
  server/service/src/invoice_line/inbound_shipment_service_line/delete/validate.rs
  server/service/src/invoice_line/mod.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/allocate/generate.rs
  server/service/src/invoice_line/stock_in_line/delete/validate.rs
  server/service/src/invoice_line/stock_in_line/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/insert/validate.rs
  server/service/src/invoice_line/stock_in_line/mod.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
  server/service/src/invoice_line/stock_in_line/update/validate.rs
  server/service/src/invoice_line/stock_in_line/validate.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/insert/mod.rs
  server/service/src/invoice_line/stock_out_line/insert/validate.rs
  server/service/src/invoice_line/stock_out_line/mod.rs
  server/service/src/stocktake/update.rs
Labels: refactor, Team Ruru 🦉

#4121 Add the fifth year
  client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/NameColumn.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/PercentageColumn.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/PopulationColumn.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/utils.test.ts
  client/packages/system/src/IndicatorsDemographics/DetailView/utils.tsx
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicators.ts
Labels: bug, Team Piwakawaka, feature: GAPS

#4122 Move demographics
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/components/Navigation/CatalogueNav.tsx
  client/packages/host/src/components/Navigation/ManageNav.tsx
  client/packages/host/src/components/Navigation/ProgramsNav.tsx
  client/packages/host/src/routers/CatalogueRouter.tsx
  client/packages/host/src/routers/ManageRouter.tsx
Labels: enhancement, Team Piwakawaka, feature: GAPS

#4135 4125 Immunization programs create UI fixes
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/VaccineCourseCreateModal.tsx
  client/packages/system/src/Immunisation/ListView/ImmunisationProgramCreateModal.tsx
  client/packages/system/src/Immunisation/ListView/ListView.tsx
  client/packages/system/src/Immunisation/api/hooks/useImmunisationProgram.ts
  client/packages/system/src/Immunisation/api/operations.generated.ts
  client/packages/system/src/Immunisation/api/operations.graphql
  server/graphql/programs/src/mutations/immunisation/insert.rs
Labels: bug, Team Piwakawaka, feature: GAPS

#4120 4117 replace FEATURE_GAPS flag with vaccine module check
  client/packages/config/src/config.ts
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/components/Footer/Footer.tsx
  client/packages/host/src/components/Navigation/CatalogueNav.tsx
  client/packages/host/src/components/Navigation/ManageNav.tsx
  client/packages/host/src/components/Navigation/ProgramsNav.tsx
  client/packages/host/webpack.config.js
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/VaccineCourseCreateModal.tsx
  client/packages/system/src/Immunisation/Service/Service.tsx
Labels: enhancement, Team Piwakawaka, feature: GAPS

#3932 2790 integration speed up for Sqlite and Postgres
  server/cli/src/cli.rs
  server/repository/src/db_diesel/sync_log.rs
  server/repository/src/db_diesel/sync_log_row.rs
  server/service/src/sync/sync_on_central/mod.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/test/pull_and_push.rs
  server/service/src/sync/translation_and_integration.rs
  server/service/src/sync/translations/special/clinician_merge.rs
  server/service/src/sync/translations/special/item_merge.rs
  server/service/src/sync/translations/special/name_merge.rs
Labels: enhancement, Priority: Must Have, Team Tauhou

#4130 4118 remote editability toggle for name properties
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Name/ListView/Facilities/FacilityEditModal.tsx
  client/packages/system/src/Name/api/operations.generated.ts
  client/packages/system/src/Name/api/operations.graphql
  server/graphql/general/src/queries/name_property.rs
  server/repository/src/db_diesel/name_property_row.rs
  server/repository/src/migrations/v2_01_00/name_properties/name_property.rs
  server/repository/src/migrations/v2_01_00/name_properties/name_property_data.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#4096 2558 name merging store
  server/graphql/types/src/types/store.rs
  server/graphql/types/src/types/user.rs
  server/repository/migrations/postgres/2021-12-10T10-00_number_table/up.sql
  server/repository/src/db_diesel/changelog/test.rs
  server/repository/src/db_diesel/item.rs
  server/repository/src/db_diesel/master_list.rs
  server/repository/src/db_diesel/name.rs
  server/repository/src/db_diesel/name_tag.rs
  server/repository/src/db_diesel/program_requisition/program_supplier.rs
  server/repository/src/db_diesel/stock_movement.rs
  server/repository/src/db_diesel/store.rs
  server/repository/src/db_diesel/store_row.rs
  server/repository/src/migrations/v2_01_00/decimal_pack_size.rs
  server/repository/src/migrations/v2_01_00/ledger.rs
  server/repository/src/migrations/v2_01_00/mod.rs
  server/repository/src/migrations/v2_01_00/store_add_name_link_id.rs
  server/repository/src/migrations/version.rs
  server/repository/src/mock/store.rs
  server/repository/src/mock/test_master_list_repository.rs
  server/repository/src/mock/test_name_query.rs
  server/repository/src/mock/test_name_store_id.rs
  server/repository/src/mock/test_remote_pull.rs
  server/repository/src/tests.rs
  server/service/src/auth.rs
  server/service/src/dashboard/item_count.rs
  server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
  server/service/src/processors/transfer/invoice/test.rs
  server/service/src/processors/transfer/requisition/create_response_requisition.rs
  server/service/src/processors/transfer/requisition/test.rs
  server/service/src/requisition_line/chart/mod.rs
  server/service/src/sync/test/test_data/special/name_to_name_store_join.rs
  server/service/src/sync/test/test_data/store.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/name_store_join.rs
  server/service/src/sync/translations/store.rs
  server/service/src/temperature_excursion.rs
Labels: enhancement, back-end, Priority: Should have, feature: merging, Team Tauhou

#4107 Use a static LinkPatientModal to avoid recreating it on each render
  client/packages/system/src/ContactTrace/DetailView/LinkPatientModal.tsx
Labels: bug, Team Tauhou, docs: external

#4092 4090 program event order
  server/Cargo.lock
  server/repository/Cargo.toml
  server/service/src/programs/program_event.rs
Labels: bug, Team Tauhou

#4151 3642 patient search results display in created date order
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Patient/ListView/ListView.tsx
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  server/graphql/programs/src/queries/patient.rs
  server/graphql/reports/src/printing.rs
  server/graphql/types/src/types/program/patient.rs
  server/graphql/types/src/types/user.rs
  server/repository/src/db_diesel/patient.rs
Labels: enhancement, Team Tauhou, feature: dispensing, docs: external

#4150 Clippy 13
  server/Cargo.toml
  server/graphql/invoice/src/mutations/inbound_shipment/update.rs
  server/graphql/invoice/src/mutations/outbound_shipment/update.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/service_line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/service_line/update.rs
  server/repository/src/db_diesel/item_row.rs
  server/repository/src/db_diesel/report_query.rs
  server/repository/src/db_diesel/storage_connection.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/test_db/mod.rs
  server/repository/src/test_db/sqlite.rs
  server/service/src/auth.rs
  server/service/src/invoice/inbound_return/update/mod.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
  server/service/src/invoice_line/stock_in_line/update/mod.rs
  server/service/src/lib.rs
  server/service/src/login.rs
  server/service/src/programs/contact_trace/contact_trace_schema.rs
  server/service/src/programs/encounter/encounter_schema.rs
  server/service/src/programs/patient/patient_schema.rs
  server/service/src/programs/patient/patient_updated.rs
  server/service/src/programs/program_enrolment/program_schema.rs
  server/service/src/programs/update_program_document.rs
  server/service/src/requisition/program_settings/map.rs
  server/service/src/requisition_line/request_requisition_line/insert.rs
  server/service/src/settings_service.rs
  server/service/src/stock_line/update.rs
  server/service/src/stocktake/update.rs
  server/service/src/sync/api/core.rs
  server/service/src/sync/api/get_central_records.rs
  server/service/src/sync/api/get_queued_records.rs
  server/service/src/sync/api/get_site_info.rs
  server/service/src/sync/api/get_site_status.rs
  server/service/src/sync/api/post_acknowledged_records.rs
  server/service/src/sync/api/post_initialise.rs
  server/service/src/sync/api/post_queued_records.rs
  server/service/src/sync/api_v6/core.rs
  server/service/src/sync/api_v6/upload_file.rs
  server/service/src/sync/sync_buffer.rs
  server/service/src/sync/sync_status/test.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/translation_and_integration.rs
  server/service/src/sync/translations/barcode.rs
  server/service/src/temperature_excursion.rs
Labels: Priority: Should have, refactor, Build tested: Dev, Team Tauhou, Tooling

#4088 Disable centralPatientSearch query if the input params object is empty
  client/packages/system/src/Patient/api/hooks/utils/useCentralPatientSearch.ts
Labels: bug, Team Tauhou

#4134 Save demographic projection data
  client/packages/common/src/types/schema.ts
  client/packages/system/src/IndicatorsDemographics/DetailView/AppBarButtons.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/GrowthRow.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/PercentageColumn.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/utils.test.ts
  client/packages/system/src/IndicatorsDemographics/DetailView/utils.tsx
  client/packages/system/src/IndicatorsDemographics/api/api.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/index.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicatorInsert.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicatorUpdate.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicators.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjection.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjectionInsert.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjectionUpdate.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjectionUpsert.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjections.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/index.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/utils/useDemographicApi.ts
  client/packages/system/src/IndicatorsDemographics/api/operations.generated.ts
  client/packages/system/src/IndicatorsDemographics/api/operations.graphql
  client/packages/system/src/IndicatorsDemographics/types.ts
  server/graphql/demographic/src/lib.rs
  server/graphql/demographic/src/mutations/insert_projection.rs
  server/graphql/demographic/src/mutations/update_projection.rs
  server/graphql/demographic/src/types.rs
  server/repository/src/db_diesel/demographic_projection_row.rs
  server/repository/src/migrations/v2_01_00/demographics.rs
  server/service/src/demographic/insert_demographic_projection.rs
  server/service/src/demographic/mod.rs
  server/service/src/demographic/query_demographic_projection.rs
  server/service/src/demographic/update_demographic_projection.rs
  server/service/src/demographic/validate.rs
Labels: bug, Priority: Must Have, Team Piwakawaka, feature: GAPS

#4153 4112 translatable name properties
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/host/src/Admin/ConfigurationSettings.tsx
  client/packages/host/src/Admin/Settings.tsx
  client/packages/host/src/api/api.ts
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
  client/packages/host/src/api/hooks/settings/useConfigureNameProperties.ts
  client/packages/host/src/api/operations.generated.ts
  client/packages/host/src/api/operations.graphql
  client/packages/host/src/components/Footer/Footer.tsx
  client/packages/system/src/Name/api/hooks/utils/useNameApi.ts
  client/packages/system/src/Name/api/index.ts
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/name_property.rs
  server/graphql/lib.rs
  server/graphql/types/src/types/property.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/property.rs
  server/repository/src/migrations/v2_01_00/mod.rs
  server/repository/src/migrations/v2_01_00/name_properties/mod.rs
  server/repository/src/migrations/v2_01_00/name_properties/name_property_data.rs
  server/repository/src/migrations/v2_01_00/name_property.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/property.rs
  server/service/src/name_property.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/name_property.rs
  server/service/src/sync/test/test_data/property.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/name_property.rs
  server/service/src/sync/translations/property.rs
  server/service/src/validate.rs
Labels: Bug, Team Piwakawaka, feature: GAPS

#4157 GAPS UI tweaks
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/host/src/components/AppBar/SectionIcon.tsx
  client/packages/host/src/components/Footer/Footer.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/Toolbar.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/VaccineCourseCreateModal.tsx
  client/packages/system/src/Immunisation/ListView/ImmunisationProgramCreateModal.tsx
  client/packages/system/src/Immunisation/ListView/ListView.tsx
  client/packages/system/src/Immunisation/api/hooks/useVaccineCourse.ts
  client/packages/system/src/Immunisation/api/operations.generated.ts
  client/packages/system/src/Immunisation/api/operations.graphql
Labels: enhancement, Team Piwakawaka, feature: GAPS

#4146 4079 facilities list should only include stores
  client/packages/system/src/Name/api/api.ts
Labels: Bug, Team Piwakawaka, feature: GAPS

#4009 3656 (3) Finish Stock API refactor
  client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
  client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
  client/packages/system/src/Stock/ListView/AppBarButtons.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/api/api.ts
  client/packages/system/src/Stock/api/hooks/index.ts
  client/packages/system/src/Stock/api/hooks/keys.ts
  client/packages/system/src/Stock/api/hooks/line/index.ts
  client/packages/system/src/Stock/api/hooks/line/useInsertRepack.ts
  client/packages/system/src/Stock/api/hooks/line/useRepack.ts
  client/packages/system/src/Stock/api/hooks/line/useRepacksByStockLine.ts
  client/packages/system/src/Stock/api/hooks/line/useSortedStockLines.ts
  client/packages/system/src/Stock/api/hooks/line/useStockLine.ts
  client/packages/system/src/Stock/api/hooks/line/useStockLineUpdate.ts
  client/packages/system/src/Stock/api/hooks/line/useStockLines.ts
  client/packages/system/src/Stock/api/hooks/line/useStockLinesAll.ts
  client/packages/system/src/Stock/api/hooks/useExportStockList.ts
  client/packages/system/src/Stock/api/hooks/useRepack.ts
  client/packages/system/src/Stock/api/hooks/useStockList.ts
  client/packages/system/src/Stock/api/hooks/utils/index.ts
  client/packages/system/src/Stock/api/hooks/utils/useStockApi.ts
  client/packages/system/src/Stock/index.ts
  client/packages/system/src/Stock/types.ts
Labels: Priority: Should have, refactor, Team Ruru 🦉

#4163 4129 fix item link for vaccine course
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseItemSelect.tsx
  client/packages/system/src/Immunisation/api/hooks/types.ts
  client/packages/system/src/Immunisation/api/hooks/useVaccineCourse.ts
  client/packages/system/src/Immunisation/api/operations.generated.ts
  client/packages/system/src/Immunisation/api/operations.graphql
  server/graphql/core/src/loader/vaccine_course_item_by_vaccine_course.rs
  server/graphql/types/src/types/vaccine_course_item.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_item.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_item_row.rs
  server/repository/src/migrations/v2_01_00/mod.rs
  server/service/src/vaccine_course/test/update.rs
  server/service/src/vaccine_course/validate.rs
Labels: Bug, Team Piwakawaka, feature: GAPS

#4142 4064 can save vaccine course details
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/system/src/Immunisation/VaccineCourseView/AppFooterComponent.tsx
  client/packages/system/src/Immunisation/VaccineCourseView/DescriptionColumn.tsx
  client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseItemSelect.tsx
  client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseView.tsx
  client/packages/system/src/Immunisation/api/hooks/index.ts
  client/packages/system/src/Immunisation/api/hooks/types.ts
  client/packages/system/src/Immunisation/api/hooks/useImmunisationProgram.ts
  client/packages/system/src/Immunisation/api/hooks/useImmunisationProgramList.ts
  client/packages/system/src/Immunisation/api/hooks/useVaccineCourse.ts
  client/packages/system/src/Immunisation/api/index.ts
  client/packages/system/src/Immunisation/api/operations.generated.ts
  client/packages/system/src/Immunisation/api/operations.graphql
  client/packages/system/src/Immunisation/index.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/index.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicators.ts
  client/packages/system/src/IndicatorsDemographics/index.ts
  client/packages/system/src/Item/api/api.ts
  client/packages/system/src/Item/api/hooks/index.ts
  client/packages/system/src/Item/api/hooks/useVaccineItem/index.ts
  client/packages/system/src/Item/api/hooks/useVaccineItem/useVaccineItems.ts
  client/packages/system/src/index.ts
  server/graphql/core/src/loader/vaccine_course_item_by_vaccine_course.rs
  server/graphql/core/src/simple_generic_errors.rs
  server/graphql/general/src/queries/item.rs
  server/graphql/types/src/types/activity_log.rs
  server/graphql/types/src/types/vaccine_course_item.rs
  server/graphql/types/src/types/vaccine_course_schedule.rs
  server/graphql/vaccine_course/src/lib.rs
  server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/mod.rs
  server/graphql/vaccine_course/src/mutations/update_vaccine_course.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/item.rs
  server/repository/src/db_diesel/item_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_item.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_item_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_schedule_row.rs
  server/repository/src/migrations/v2_01_00/activity_log.rs
  server/repository/src/migrations/v2_01_00/item_add_is_vaccine.rs
  server/repository/src/migrations/v2_01_00/mod.rs
  server/repository/src/migrations/v2_01_00/vaccine_course.rs
  server/repository/src/mock/program.rs
  server/service/src/demographic/mod.rs
  server/service/src/sync/test/test_data/item.rs
  server/service/src/sync/test/test_data/unit.rs
  server/service/src/sync/translations/item.rs
  server/service/src/vaccine_course/insert.rs
  server/service/src/vaccine_course/mod.rs
  server/service/src/vaccine_course/test/insert.rs
  server/service/src/vaccine_course/test/mod.rs
  server/service/src/vaccine_course/test/query.rs
  server/service/src/vaccine_course/test/update.rs
  server/service/src/vaccine_course/update.rs
  server/service/src/vaccine_course/validate.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#4164 2882.1 update b/e crates
  server/Cargo.lock
  server/Cargo.toml
  server/android/Cargo.toml
  server/android/src/android.rs
  server/cli/Cargo.toml
  server/cli/src/cli.rs
  server/graphql/Cargo.toml
  server/graphql/cold_chain/Cargo.toml
  server/graphql/core/Cargo.toml
  server/graphql/form_schema/Cargo.toml
  server/graphql/invoice_line/Cargo.toml
  server/graphql/plugin/Cargo.toml
  server/graphql/programs/Cargo.toml
  server/graphql/stocktake_line/Cargo.toml
  server/report_builder/Cargo.toml
  server/repository/Cargo.toml
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/diesel_extensions.rs
  server/repository/src/lib.rs
  server/server/Cargo.toml
  server/server/src/certs.rs
  server/server/src/configuration.rs
  server/service/Cargo.toml
  server/util/Cargo.toml
  server/windows/Cargo.toml
Labels: enhancement, back-end, Build Tested: Dev, Team Tauhou

#4184 3934 Item name is cut off in requisition line edit modal
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEditForm.tsx
Labels: Bug, Team Ruru 🦉, Severity: Normal

#4169 Fix asset catalogue import with properties
  client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
Labels: Bug, Priority: Must Have, Team Piwakawaka, Severity: High, feature: GAPS

#4174 Remove conditional test migrations from migration list
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/templates/add_data_from_sync_buffer/mod.rs
  server/repository/src/migrations/templates/adding_table/mod.rs
  server/repository/src/migrations/templates/data_and_schema/mod.rs
  server/repository/src/migrations/templates/data_migration/mod.rs
  server/repository/src/migrations/v1_07_00/mod.rs
  server/repository/src/migrations/v2_00_00/mod.rs
Labels: Priority: Must Have, Team Piwakawaka

#4149 4057 gaps permissions
  client/packages/common/src/authentication/hooks/index.ts
  client/packages/common/src/authentication/hooks/useCheckPermissionWithError.ts
  client/packages/common/src/authentication/hooks/usePermissionCheck.ts
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/AppBarButtons.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/VaccineCourseCreateModal.tsx
  client/packages/system/src/Immunisation/ListView/AppBarButtons.tsx
  client/packages/system/src/Immunisation/ListView/ImmunisationProgramCreateModal.tsx
  client/packages/system/src/Immunisation/api/hooks/useImmunisationProgram.ts
  client/packages/system/src/Immunisation/api/hooks/useVaccineCourse.ts
  client/packages/system/src/IndicatorsDemographics/DetailView/AppBarButtons.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/Footer.tsx
  client/packages/system/src/IndicatorsDemographics/api/api.ts
  server/graphql/core/src/standard_graphql_error.rs
  server/graphql/demographic/src/mutations/insert_indicator.rs
  server/graphql/demographic/src/mutations/insert_projection.rs
  server/graphql/demographic/src/mutations/update_indicator.rs
  server/graphql/demographic/src/mutations/update_projection.rs
  server/graphql/programs/src/mutations/immunisation/insert.rs
  server/graphql/programs/src/mutations/immunisation/update.rs
  server/graphql/types/src/types/permissions.rs
  server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/update_vaccine_course.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v2_01_00/pg_enums.rs
  server/service/src/apis/permissions.rs
  server/service/src/auth.rs
  server/service/src/login.rs
Labels: enhancement, Priority: Must Have, Team Piwakawaka, feature: GAPS

#4158 4094 soft delete vaccine course
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/Toolbar.tsx
  client/packages/system/src/Immunisation/api/hooks/useDeleteSelectedVaccineCourses.ts
  client/packages/system/src/Immunisation/api/operations.generated.ts
  client/packages/system/src/Immunisation/api/operations.graphql
  server/graphql/vaccine_course/src/lib.rs
  server/graphql/vaccine_course/src/mutations/delete_vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/mod.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_row.rs
  server/repository/src/migrations/v2_01_00/vaccine_course.rs
  server/service/src/vaccine_course/delete.rs
  server/service/src/vaccine_course/insert.rs
  server/service/src/vaccine_course/mod.rs
  server/service/src/vaccine_course/test/delete.rs
  server/service/src/vaccine_course/test/mod.rs
  server/service/src/vaccine_course/update.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#4170 4162 delete immunisation programs
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Immunisation/ListView/ListView.tsx
  client/packages/system/src/Immunisation/ListView/Toolbar.tsx
  client/packages/system/src/Immunisation/api/hooks/useDeleteSelectedImmunisationPrograms.ts
  client/packages/system/src/Immunisation/api/operations.generated.ts
  client/packages/system/src/Immunisation/api/operations.graphql
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/mutations/immunisation/delete.rs
  server/graphql/programs/src/mutations/immunisation/mod.rs
  server/repository/src/db_diesel/program_requisition/program.rs
  server/repository/src/db_diesel/program_requisition/program_row.rs
  server/repository/src/migrations/v2_01_00/program.rs
  server/repository/src/mock/program.rs
  server/service/src/missing_program.rs
  server/service/src/program/delete_immunisation.rs
  server/service/src/program/insert_immunisation.rs
  server/service/src/program/mod.rs
  server/service/src/program/test/delete.rs
  server/service/src/program/test/mod.rs
  server/service/src/program/update_immunisation.rs
  server/service/src/sync/test/test_data/program_requisition_settings.rs
  server/service/src/sync/translations/program_requisition_settings.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#4193 Permission f/e refactor
  client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
  client/packages/common/src/authentication/hooks/index.ts
  client/packages/common/src/authentication/hooks/useCallbackWithPermission.ts
  client/packages/common/src/authentication/hooks/useCheckPermissionWithError.ts
  client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/utils/index.ts
  client/packages/common/src/utils/regex/RegexUtils.tsx
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/useSelectedIds.ts
  client/packages/invoices/src/Returns/InboundListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/OutboundListView/AppBarButtons.tsx
  client/packages/programs/src/JsonForms/common/components/CategorizationTabLayout.tsx
  client/packages/programs/src/JsonForms/common/components/ConditionalSelect.tsx
  client/packages/programs/src/JsonForms/common/components/Select.tsx
  client/packages/programs/src/JsonForms/components/AdherenceScore.tsx
  client/packages/programs/src/JsonForms/components/DecisionTree/DecisionTree.tsx
  client/packages/programs/src/JsonForms/components/EncounterLineChart.tsx
  client/packages/programs/src/JsonForms/components/EnrolmentId.tsx
  client/packages/programs/src/JsonForms/components/HistoricEncounterData.tsx
  client/packages/programs/src/JsonForms/components/IdGenerator.tsx
  client/packages/programs/src/JsonForms/components/PreviousEncounterField.tsx
  client/packages/programs/src/JsonForms/components/ProgramEvent.tsx
  client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx
  client/packages/programs/src/JsonForms/components/Search/SearchWithDocumentSource.tsx
  client/packages/programs/src/JsonForms/stripEmptyAdditions.ts
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/AppBarButtons.tsx
  client/packages/system/src/Immunisation/ListView/AppBarButtons.tsx
  client/packages/system/src/Immunisation/api/hooks/useImmunisationProgram.ts
  client/packages/system/src/Immunisation/api/hooks/useVaccineCourse.ts
  client/packages/system/src/IndicatorsDemographics/DetailView/AppBarButtons.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/Footer.tsx
  client/packages/system/src/IndicatorsDemographics/api/api.ts
  client/packages/system/src/Patient/ListView/AppBarButtons.tsx
Labels: enhancement, Priority: Must Have, Team Piwakawaka, feature: GAPS

#4188 4187 Add config env variable override to docs and build script
  build/mac/open_msupply_server.sh
  server/README.md
  server/server/src/configuration.rs
  server/service/src/sync/test/integration/README.md
Labels: Team Ruru 🦉, Severity: High

#4189 Comment out table relevant fields
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseView.tsx
Labels: Bug, Priority: Should have, Team Piwakawaka, feature: GAPS

#4190 Add baseYear to demographicIndicator graphql call for consistent display
  client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseItemSelect.tsx
  client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseView.tsx
  client/packages/system/src/Immunisation/api/operations.generated.ts
  client/packages/system/src/Immunisation/api/operations.graphql
Labels: Bug, Team Piwakawaka, Severity: Normal, feature: GAPS

#4192 Update GAPS Enums for Gas and Kerosene
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
Labels: Bug, Priority: Must Have, Team Piwakawaka, feature: GAPS

#4181 3827 Footer being real cosy with nav
  client/packages/common/src/ui/components/portals/AppFooter/AppFooter.tsx
Labels: Bug, make omSupply delightful, Team Ruru 🦉, Severity: Low, docs: external

#4172 Demographic UI updates
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.test.tsx
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/GrowthRow.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/NameColumn.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/PercentageColumn.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/PopulationColumn.tsx
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicators.ts
Labels: Bug, Team Piwakawaka, feature: GAPS

#4182 3729 Returns: if there is no 'Reason' configured on mSupply, you still can type to search
  client/packages/system/src/ReturnReason/Components/ReturnReasonSearchInput.tsx
Labels: enhancement, Priority: Nice to Have, Team Ruru 🦉, feature: returns

#4186 Drop consumption view in migration
  server/repository/src/migrations/v2_01_00/ledger.rs
Labels: Bug, Severity: Low

#4183 3425 Column titles/headers truncated throughout app despite plenty of screen space
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/Returns/InboundListView/ListView.tsx
  client/packages/invoices/src/Returns/OutboundListView/ListView.tsx
Labels: Bug, Team Ruru 🦉, Severity: Normal, docs: external

#4196 GAPS: Add 0.0 storage capacity to Fridge Freezers where it wasn't defined
  server/repository/src/migrations/v2_01_00/assets/asset_property_data.rs
Labels: Bug, Priority: Nice to Have, Team Piwakawaka, feature: CCEI, feature: GAPS

#4178 3331 add return reason to invoice query
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/return_reason.rs
  server/graphql/types/src/types/invoice_line.rs
  server/service/src/name_property.rs
  server/service/src/sync/translations/property.rs
Labels: enhancement, back-end, Build Tested: Dev, Team Ruru 🦉, feature: returns

#4195 4086 add custom properties to cold chain equipment csv import
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
  client/packages/system/src/Asset/index.ts
  client/packages/system/src/index.ts
  client/packages/system/src/utils.ts
Labels: enhancement, Severity: Normal, feature: GAPS

#4208 4205 vaccine course enabled wording
  client/packages/common/src/intl/locales/en/coldchain.json
Labels: enhancement, Priority: Nice to Have, Team Piwakawaka, feature: GAPS

#4210 remove editable input on catalogue asset model
  client/packages/system/src/Asset/ListView/EditableInput.tsx
  client/packages/system/src/Asset/ListView/ListView.tsx
Labels: bug, Team Piwakawaka, feature: CCEI

#4211 4203 remove voltage stabilizer for insulated containers
  server/repository/src/migrations/v2_01_00/assets/asset_property_data.rs
Labels: enhancement, Priority: Nice to Have, Team Piwakawaka, feature: CCEI

#4223 4194 increase stock by less than one
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/prescription_line/update.rs
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/insert/validate.rs
  server/service/src/invoice_line/stock_in_line/update/mod.rs
  server/service/src/invoice_line/stock_in_line/update/validate.rs
  server/service/src/invoice_line/stock_in_line/validate.rs
Labels: bug, Team Piwakawaka, Severity: High

#4216 4171 remove as type usage
  client/packages/system/src/IndicatorsDemographics/DetailView/AppBarButtons.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/GrowthRow.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/utils.tsx
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjection.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjections.ts
Labels: refactor, Team Piwakawaka, feature: CCEI

#4227 Display RC version
  package.json
  server/repository/src/migrations/version.rs
Labels: enhancement

#4228 add client tests action
  .github/workflows/client-tests.yaml
Labels: enhancement, Priority: Must Have, Team Piwakawaka

#4225 #4152 Date filter label fix
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
Labels: bug, Team Ruru 🦉, Severity: High

#4232 4215 asset import template has duplicates
  client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
Labels: bug, Team Piwakawaka, Severity: Normal, feature: CCEI

#4241 4238 Can't upgrade from 2.0.3 to 2.1
  server/repository/src/migrations/v2_01_00/store_add_name_link_id.rs
Labels: bug, Team Ruru 🦉, Severity: High

#4236 4229 assets with no store cant be edited
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/types.ts
  client/packages/system/src/Store/api/api.ts
  client/packages/system/src/Store/api/hooks/document/useStores.ts
  client/packages/system/src/Store/api/hooks/utils/useStoreApi.ts
Labels: bug, feature: coldchain, Team Piwakawaka, Severity: High, feature: GAPS

#4245 4231 fix properties typo
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
Labels: bug, feature: coldchain, Team Piwakawaka, Severity: Low, feature: GAPS

#4244 3885 fix catalogue item autocomplete duplicates
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
Labels: bug, Team Piwakawaka, Severity: Normal, feature: CCEI

#4246 4207 fix ledger quantities in postgres
  server/graphql/general/src/queries/ledger.rs
  server/repository/src/db_diesel/ledger.rs
Labels: bug, Team Piwakawaka, Severity: Normal, HUNCHY FUNCHY

#4247 4020 map sell prices through on invoice transfer
  server/service/src/processors/transfer/invoice/common.rs
  server/service/src/processors/transfer/invoice/test.rs
Labels: bug, Team Piwakawaka, Severity: Normal

#4243 Add unit and allow decimals to vaccine course view fields
  .github/workflows/client-tests.yaml
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
  client/packages/system/src/Asset/index.ts
  client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseView.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/GrowthRow.tsx
  client/packages/system/src/index.ts
  client/packages/system/src/utils.ts
Labels: enhancement, Team Piwakawaka, Severity: Low, feature: GAPS

#4249 3696 remove caching of reasons
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/document/useInventoryAdjustmentReason.ts
  client/packages/system/src/ReturnReason/api/hooks/document/useReturnReasons.ts
Labels: bug, Team Piwakawaka, Severity: Normal

#4177 2882.3 update be crates
  server/Cargo.lock
  server/README.md
  server/server/Cargo.toml
  server/server/src/certs.rs
  server/server/src/lib.rs
Labels: enhancement, back-end, Build Tested: Dev, Team Tauhou, Team Ruru 🦉

#4212 #4126 Fix stockline invalidation after repack
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
  client/packages/system/src/Stock/api/hooks/useRepack.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
Labels: bug, Team Ruru 🦉, Severity: High

#4259 3806 Cold chain: Rename mSupply sensor type
  client/packages/common/src/intl/locales/en/coldchain.json
Labels: enhancement, feature: coldchain, Team Ruru 🦉, docs: external

#4258 4175 Can't enter exact decimal value under 'Pack Qty Issued' column in item-line in Outbounds
  client/packages/invoices/src/StockOut/utils.tsx
Labels: Team Ruru 🦉, Severity: High

#4255 3874 you can perform transactions on disabled oms store
  client/packages/common/src/authentication/api/hooks/useLogin.ts
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.graphql
  client/packages/common/src/types/schema.ts
  client/packages/host/src/components/Footer/StoreSelector.tsx
  server/graphql/types/src/types/user.rs
  server/repository/src/db_diesel/store_row.rs
  server/repository/src/migrations/v2_01_00/mod.rs
  server/repository/src/migrations/v2_01_00/store_add_name_link_id_and_is_disabled.rs
  server/service/src/sync/translations/store.rs
Labels: bug, Priority: Should have, Team Ruru 🦉, Severity: High

#4261 2780 requisition no bar graph shown if soh = 0
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/requisitions/src/ResponseRequisition/DetailView/ReponseStats/ResponseStoreStats.tsx
Labels: enhancement, Priority: Should have, docs: external

#4267 Add commas to demographic numbers
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/PopulationColumn.tsx
Labels: bug, Severity: Low

#4257 4067 view stock 'cancel/close' button disabled
  client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
  client/packages/system/src/Stock/DetailView/DetailView.tsx
  client/packages/system/src/Stock/DetailView/Footer.tsx
Labels: enhancement, Priority: Should have, Team Ruru 🦉, Severity: Normal, docs: external

#4276 3935 prevent update of stock line when counted packs is none
  server/service/src/stocktake/update.rs
Labels: bug, Team Piwakawaka, Severity: Normal

#4277 4264 demographic growth rates not saving
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicProjectionUpsert.ts
Labels: bug, Team Piwakawaka, feature: GAPS

#4274 3994 Don't display foreign currency total if foreign currency id is the same as home currency
  client/packages/coldchain/src/Equipment/DetailView/Tabs/StatusLogs.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureTooltip.tsx
  client/packages/coldchain/src/Sensor/Components/SensorLineForm.tsx
  client/packages/coldchain/src/Sensor/ListView/ListView.tsx
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/common/src/utils/globalConst.ts
  client/packages/common/src/utils/index.ts
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/RelatedDocumentsSection.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/RelatedDocumentsSection.tsx
  client/packages/programs/src/JsonForms/components/EncounterLineChart.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Footer/StatusChangeButton.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/SidePanel.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/AdditionalInfoSection.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/RelatedDocumentsSection.tsx
  client/packages/system/src/Encounter/DetailView/SidePanel.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/system/src/Immunisation/ListView/ListView.tsx
  client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx
Labels: bug, Severity: Low, docs: external

#4288 remove selection column for remote sites
  client/packages/system/src/Asset/ListView/ListView.tsx
Labels: bug, feature: coldchain, Team Piwakawaka, Severity: Low

#4282 3738 transfer comment and reference updates
  server/service/src/processors/transfer/invoice/common.rs
  server/service/src/processors/transfer/invoice/test.rs
  server/service/src/processors/transfer/invoice/update_inbound_invoice.rs
Labels: bug, Team Piwakawaka, Severity: Normal

#4242 4221 cannot save blank lines
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/formatters/formatters.ts
  client/packages/system/src/IndicatorsDemographics/DetailView/AppBarButtons.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/NameColumn.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/utils.tsx
  client/packages/system/src/IndicatorsDemographics/api/api.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicatorInsert.ts
  client/packages/system/src/IndicatorsDemographics/api/hooks/document/useDemographicIndicatorUpdate.ts
  client/packages/system/src/IndicatorsDemographics/types.ts
  server/graphql/demographic/src/mutations/insert_indicator.rs
  server/service/src/demographic/insert_demographic_indicator.rs
  server/service/src/demographic/tests/insert_indicator.rs
  server/service/src/demographic/tests/update_indicator.rs
Labels: bug, Team Piwakawaka, Severity: Normal, feature: GAPS

#4285 Update f/e dependencies part #1
  client/__mocks__/zustand.ts
  client/package.json
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
  client/packages/common/package.json
  client/packages/common/src/hooks/useBoundingClientRect/useBoundingClientRect.test.tsx
  client/packages/common/src/hooks/useDebounce/useDebounceCallback.test.tsx
  client/packages/common/src/hooks/useDebounce/useDebouncedValue.test.tsx
  client/packages/common/src/hooks/useDebounce/useDebouncedValueCallback.test.tsx
  client/packages/common/src/hooks/useDrawer/useDrawer.test.tsx
  client/packages/common/src/hooks/useWindowDimensions/useWindowDimensions.test.tsx
  client/packages/common/src/intl/strings/IntlStrings.ts
  client/packages/common/src/styles/RTLProvider.test.tsx
  client/packages/common/src/ui/components/buttons/standard/ButtonWithIcon.tsx
  client/packages/common/src/ui/components/buttons/standard/ShrinkableBaseButton.tsx
  client/packages/common/src/ui/components/inputs/Select/Select.tsx
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/PasswordTextInput.tsx
  client/packages/common/src/ui/components/menus/DropdownMenu/DropdownMenu.test.tsx
  client/packages/common/src/ui/components/navigation/Tabs/Tabs.tsx
  client/packages/common/src/ui/components/navigation/Tabs/useTabs.test.ts
  client/packages/common/src/ui/components/portals/DetailPanel/DetailPanel.test.tsx
  client/packages/common/src/ui/components/steppers/VerticalStepper/VerticalStepper.tsx
  client/packages/common/src/ui/index.ts
  client/packages/common/src/ui/layout/tables/context/TableContext.test.tsx
  client/packages/electron/package.json
  client/packages/host/package.json
  client/packages/host/src/components/Login/LoginTextInput.tsx
  client/packages/programs/package.json
  client/packages/programs/src/JsonForms/common/components/Array/common.tsx
  client/packages/system/package.json
  client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseView.tsx
  client/yarn.lock
Labels: enhancement, Priority: Should have, refactor, Team Piwakawaka, Tooling

#4275 4024 stock lines not included in search
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/ItemSelector.tsx
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
  client/packages/system/src/Item/api/api.ts
  client/packages/system/src/Item/api/hooks/useItemStockOnHand/useItemStockOnHand.tsx
  client/packages/system/src/Item/utils.ts
  server/graphql/general/src/queries/item.rs
  server/repository/src/db_diesel/item.rs
  server/repository/src/db_diesel/stock_line.rs
  server/repository/src/db_diesel/stock_on_hand.rs
Labels: bug, Team Piwakawaka, Severity: Normal
