Repository msupply-foundation/open-msupply, pull requests merged in 2024-03, with the labels that each got.

#3122 #3011 Outbound returns data table
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/invoices/src/Returns/DetailView/ContentArea.tsx
  client/packages/invoices/src/Returns/DetailView/DetailView.tsx
  client/packages/invoices/src/Returns/DetailView/columns.ts
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/useOutboundReturn.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
Labels: Team Ruru 🦉

#3124 Asset Reference DataLoaders
  server/graphql/asset/src/types.rs
  server/graphql/core/src/loader/asset_catalogue_item.rs
  server/graphql/core/src/loader/asset_category.rs
  server/graphql/core/src/loader/asset_class.rs
  server/graphql/core/src/loader/asset_type.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/types/src/types/asset_catalogue_item.rs
  server/service/src/asset/update.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3152 Remove store_id from catalogue queries
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Asset/api/api.ts
  client/packages/system/src/Asset/api/operations.generated.ts
  client/packages/system/src/Asset/api/operations.graphql
Labels: Team Piwakawaka

#2909 2903 currency selection for outbound shipment
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
  server/graphql/invoice/src/mutations/outbound_shipment/update.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/invoice/outbound_shipment/update/validate.rs
Labels: enhancement, feature: currency, Team Tauhou

#3161 Add page titles and placeholder docs links
  client/packages/common/src/utils/environment/EnvUtils.ts
Labels: enhancement, Team Ruru 🦉

#3156 Asset detail base
  client/packages/coldchain/src/ColdchainService.tsx
  client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/DetailView/Footer/Footer.tsx
  client/packages/coldchain/src/Equipment/DetailView/Footer/index.ts
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Details.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Documents.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/StatusLogs.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/index.ts
  client/packages/coldchain/src/Equipment/DetailView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/coldchain/src/Equipment/DetailView/index.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  server/graphql/reports/src/reports.rs
  server/repository/src/db_diesel/report_row.rs
  server/repository/src/migrations/v1_08_00/assets/asset.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3137 2973 asset list view
  client/packages/coldchain/src/ColdchainService.tsx
  client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/DetailView/Footer/Footer.tsx
  client/packages/coldchain/src/Equipment/DetailView/Footer/index.ts
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Details.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Documents.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/StatusLogs.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/index.ts
  client/packages/coldchain/src/Equipment/DetailView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/coldchain/src/Equipment/DetailView/index.ts
  client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/ListView/index.ts
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAsset.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetFields.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetInsert.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetsAll.ts
  client/packages/coldchain/src/Equipment/api/hooks/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/line/useAssets/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/utils/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/utils/useAssetApi.ts
  client/packages/coldchain/src/Equipment/api/index.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/coldchain/src/Equipment/index.ts
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/catalogue.json
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/config/src/routes.ts
  client/packages/host/src/components/AppBar/SectionIcon.tsx
  client/packages/host/src/components/Navigation/ColdChainNav.tsx
  client/packages/host/src/routers/ColdChainRouter.tsx
  client/packages/system/src/Asset/ListView/AppBarButtons.tsx
  client/packages/system/src/Asset/ListView/ListView.tsx
  client/packages/system/src/Asset/ListView/Toolbar.tsx
  client/packages/system/src/Asset/api/api.ts
  client/packages/system/src/Asset/api/hooks/document/useAssets.ts
  client/packages/system/src/Asset/api/hooks/index.ts
  client/packages/system/src/Asset/api/hooks/utils/useAssetApi.ts
  client/packages/system/src/Asset/api/hooks/utils/useAssetCategories.ts
  client/packages/system/src/Asset/api/operations.generated.ts
  client/packages/system/src/Asset/api/operations.graphql
  client/packages/system/src/Asset/index.ts
  client/packages/system/src/Asset/utils.ts
  server/graphql/reports/src/reports.rs
  server/repository/src/db_diesel/report_row.rs
  server/repository/src/migrations/v1_08_00/assets/asset.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3138 2987 query asset register log list
  package.json
  server/graphql/asset/src/lib.rs
  server/graphql/asset/src/logs/mod.rs
  server/graphql/asset/src/logs/query.rs
  server/graphql/asset/src/types.rs
  server/repository/src/db_diesel/assets/asset_log.rs
  server/repository/src/db_diesel/assets/asset_log_row.rs
  server/repository/src/db_diesel/assets/mod.rs
  server/repository/src/migrations/v1_08_00/assets/asset_log.rs
  server/repository/src/migrations/v1_08_00/assets/mod.rs
  server/repository/src/mock/asset_log.rs
  server/repository/src/mock/mod.rs
  server/service/src/asset/mod.rs
  server/service/src/asset/query_log.rs
  server/service/src/asset/tests/mod.rs
  server/service/src/asset/tests/query_log.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3165 2986 mutations for asset register logs
  server/graphql/asset/src/lib.rs
  server/graphql/asset/src/logs/insert.rs
  server/graphql/asset/src/logs/mod.rs
  server/repository/src/db_diesel/assets/asset_log.rs
  server/service/src/asset/insert_log.rs
  server/service/src/asset/mod.rs
  server/service/src/asset/tests/insert_log.rs
  server/service/src/asset/tests/mod.rs
  server/service/src/asset/validate.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3162 3085 Tetum translation FE errors
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/common/src/intl/locales/tet/distribution.json
  client/packages/common/src/intl/locales/tet/inventory.json
  client/packages/common/src/intl/locales/tet/replenishment.json
  client/packages/inventory/src/Stocktake/ListView/Toolbar.tsx
  client/packages/invoices/src/InboundShipment/ListView/Toolbar.tsx
  client/packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/ListView/Toolbar.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/Toolbar.tsx
  client/packages/system/src/Location/ListView/Toolbar.tsx
Labels: bug, front-end, Team Tauhou, Severity: Normal

#3151 3055 & 3030 cold chain display
  client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx
  client/packages/coldchain/src/Sensor/Components/SensorLineForm.tsx
  client/packages/coldchain/src/Sensor/ListView/ListView.tsx
  client/packages/coldchain/src/common/utils.ts
  client/packages/common/src/intl/locales/en/coldchain.json
Labels: bug, enhancement, feature: coldchain, Team Tauhou

#3131 3040 Location filter is for location name, but the code is shown in the list view
  client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/Toolbar.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts
  client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/Toolbar.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/ListView/Toolbar.tsx
Labels: bug, Team Tauhou, Severity: Normal

#3129 2917 Cannot allocate expiry message not clear enough
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/common/src/intl/locales/en/distribution.json
Labels: bug, Team Tauhou, Severity: Normal

#3168 Inbound shipments: long references not visible when status is "shipped" #3079
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
Labels: bug, needs details/discussion, make omSupply delightful, Team Tauhou, Severity: Normal, needs design

#3171 3076 coldchain breach comment overflow
  client/packages/common/src/ui/components/popover/PaperPopover/PaperPopoverSection.tsx
Labels: bug, make omSupply delightful, Severity: Low

#3041 3022 add items to existing outbound return
  client/packages/invoices/src/Returns/DetailView/DetailView.tsx
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/index.ts
  client/packages/invoices/src/Returns/api/hooks/line/index.ts
  client/packages/invoices/src/Returns/api/hooks/line/useInboundReturnLines.ts
  client/packages/invoices/src/Returns/api/hooks/line/useOutboundReturnLines.ts
  client/packages/invoices/src/Returns/api/hooks/line/useUpdateOutboundReturnLines.ts
  client/packages/invoices/src/Returns/api/hooks/utils/useReturnsApi.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/modals/OutboundReturn/ItemSelector.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/OutboundReturn.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/ReturnSteps.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/useDraftOutboundReturnLines.ts
  client/packages/invoices/src/Returns/modals/ReturnReasonsTable.tsx
Labels: enhancement, Team Ruru 🦉

#3027 2857 program event clean up
  server/graphql/programs/src/queries/program_event.rs
  server/graphql/types/src/types/program/encounter.rs
  server/graphql/types/src/types/program/program_enrolment.rs
  server/service/src/programs/encounter/encounter_updated.rs
  server/service/src/programs/encounter/suggested_next_encounter.rs
  server/service/src/programs/program_event.rs
Labels: feature: programs, Team Tauhou

#3026 2857 suggest next encounter date
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
  client/packages/system/src/Patient/Encounter/EncounterSearchInput.tsx
  client/packages/system/src/Patient/api/api.ts
  client/packages/system/src/Patient/api/hooks/document/index.ts
  client/packages/system/src/Patient/api/hooks/document/useLatestPatientEncounter.ts
  client/packages/system/src/Patient/api/hooks/index.ts
  client/packages/system/src/Patient/api/hooks/utils/usePatientApi.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  server/graphql/programs/src/queries/program_event.rs
  server/graphql/types/src/types/program/encounter.rs
  server/graphql/types/src/types/program/program_enrolment.rs
  server/repository/src/db_diesel/document_registry_config.rs
  server/service/src/programs/encounter/encounter_updated.rs
  server/service/src/programs/encounter/mod.rs
  server/service/src/programs/encounter/suggested_next_encounter.rs
  server/service/src/programs/program_event.rs
Labels: feature: programs, Team Tauhou

#3158 3051 Doesn't select the searched entry from list in program enrolment form
  client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
Labels: bug, feature: programs, Team Tauhou, Severity: High

#3201 3198 fix rust warnings
  server/Cargo.lock
  server/cli/src/refresh_dates.rs
  server/graphql/batch_mutations/src/batch_inbound_shipment.rs
  server/graphql/batch_mutations/src/batch_outbound_shipment.rs
  server/graphql/batch_mutations/src/batch_prescription.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/general/src/queries/initialisation_status.rs
  server/graphql/general/src/queries/log.rs
  server/graphql/stocktake/src/stocktake_queries.rs
  server/graphql/stocktake_line/src/lib.rs
  server/graphql/stocktake_line/src/stocktake_line_queries.rs
  server/graphql/types/src/types/barcode.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/item_chart.rs
  server/graphql/types/src/types/location.rs
  server/graphql/types/src/types/name.rs
  server/graphql/types/src/types/program/document.rs
  server/graphql/types/src/types/program/encounter.rs
  server/graphql/types/src/types/stocktake.rs
  server/report_builder/src/build.rs
  server/repository/src/database_settings.rs
  server/repository/src/db_diesel/consumption.rs
  server/repository/src/db_diesel/stock_movement.rs
  server/repository/src/db_diesel/stock_on_hand.rs
  server/repository/src/db_diesel/temperature_chart/temperature_chart.rs
  server/repository/src/diesel_extensions.rs
  server/repository/src/migrations/templates/add_data_from_sync_buffer/mod.rs
  server/repository/src/migrations/templates/adding_table/mod.rs
  server/repository/src/migrations/templates/data_and_schema/mod.rs
  server/repository/src/migrations/templates/data_migration/mod.rs
  server/repository/src/migrations/v1_03_00/user.rs
  server/repository/src/migrations/v1_06_00/changelog_deduped.rs
  server/repository/src/migrations/v1_06_00/plugin_data.rs
  server/service/src/auth.rs
  server/service/src/document/document_service.rs
  server/service/src/document/raw_document.rs
  server/service/src/requisition_line/chart/mod.rs
  server/service/src/stocktake/batch.rs
  server/service/src/sync/translations/special/clinician_merge.rs
  server/service/src/sync/translations/special/item_merge.rs
  server/service/src/sync/translations/special/name_merge.rs
  server/service/src/token.rs
  server/service/src/user_account.rs
Labels: refactor, Team Tauhou

#3197 Disable the modal save button when creating an encounter
  client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
Labels: bug, feature: programs, Team Tauhou, Severity: High

#3194 Bug fix for sqlite download on old android installs with old database…
  client/packages/android/app/src/main/java/org/openmsupply/client/FileManager.java
  client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
Labels: bug, Severity: High

#3127 UI improvements for pack variant
  client/packages/common/src/ui/layout/tables/DataTable.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/utils.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/system/src/Item/Components/PackVariant/PackVariantEntryCell.tsx
  client/packages/system/src/Item/ListView/ListView.tsx
  client/packages/system/src/Item/context/usePackVariant.ts
  client/packages/system/src/Stock/ListView/ListView.tsx
  server/service/src/pack_variant/query.rs
  server/service/src/sync/synchroniser.rs
Labels: enhancement, feature: pack variant, Team Ruru 🦉

#3169 #3012 Detail view Footer
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/invoices/src/Returns/DetailView/DetailView.tsx
  client/packages/invoices/src/Returns/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/DetailView/Footer/OnHoldButton.tsx
  client/packages/invoices/src/Returns/DetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Returns/DetailView/Footer/index.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/utils.ts
Labels: Team Ruru 🦉

#3221 Move PV migrations to 1.8
  client/packages/system/src/Item/Components/PackVariant/PackVariantCell.tsx
  package.json
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v1_07_00/mod.rs
  server/repository/src/migrations/v1_08_00/central_omsupply.rs
  server/repository/src/migrations/v1_08_00/mod.rs
  server/repository/src/migrations/v1_08_00/pack_variant.rs
Labels: bug, Severity: High

#3200 Asset summary tab
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/DetailView/Footer/Footer.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetUpdate.ts
  client/packages/coldchain/src/Equipment/api/hooks/index.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/user_permission_row.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3228 Rename name
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Details.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  server/graphql/asset/src/lib.rs
  server/graphql/asset/src/mutations/insert.rs
  server/graphql/asset/src/mutations/update.rs
  server/graphql/asset/src/types.rs
  server/repository/src/db_diesel/assets/asset.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/migrations/v1_08_00/assets/asset.rs
  server/repository/src/mock/asset.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/tests/insert.rs
  server/service/src/asset/tests/query.rs
  server/service/src/asset/tests/update.rs
  server/service/src/asset/update.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3225 Delete assets
  client/packages/coldchain/src/ColdchainNotification.tsx
  client/packages/coldchain/src/Equipment/DetailView/Footer/Footer.tsx
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/api/hooks/document/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetDelete.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetsDelete.ts
  client/packages/coldchain/src/Equipment/api/hooks/index.ts
  client/packages/coldchain/src/Monitoring/ListView/AppBarButtons.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/useAcknowledgeBreachModal.tsx
  client/packages/coldchain/src/Sensor/Components/SensorEditModal.tsx
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/ui/components/buttons/standard/BaseButton.tsx
  client/packages/common/src/ui/components/buttons/standard/ButtonWithIcon.tsx
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3114 3081 update outbound return lines
  server/graphql/invoice/src/lib.rs
  server/graphql/invoice/src/mutations/outbound_return/insert.rs
  server/graphql/invoice/src/mutations/outbound_return/mod.rs
  server/graphql/invoice/src/mutations/outbound_return/update_lines.rs
  server/repository/src/mock/invoice_line.rs
  server/service/src/invoice/mod.rs
  server/service/src/invoice/outbound_return/insert/generate.rs
  server/service/src/invoice/outbound_return/insert/mod.rs
  server/service/src/invoice/outbound_return/mod.rs
  server/service/src/invoice/outbound_return/update_lines/generate.rs
  server/service/src/invoice/outbound_return/update_lines/mod.rs
  server/service/src/invoice/outbound_return/update_lines/validate.rs
Labels: enhancement, Team Ruru 🦉

#3224 3163 inbound return details view
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/common/src/localStorage/keys.ts
  client/packages/common/src/ui/layout/tables/context/hooks/useIsGrouped.ts
  client/packages/invoices/src/InvoiceService.tsx
  client/packages/invoices/src/Returns/DetailView/index.ts
  client/packages/invoices/src/Returns/InboundDetailView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/InboundDetailView/ContentArea.tsx
  client/packages/invoices/src/Returns/InboundDetailView/DetailView.tsx
  client/packages/invoices/src/Returns/InboundDetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/InboundDetailView/Footer/OnHoldButton.tsx
  client/packages/invoices/src/Returns/InboundDetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Returns/InboundDetailView/Footer/index.ts
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/index.ts
  client/packages/invoices/src/Returns/InboundDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/InboundDetailView/columns.ts
  client/packages/invoices/src/Returns/InboundDetailView/index.ts
  client/packages/invoices/src/Returns/OutboundDetailView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/ContentArea.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/DetailView.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/Footer/OnHoldButton.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/Footer/index.ts
  client/packages/invoices/src/Returns/OutboundDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/columns.ts
  client/packages/invoices/src/Returns/OutboundDetailView/index.ts
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/index.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInboundDelete.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInboundDeleteRows.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInboundReturn.ts
  client/packages/invoices/src/Returns/api/hooks/index.ts
  client/packages/invoices/src/Returns/api/hooks/line/index.ts
  client/packages/invoices/src/Returns/api/hooks/line/useDeleteSelectedInboundLines.ts
  client/packages/invoices/src/Returns/api/hooks/line/useInboundReturnRows.ts
  client/packages/invoices/src/Returns/api/hooks/utils/index.ts
  client/packages/invoices/src/Returns/api/hooks/utils/useInboundReturnIsDisabled.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/index.ts
  client/packages/invoices/src/types.ts
  client/packages/invoices/src/utils.ts
  server/graphql/invoice/src/invoice_queries.rs
Labels: enhancement, Team Ruru 🦉

#3202 Reduce bundle size
  client/packages/coldchain/src/index.ts
  client/packages/common/src/intl/utils/IntlUtils.ts
  client/packages/host/webpack.config.js
  client/packages/programs/package.json
Labels: bug

#3234 3094 Pricing tab in invoice lines has a confusing column selection
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/system/src/Item/Components/ItemOptionRenderer/ItemOptionRenderer.tsx
Labels: bug, enhancement, Priority: Should have, Team Tauhou, Severity: Normal

#3196 Fix end of supply display
  client/packages/programs/src/JsonForms/components/QuantityDispensed.tsx
Labels: bug, Team Tauhou, Severity: Normal

#3235 #3013 Outbound return SidePanel
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/invoices/src/Returns/OutboundDetailView/DetailView.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/index.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/utils.ts
Labels: Team Ruru 🦉

#3229 Add full type description of asset log.
  server/graphql/asset/src/lib.rs
  server/graphql/asset/src/logs/insert.rs
  server/graphql/asset/src/types.rs
  server/graphql/lib.rs
  server/repository/src/db_diesel/assets/asset_log.rs
  server/repository/src/db_diesel/assets/asset_log_row.rs
  server/repository/src/migrations/v1_08_00/assets/asset_log.rs
  server/repository/src/mock/asset_log.rs
  server/repository/src/mock/mod.rs
  server/service/src/asset/insert_log.rs
  server/service/src/asset/tests/insert_log.rs
  server/service/src/asset/validate.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3244 3126 mandatory patient fields 2
  client/packages/programs/src/JsonForms/common/components/Text.tsx
  client/packages/system/src/Patient/DefaultPatientSchema.json
Labels: bug, Team Tauhou, Severity: High, feature: dispensing

#3253 Table Hide/Show columns selector not mapping selection correctly #3125
  client/packages/common/src/ui/layout/tables/components/Header/ColumnPicker.tsx
Labels: bug, Team Tauhou, Severity: Normal

#3249 2541 can't close a patient without first editing something
  client/packages/system/src/Patient/PatientView/Footer.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
Labels: bug, front-end, Priority: Nice to Have, make omSupply delightful, Team Tauhou

#3250 2926 Datepicker moves if it is to close to the edge
  client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
Labels: bug, Team Tauhou, Severity: Normal

#3241 3204 add enum of reasons
  server/graphql/asset/src/logs/insert.rs
  server/graphql/asset/src/mutations/insert.rs
  server/graphql/asset/src/types.rs
  server/repository/src/db_diesel/assets/asset.rs
  server/repository/src/db_diesel/assets/asset_log.rs
  server/repository/src/db_diesel/assets/asset_log_row.rs
  server/repository/src/migrations/v1_08_00/assets/asset_log.rs
  server/repository/src/mock/asset_log.rs
  server/service/src/asset/insert_log.rs
  server/service/src/asset/tests/insert_log.rs
  server/service/src/asset/tests/update.rs
  server/service/src/asset/validate.rs
Labels: enhancement, Team Piwakawaka

#3247 2523 requisition columns 'remaining' is confusing people
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr-DJ/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  server/graphql/general/src/queries/tests/master_lists.rs
  server/graphql/types/src/types/requisition_line.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/mod.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/validate.rs
Labels: bug, needs architecture/solution, Team Tauhou, needs design

#3170 3155 generate inbound return lines
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/OutboundShipment/api/hooks/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/useSelectedIds.ts
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/index.ts
  client/packages/invoices/src/Returns/api/hooks/line/index.ts
  client/packages/invoices/src/Returns/api/hooks/line/useGenerateInboundReturnLines.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/modals/InboundReturn/InboundReturn.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/ReturnQuantitiesTable.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/useDraftInboundReturnLines.ts
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/generate_inbound_return_lines.rs
  server/graphql/types/src/types/inbound_return_line.rs
  server/graphql/types/src/types/mod.rs
  server/repository/src/mock/invoice.rs
  server/repository/src/mock/invoice_line.rs
  server/service/src/invoice/inbound_return/generate_lines.rs
  server/service/src/invoice/inbound_return/mod.rs
  server/service/src/invoice/mod.rs
Labels: enhancement, Team Ruru 🦉

#3260 Return empty string instead of "multiple" if there are no lines
  client/packages/common/src/ui/layout/tables/utils/ColumnUtils.test.ts
  client/packages/common/src/ui/layout/tables/utils/ColumnUtils.ts
Labels: bug, Severity: Normal

#3237 3181 insert inbound return
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/api/hooks/line/index.ts
  client/packages/invoices/src/Returns/modals/InboundReturn/InboundReturn.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/useDraftInboundReturnLines.ts
  client/packages/invoices/src/Returns/modals/ReturnReasonsTable.tsx
  client/packages/invoices/src/utils.ts
  client/packages/system/src/ReturnReason/Components/ReturnReasonSearchInput.tsx
  server/graphql/invoice/src/invoice_queries.rs
  server/graphql/invoice/src/mutations/inbound_return/insert.rs
  server/repository/src/mock/name.rs
  server/repository/src/mock/name_store_join.rs
  server/service/src/invoice/inbound_return/insert/generate.rs
  server/service/src/invoice/inbound_return/insert/mod.rs
  server/service/src/invoice/inbound_return/insert/validate.rs
  server/service/src/invoice/inbound_return/mod.rs
  server/service/src/invoice/mod.rs
  server/service/src/invoice_line/mod.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/insert/validate.rs
  server/service/src/invoice_line/stock_in_line/mod.rs
Labels: enhancement, Team Ruru 🦉

#3257 Equipment list to show Status
  client/packages/coldchain/src/Equipment/Components/Status.tsx
  client/packages/coldchain/src/Equipment/Components/index.ts
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/styles/theme.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/types/TypeUtils.ts
  server/graphql/asset/src/types.rs
  server/graphql/core/src/loader/asset_status.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/repository/src/db_diesel/assets/asset_log.rs
  server/repository/src/db_diesel/assets/asset_log_row.rs
  server/repository/src/migrations/v1_08_00/assets/asset_log.rs
  server/repository/src/migrations/v1_08_00/assets/latest_asset_log.rs
  server/repository/src/migrations/v1_08_00/assets/mod.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3238 3112 fix sort direction
  client/packages/common/src/hooks/useQueryParams/types.ts
  client/packages/common/src/hooks/useQueryParams/useQueryParams.test.tsx
  client/packages/common/src/hooks/useQueryParams/useQueryParamsStore.tsx
  client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts
  client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
  client/packages/common/src/ui/layout/tables/columns/types.ts
  client/packages/common/src/ui/layout/tables/components/Header/Header.stories.tsx
  client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
  client/packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/api/hooks/line/useInboundItems.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/OutboundShipment/api/api.ts
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/system/src/Encounter/ListView/columns.ts
  client/packages/system/src/Patient/ContactTrace/Components/ListView.tsx
Labels: bug, Team Tauhou, Severity: Normal

#3133 3132 delete outbound returns
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/useOutboundDeleteRows.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/utils.ts
  server/graphql/invoice/src/lib.rs
  server/graphql/invoice/src/mutations/inbound_return/delete.rs
  server/graphql/invoice/src/mutations/outbound_return/delete.rs
  server/service/src/invoice/mod.rs
  server/service/src/invoice/outbound_return/delete/mod.rs
  server/service/src/invoice/outbound_return/delete/validate.rs
  server/service/src/invoice/outbound_return/mod.rs
Labels: enhancement, Team Ruru 🦉

#3154 3144 generate outbound lines existing return
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/line/useOutboundReturnLines.ts
  client/packages/invoices/src/Returns/modals/OutboundReturn/useDraftOutboundReturnLines.ts
  server/graphql/general/src/queries/generate_outbound_return_lines.rs
  server/graphql/types/src/types/outbound_return_line.rs
  server/repository/src/mock/invoice.rs
  server/repository/src/mock/invoice_line.rs
  server/service/src/invoice/outbound_return/generate_outbound_return_lines.rs
Labels: enhancement, Team Ruru 🦉

#3264 1710 The internal order Hide items over the minimum toggle button hides also lines that equals the minimum
  client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/ToolbarActions.tsx
  client/packages/requisitions/src/RequestRequisition/api/hooks/line/useRequestLines.ts
  client/packages/system/src/Item/api/hooks/useStockItemsWithStats/useStockItemsWithStats.tsx
Labels: bug, good first issue, front-end, platform: desktop, Priority: Nice to Have, Team Tauhou

#3251 #3195 Alert when attempting to return 0 quantities
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/DetailView.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/InboundReturn.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/OutboundReturn.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/ReturnSteps.tsx
Labels: enhancement, needs architecture/solution, Team Ruru 🦉

#3258 3254 User Login fails If sqlite database is locked for writing
  client/packages/common/src/api/GqlContext.tsx
  client/packages/common/src/authentication/api/api.ts
  client/packages/common/src/intl/locales/en/app.json
  client/packages/host/src/components/Login/Login.tsx
Labels: bug, Team Tauhou, Severity: High

#3280 Triggers for name store join
  server/repository/src/migrations/v1_07_00/changelog_add_name_link_id.rs
  server/repository/src/migrations/v1_07_00/name_store_join_add_name_link_id.rs
Labels: bug, Team Tauhou, Severity: High

#3259 3243 add asset changes logs
  server/graphql/types/src/types/activity_log.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/migrations/v1_08_00/assets/activity_log.rs
  server/repository/src/migrations/v1_08_00/assets/mod.rs
  server/service/src/asset/delete.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/insert_log.rs
  server/service/src/asset/update.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3274 Insert asset log (UI)
  client/packages/coldchain/src/Equipment/Components/AssetLogPanel.tsx
  client/packages/coldchain/src/Equipment/Components/index.ts
  client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/DetailView/StatusTab.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/coldchain/src/Equipment/DetailView/UploadTab.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/line/useAssets/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/log/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/log/useAssetLogInsert.ts
  client/packages/coldchain/src/Equipment/api/hooks/utils/useAssetApi.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/forms/Detail/Container.tsx
  server/graphql/asset/src/types.rs
  server/graphql/core/src/loader/asset_status_log.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3291 #3288 Fix for 0 value in stocktake count
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Labels: bug, Team Ruru 🦉, Severity: High

#3267 2109 Patient query fails for name_or_code AND identifier
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
  client/packages/system/src/Patient/Components/utils.ts
  server/graphql/programs/src/queries/patient_search.rs
  server/graphql/programs/src/queries/patient_search_central.rs
  server/graphql/types/src/types/program/patient.rs
  server/repository/src/db_diesel/patient.rs
  server/service/src/programs/patient/search.rs
  server/service/src/programs/patient/search_central.rs
Labels: bug, Priority: Nice to Have, Team Tauhou

#3290 Asset logs list
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/StatusLogs.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/log/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/log/useAssetLogs.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/ui/icons/UserCircle.tsx
  client/packages/common/src/ui/icons/index.ts
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3270 3213 Selected tab underline doesn't move correctly with SidePanel open/close
  client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
Labels: bug, front-end, Team Tauhou, Severity: Low

#3272 3185 update inbound return
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/InboundDetailView/Footer/OnHoldButton.tsx
  client/packages/invoices/src/Returns/InboundDetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Returns/InboundListView/ListView.tsx
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/index.ts
  client/packages/invoices/src/Returns/api/hooks/document/useUpdateInboundReturn.ts
  client/packages/invoices/src/Returns/api/hooks/index.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  server/graphql/invoice/src/lib.rs
  server/graphql/invoice/src/mutations/inbound_return/mod.rs
  server/graphql/invoice/src/mutations/inbound_return/update.rs
  server/repository/src/mock/invoice.rs
  server/repository/src/mock/invoice_line.rs
  server/service/src/invoice/inbound_return/mod.rs
  server/service/src/invoice/inbound_return/update/generate.rs
  server/service/src/invoice/inbound_return/update/mod.rs
  server/service/src/invoice/inbound_return/update/validate.rs
  server/service/src/invoice/mod.rs
  server/service/src/invoice/outbound_return/update/generate.rs
Labels: enhancement, Team Ruru 🦉

#3282 3186 delete inbound return
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInboundDeleteRows.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  server/graphql/invoice/src/lib.rs
  server/graphql/invoice/src/mutations/inbound_return/delete.rs
  server/service/src/invoice/inbound_return/delete/mod.rs
  server/service/src/invoice/inbound_return/delete/validate.rs
  server/service/src/invoice/inbound_return/mod.rs
  server/service/src/invoice/mod.rs
  server/service/src/invoice/outbound_return/delete/mod.rs
  server/service/src/invoice_line/stock_in_line/delete/mod.rs
Labels: enhancement, Team Ruru 🦉

#3281 Use a new CurrencyCell to display prices < 0.01
  client/packages/common/src/intl/currency/currency.ts
  client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell/CurrencyCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell/index.ts
  client/packages/common/src/ui/layout/tables/components/Cells/index.ts
  client/packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/useServiceLineColumns.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Labels: bug, Team Tauhou, Severity: Normal, needs design

#3278 3183 update inbound return lines
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInboundDeleteRows.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  server/graphql/invoice/src/lib.rs
  server/graphql/invoice/src/mutations/inbound_return/delete.rs
  server/graphql/invoice/src/mutations/inbound_return/insert.rs
  server/graphql/invoice/src/mutations/inbound_return/mod.rs
  server/graphql/invoice/src/mutations/inbound_return/update_lines.rs
  server/graphql/invoice/src/mutations/outbound_return/insert.rs
  server/repository/src/mock/invoice_line.rs
  server/service/src/invoice/inbound_return/delete/mod.rs
  server/service/src/invoice/inbound_return/delete/validate.rs
  server/service/src/invoice/inbound_return/insert/generate.rs
  server/service/src/invoice/inbound_return/insert/mod.rs
  server/service/src/invoice/inbound_return/mod.rs
  server/service/src/invoice/inbound_return/update_lines/generate.rs
  server/service/src/invoice/inbound_return/update_lines/mod.rs
  server/service/src/invoice/inbound_return/update_lines/validate.rs
  server/service/src/invoice/mod.rs
  server/service/src/invoice/outbound_return/delete/mod.rs
  server/service/src/invoice_line/stock_in_line/delete/mod.rs
  server/service/src/invoice_line/stock_in_line/delete/validate.rs
  server/service/src/invoice_line/stock_in_line/mod.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
  server/service/src/invoice_line/stock_in_line/update/mod.rs
  server/service/src/invoice_line/stock_in_line/update/validate.rs
Labels: enhancement, Team Ruru 🦉

#3265 #3256 Decimal input fix
  client/packages/common/src/intl/number/IntlNumber.ts
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.test.tsx
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/TextInput.stories.tsx
Labels: bug, Team Ruru 🦉, Severity: High

#3311 3269 remove service charge when adding from master list
  server/repository/src/db_diesel/item.rs
  server/repository/src/db_diesel/master_list_line.rs
  server/service/src/invoice/inbound_shipment/add_from_master_list.rs
  server/service/src/invoice/outbound_shipment/add_from_master_list.rs
  server/service/src/requisition/request_requisition/add_from_master_list.rs
  server/service/src/stocktake/insert.rs
Labels: bug, back-end, Team Tauhou, Severity: High

#3313 Use a TooltipTextCell to display batch columns
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
Labels: bug, Team Tauhou, Severity: High, needs design

#3255 3050 fix height input
  client/packages/programs/src/JsonForms/common/components/Number.tsx
  client/packages/programs/src/JsonForms/stripEmptyAdditions.test.ts
  client/packages/programs/src/JsonForms/stripEmptyAdditions.ts
Labels: bug, feature: programs, Team Tauhou, Severity: Normal

#3307 Asset changes after demo / reivew
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/DetailView/StatusTab.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/StatusLogs.tsx
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/popover/DisabledNotification/DisabledNotification.stories.tsx
  client/packages/common/src/ui/components/popover/DisabledNotification/index.ts
  client/packages/common/src/ui/components/popover/DisabledNotification/useDisabledNotification.tsx
  client/packages/common/src/ui/components/popover/PaperPopover/PaperPopoverSection.tsx
  client/packages/common/src/ui/components/popover/index.ts
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/ui/icons/SettingsCircle.tsx
  client/packages/common/src/ui/icons/index.ts
  server/graphql/asset/src/lib.rs
  server/graphql/asset/src/logs/insert.rs
  server/graphql/asset/src/mutations/insert.rs
  server/graphql/asset/src/mutations/update.rs
  server/graphql/asset/src/types.rs
  server/graphql/catalogue/src/asset_catalogue_item_queries.rs
  server/graphql/catalogue/src/asset_category_queries.rs
  server/graphql/catalogue/src/asset_class_queries.rs
  server/graphql/catalogue/src/asset_type_queries.rs
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/assets/asset.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v1_08_00/assets/asset.rs
  server/repository/src/mock/asset.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/update.rs
  server/service/src/auth.rs
  server/service/src/login.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3318 3190 print returns
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/InboundDetailView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/AppBarButtons.tsx
  server/graphql/reports/src/reports.rs
  server/repository/src/db_diesel/report_row.rs
  server/repository/src/migrations/v1_08_00/mod.rs
  server/repository/src/migrations/v1_08_00/return_context_types.rs
Labels: enhancement, Team Ruru 🦉

#3309 3246 Vertical scroll in modals breaks the rounded corners
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditTable.tsx
Labels: bug, front-end, Team Tauhou, Severity: Low

#3310 Handle long column labels in table headers
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/common/src/intl/locales/es/inventory.json
  client/packages/common/src/intl/locales/es/replenishment.json
  client/packages/common/src/intl/locales/fr/inventory.json
  client/packages/common/src/intl/locales/fr/replenishment.json
  client/packages/common/src/intl/locales/pt/inventory.json
  client/packages/common/src/intl/locales/pt/replenishment.json
  client/packages/common/src/intl/locales/ru/inventory.json
  client/packages/common/src/intl/locales/ru/replenishment.json
  client/packages/common/src/intl/locales/tet/inventory.json
  client/packages/common/src/intl/locales/tet/replenishment.json
  client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
Labels: bug, Team Tauhou, Severity: Normal

#3330 Hide the report printing frame to prevent it from being rendered
  client/packages/system/src/Report/api/hooks/utils/usePrintReport.ts
Labels: bug, Team Tauhou

#3358 911 show created date in the detail panel for invoice, requisition, stocktake windows
  client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
  client/packages/inventory/src/Stocktake/ListView/ListView.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/AdditionalInfoSection.tsx
Labels: enhancement, front-end, Priority: Nice to Have, Team Tauhou

#3364 Allow outbound shipments to be deleted until picked
  client/packages/invoices/src/utils.ts
Labels: enhancement

#3336 3191 generate other returns half
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/invoices/src/Returns/InboundDetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/InboundDetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Returns/InboundDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/utils.ts
  server/service/src/invoice/inbound_return/update/mod.rs
  server/service/src/invoice/inbound_return/update/validate.rs
  server/service/src/invoice/outbound_return/delete/mod.rs
  server/service/src/invoice/outbound_return/update/mod.rs
  server/service/src/invoice/outbound_return/update_lines/mod.rs
  server/service/src/processors/transfer/shipment/assign_invoice_number.rs
  server/service/src/processors/transfer/shipment/common.rs
  server/service/src/processors/transfer/shipment/create_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/delete_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/link_outbound_shipment.rs
  server/service/src/processors/transfer/shipment/update_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/update_outbound_shipment_status.rs
  server/service/src/sync/translations/invoice.rs
Labels: enhancement, Team Ruru 🦉

#3334 Implement master_list_line try_translate_pull_delete
  server/service/src/sync/test/mod.rs
  server/service/src/sync/translation_and_integration.rs
  server/service/src/sync/translations/master_list_line.rs
  server/service/src/sync/translations/mod.rs
Labels: bug, feature: merging, Team Tauhou, Severity: High

#3354 Add rusttls to workspace features to fix graphql tests
  server/Cargo.toml
  server/cli/Cargo.toml
  server/graphql/plugin/Cargo.toml
  server/graphql/programs/Cargo.toml
  server/graphql/sensor/Cargo.toml
  server/service/Cargo.toml
Labels: bug, Team Piwakawaka

#3337 3164 file uploads backend
  server/Cargo.lock
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/sync_file_reference_row.rs
  server/repository/src/migrations/v1_08_00/mod.rs
  server/repository/src/migrations/v1_08_00/sync_file_reference.rs
  server/server/Cargo.toml
  server/server/src/middleware/content_length_limit.rs
  server/server/src/middleware/mod.rs
  server/server/src/static_files.rs
  server/service/src/report/report_service.rs
  server/service/src/static_files.rs
Labels: enhancement, Priority: Must Have, Team Piwakawaka, feature: CCEI

#3365 3361 master list
  client/packages/system/src/MasterList/api/api.ts
  server/graphql/general/src/queries/master_list.rs
  server/graphql/general/src/queries/tests/master_lists.rs
  server/repository/src/db_diesel/master_list.rs
  server/repository/src/mock/full_master_list.rs
  server/service/src/master_list/mod.rs
  server/service/src/master_list/query.rs
  server/service/src/master_list/tests/query.rs
  server/service/src/stocktake/insert.rs
Labels: bug, Team Tauhou

#3368 #3239 Delete Inbound Return lines
  client/packages/invoices/src/Returns/InboundDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/api/hooks/line/useDeleteSelectedInboundLines.ts
Labels: enhancement, Team Ruru 🦉

#3381 Tooltip for item code
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
Labels: bug, Team Tauhou

#3376 2853 sql reports
  server/Cargo.lock
  server/graphql/asset_catalogue/src/lib.rs
  server/graphql/reports/src/lib.rs
  server/graphql/reports/src/printing.rs
  server/report_builder/src/build.rs
  server/report_builder/src/lib.rs
  server/repository/Cargo.toml
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/report_query.rs
  server/repository/src/migrations/v1_08_00/central_omsupply.rs
  server/repository/src/migrations/v1_08_00/pack_variant.rs
  server/repository/src/migrations/v1_08_00/sync_file_reference.rs
  server/service/src/asset/update.rs
  server/service/src/auth.rs
  server/service/src/report/definition.rs
  server/service/src/report/report_service.rs
  server/service/src/sync/api_v6/core.rs
  server/service/src/sync/translation_and_integration.rs
Labels: enhancement, needs architecture/solution

#3371 3319 show actual error if no stock lines are associated with shipment lines to return
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/utils/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/utils/useSelectedLines.ts
  client/packages/invoices/src/InboundShipment/api/hooks/utils/useSelectedStockLineIds.ts
Labels: bug, Team Ruru 🦉, feature: returns

#3350 3326 qty available for return should include amount already in return
  server/graphql/types/src/types/outbound_return_line.rs
  server/service/src/invoice/outbound_return/generate_outbound_return_lines.rs
Labels: bug, Team Ruru 🦉

#3382 Add login to graphql playground
  server/graphql/lib.rs
  server/graphql/playground.html
Labels: enhancement, Tooling

#3375 3338 fix error popup when creating inbound return from outbound shipment
  client/packages/invoices/src/Returns/modals/InboundReturn/AddBatch.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/ReturnSteps.tsx
Labels: bug, Team Ruru 🦉, feature: returns

#3388 #3239 Delete Outbound return lines
  client/packages/common/src/localStorage/keys.ts
  client/packages/common/src/ui/layout/tables/context/hooks/useIsGrouped.ts
  client/packages/invoices/src/Returns/OutboundDetailView/ContentArea.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/DetailView.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/columns.ts
  client/packages/invoices/src/Returns/api/hooks/index.ts
  client/packages/invoices/src/Returns/api/hooks/line/index.ts
  client/packages/invoices/src/Returns/api/hooks/line/useDeleteSelectedOutboundLines.ts
  client/packages/invoices/src/Returns/api/hooks/line/useOutboundReturnRows.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/types.ts
Labels: enhancement, Team Ruru 🦉

#3335 QR code scanning
  client/packages/coldchain/src/Equipment/ListView/AddFromScannerButton.tsx
  client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/api/hooks/document/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAsset.ts
  client/packages/coldchain/src/Equipment/api/hooks/index.ts
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/number/IntlNumber.ts
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3372 Non-catalogue assets
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Asset/api/api.ts
  client/packages/system/src/Asset/api/hooks/utils/useAssetApi.ts
  client/packages/system/src/Asset/api/hooks/utils/useAssetTypes.ts
  client/packages/system/src/Asset/api/operations.generated.ts
  client/packages/system/src/Asset/api/operations.graphql
  server/graphql/asset/src/mutations/insert.rs
  server/graphql/asset/src/types.rs
  server/repository/src/db_diesel/assets/asset.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/migrations/v1_08_00/assets/asset.rs
  server/repository/src/mock/asset.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/tests/insert.rs
  server/service/src/asset/tests/update.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3379 3317 implement isDisabled hook for outbound returns
  client/packages/invoices/src/Returns/InboundDetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/ContentArea.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/DetailView.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/Footer/OnHoldButton.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/api/hooks/document/useInboundReturn.ts
  client/packages/invoices/src/Returns/api/hooks/document/useOutboundReturn.ts
  client/packages/invoices/src/Returns/api/hooks/index.ts
  client/packages/invoices/src/Returns/api/hooks/utils/index.ts
  client/packages/invoices/src/Returns/api/hooks/utils/useOutboundReturnIsDisabled.ts
  client/packages/invoices/src/Returns/modals/InboundReturn/InboundReturn.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/ReturnQuantitiesTable.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/ReturnSteps.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/OutboundReturn.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/ReturnQuantitiesTable.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/ReturnSteps.tsx
  client/packages/invoices/src/Returns/modals/ReturnReasonsTable.tsx
  client/packages/invoices/src/utils.ts
  client/packages/system/src/Item/Components/PackVariant/PackVariantEntryCell.tsx
  client/packages/system/src/ReturnReason/Components/ReturnReasonSearchInput.tsx
Labels: bug, Team Ruru 🦉, feature: returns

#3413 Asset internal locations - Branch Fixup
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetUpdate.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteMulti.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/index.ts
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
  server/cli/src/refresh_dates.rs
  server/graphql/asset/src/logs/insert.rs
  server/graphql/asset/src/mutations/update.rs
  server/graphql/asset/src/types.rs
  server/graphql/core/src/loader/asset_location.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/repository/src/db_diesel/assets/asset_internal_location.rs
  server/repository/src/db_diesel/assets/asset_internal_location_row.rs
  server/repository/src/db_diesel/assets/mod.rs
  server/repository/src/migrations/v1_08_00/assets/asset.rs
  server/repository/src/mock/location.rs
  server/service/src/asset/delete.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/location.rs
  server/service/src/asset/mod.rs
  server/service/src/asset/tests/update.rs
  server/service/src/asset/update.rs
  server/service/src/asset/validate.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3436 Revert master list changes
  client/packages/system/src/MasterList/api/api.ts
  server/graphql/general/src/queries/master_list.rs
  server/graphql/general/src/queries/tests/master_lists.rs
  server/repository/src/db_diesel/master_list.rs
  server/repository/src/mock/full_master_list.rs
  server/service/src/master_list/mod.rs
  server/service/src/master_list/query.rs
  server/service/src/master_list/tests/query.rs
  server/service/src/stocktake/insert.rs
Labels: Severity: High

#3347 3187 implement permissions for returns
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/InboundListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/OutboundListView/AppBarButtons.tsx
  server/graphql/general/src/queries/generate_inbound_return_lines.rs
  server/graphql/general/src/queries/generate_outbound_return_lines.rs
  server/graphql/invoice/src/mutations/inbound_return/delete.rs
  server/graphql/invoice/src/mutations/inbound_return/insert.rs
  server/graphql/invoice/src/mutations/inbound_return/update.rs
  server/graphql/invoice/src/mutations/inbound_return/update_lines.rs
  server/graphql/invoice/src/mutations/outbound_return/delete.rs
  server/graphql/invoice/src/mutations/outbound_return/insert.rs
  server/graphql/invoice/src/mutations/outbound_return/update.rs
  server/graphql/invoice/src/mutations/outbound_return/update_lines.rs
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v1_08_00/mod.rs
  server/repository/src/migrations/v1_08_00/returns/mod.rs
  server/repository/src/migrations/v1_08_00/returns/return_context_types.rs
  server/repository/src/migrations/v1_08_00/returns/return_invoice_types.rs
  server/repository/src/migrations/v1_08_00/returns/return_permissions.rs
  server/repository/src/migrations/v1_08_00/returns/return_reasons.rs
  server/service/src/apis/permissions.rs
  server/service/src/auth.rs
  server/service/src/login.rs
Labels: enhancement, Team Ruru 🦉

#3440 Catalogue master lists export exports all master lists, not just the ones the store has visibility to #3361
  client/packages/system/src/MasterList/ListView/AppBarButtons.tsx
  server/repository/src/mock/full_master_list.rs
  server/service/src/master_list/tests/query.rs
  server/service/src/stocktake/insert.rs
Labels: bug, Team Tauhou

#3205 3159 sync assets remote central
  server/cli/src/refresh_dates.rs
  server/graphql/general/src/queries/sync_status.rs
  server/postman/Open mSupply REST.postman_collection.json
  server/repository/Cargo.toml
  server/repository/src/db_diesel/assets/asset.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/changelog/test.rs
  server/repository/src/db_diesel/key_value_store.rs
  server/repository/src/db_diesel/sync_buffer.rs
  server/repository/src/db_diesel/sync_log_row.rs
  server/repository/src/lib.rs
  server/repository/src/migrations/v1_08_00/add_source_site_id.rs
  server/repository/src/migrations/v1_08_00/assets/asset.rs
  server/repository/src/migrations/v1_08_00/central_omsupply.rs
  server/repository/src/migrations/v1_08_00/mod.rs
  server/repository/src/migrations/v1_08_00/pack_variant.rs
  server/server/src/sync_on_central/mod.rs
  server/service/src/sync/api/common_records.rs
  server/service/src/sync/api_v6/core.rs
  server/service/src/sync/api_v6/mod.rs
  server/service/src/sync/central_data_synchroniser.rs
  server/service/src/sync/central_data_synchroniser_v6.rs
  server/service/src/sync/sync_on_central/mod.rs
  server/service/src/sync/sync_status/logger.rs
  server/service/src/sync/sync_status/status.rs
  server/service/src/sync/sync_status/test.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/test/mod.rs
  server/service/src/sync/test/pull_and_push.rs
  server/service/src/sync/test/test_data/asset.rs
  server/service/src/sync/test/test_data/asset_catalogue_item.rs
  server/service/src/sync/test/test_data/asset_category.rs
  server/service/src/sync/test/test_data/asset_class.rs
  server/service/src/sync/test/test_data/asset_type.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/pack_variant.rs
  server/service/src/sync/translation_and_integration.rs
  server/service/src/sync/translations/asset.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/name.rs
Labels: enhancement, Priority: Must Have, Team Piwakawaka

#3321 3312 assetlog sync
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/assets/asset_log_row.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/changelog/test.rs
  server/repository/src/migrations/v1_08_00/assets/asset_log.rs
  server/service/src/sync/test/test_data/asset_log.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/asset_log.rs
  server/service/src/sync/translations/mod.rs
Labels: enhancement, needs triage, Team Piwakawaka, feature: CCEI

#3322 Print QR code labels
  client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/utils/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/utils/useAssetApi.ts
  client/packages/coldchain/src/Equipment/api/hooks/utils/useLabelPrinterSettings.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/config/src/config.ts
  client/packages/host/src/Admin/DisplaySettings.tsx
  client/packages/host/src/Admin/ElectronSettings.tsx
  client/packages/host/src/Admin/LabelPrinterSettings.tsx
  client/packages/host/src/Admin/ServerSettings.tsx
  client/packages/host/src/Admin/Settings.tsx
  client/packages/host/src/Admin/SettingsSection.tsx
  client/packages/host/src/Admin/SyncSettings.tsx
  client/packages/host/src/api/api.ts
  client/packages/host/src/api/hooks/index.ts
  client/packages/host/src/api/hooks/settings/index.ts
  client/packages/host/src/api/hooks/settings/useLabelPrinterSettings.ts
  client/packages/host/src/api/hooks/settings/useUpdateLabelPrinterSettings.ts
  client/packages/host/src/api/hooks/utils/useHostApi.ts
  client/packages/host/src/api/operations.generated.ts
  client/packages/host/src/api/operations.graphql
  server/Cargo.lock
  server/graphql/general/src/lib.rs
  server/graphql/general/src/mutations/label_printer_settings.rs
  server/graphql/general/src/mutations/mod.rs
  server/graphql/general/src/queries/label_printer_settings.rs
  server/graphql/general/src/queries/mod.rs
  server/repository/src/db_diesel/key_value_store.rs
  server/repository/src/migrations/v1_08_00/assets/label_printer.rs
  server/repository/src/migrations/v1_08_00/assets/mod.rs
  server/server/Cargo.toml
  server/server/src/lib.rs
  server/server/src/print/label.rs
  server/server/src/print/mod.rs
  server/service/Cargo.toml
  server/service/src/label_printer_settings_service.rs
  server/service/src/lib.rs
  server/service/src/print/jetdirect.rs
  server/service/src/print/label.rs
  server/service/src/print/mod.rs
  server/service/src/service_provider.rs
  server/service/src/settings.rs
Labels: Team Piwakawaka

#3437 3408 Repacks: 'Number of packs to repack' field is not required
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
Labels: bug, Team Tauhou

#3369 3316 accept more return invoice fields on update mutation
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/TransportSection.tsx
  client/packages/invoices/src/Returns/InboundDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/Footer/OnHoldButton.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/TransportSection.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/OutboundListView/ListView.tsx
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInboundReturn.ts
  client/packages/invoices/src/Returns/api/hooks/document/useOutboundReturn.ts
  client/packages/invoices/src/Returns/api/hooks/document/useUpdateInboundReturn.ts
  client/packages/invoices/src/Returns/api/hooks/document/useUpdateOutboundReturn.ts
  client/packages/invoices/src/Returns/api/hooks/line/useDeleteSelectedOutboundLines.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  server/graphql/invoice/src/mutations/inbound_return/update.rs
  server/graphql/invoice/src/mutations/outbound_return/update.rs
  server/service/src/invoice/inbound_return/update/generate.rs
  server/service/src/invoice/inbound_return/update/mod.rs
  server/service/src/invoice/outbound_return/update/generate.rs
  server/service/src/invoice/outbound_return/update/mod.rs
  server/service/src/invoice/outbound_return/update/validate.rs
Labels: enhancement, Team Ruru 🦉

#3451 Bug fix making currency_id required
  server/repository/src/migrations/v1_08_00/invoice_required_currency_id.rs
Labels: bug, Severity: High

#3427 3017.3 fix clippy warnings
  server/graphql/cold_chain/src/lib.rs
  server/report_builder/src/build.rs
  server/repository/src/db_diesel/assets/asset.rs
  server/repository/src/db_diesel/document.rs
  server/repository/src/db_diesel/encounter.rs
  server/repository/src/db_diesel/form_schema.rs
  server/repository/src/db_diesel/item_row.rs
  server/repository/src/db_diesel/name_row.rs
  server/repository/src/db_diesel/name_store_join.rs
  server/repository/src/db_diesel/program_event.rs
  server/repository/src/db_diesel/report_query.rs
  server/repository/src/db_diesel/stocktake.rs
  server/repository/src/db_diesel/sync_buffer.rs
  server/repository/src/migrations/mod.rs
  server/service/src/invoice/common.rs
  server/service/src/invoice/inbound_shipment/add_from_master_list.rs
  server/service/src/invoice/inbound_shipment/delete/mod.rs
  server/service/src/invoice/inbound_shipment/insert/mod.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice/inbound_shipment/update/validate.rs
  server/service/src/invoice/outbound_shipment/add_from_master_list.rs
  server/service/src/invoice/outbound_shipment/delete/mod.rs
  server/service/src/invoice/outbound_shipment/delete/validate.rs
  server/service/src/invoice/outbound_shipment/insert/mod.rs
  server/service/src/invoice/outbound_shipment/update_name/generate.rs
  server/service/src/invoice/outbound_shipment/update_name/mod.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/delete.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/update.rs
  server/service/src/invoice_line/query.rs
  server/service/src/invoice_line/stock_out_line/delete/mod.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/insert/mod.rs
  server/service/src/invoice_line/stock_out_line/insert/validate.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
  server/service/src/invoice_line/stock_out_line/update/validate.rs
  server/service/src/invoice_line/stock_out_line/validate.rs
  server/service/src/invoice_line/validate.rs
Labels: needs architecture/solution, Priority: Should have, refactor, Team Tauhou, Tooling

#3435 Don't allow clearing of languages
  client/packages/common/src/ui/components/inputs/Select/Select.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
Labels: bug, Team Tauhou, Severity: Low

#3397 Sync File Reference Sync
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/sync_file_reference_row.rs
  server/repository/src/migrations/v1_08_00/sync_file_reference.rs
  server/service/src/sync/central_data_synchroniser_v6.rs
  server/service/src/sync/sync_on_central/mod.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/sync_file_reference.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/sync_file_reference.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI

#3389 3386 Show all suppliers when creating inbound shipment from dashboard
  client/packages/dashboard/src/widgets/ReplenishmentWidget.tsx
Labels: bug, Team Tauhou

#3450 3276 delete duplicate name store joins on merge
  server/graphql/general/src/queries/store.rs
  server/repository/src/db_diesel/store.rs
  server/repository/src/mock/name_store_join.rs
  server/service/src/sync/translations/special/name_merge.rs
Labels: bug, feature: merging, Team Tauhou, Severity: High

#3411 #3912 Return modal navigation updates
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/Returns/InboundDetailView/DetailView.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/DetailView.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/InboundReturn.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/useDraftInboundReturnLines.ts
  client/packages/invoices/src/Returns/modals/OutboundReturn/OutboundReturn.tsx
  client/packages/invoices/src/utils.ts
Labels: enhancement, Team Ruru 🦉, feature: returns

#3416 3343 sync return reasons from central
  server/repository/src/db_diesel/return_reason_row.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/test/test_data/inventory_adjustment_reason.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/reason.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/reason.rs
  server/service/src/sync/translations/stocktake_line.rs
Labels: enhancement, Team Ruru 🦉, feature: returns

#3433 3299 link original shipment to return
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/RelatedDocumentsSection.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/RelatedDocumentsSection.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/modals/InboundReturn/InboundReturn.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/useDraftInboundReturnLines.ts
  client/packages/invoices/src/Returns/modals/OutboundReturn/OutboundReturn.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/useDraftOutboundReturnLines.ts
  server/graphql/invoice/src/mutations/inbound_return/insert.rs
  server/graphql/invoice/src/mutations/outbound_return/insert.rs
  server/graphql/types/src/types/invoice_query.rs
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/migrations/v1_08_00/linked_shipment.rs
  server/repository/src/migrations/v1_08_00/mod.rs
  server/service/src/invoice/inbound_return/insert/generate.rs
  server/service/src/invoice/inbound_return/insert/mod.rs
  server/service/src/invoice/inbound_return/insert/validate.rs
  server/service/src/invoice/inbound_shipment/insert/generate.rs
  server/service/src/invoice/outbound_return/insert/generate.rs
  server/service/src/invoice/outbound_return/insert/mod.rs
  server/service/src/invoice/outbound_return/insert/validate.rs
  server/service/src/invoice/outbound_shipment/insert/generate.rs
  server/service/src/invoice/prescription/insert/generate.rs
  server/service/src/processors/transfer/mod.rs
  server/service/src/processors/transfer/shipment/assign_invoice_number.rs
  server/service/src/processors/transfer/shipment/create_inbound_shipment.rs
  server/service/src/processors/transfer/shipment/mod.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/update.rs
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/translations/invoice.rs
Labels: enhancement, needs architecture/solution, Team Ruru 🦉, feature: returns

#3431 3410 sync basic user information
  server/graphql/general/src/mutations/update_user.rs
  server/graphql/types/src/types/activity_log.rs
  server/graphql/types/src/types/invoice_query.rs
  server/graphql/types/src/types/program/document.rs
  server/graphql/types/src/types/requisition.rs
  server/graphql/types/src/types/stocktake.rs
  server/repository/src/db_diesel/user_row.rs
  server/repository/src/migrations/v1_08_00/mod.rs
  server/repository/src/migrations/v1_08_00/user_change_last_synced_to_optional.rs
  server/service/src/login.rs
  server/service/src/sync/sync_user.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/user.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/user.rs
Labels: enhancement, Migrate Existing Desktop, Team Tauhou

#3396 2229 move navigation out of delete hooks
  client/packages/dashboard/src/widgets/DistributionWidget.tsx
  client/packages/dashboard/src/widgets/ReplenishmentWidget.tsx
  client/packages/dashboard/src/widgets/StockWidget.tsx
  client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
  client/packages/inventory/src/Stocktake/api/hooks/document/useStocktakeDelete.ts
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/document/useInboundDelete.ts
  client/packages/invoices/src/InboundShipment/api/hooks/document/useInsertInbound.ts
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/OutboundShipment/ListView/AppBarButtons.tsx
  client/packages/invoices/src/OutboundShipment/api/hooks/document/useOutboundDelete.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/document/useOutboundInsert.ts
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Prescriptions/ListView/AppBarButtons.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionDelete.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionInsert.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/SidePanel.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useDeleteRequests.ts
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useInsertProgramRequest.ts
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useInsertRequest.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/CreateShipmentButton.tsx
  client/packages/requisitions/src/ResponseRequisition/api/hooks/utils/useCreateOutboundFromResponse.ts
Labels: enhancement, front-end, Priority: Nice to Have, refactor, Team Tauhou
