Repository msupply-foundation/open-msupply, pull requests merged in 2024-11, with the labels that each got.

#5287 #4367(3) Edit cold storage on Location modal
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Item/Components/ColdStorageTypeInput/ColdStorageTypeInput.tsx
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx
  client/packages/system/src/Location/api/api.ts
  server/graphql/location/src/mutations/update.rs
  server/repository/src/db_diesel/location_row.rs
  server/service/src/location/update.rs
Labels: enhancement, Team Piwakawaka, feature: CCEI, feature: GAPS

#5291 #5289 Clear inbound item selection
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEditForm.tsx
Labels: bug, Team Piwakawaka, Severity: Hotfix

#5254 5137.1 requisition line edit + UI updates to line columns
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/reason_option.rs
  server/graphql/requisition_line/src/mutations/response_requisition_line/insert.rs
  server/graphql/requisition_line/src/mutations/response_requisition_line/update.rs
  server/graphql/types/src/types/requisition_line.rs
  server/service/src/item/item.rs
  server/service/src/requisition_line/response_requisition_line/insert/generate.rs
  server/service/src/requisition_line/response_requisition_line/insert/mod.rs
  server/service/src/requisition_line/response_requisition_line/insert/validate.rs
  server/service/src/requisition_line/response_requisition_line/update.rs
Labels: enhancement, Team Ruru 🦉, feature: manual requisition

#5286 Improve confirm on leaving modal
  client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
Labels: enhancement

#5301 5282 Allow initialisation from export
  server/service/src/sync/translations/activity_log.rs
  server/service/src/sync/translations/name.rs
Labels: Team Piwakawaka

#5307 Fix frontend tests in develop
  client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx
Labels: bug

#5292 3923 bundled items (Backend)
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/core/src/loader/item_variant.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/item_bundle/Cargo.toml
  server/graphql/item_bundle/src/lib.rs
  server/graphql/item_bundle/src/mutations/delete.rs
  server/graphql/item_bundle/src/mutations/mod.rs
  server/graphql/item_bundle/src/mutations/upsert.rs
  server/graphql/lib.rs
  server/graphql/types/src/types/bundled_item.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/mod.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/item_variant/bundled_item.rs
  server/repository/src/db_diesel/item_variant/bundled_item_row.rs
  server/repository/src/db_diesel/item_variant/mod.rs
  server/repository/src/migrations/v2_04_00/add_bundled_item_table.rs
  server/repository/src/migrations/v2_04_00/mod.rs
  server/repository/src/mock/item_variant.rs
  server/repository/src/mock/mod.rs
  server/service/src/item/bundled_item/delete.rs
  server/service/src/item/bundled_item/mod.rs
  server/service/src/item/bundled_item/query.rs
  server/service/src/item/bundled_item/test/mod.rs
  server/service/src/item/bundled_item/upsert.rs
  server/service/src/item/item_variant/mod.rs
  server/service/src/item/item_variant/validate.rs
  server/service/src/item/mod.rs
Labels: Team Piwakawaka, feature: GAPS

#5288 5250 gaps improve validation on packagingitem variants
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemPackagingVariantsTable.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
  client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariant.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  server/graphql/item_variant/src/mutations/upsert.rs
  server/service/src/item/item_variant/test/mod.rs
  server/service/src/item/item_variant/upsert.rs
  server/service/src/item/packaging_variant/test/mod.rs
  server/service/src/item/packaging_variant/upsert.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#5317 #5164 Fix Prescriptions DatePicker/Confirmation conflict
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
Labels: bug, Team Piwakawaka, Severity: High

#5328 5213 indicator value table
  .github/workflows/server-tests.yaml
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/indicator_column.rs
  server/repository/src/db_diesel/indicator_line.rs
  server/repository/src/db_diesel/indicator_value.rs
  server/repository/src/db_diesel/indicator_value_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_04_00/indicator_value_create_table.rs
  server/repository/src/migrations/v2_04_00/mod.rs
  server/repository/src/mock/indicator_line.rs
  server/service/src/sync/test/test_data/indicator_value.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/indicator_attribute.rs
  server/service/src/sync/translations/indicator_value.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/program_indicator.rs
Labels: enhancement, back-end, Team Ruru 🦉, feature: manual requisition

#5319 Bundled Item Validations
  server/graphql/item_bundle/src/mutations/upsert.rs
  server/repository/src/mock/item_variant.rs
  server/service/src/invoice_line/stock_in_line/insert/validate.rs
  server/service/src/invoice_line/stock_in_line/update/validate.rs
  server/service/src/item/bundled_item/test/mod.rs
  server/service/src/item/bundled_item/upsert.rs
  server/service/src/item/packaging_variant/upsert.rs
  server/service/src/lib.rs
  server/service/src/stock_line/update.rs
Labels: Team Piwakawaka, feature: GAPS

#5309 #4917 Fix patches with nullable values
  client/packages/common/src/utils/functions/ApiUtils.tsx
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
Labels: bug, Team Piwakawaka, Severity: Normal

#5338 5337 make indicator_value structs consistent
  server/repository/src/db_diesel/indicator_value.rs
  server/repository/src/db_diesel/indicator_value_row.rs
Labels: enhancement, Team Ruru 🦉

#5323 #4343 Activity log for Demographics
  client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
  project-words.txt
  server/graphql/types/src/types/activity_log.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/demographic_projection_row.rs
  server/repository/src/migrations/v2_04_00/add_demographic_indicator_types_to_activity_log.rs
  server/repository/src/migrations/v2_04_00/mod.rs
  server/service/src/demographic/insert_demographic_indicator.rs
  server/service/src/demographic/insert_demographic_projection.rs
  server/service/src/demographic/update_demographic_indicator.rs
  server/service/src/demographic/update_demographic_projection.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#5324 5302 bundled item UI
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Item/Components/ItemVariantSearchInput/ItemVariantSearchInput.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/BundledItemModal.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/BundledItemVariants.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemPackagingVariantsTable.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/Item/api/hooks/bundledItem/index.ts
  client/packages/system/src/Item/api/hooks/bundledItem/useDeleteBundledItem.ts
  client/packages/system/src/Item/api/hooks/bundledItem/useUpsertBundledItem.ts
  client/packages/system/src/Item/api/hooks/index.ts
  client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariant.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  server/graphql/core/src/loader/bundled_item.rs
  server/graphql/core/src/loader/item_variant.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/item_variant/src/mutations/upsert.rs
  server/graphql/types/src/types/bundled_item.rs
  server/graphql/types/src/types/item_variant.rs
  server/repository/src/db_diesel/item_variant/item_variant.rs
  server/repository/src/db_diesel/item_variant/item_variant_row.rs
  server/service/src/item/item_variant/query.rs
  server/service/src/item/item_variant/test/mod.rs
  server/service/src/item/item_variant/upsert.rs
  server/service/src/item/mod.rs
  server/service/src/item/packaging_variant/test/mod.rs
Labels: Team Piwakawaka, feature: GAPS

#5329 Improve handing of backdated date
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  server/service/src/invoice/prescription/update/generate.rs
Labels: bug, Severity: Hotfix

#5308 5137.3 Requisition line edit + UI updates to line columns
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/common/src/hooks/useDialog/useDialog.stories.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/buttons/ButtonShowcase.stories.tsx
  client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
  client/packages/common/src/ui/components/navigation/ListOptions/ListOptions.tsx
  client/packages/common/src/ui/components/navigation/ListOptions/index.ts
  client/packages/common/src/ui/components/navigation/index.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditModal.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Returns/modals/CustomerReturn/CustomerReturn.tsx
  client/packages/invoices/src/Returns/modals/SupplierReturn/SupplierReturn.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequisitionService.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ContentArea.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEditForm.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/index.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/index.ts
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/index.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/index.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useInsertResponseLines.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useResponseLineStatsData.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  client/packages/system/src/Asset/ImportCatalogueItem/CatalogueItemImportModal.tsx
  client/packages/system/src/Item/Components/ListItems/ListItems.tsx
  client/packages/system/src/Item/Components/ListItems/index.ts
  client/packages/system/src/Item/Components/index.ts
  client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx
  client/packages/system/src/Name/ListView/Facilities/FacilityEditModal.tsx
  client/packages/system/src/Name/ListView/ImportProperties/PropertiesImportModal.tsx
  client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
  client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx
  client/packages/system/src/index.ts
  server/graphql/requisition_line/src/mutations/response_requisition_line/insert.rs
  server/graphql/types/src/types/requisition_line.rs
  server/service/src/requisition_line/response_requisition_line/insert/generate.rs
  server/service/src/requisition_line/response_requisition_line/insert/mod.rs
Labels: enhancement, Team Ruru 🦉, feature: manual requisition

#5352 Merge V2.3.2 to develop
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
  client/packages/invoices/src/Prescriptions/api/api.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptions.ts
  package.json
  server/graphql/invoice/src/invoice_queries.rs
  server/repository/src/db_diesel/invoice.rs
  server/repository/src/diesel_extensions.rs
  server/service/src/invoice/prescription/update/generate.rs
Labels: Team Piwakawaka

#5355 #5000 Improve fetching remote patient UX
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
  client/packages/system/src/Patient/CreatePatientModal/FetchPatientModal.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
Labels: bug, Team Piwakawaka, Severity: High

#5322 5137.4
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/common/src/ui/components/charts/NewValueBar/NewValueBar.stories.tsx
  client/packages/common/src/ui/components/charts/NewValueBar/NewValueBar.tsx
  client/packages/common/src/ui/components/charts/NewValueBar/index.ts
  client/packages/common/src/ui/components/charts/index.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/ReponseStats/ResponseStoreStats.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/RequestStoreStats.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/ResponseStoreStats.tsx
Labels: enhancement, Team Ruru 🦉, feature: manual requisition

#5326 5321 manual requisitions UI feedback
  client/packages/common/src/ui/components/navigation/ListOptions/ListOptions.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/ResponseStoreStats.tsx
Labels: enhancement, Team Ruru 🦉, feature: manual requisition

#5269 5242 add delete response requisitions
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/Toolbar.tsx
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/index.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useDeleteResponses.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useDeleteSelectedResponseRequisitions.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/index.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  server/graphql/batch_mutations/src/batch_response_requisition.rs
  server/graphql/requisition/src/lib.rs
  server/graphql/requisition/src/mutations/errors.rs
  server/graphql/requisition/src/mutations/response_requisition/delete.rs
  server/graphql/requisition/src/mutations/response_requisition/mod.rs
  server/service/src/requisition/mod.rs
  server/service/src/requisition/response_requisition/batch.rs
  server/service/src/requisition/response_requisition/delete.rs
  server/service/src/requisition/response_requisition/mod.rs
Labels: enhancement, Team Ruru 🦉

#5361 5360 rename indicator_value.supplier_store_id to store_id
  server/repository/src/db_diesel/indicator_value.rs
  server/repository/src/db_diesel/indicator_value_row.rs
  server/repository/src/migrations/v2_04_00/indicator_value_create_table.rs
  server/service/src/sync/test/test_data/indicator_value.rs
  server/service/src/sync/translations/indicator_value.rs
Labels: enhancement, Team Ruru 🦉, feature: manual requisition

#5346 5345 manual reqs stock on hand value overwritten
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/charts/NewValueBar/NewValueBar.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  server/graphql/requisition_line/src/mutations/response_requisition_line/update.rs
  server/service/src/requisition_line/response_requisition_line/update.rs
Labels: bug, Team Ruru 🦉, feature: manual requisition

#5356 5354 Hide extra columns for general requisitions
  client/packages/requisitions/src/RequestRequisition/ListView/ProgramRequisitionOptions.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/RequestStoreStats.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
Labels: enhancement, Team Ruru 🦉, feature: manual requisition

#5370 5100 sync items to legacy
  package.json
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/item_row.rs
  server/service/src/sync/translations/item.rs
Labels: enhancement, Priority: Should have, Team Piwakawaka, feature: GAPS

#5343 5330 category tables
  decisions/2024-11-12_categories.md
  server/repository/src/db_diesel/category_row.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/item_category_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_04_01/category_and_item_categories.rs
  server/repository/src/migrations/v2_04_01/mod.rs
Labels: feature: programs, Team Piwakawaka

#5373 5362 hide item variants if none configured
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/Returns/modals/CustomerReturn/ReturnQuantitiesTable.tsx
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/system/src/Item/api/hooks/useItemVariant/index.ts
  client/packages/system/src/Item/api/hooks/useItemVariant/useIsItemVariantsEnabled.ts
  client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariant.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  server/graphql/item_variant/src/lib.rs
  server/graphql/lib.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#5393 4935 Change ledger number column to "invoice no."
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
Labels: bug, good first issue, front-end, Severity: Low

#5304 5215 add program indicator graphql layer queries
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/program.rs
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/queries/mod.rs
  server/graphql/programs/src/queries/program_indicator.rs
  server/graphql/types/src/types/program/mod.rs
  server/graphql/types/src/types/program/program_indicator.rs
  server/repository/src/db_diesel/indicator_column_row.rs
  server/repository/src/db_diesel/indicator_line_row.rs
  server/repository/src/db_diesel/program_indicator.rs
  server/repository/src/db_diesel/program_indicator_row.rs
  server/repository/src/mock/indicator_line.rs
  server/repository/src/mock/mod.rs
  server/service/src/programs/mod.rs
  server/service/src/programs/program_indicator/mod.rs
  server/service/src/programs/program_indicator/query.rs
  server/service/src/service_provider.rs
  server/service/src/sync/translations/indicator_attribute.rs
Labels: enhancement, back-end, Team Ruru 🦉, feature: manual requisition

#5327 5310 add graphql loader for values
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/program_indicator_value.rs
  server/graphql/types/src/types/program/program_indicator.rs
Labels: enhancement, needs triage, Team Ruru 🦉, feature: manual requisition

#5347 5305 add mutate program indicator values
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/queries/mod.rs
  server/graphql/requisition/src/lib.rs
  server/graphql/requisition/src/mutations/mod.rs
  server/graphql/requisition/src/mutations/update_indicator_value.rs
  server/graphql/requisition/src/program_indicator.rs
  server/graphql/types/src/types/program/program_indicator.rs
  server/repository/src/db_diesel/indicator_value.rs
  server/repository/src/mock/indicator_value.rs
  server/repository/src/mock/mod.rs
  server/service/src/programs/mod.rs
  server/service/src/requisition/indicator_value/mod.rs
  server/service/src/requisition/indicator_value/update.rs
  server/service/src/requisition/mod.rs
  server/service/src/requisition/program_indicator/mod.rs
  server/service/src/requisition/program_indicator/query.rs
  server/service/src/requisition/response_requisition/insert_program.rs
  server/service/src/service_provider.rs
Labels: enhancement, Team Ruru 🦉

#5407 5398 use store pref to hide extra columns
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.graphql
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  server/graphql/types/src/types/store_preference.rs
  server/repository/src/db_diesel/store_preference_row.rs
  server/repository/src/migrations/v2_04_00/add_store_pref_use_extra_fields.rs
  server/repository/src/migrations/v2_04_00/mod.rs
  server/service/src/sync/test/test_data/store_preference.rs
  server/service/src/sync/translations/store_preference.rs
Labels: enhancement, Team Ruru 🦉, feature: manual requisition

#5421 5412 Add indicator indexes
  server/repository/src/migrations/v2_04_00/indicator_indexes.rs
  server/repository/src/migrations/v2_04_00/mod.rs
Labels: enhancement, Build Tested: Dev, feature: manual requisition

#5405 change buffered state to draft
  client/packages/invoices/src/Returns/CustomerDetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/api/hooks/document/useCustomerReturn.ts
Labels: bug, good first issue, front-end, Severity: Normal, Team Korimako

#5401 5390 correctly handle gs1 2d data matrix format
  client/packages/coldchain/src/Equipment/ListView/AddFromScannerButton.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAsset.ts
  client/packages/coldchain/src/Equipment/api/hooks/index.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/BarcodeScannerContext.tsx
  server/graphql/asset/src/lib.rs
  server/graphql/asset/src/types/asset.rs
  server/graphql/asset/src/types/gs1.rs
  server/graphql/asset/src/types/mod.rs
  server/service/src/asset/mod.rs
  server/service/src/asset/parse.rs
  server/util/src/gs1.rs
Labels: bug, Priority: Must Have, Team Piwakawaka, feature: GAPS

#5414 Change OK button to Loading Button type
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx
Labels: bug, good first issue, front-end, Severity: Normal, Team Korimako

#5435 5422 indicator api not retrieving an indicator value
  server/repository/src/db_diesel/filter_sort_pagination.rs
  server/repository/src/db_diesel/indicator_value.rs
Labels: bug, Build Tested: Dev, Team Ruru 🦉, Severity: High, feature: manual requisition

#5434 5372 unit grouping symbol in stocktake difference
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Labels: bug, good first issue, front-end, Severity: Normal, Team Korimako

#5426 5383 Android - Load Plugins after they've be registered properly
  client/packages/android/README.MD
  client/packages/android/app/src/main/java/org/openmsupply/client/ExtendedWebViewClient.java
  client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
  client/packages/android/app/src/main/java/org/openmsupply/client/RemoteServer.java
Labels: bug, Severity: Hotfix

#5451 5448 Navigating back from editing requisition line goes back to requisition list rather than to the requisition being modified
  client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/AppBarButtons.tsx
  client/packages/system/src/Item/Components/ListItems/ListItems.tsx
Labels: bug, Team Ruru 🦉

#5455 5423 cant download CCE template on android
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
  client/packages/common/src/intl/locales/en/common.json
Labels: bug, Team Piwakawaka, Severity: High, docs: external, feature: GAPS

#5441 4097 browser back button behaviour
  client/packages/dashboard/src/widgets/DistributionWidget.tsx
  client/packages/dashboard/src/widgets/ReplenishmentWidget.tsx
  client/packages/dashboard/src/widgets/StockWidget.tsx
  client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
  client/packages/invoices/src/OutboundShipment/ListView/AppBarButtons.tsx
  client/packages/invoices/src/Prescriptions/ListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/SupplierListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/api/hooks/document/useInsertCustomerReturn.ts
  client/packages/invoices/src/Returns/api/hooks/document/useInsertSupplierReturn.ts
  client/packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/AppBarButtons.tsx
Labels: bug, good first issue, Severity: Normal, Team Korimako

#5454 5413 remove sorting by storage type
  client/packages/system/src/Location/ListView/ListView.tsx
Labels: bug, Team Piwakawaka, Severity: High, feature: GAPS

#5457 5442 Include location type in selected location option
  client/packages/system/src/Location/Components/LocationSearchInput.tsx
Labels: bug, Team Piwakawaka, Severity: High, feature: GAPS

#5436 new util function to display age
  client/packages/common/src/intl/utils/DateUtils.test.ts
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
  client/packages/system/src/Patient/PatientView/PatientSummary.tsx
Labels: bug, good first issue, front-end, Severity: Normal, Team Korimako

#5453 5404 fix empty equipment category filter options
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/Filters/FilterMenu.tsx
Labels: bug, Team Piwakawaka, Severity: High, feature: GAPS

#5428 5331 translate item categories
  server/repository/src/db_diesel/category_row.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/item_category.rs
  server/repository/src/db_diesel/item_category_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_04_01/category_and_item_categories.rs
  server/repository/src/mock/mod.rs
  server/service/src/sync/test/test_data/item.rs
  server/service/src/sync/test/test_data/item_category.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/category.rs
  server/service/src/sync/translations/item.rs
  server/service/src/sync/translations/mod.rs
Labels: feature: programs, Team Piwakawaka

#5491 Update installation date column in Equipment ListView.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/ImportReviewDataTable.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
Labels: bug, Severity: Low, feature: GAPS, Team Korimako

#5484 5367 add category id to item filter
  server/graphql/general/src/queries/item.rs
  server/repository/src/db_diesel/item.rs
Labels: feature: programs, Team Piwakawaka

#5478 5461 delete bundled items when item variant deleted
  server/repository/src/db_diesel/item_variant/bundled_item.rs
  server/service/src/item/item_variant/delete.rs
  server/service/src/item/item_variant/test/mod.rs
Labels: bug, Team Piwakawaka, feature: GAPS

#5477 5471 Requisition's supply quantity is incorrect
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
Labels: bug, Team Ruru 🦉, Severity: Normal, Severity: High

#5495 Add min/max to temperature dropdown
  client/packages/system/src/Item/Components/ColdStorageTypeInput/ColdStorageTypeInput.tsx
Labels: bug, good first issue, Severity: Normal, feature: GAPS, Team Korimako

#5489 4967 new encounter window appearance
  client/packages/system/src/Clinician/ClinicianSearchInput.tsx
  client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
  client/packages/system/src/Patient/Encounter/EncounterSearchInput.tsx
Labels: bug, good first issue, Severity: Low, Team Korimako

#5500 Windows panic
  server/windows/src/windows.rs
Labels: bug, Severity: Normal

#5502 update temperature spacer from '-' to 'to'
  client/packages/system/src/Item/Components/ColdStorageTypeInput/ColdStorageTypeInput.tsx
  client/packages/system/src/Location/ListView/ListView.tsx
Labels: bug, good first issue, Severity: Low, docs: external, feature: GAPS, Team Korimako

#5509 5447 fix equipment date format
  client/packages/coldchain/src/Equipment/ImportAsset/ImportReviewDataTable.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
Labels: bug, Severity: Low, feature: GAPS, Team Korimako

#5506 Add temperature label to location temperature input
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
Labels: bug, good first issue, Severity: Low, feature: GAPS, Team Korimako

#5518 5409 hide temperature ranges if unspecified
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/Location/ListView/ListView.tsx
  client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx
  server/repository/src/db_diesel/cold_storage_type.rs
Labels: bug, good first issue, Severity: Normal, feature: GAPS

#5456 5388 add error for reasons in manual requisition changes
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/StatusChangeButton.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  client/packages/requisitions/src/ResponseRequisition/context/index.ts
  client/packages/requisitions/src/ResponseRequisition/context/responseRequisitionLineError.tsx
  server/graphql/requisition/src/mutations/response_requisition/update.rs
  server/graphql/types/src/generic_errors.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/option.rs
  server/repository/src/mock/test_requisition_service.rs
  server/service/src/requisition/response_requisition/update.rs
  server/service/src/requisition_line/response_requisition_line/delete.rs
  server/service/src/requisition_line/response_requisition_line/update.rs
Labels: enhancement, Team Ruru 🦉, feature: manual requisition

#5539 Add check for if extra fields in requisition showing
  server/service/src/requisition/response_requisition/update.rs
Labels: bug, Team Ruru 🦉, feature: manual requisition

#5549 Update AssetNumberAlreadyExists error message
  server/service/src/asset/insert.rs
Labels: bug, good first issue, Severity: Normal, feature: GAPS, Team Korimako

#5521 Remove doses_per_unit from item_variant
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariant.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  server/graphql/item_variant/src/mutations/upsert.rs
  server/graphql/types/src/types/item_variant.rs
  server/repository/src/db_diesel/item_variant/item_variant.rs
  server/repository/src/db_diesel/item_variant/item_variant_row.rs
  server/repository/src/db_diesel/item_variant/packaging_variant.rs
  server/repository/src/migrations/v2_04_00/item_variant.rs
  server/repository/src/mock/item_variant.rs
  server/service/src/item/item_variant/upsert.rs
  server/service/src/sync/test/test_data/item_variant.rs
Labels: Team Piwakawaka, feature: GAPS

#5552 Stocktake item variants
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/utils.ts
  client/packages/inventory/src/Stocktake/api/api.ts
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/inventory/src/Stocktake/api/operations.graphql
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/system/src/Item/Components/ItemVariantSearchInput/ItemVariantSearchInput.tsx
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  server/graphql/stocktake_line/src/mutations/insert.rs
  server/graphql/stocktake_line/src/mutations/update.rs
  server/graphql/types/src/types/stocktake_line.rs
  server/repository/src/db_diesel/stocktake_line_row.rs
  server/repository/src/migrations/v2_04_00/add_item_variant_id_to_stocktake_line.rs
  server/repository/src/migrations/v2_04_00/mod.rs
  server/repository/src/mock/stocktake_line.rs
  server/service/src/stocktake/insert/generate.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/stocktake_line/insert/generate.rs
  server/service/src/stocktake_line/insert/mod.rs
  server/service/src/stocktake_line/update/generate.rs
  server/service/src/stocktake_line/update/mod.rs
  server/service/src/sync/test/test_data/stocktake_line.rs
  server/service/src/sync/translations/stock_line.rs
  server/service/src/sync/translations/stocktake_line.rs
Labels: enhancement, Priority: Must Have, feature: GAPS

#5450 5100 import gaps data script
  server/gaps/.gitignore
  server/gaps/README.md
  server/gaps/asset_catalogue/create_catalogue_migration.py
  server/gaps/asset_catalogue/migration.sql
  server/gaps/asset_catalogue/pqs_catalogue_properties.py
  server/gaps/items/create_gaps_item_sql_script.py
  server/gaps/items/gaps_insert_functions.py
  server/gaps/items/gaps_item_variants.csv
  server/gaps/items/generated/gaps_item_inserts.sql
  server/gaps/items/helpers.py
  server/gaps/items/id_lookup.json
  server/repository/src/migrations/v2_04_00/item_changelog.rs
  server/repository/src/migrations/v2_04_00/mod.rs
Labels: enhancement, Priority: Should have, Team Piwakawaka, feature: GAPS

#5546 Add UTC to date columns in export file
  client/packages/coldchain/src/Equipment/utils.ts
Labels: bug, good first issue, Severity: Low, feature: GAPS, Team Korimako

#5558 Update new stock item pack size to use item default
  client/packages/system/src/Stock/Components/NewStockLineModal.tsx
Labels: bug, good first issue, front-end, Severity: High, Effort: small, Team Korimako

#5565 add temperature range to item variants detail
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
Labels: bug, good first issue, Build Tested: Issues Found, Tester: Maria, Severity: Normal, feature: GAPS, Team Korimako

#5476 5437 manual requisitions inconsistent behaviour in the reasons dropdown
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
  server/repository/src/db_diesel/requisition_line/requisition_line_row.rs
  server/service/src/requisition_line/response_requisition_line/update.rs
Labels: bug, Team Ruru 🦉, Severity: High, feature: manual requisition

#5563 Bugfixes for asset locations
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetUpdate.ts
Labels: bug, Team Piwakawaka, Severity: Normal, feature: GAPS

#5581 #5264 JSON Forms prescription renderer
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/api/api.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/index.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionById.ts
  client/packages/invoices/src/Prescriptions/api/hooks/index.ts
  client/packages/invoices/src/Prescriptions/api/index.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  client/packages/invoices/src/Prescriptions/index.ts
  client/packages/programs/src/JsonForms/common/JsonForm.tsx
  client/packages/programs/src/JsonForms/components/Prescription/Prescription.tsx
  client/packages/programs/src/JsonForms/components/Prescription/StockLineTable.tsx
  client/packages/programs/src/JsonForms/components/index.ts
  client/packages/programs/src/JsonForms/useFormActions.tsx
  client/packages/programs/src/JsonForms/useJsonForms.tsx
Labels: feature: programs, Team Piwakawaka

#5566 Basic spinner if current item isn't populated yet
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
Labels: bug, Team Ruru 🦉, Severity: High, feature: manual requisition

#5587 5463 manual requisitions some UI improvements to consider
  client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
  client/packages/common/src/ui/components/navigation/ListOptions/ListOptions.tsx
Labels: bug, front-end, Severity: High, feature: manual requisition

#5585 Don't calculated suggested quantity
  server/service/src/requisition/response_requisition/insert_program.rs
Labels: bug, feature: manual requisition

#5580 5568 show customer for program by tag
  server/repository/src/db_diesel/diesel_schema.rs
  server/repository/src/db_diesel/name_tag.rs
  server/repository/src/db_diesel/name_tag_join.rs
  server/repository/src/db_diesel/name_tag_row.rs
  server/repository/src/db_diesel/program_requisition/program_customer.rs
  server/repository/src/db_diesel/program_requisition/program_requisition_settings_row.rs
  server/repository/src/db_diesel/program_requisition/program_row.rs
  server/service/src/requisition/program_settings/customer_program_settings/prepare.rs
  server/service/src/requisition/response_requisition/update.rs
Labels: bug, Team Ruru 🦉, Severity: High, feature: manual requisition

#5592 Fix fail to parse json "index.ts" when running cargo test
  server/service/src/localisations.rs
Labels: bug, good first issue, back-end, Severity: Low, feature: reports

#5570 #5560 JSON Forms Prescription -- category filtering
  client/packages/common/src/hooks/useQueryParams/types.ts
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/JsonForms/components/Prescription/Prescription.tsx
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
  client/packages/system/src/Item/api/api.ts
  client/packages/system/src/Item/api/hooks/useItemStockOnHand/useItemStockOnHand.tsx
  client/packages/system/src/Item/utils.ts
  server/graphql/general/src/queries/item.rs
  server/repository/src/db_diesel/item.rs
  server/repository/src/db_diesel/item_category_row.rs
Labels: feature: programs, Team Piwakawaka

#5593 5409 fix location filter
  server/repository/src/db_diesel/cold_storage_type.rs
Labels: bug, good first issue, Build Tested: Issues Found, Tester: Maria, Severity: Normal, feature: GAPS

#5615 Disable breadcrumb link for indicators
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
Labels: bug, Team Ruru 🦉, feature: manual requisition

#5608 5492 unable to delete lines from a stocktake
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeDeleteSelectedLines.ts
Labels: bug, Team Ruru 🦉, Severity: High

#5611 5609 JSON Forms prescription -- validate quantities
  client/packages/programs/src/JsonForms/components/Prescription/StockLineTable.tsx
Labels: feature: programs, Team Piwakawaka

#5613 Sync return reasons
  server/service/src/sync/translations/invoice_line.rs
Labels: bug, Team Ruru 🦉, Severity: High

#5616 5583 error operator does not exist text asset log status on asset status page
  server/repository/src/migrations/v2_04_00/fix_asset_log_reasons_postgres.rs
  server/repository/src/migrations/v2_04_00/mod.rs
Labels: bug, Team Piwakawaka, Severity: High

#5641 Fix tests
  server/service/src/sync/test/test_data/invoice_line.rs
Labels: bug, Team Ruru 🦉, Severity: High

#5638 5635 when emptying an hiv indicator from it's default value, it is replaced by a strange text value and you can't change it easily to a valid value
  client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
Labels: bug, Severity: High, feature: manual requisition

#5637 5619 indicators should show indicator line name
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/ListIndicators.tsx
Labels: bug, Team Ruru 🦉, Severity: High

#5640 Add new ```Help```page in App drawer
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
  client/packages/common/src/ui/icons/Help.tsx
  client/packages/config/src/routes.ts
  client/packages/host/src/CommandK.tsx
  client/packages/host/src/Help/Help.tsx
  client/packages/host/src/Site.tsx
  client/packages/host/src/components/AppBar/SectionIcon.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
Labels: feature: GEDSI, Team Korimako

#5623 5465 rows per page doesnt update on import assets
  client/packages/coldchain/src/Equipment/ImportAsset/ImportReviewDataTable.tsx
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/useUserPreferencePagination.ts
  client/packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/ImportReviewDataTable.tsx
Labels: bug, good first issue, Severity: Normal, feature: GAPS, Team Korimako
