Repository msupply-foundation/open-msupply, pull requests merged in 2024-09, with the labels that each got.

#4716 4652 translate is immunisation program
  server/cli/src/test_connection.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/test/test_data/master_list.rs
  server/service/src/sync/test/test_data/program_requisition_settings.rs
  server/service/src/sync/translations/program_requisition_settings.rs
Labels: Team Piwakawaka, feature: vaccine card

#4717 4653 vaccine course dose edit modal
  client/packages/common/src/hooks/useDialog/useDialog.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/programs.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/programs/src/api/hooks/types.ts
  client/packages/programs/src/api/hooks/useVaccineCourse.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  server/graphql/types/src/types/vaccine_course_schedule.rs
Labels: Team Piwakawaka, feature: vaccine card

#4723 4654 add min age and interval columns
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/programs/src/api/hooks/useVaccineCourse.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/vaccine_course_dose_by_vaccine_course.rs
  server/graphql/core/src/loader/vaccine_course_schedule_by_vaccine_course.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/vaccine_course.rs
  server/graphql/types/src/types/vaccine_course_dose.rs
  server/graphql/types/src/types/vaccine_course_schedule.rs
  server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/update_vaccine_course.rs
  server/repository/src/db_diesel/vaccine_course/mod.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_dose.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_dose_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_schedule.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_schedule_row.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/repository/src/migrations/v2_03_00/remove_num_doses_from_vaccine_course.rs
  server/repository/src/migrations/v2_03_00/remove_vaccine_course_dose_dose_number.rs
  server/repository/src/migrations/v2_03_00/rename_vaccine_course_schedule_to_dose.rs
  server/service/src/vaccine_course/insert.rs
  server/service/src/vaccine_course/test/delete.rs
  server/service/src/vaccine_course/test/insert.rs
  server/service/src/vaccine_course/test/query.rs
  server/service/src/vaccine_course/test/update.rs
  server/service/src/vaccine_course/update.rs
  server/service/src/vaccine_course/validate.rs
Labels: Team Piwakawaka, feature: vaccine card

#4736 Sync master list line prices to OMS
  server/repository/src/db_diesel/item.rs
  server/repository/src/db_diesel/master_list_line_row.rs
  server/repository/src/migrations/v2_02_02/master_list_line.rs
  server/repository/src/migrations/v2_02_02/mod.rs
  server/repository/src/mock/full_master_list.rs
  server/repository/src/tests.rs
  server/service/src/dashboard/item_count.rs
  server/service/src/invoice/inbound_shipment/add_from_master_list.rs
  server/service/src/invoice/outbound_shipment/add_from_master_list.rs
  server/service/src/requisition/request_requisition/add_from_master_list.rs
  server/service/src/stocktake/insert.rs
  server/service/src/sync/test/test_data/master_list_line.rs
  server/service/src/sync/translations/master_list_line.rs
Labels: enhancement, needs triage, Team Ruru 🦉

#4644 4425 add better error messaging for unsynced passwords
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.graphql
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/types/schema.ts
  client/packages/host/src/components/Login/Login.tsx
  server/graphql/general/src/mutations/update_user.rs
  server/graphql/general/src/queries/login.rs
  server/repository/src/db_diesel/user.rs
  server/repository/src/db_diesel/user_row.rs
  server/repository/src/mock/user_account.rs
  server/service/src/login.rs
  server/service/src/user_account.rs
Labels: bug, Severity: High

#4688 4676 add rust embed to lower dependency
  server/Cargo.lock
  server/service/Cargo.toml
  server/service/src/service_provider.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#4698 4676 add translation files to service provider
  server/service/src/lib.rs
  server/service/src/localisations.rs
  server/service/src/service_provider.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#4715 4678 add translation function to tera context
  server/graphql/reports/src/print.rs
  server/service/src/localisations.rs
  server/service/src/report/report_service.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#4738 add vax card tab for immunisation program encounters
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/programs/src/api/api.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
Labels: Team Piwakawaka, feature: vaccine card

#4742 Pass front end language to report generation
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Report/api/hooks/useGenerateReport.ts
  client/packages/system/src/Report/api/operations.generated.ts
  client/packages/system/src/Report/api/operations.graphql
  server/graphql/reports/src/lib.rs
  server/graphql/reports/src/print.rs
  server/service/src/report/report_service.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#4740 Automate android build
  build/windows/installers-build.bat
  build/windows/omsupply-android.bat
  build/windows/omsupply-build.bat
  build/windows/omsupply-electron.bat
  build/windows/omsupply-prepare.bat
Labels: Priority: Must Have, Tooling

#4751 Change to user price_per_unit rather than just price on master_list_l…
  server/repository/src/db_diesel/master_list_line_row.rs
  server/repository/src/migrations/v2_02_02/master_list_line.rs
  server/service/src/sync/test/test_data/master_list_line.rs
  server/service/src/sync/translations/master_list_line.rs
Labels: enhancement, Team Ruru 🦉

#4749 Apply discounts to Outbound Shipments
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/useGetDiscountPercentage.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
  client/packages/invoices/src/StockOut/utils.tsx
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/discount.rs
  server/graphql/general/src/queries/master_list.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/general/src/queries/tests/master_lists.rs
  server/repository/src/db_diesel/master_list.rs
  server/repository/src/db_diesel/master_list_line_row.rs
  server/repository/src/db_diesel/master_list_row.rs
  server/repository/src/migrations/v2_02_02/master_list.rs
  server/repository/src/migrations/v2_02_02/master_list_line.rs
  server/service/src/lib.rs
  server/service/src/pricing/discount.rs
  server/service/src/pricing/mod.rs
  server/service/src/pricing/tests/discount.rs
  server/service/src/pricing/tests/mod.rs
  server/service/src/service_provider.rs
  server/service/src/sync/test/test_data/master_list.rs
  server/service/src/sync/test/test_data/master_list_line.rs
  server/service/src/sync/translations/master_list.rs
  server/service/src/sync/translations/master_list_line.rs
Labels: enhancement, Team Ruru 🦉

#4732 4729 sync out vaccine course data
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/demographic_indicator_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_dose_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_item_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_row.rs
  server/repository/src/migrations/v2_03_00/add_vaccine_course_changelog_table_names.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/service/src/sync/test/test_data/demographic_indicator.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/vaccine_course.rs
  server/service/src/sync/test/test_data/vaccine_course_dose.rs
  server/service/src/sync/test/test_data/vaccine_course_item.rs
  server/service/src/sync/translations/demographic_indicator.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/vaccine_course.rs
  server/service/src/sync/translations/vaccine_course_dose.rs
  server/service/src/sync/translations/vaccine_course_item.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine card

#4756 4703 structured pricing response
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
  client/packages/invoices/src/OutboundShipment/api/api.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/useGetDiscountPercentage.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/useGetItemPricing.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
  client/packages/invoices/src/StockOut/utils.tsx
  client/packages/invoices/src/utils.ts
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/discount.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/general/src/queries/pricing.rs
  server/repository/src/db_diesel/master_list_line.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/insert/mod.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
  server/service/src/pricing/calculate_sell_price.rs
  server/service/src/pricing/discount.rs
  server/service/src/pricing/item_price.rs
  server/service/src/pricing/mod.rs
  server/service/src/pricing/tests/discount.rs
  server/service/src/pricing/tests/item_price.rs
  server/service/src/pricing/tests/mod.rs
Labels: enhancement, Team Ruru 🦉

#4748 4710 administer dose modal
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/programs/src/api/hooks/useVaccineCourse.ts
  client/packages/system/src/Clinician/ClinicianSearchInput.tsx
  client/packages/system/src/Clinician/utils.ts
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
  client/packages/system/src/Encounter/DetailView/VaccinationsTab.tsx
  client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/Components/index.ts
  client/packages/system/src/Vaccination/api/index.ts
  client/packages/system/src/Vaccination/api/keys.ts
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  client/packages/system/src/Vaccination/api/useVaccination.ts
  client/packages/system/src/Vaccination/api/useVaccinationsGraphQL.ts
  client/packages/system/src/Vaccination/index.ts
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/vaccine_course.rs
  server/graphql/types/src/types/vaccine_course_dose.rs
  server/graphql/vaccine_course/src/lib.rs
  server/graphql/vaccine_course/src/vaccine_course_queries.rs
  server/service/src/vaccine_course/query.rs
Labels: Team Piwakawaka, feature: vaccine card

#4758 4710 save vaccination
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/VaccinationsTab.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/mutations/mod.rs
  server/graphql/programs/src/mutations/vaccination/insert.rs
  server/graphql/programs/src/mutations/vaccination/mod.rs
  server/graphql/types/src/types/activity_log.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/vaccination.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/encounter_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_item.rs
  server/repository/src/migrations/v2_03_00/add_vaccination_activity_log_types.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/repository/src/mock/encounter.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/program_enrolment.rs
  server/repository/src/mock/stock_line.rs
  server/repository/src/mock/vaccination.rs
  server/repository/src/mock/vaccine_course.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
  server/service/src/vaccination/insert/generate.rs
  server/service/src/vaccination/insert/mod.rs
  server/service/src/vaccination/insert/validate.rs
  server/service/src/vaccination/mod.rs
  server/service/src/vaccination/query.rs
  server/service/src/vaccination/validate.rs
Labels: Team Piwakawaka, feature: vaccine card

#4762 4703-dispensing
  server/service/src/pricing/item_price.rs
Labels: enhancement, Team Ruru 🦉

#4760 4711 select vaccination batch
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Vaccination/Components/SelectBatchModal.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/api/useVaccination.ts
Labels: Team Piwakawaka, feature: vaccine card

#4767 4763 cleanup pricing discounts
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
  client/packages/invoices/src/OutboundShipment/api/api.ts
  client/packages/invoices/src/utils.ts
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/insert/mod.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
Labels: refactor, Team Ruru 🦉

#4772 4737 vaccination details
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Encounter/DetailView/VaccinationsTab.tsx
  client/packages/system/src/Vaccination/Components/SelectBatchModal.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/queries/mod.rs
  server/graphql/programs/src/queries/vaccination.rs
  server/graphql/types/src/types/vaccination.rs
Labels: Team Piwakawaka, feature: vaccine card

#4770 4712 create prescription from vaccination
  server/graphql/core/src/loader/vaccine_course_dose_by_vaccine_course.rs
  server/graphql/programs/src/mutations/vaccination/insert.rs
  server/graphql/types/src/types/item.rs
  server/repository/src/db_diesel/item_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_dose.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_dose_row.rs
  server/repository/src/migrations/v2_03_00/add_vaccine_doses_to_item.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/repository/src/mock/encounter.rs
  server/repository/src/mock/item.rs
  server/repository/src/mock/program_enrolment.rs
  server/repository/src/mock/stock_line.rs
  server/repository/src/mock/vaccination.rs
  server/repository/src/mock/vaccine_course.rs
  server/service/src/sync/test/test_data/item.rs
  server/service/src/sync/translations/item.rs
  server/service/src/vaccination/insert/generate.rs
  server/service/src/vaccination/insert/mod.rs
  server/service/src/vaccination/insert/validate.rs
  server/service/src/vaccination/validate.rs
  server/service/src/vaccine_course/query.rs
  server/service/src/vaccine_course/test/update.rs
Labels: Team Piwakawaka, feature: vaccine card

#4777 4665 vax card api
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Patient/VaccinationCards/DetailView/DetailView.tsx
  client/packages/system/src/Patient/api/hooks/keys.ts
  client/packages/system/src/Patient/api/hooks/usePatientVaccineCard.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  server/cli/src/refresh_dates.rs
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/queries/vaccination.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/program/mod.rs
  server/graphql/types/src/types/program/program_enrolment.rs
  server/graphql/types/src/types/program/vaccination.rs
  server/graphql/types/src/types/program/vaccination_card.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/program_enrolment.rs
  server/repository/src/db_diesel/vaccination_card.rs
  server/repository/src/migrations/views/mod.rs
  server/service/src/vaccination/get_vaccination_card.rs
  server/service/src/vaccination/insert/validate.rs
  server/service/src/vaccination/mod.rs
Labels: Team Piwakawaka, feature: vaccine card

#4778 4663(2) Patient vax card (formatting)
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/styles/theme.ts
  client/packages/common/src/ui/layout/tables/components/Cells/StatusCell/StatusCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/StatusCell/index.ts
  client/packages/common/src/ui/layout/tables/components/Cells/index.ts
  client/packages/common/src/ui/layout/tables/context/TableContext.tsx
  client/packages/common/src/ui/layout/tables/context/hooks/useRowStyle.ts
  client/packages/system/src/Patient/VaccinationCards/DetailView/DetailView.tsx
Labels: Team Piwakawaka, feature: vaccine card

#4743 4739 refactor translation function
  server/report_builder/README.md
  server/service/src/localisations.rs
  server/service/src/report/report_service.rs
  server/service/src/report/templates/test.html
  server/service/src/service_provider.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#4773 #4663(1) Patient Vaccine card
  client/packages/common/src/hooks/useBreadcrumbs/useBreadcrumbs.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/common/src/styles/theme.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/components/Cells/StatusCell/StatusCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/StatusCell/index.ts
  client/packages/common/src/ui/layout/tables/components/Cells/index.ts
  client/packages/common/src/ui/layout/tables/context/TableContext.tsx
  client/packages/common/src/ui/layout/tables/context/hooks/useRowStyle.ts
  client/packages/system/src/Patient/Service/Service.tsx
  client/packages/system/src/Patient/VaccinationCards/DetailView/DetailView.tsx
  client/packages/system/src/Patient/VaccinationCards/DetailView/index.ts
  client/packages/system/src/Patient/VaccinationCards/index.ts
  client/packages/system/src/Patient/api/hooks/keys.ts
  client/packages/system/src/Patient/api/hooks/usePatientVaccineCard.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  client/packages/system/src/Patient/api/usePatientGraphQL.ts
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  server/cli/src/refresh_dates.rs
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/queries/vaccination.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/program/mod.rs
  server/graphql/types/src/types/program/program_enrolment.rs
  server/graphql/types/src/types/program/vaccination.rs
  server/graphql/types/src/types/program/vaccination_card.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/program_enrolment.rs
  server/repository/src/db_diesel/vaccination_card.rs
  server/repository/src/migrations/views/mod.rs
  server/service/src/vaccination/get_vaccination_card.rs
  server/service/src/vaccination/insert/validate.rs
  server/service/src/vaccination/mod.rs
Labels: Team Piwakawaka, feature: vaccine card

#4783 4774 backlog prescription entry backdated stock levels service
  server/repository/src/db_diesel/stock_movement.rs
  server/service/src/stock_line/historical_stock.rs
  server/service/src/stock_line/mod.rs
  server/service/src/stock_line/tests/historical_stock.rs
  server/service/src/stock_line/tests/mod.rs
Labels: enhancement, Team Ruru 🦉

#4788 Backdating Prescriptions - Save Date
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/api/api.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  server/graphql/invoice/src/mutations/prescription/update.rs
  server/service/src/invoice/prescription/update/generate.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/invoice/prescription/update/validate.rs
  server/service/src/vaccination/insert/generate.rs
Labels: enhancement, feature: dispensing

#4752 4679 add translations to standard reports
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/reports.json
  client/packages/common/src/intl/locales/index.ts
  client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/AppBarButtons.tsx
  client/packages/reports/src/DetailView/DetailView.tsx
  client/packages/reports/src/ListView/ListView.tsx
  client/packages/reports/src/ListView/SidePanel.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/RnRForms/DetailView/AppBarButtons.tsx
  client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
  client/packages/system/src/Report/components/ReportArgumentsModal.tsx
Labels: enhancement, Team Ruru 🦉, feature: reports

#4802 #4797 Add Vaccine card to Encounter
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/Clinician/ClinicianSearchInput.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/VaccinationsTab.tsx
  client/packages/system/src/Patient/VaccinationCards/DetailView/DetailView.tsx
  client/packages/system/src/Patient/VaccinationCards/VaccineCardTable.tsx
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/graphql/types/src/types/program/vaccination_card.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine card

#4821 fix translations - Move string to common
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/distribution.json
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#4809 4714 edit vaccination
  client/packages/invoices/src/utils.ts
  server/graphql/invoice/src/mutations/customer_return/insert.rs
  server/repository/src/db_diesel/vaccination.rs
  server/repository/src/mock/stock_line.rs
  server/service/src/invoice/customer_return/insert/generate.rs
  server/service/src/invoice/customer_return/insert/mod.rs
  server/service/src/invoice/customer_return/insert/validate.rs
  server/service/src/invoice/customer_return/mod.rs
  server/service/src/invoice/customer_return/update/generate.rs
  server/service/src/invoice/customer_return/update_lines/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/lib.rs
  server/service/src/vaccination/generate.rs
  server/service/src/vaccination/insert/generate.rs
  server/service/src/vaccination/insert/mod.rs
  server/service/src/vaccination/mod.rs
  server/service/src/vaccination/update/generate.rs
  server/service/src/vaccination/update/mod.rs
  server/service/src/vaccination/update/validate.rs
  server/service/src/vaccination/validate.rs
  server/service/src/validate.rs
Labels: Team Piwakawaka, feature: vaccine card

#4823 Adds QR Code functionality to oms Reports
  package.json
  server/Cargo.lock
  server/service/Cargo.toml
  server/service/src/report/mod.rs
  server/service/src/report/qr_code.rs
  server/service/src/report/report_service.rs
Labels: enhancement, Severity: Hotfix

#4829 4825 fix handling of 0 discount masterlists
  package.json
  server/graphql/general/src/queries/master_list.rs
  server/repository/src/db_diesel/master_list.rs
  server/service/src/pricing/item_price.rs
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#4813 4714 edit vax UI
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/functions/ApiUtils.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/mutations/vaccination/mod.rs
  server/graphql/programs/src/mutations/vaccination/update.rs
  server/graphql/types/src/types/invoice_query.rs
Labels: Team Piwakawaka, feature: vaccine card

#4827 4714 file rearrange
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Patient/Service/Service.tsx
  client/packages/system/src/Patient/VaccinationCard/DetailView.tsx
  client/packages/system/src/Patient/VaccinationCard/ListView.tsx
  client/packages/system/src/Patient/VaccinationCard/index.ts
  client/packages/system/src/Patient/VaccinationCards/DetailView/index.ts
  client/packages/system/src/Patient/api/hooks/keys.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  client/packages/system/src/Patient/api/usePatientGraphQL.ts
  client/packages/system/src/Vaccination/Components/VaccinationCard.tsx
  client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
  client/packages/system/src/Vaccination/Components/index.ts
  client/packages/system/src/Vaccination/api/keys.ts
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  client/packages/system/src/Vaccination/api/usePatientVaccineCard.ts
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/repository/src/migrations/views/mod.rs
Labels: Team Piwakawaka, feature: vaccine card

#4824 #4173 Prevent dose skipping
  server/graphql/programs/src/mutations/vaccination/insert.rs
  server/repository/src/mock/vaccination.rs
  server/service/src/vaccination/get_vaccination_card.rs
  server/service/src/vaccination/insert/mod.rs
  server/service/src/vaccination/insert/validate.rs
  server/service/src/vaccination/update/mod.rs
  server/service/src/vaccination/update/validate.rs
  server/service/src/vaccination/validate.rs
Labels: Team Piwakawaka, feature: vaccine card

#4803 3672 Fix ledger discrepancy risk with historical available stock
  server/repository/src/db_diesel/stock_movement.rs
  server/service/src/stock_line/historical_stock.rs
  server/service/src/stock_line/tests/historical_stock.rs
Labels: enhancement, feature: dispensing

#4833 4796 add facility to vaccination
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Vaccination/Components/FacilitySearchInput.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  client/packages/system/src/Vaccination/api/useVaccination.ts
  client/packages/system/src/Vaccination/api/useVaccinationsGraphQL.ts
  server/graphql/programs/src/mutations/vaccination/insert.rs
  server/graphql/programs/src/mutations/vaccination/update.rs
  server/graphql/types/src/types/program/vaccination.rs
  server/repository/src/db_diesel/vaccination.rs
  server/repository/src/db_diesel/vaccination_row.rs
  server/repository/src/migrations/v2_03_00/add_facility_to_vaccination.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/service/src/name/mod.rs
  server/service/src/sync/test/test_data/vaccination.rs
  server/service/src/vaccination/insert/generate.rs
  server/service/src/vaccination/insert/mod.rs
  server/service/src/vaccination/insert/validate.rs
  server/service/src/vaccination/update/generate.rs
  server/service/src/vaccination/update/mod.rs
  server/service/src/vaccination/update/validate.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine card

#4836 4721 Program enrolment date not populated in edit modal
  client/packages/programs/src/JsonForms/common/components/DateTime.tsx
Labels: bug, Team Piwakawaka, Severity: Normal

#4839 4784 After migration the price on service charges does not show
  server/service/src/sync/translations/invoice_line.rs
Labels: bug, Migrate Existing Desktop, Severity: Normal

#4838 4683 Broken translation: Supplier/outbound returns linked shipment
  client/packages/invoices/src/Returns/SupplierDetailView/SidePanel/RelatedDocumentsSection.tsx
Labels: bug, Severity: Low

#4812 4792 report versioning schema changes
  server/cli/src/cli.rs
  server/repository/src/db_diesel/report_row.rs
  server/repository/src/migrations/v2_03_00/add_report_versioning.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/service/src/report/report_service.rs
  server/service/src/sync/test/test_data/report.rs
  server/service/src/sync/translations/report.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#4844 4691 Wrapped AppBarButtons have no margin
  client/packages/common/src/ui/components/portals/AppBarButtons/AppBarButtons.tsx
Labels: bug, Severity: Low

#4841 #4656 Maximum age for vaccination dose (1)
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/programs/src/api/hooks/useVaccineCourse.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  server/graphql/types/src/types/program/vaccination_card.rs
  server/graphql/types/src/types/vaccine_course_dose.rs
  server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/update_vaccine_course.rs
  server/repository/src/db_diesel/vaccination_card.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_dose_row.rs
  server/repository/src/migrations/v2_03_00/add_max_age_to_vaccine_dose.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/repository/src/migrations/views/mod.rs
  server/repository/src/mock/vaccine_course.rs
  server/service/src/sync/test/test_data/vaccine_course_dose.rs
  server/service/src/vaccine_course/update.rs
Labels: Team Piwakawaka, feature: vaccine card

#4849 4684 Can change the other party (supplier) of automatic supplier returns
  client/packages/invoices/src/Returns/SupplierDetailView/Toolbar.tsx
Labels: bug, Severity: Normal

#4820 4790 add standard report
  client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx
  server/cli/src/cli.rs
  server/report_builder/src/cli.rs
  server/reports/expiring-items/1_0/arguments.json
  server/reports/expiring-items/1_0/arguments_ui.json
  server/reports/expiring-items/1_0/manifest.json
  server/reports/expiring-items/1_0/query.graphql
  server/reports/expiring-items/1_0/style.css
  server/reports/expiring-items/1_0/template.html
Labels: enhancement, Team Ruru 🦉, feature: reports

#4851 4799 add embedding standard reports in oms build
  server/cli/src/cli.rs
  server/report_builder/src/build.rs
  server/reports/generated/standard_reports.json
  server/repository/src/db_diesel/report_row.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#4848 4656(2) Age Month/Year input
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/MultiNumberInputCell/MultiNumberInputCell.test.ts
  client/packages/common/src/ui/layout/tables/components/Cells/MultiNumberInputCell/MultiNumberInputCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/MultiNumberInputCell/index.ts
  client/packages/common/src/ui/layout/tables/components/Cells/index.ts
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
Labels: Team Piwakawaka, feature: vaccine card

#4869 4863 add standard reports folder to embedded rust
  server/cli/src/cli.rs
  server/repository/src/db_diesel/report_row.rs
  server/server/src/lib.rs
  server/service/src/lib.rs
  server/service/src/localisations.rs
  server/service/src/service_provider.rs
  server/service/src/standard_reports.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#4868 4657 vaccine course dose soft delete
  server/repository/src/db_diesel/vaccine_course/vaccine_course_dose.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_dose_row.rs
  server/repository/src/migrations/v2_03_00/add_vaccine_course_dose_deleted_datetime.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/repository/src/migrations/views/mod.rs
  server/repository/src/mock/vaccine_course.rs
  server/service/src/sync/test/test_data/vaccine_course_dose.rs
  server/service/src/vaccine_course/insert.rs
  server/service/src/vaccine_course/query.rs
  server/service/src/vaccine_course/test/update.rs
  server/service/src/vaccine_course/update.rs
Labels: Team Piwakawaka, feature: vaccine card

#4871 4835 add batch and facility to vaccine card
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  server/graphql/types/src/types/program/vaccination_card.rs
  server/repository/src/db_diesel/vaccination_card.rs
  server/repository/src/migrations/views/mod.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine card

#4854 3672 show historical stock in prescription
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/hooks/useDraftPrescriptionLines.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  client/packages/invoices/src/StockOut/utils.tsx
  client/packages/system/src/Item/api/hooks/index.ts
  client/packages/system/src/Item/api/hooks/useHistoricalStockLines/index.ts
  client/packages/system/src/Item/api/hooks/useHistoricalStockLines/useHistoricalStockLines.tsx
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  server/graphql/stock_line/src/lib.rs
  server/service/src/stock_line/historical_stock.rs
Labels: enhancement, feature: dispensing

#4845 4801 prevent historic vaccination transactions
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Vaccination/Components/SelectItemAndBatch.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/Components/getSwitchReason.test.ts
  client/packages/system/src/Vaccination/Components/getSwitchReason.ts
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/graphql/programs/src/mutations/vaccination/insert.rs
  server/graphql/programs/src/mutations/vaccination/update.rs
  server/service/src/vaccination/insert/mod.rs
  server/service/src/vaccination/insert/validate.rs
  server/service/src/vaccination/update/generate.rs
  server/service/src/vaccination/update/mod.rs
  server/service/src/vaccination/update/validate.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine card

#4876 Map and display update prescription stock not available error
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/api/hooks/document/usePrescriptionFields.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
Labels: bug, Severity: Normal

#4870 4867 add remaining reports to oms repo
  server/reports/expiring-items/1_0/generated/expiring-items.json
  server/reports/expiring-items/1_0/src/template.html
  server/reports/expiring-items/2_3_0/argument_schemas/arguments.json
  server/reports/expiring-items/2_3_0/argument_schemas/arguments_ui.json
  server/reports/expiring-items/2_3_0/generated/expiring-items.json
  server/reports/expiring-items/2_3_0/manifest.json
  server/reports/expiring-items/2_3_0/src/query.graphql
  server/reports/expiring-items/2_3_0/src/style.css
  server/reports/expiring-items/2_3_0/src/template.html
  server/reports/generated/standard_reports.json
  server/reports/item-usage/2_3_0/argument_schemas/arguments.json
  server/reports/item-usage/2_3_0/argument_schemas/arguments_ui.json
  server/reports/item-usage/2_3_0/manifest.json
  server/reports/item-usage/2_3_0/src/AMCTwelve.postgres.sql
  server/reports/item-usage/2_3_0/src/AMCTwelve.sqlite.sql
  server/reports/item-usage/2_3_0/src/AMCTwentyFour.postgres.sql
  server/reports/item-usage/2_3_0/src/AMCTwentyFour.sqlite.sql
  server/reports/item-usage/2_3_0/src/expiringInSixMonths.postgres.sql
  server/reports/item-usage/2_3_0/src/expiringInSixMonths.sqlite.sql
  server/reports/item-usage/2_3_0/src/expiringInTwelveMonths.postgres.sql
  server/reports/item-usage/2_3_0/src/expiringInTwelveMonths.sqlite.sql
  server/reports/item-usage/2_3_0/src/lastMonthConsumption.postgres.sql
  server/reports/item-usage/2_3_0/src/lastMonthConsumption.sqlite.sql
  server/reports/item-usage/2_3_0/src/query.graphql
  server/reports/item-usage/2_3_0/src/stockOnOrder.sql
  server/reports/item-usage/2_3_0/src/style.css
  server/reports/item-usage/2_3_0/src/template.html
  server/reports/item-usage/2_3_0/src/thisMonthConsumption.postgres.sql
  server/reports/item-usage/2_3_0/src/thisMonthConsumption.sqlite.sql
  server/reports/item-usage/2_3_0/src/twoMonthsAgoConsumption.postgres.sql
  server/reports/item-usage/2_3_0/src/twoMonthsAgoConsumption.sqlite.sql
  server/reports/stock-detail/2_3_0/argument_schemas/arguments.json
  server/reports/stock-detail/2_3_0/argument_schemas/arguments_ui.json
  server/reports/stock-detail/2_3_0/manifest.json
  server/reports/stock-detail/2_3_0/src/query.graphql
  server/reports/stock-detail/2_3_0/src/style.css
  server/reports/stock-detail/2_3_0/src/template.html
  server/reports/stock-status/2_3_0/argument_schemas/arguments.json
  server/reports/stock-status/2_3_0/argument_schemas/arguments_ui.json
  server/reports/stock-status/2_3_0/manifest.json
  server/reports/stock-status/2_3_0/src/query.graphql
  server/reports/stock-status/2_3_0/src/style.css
  server/reports/stock-status/2_3_0/src/template.html
Labels: enhancement, Team Ruru 🦉, feature: reports

#4880 Adjust test connection binary paths for server installer
  build/windows/omsupply_desktop.suf
  build/windows/omsupply_server.suf
Labels: bug, Severity: High

#4877 4864 back date UI
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  server/service/src/invoice/prescription/insert/generate.rs
  server/service/src/invoice/prescription/update/generate.rs
Labels: enhancement, needs triage

#4881 #4805 Vaccination card statuses
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/common/src/styles/theme.ts
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  server/graphql/types/src/types/program/vaccination_card.rs
  server/service/src/vaccination/get_vaccination_card.rs
  server/util/src/constants.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine card

#4850 4685 Requisitions: number of shipments sort actually sorts by requisition num
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
Labels: bug, Severity: Low

#4887 4883 create return when not this facility
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/Components/getSwitchReason.test.ts
  client/packages/system/src/Vaccination/Components/getSwitchReason.ts
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/graphql/programs/src/mutations/vaccination/update.rs
  server/service/src/vaccination/generate.rs
  server/service/src/vaccination/update/generate.rs
  server/service/src/vaccination/update/mod.rs
  server/service/src/vaccination/update/validate.rs
Labels: bug, Team Piwakawaka, Severity: High, feature: vaccine card

#4902 4089 ledger table change name 'quantity' to 'units'
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/common/src/intl/locales/es/distribution.json
  client/packages/common/src/intl/locales/fr/distribution.json
  client/packages/common/src/intl/locales/pt/app.json
  client/packages/common/src/intl/locales/pt/dashboard.json
  client/packages/common/src/intl/locales/pt/distribution.json
  client/packages/common/src/intl/locales/pt/inventory.json
  client/packages/common/src/intl/locales/pt/replenishment.json
  client/packages/common/src/intl/locales/ru/distribution.json
  client/packages/common/src/intl/locales/ru/manage.json
  client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
Labels: enhancement, Priority: Should have, Team Ruru 🦉, Severity: Normal

#4862 3175 Stocktake: something's wrong with the pagination
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
  client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts
Labels: bug, refactor, Severity: High, docs: external

#4920 4910 add support for kmf as a currency
  client/packages/common/src/intl/currency/currency.ts
Labels: enhancement, Severity: Hotfix

#4847 4351 refactor stocktake in service layer
  server/service/src/stocktake/delete/mod.rs
  server/service/src/stocktake/delete/validate.rs
  server/service/src/stocktake/insert/generate.rs
  server/service/src/stocktake/insert/mod.rs
  server/service/src/stocktake/insert/validate.rs
  server/service/src/stocktake/mod.rs
  server/service/src/stocktake/update.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/stocktake/update/mod.rs
  server/service/src/stocktake/update/validate.rs
  server/service/src/stocktake/validate.rs
  server/service/src/stocktake_line/delete/mod.rs
  server/service/src/stocktake_line/delete/validate.rs
  server/service/src/stocktake_line/insert/generate.rs
  server/service/src/stocktake_line/insert/mod.rs
  server/service/src/stocktake_line/insert/validate.rs
  server/service/src/stocktake_line/update/generate.rs
  server/service/src/stocktake_line/update/mod.rs
  server/service/src/stocktake_line/update/validate.rs
Labels: refactor

#4908 4819 'Encounter missed' warning doesn't disappear until refresh
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
Labels: bug, feature: programs, Team Ruru 🦉, Severity: Low
