Repository msupply-foundation/open-msupply, pull requests merged in 2024-07, with the labels that each got.

#4283 3859 Upsert sync buffer in transaction
  server/service/src/sync/api/common_records.rs
  server/service/src/sync/central_data_synchroniser.rs
  server/service/src/sync/central_data_synchroniser_v6.rs
  server/service/src/sync/remote_data_synchroniser.rs
  server/service/src/sync/sync_on_central/mod.rs
Labels: enhancement, Priority: Must Have, Team Ruru 🦉

#4333 4324 Error when navigating back to patients list via breadcrumb
  client/packages/host/src/components/Navigation/DispensaryNav.tsx
  server/repository/src/db_diesel/patient.rs
Labels: bug

#4327 Facility list house icon
  client/packages/system/src/IndicatorsDemographics/DetailView/GrowthRow.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/PercentageColumn.tsx
  client/packages/system/src/Name/ListView/Facilities/ListView.tsx
Labels: bug, Team Piwakawaka, Severity: Low, feature: GAPS

#4316 4235 non-central stores should only see their assets
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
Labels: bug, Team Piwakawaka, Severity: High

#4326 2118 breadcrumb refactor
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/common/src/hooks/useBreadcrumbs/useBreadcrumbs.tsx
  client/packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
  client/packages/system/src/ContactTrace/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseView.tsx
  client/packages/system/src/Item/DetailView/DetailView.tsx
  client/packages/system/src/MasterList/DetailView/DetailView.tsx
  client/packages/system/src/Patient/PatientView/PatientSummary.tsx
  client/packages/system/src/Stock/DetailView/DetailView.tsx
Labels: enhancement, Priority: Must Have, refactor, Team Piwakawaka

#4329 4281 Inbound shipment: tax percentage is being displayed as the tax value
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/common/src/intl/locales/es/distribution.json
  client/packages/common/src/intl/locales/fr/distribution.json
  client/packages/common/src/intl/locales/pt/distribution.json
  client/packages/common/src/intl/locales/ru/distribution.json
  client/packages/common/src/intl/locales/tet/distribution.json
  client/packages/common/src/ui/components/inputs/TextInput/TaxEdit.tsx
  client/packages/common/src/ui/components/inputs/TextInput/index.ts
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundServiceLineEdit/useServiceLineColumns.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/index.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/useServiceLineColumns.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/modals/TaxEdit.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/modals/index.ts
Labels: bug, Team Ruru 🦉, Severity: Normal, docs: external

#4331 4271 customer-credit from OG should not be mapped as outbound-return
  server/service/src/sync/translations/invoice.rs
Labels: bug, Migrate Existing Desktop, Team Ruru 🦉, Severity: High

#4346 Line totals migration
  server/service/src/sync/translations/invoice_line.rs
Labels: bug, Migrate Existing Desktop, Team Ruru 🦉, Severity: High

#4345 4063 vaccine details as modal
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/api/hooks/line/useSaveInboundLines.ts
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/VaccineCourseCreateModal.tsx
  client/packages/system/src/Immunisation/Service/Service.tsx
  client/packages/system/src/Immunisation/VaccineCourseEditModal/DescriptionColumn.tsx
  client/packages/system/src/Immunisation/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/system/src/Immunisation/VaccineCourseEditModal/VaccineCourseItemSelect.tsx
  client/packages/system/src/Immunisation/VaccineCourseEditModal/index.ts
  client/packages/system/src/Immunisation/VaccineCourseView/AppFooterComponent.tsx
  client/packages/system/src/Immunisation/VaccineCourseView/VaccineCourseView.tsx
  client/packages/system/src/Immunisation/VaccineCourseView/index.ts
  client/packages/system/src/Immunisation/api/hooks/useVaccineCourse.ts
  client/packages/system/src/Immunisation/index.ts
  server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/update_vaccine_course.rs
  server/service/src/program/test/delete.rs
  server/service/src/vaccine_course/insert.rs
  server/service/src/vaccine_course/test/delete.rs
  server/service/src/vaccine_course/test/insert.rs
  server/service/src/vaccine_course/test/query.rs
  server/service/src/vaccine_course/test/update.rs
  server/service/src/vaccine_course/update.rs
Labels: enhancement, Priority: Nice to Have, Team Piwakawaka, feature: GAPS

#4303 1611 day to be enterable for expiry date
  client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
  client/packages/common/src/ui/components/inputs/DatePickers/ExpiryDateInput/ExpiryDateInput.tsx
  client/packages/common/src/ui/layout/tables/columns/ExpiryDateInput/ExpiryDateInput.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/ExpiryDateCell/ExpiryDateCell.tsx
  client/packages/common/src/ui/layout/tables/hooks/useColumns/useColumns.tsx
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/common/src/utils/formatters/formatters.test.ts
  client/packages/common/src/utils/formatters/formatters.ts
  server/repository/src/migrations/v2_00_00/mod.rs
  server/repository/src/migrations/v2_00_00/name_deleted_datetime.rs
Labels: enhancement, Priority: Should have, Team Ruru 🦉

#4347 4306 4305 Fix transfer migrations from mobile
  server/graphql/invoice/src/mutations/outbound_shipment/insert.rs
  server/repository/src/db_diesel/requisition/requisition_row.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/requisition.rs
  server/util/src/test_helpers.rs
Labels: bug, Migrating Existing Mobile, Team Ruru 🦉, Severity: Hotfix

#4328 3947 stock line changes from stocktake not captured in activity log
  client/packages/common/src/ui/icons/BarChart2.tsx
  server/service/src/demographic/insert_demographic_indicator.rs
  server/service/src/stocktake/update.rs
Labels: bug, Team Ruru 🦉, Severity: Normal

#4330 4280 tax displays incorrectly on totals below $1 in outbound shipments
  client/packages/common/src/utils/pricing/PricingUtils.ts
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal, Needs Investigation

#4302 4284 export asset match import
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/ImportReviewDataTable.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
  client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/coldchain/src/Equipment/utils.ts
Labels: bug, feature: coldchain, Team Piwakawaka, Severity: Normal

#4336 Remove mock service workers, update node version
  .github/workflows/client-tests.yaml
  client/.nvmrc
  client/.storybook/preview.js
  client/README.md
  client/codegen.yml
  client/package.json
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureBreach/operations.generated.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureLog/operations.generated.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureNotification/operations.generated.ts
  client/packages/coldchain/src/Sensor/api/operations.generated.ts
  client/packages/common/src/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/dashboard/src/api/operations.generated.ts
  client/packages/host/package.json
  client/packages/host/public/mockServiceWorker.js
  client/packages/host/src/api/operations.generated.ts
  client/packages/host/webpack.config.js
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useNextItem.test.tsx
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/StockOut/operations.generated.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/system/src/ActivityLog/api/operations.generated.ts
  client/packages/system/src/Asset/api/operations.generated.ts
  client/packages/system/src/Currency/api/operations.generated.ts
  client/packages/system/src/Immunisation/api/operations.generated.ts
  client/packages/system/src/IndicatorsDemographics/api/operations.generated.ts
  client/packages/system/src/InventoryAdjustmentReason/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Location/api/operations.generated.ts
  client/packages/system/src/Log/api/operations.generated.ts
  client/packages/system/src/MasterList/api/operations.generated.ts
  client/packages/system/src/Name/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Report/api/operations.generated.ts
  client/packages/system/src/ReturnReason/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Store/api/operations.generated.ts
  client/packages/system/src/Sync/api/operations.generated.ts
  client/yarn.lock
Labels: Priority: Should have, refactor, Team Piwakawaka

#4376 Show vaccine courses in list view
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Immunisation/ListView/ListView.tsx
Labels: bug, Team Piwakawaka, Severity: Hotfix, feature: GAPS

#4377 Mount capacitor js to web view onLoadResource
  client/packages/android/app/src/main/java/org/openmsupply/client/ExtendedWebViewClient.java
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#4371 3444 Move create_missing_master_list_and_program into a migration
  package.json
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_02_00/create_missing_master_list_and_program.rs
  server/repository/src/migrations/v2_02_00/create_system_user.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/server/src/lib.rs
  server/service/src/lib.rs
  server/service/src/missing_program.rs
  server/service/src/service_provider.rs
  server/service/src/system_user.rs
Labels: Priority: Nice to Have, refactor, Team Ruru 🦉

#4366 4357 Set Quantities to 0 in Inbound Shipment doesn't work and shows incorrect error
  server/service/src/invoice_line/validate.rs
Labels: bug, Team Ruru 🦉, Severity: High

#4378 4010 Repack New Location showing as old Location (new shows blank)
  client/packages/system/src/Location/Components/LocationSearchInput.tsx
  client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
  client/packages/system/src/Stock/DetailView/DetailView.tsx
  client/packages/system/src/Stock/types.ts
Labels: bug, Team Ruru 🦉, Severity: Normal

#4388 3485 When creating a new stocktake with `Items with stock` checked ON, the counted packs should be equal to the snapshot packs instead of 0
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#4390 Android is just endlessly loading...
  client/packages/android/app/src/main/java/org/openmsupply/client/ExtendedWebViewClient.java
  client/packages/host/src/components/Initialise/hooks.ts
Labels: bug, Team Piwakawaka

#4391 Add zero dose and Penta 3
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
Labels: Epic, Team Piwakawaka, feature: GAPS

#4398 3993 Can't see Supplier/Customer's full address
  client/packages/system/src/Name/DetailModal/DetailModal.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal, docs: external

#4385 2667 Can we auto-confirm requisition after the shipment has been created from the requistion?
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/distribution.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/Toolbar.tsx
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  server/graphql/requisition/src/requisition_queries.rs
  server/repository/src/db_diesel/requisition/mod.rs
  server/repository/src/db_diesel/requisition/requisition.rs
Labels: bug, Priority: Should have, Team Ruru 🦉, Severity: Normal, docs: external

#4397 4382 user permissions not working for inventory adjustment and repack
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
  client/packages/system/src/Stock/DetailView/DetailView.tsx
  server/service/src/login.rs
Labels: bug, Team Ruru 🦉, docs: external

#4402 3964 Tax Edit modal value is not updated if you edit tax percentage from service line edit modal
  client/packages/common/src/ui/components/inputs/TextInput/TaxEdit.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#4387 4161 Hardcode filtering out of patients from names query
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  server/graphql/batch_mutations/src/batch_prescription.rs
  server/graphql/general/src/queries/names.rs
  server/graphql/general/src/queries/tests/names.rs
  server/graphql/invoice/src/mutations/prescription/insert.rs
  server/graphql/invoice/src/mutations/prescription/update.rs
  server/graphql/types/src/types/name.rs
  server/repository/src/db_diesel/name.rs
  server/service/src/invoice/prescription/insert/mod.rs
  server/service/src/invoice/prescription/insert/validate.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/invoice/prescription/update/validate.rs
  server/service/src/name/query.rs
  server/service/src/validate.rs
Labels: Priority: Should have, refactor, Team Ruru 🦉

#4396 3882 transfer report related store pref data to om supply
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.graphql
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/reports.json
  client/packages/common/src/intl/locales/index.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
  client/packages/host/package.json
  client/packages/host/src/Site.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/routers/ReportsRouter.tsx
  client/packages/host/src/routers/index.ts
  client/packages/reports/README.md
  client/packages/reports/package.json
  client/packages/reports/src/Components/AppBarButton.tsx
  client/packages/reports/src/Components/ListView.tsx
  client/packages/reports/src/Components/SidePanel.tsx
  client/packages/reports/src/Components/index.ts
  client/packages/reports/src/ReportService.tsx
  client/packages/reports/src/index.ts
  client/packages/reports/tsconfig.json
  server/graphql/types/src/types/store_preference.rs
  server/repository/src/db_diesel/store_preference_row.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/repository/src/migrations/v2_02_00/store_preferences_for_reports.rs
  server/service/src/sync/sync_serde.rs
  server/service/src/sync/test/pull_and_push.rs
  server/service/src/sync/test/test_data/store_preference.rs
  server/service/src/sync/translations/store_preference.rs
Labels: enhancement, Team Ruru 🦉, docs: external, feature: reports

#4406 4356 map demographic data to correct columns
  client/packages/system/src/IndicatorsDemographics/DetailView/utils.tsx
Labels: bug, Team Piwakawaka, Severity: High, feature: GAPS

#4428 Show the target demographic
  client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureLog/TemperatureLogList.tsx
  client/packages/coldchain/src/Sensor/ListView/ListView.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
  client/packages/system/src/Immunisation/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
Labels: bug, Severity: Normal, feature: GAPS

#4427 Save the replacement date of an imported equipment item
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
Labels: bug, Severity: Normal, feature: GAPS

#4400 3873 warn only when plugin dir missing
  server/service/src/plugin/plugin_files.rs
Labels: bug, Priority: Nice to Have, feature: plugin

#4389 4180 customer requisition doesn’t accept the decimal values that came form msupply sites via internal orders and remote auth
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/system/src/Item/Components/PackVariant/PackVariantQuantityCell.tsx
Labels: Team Ruru 🦉, Severity: High

#4403 4365 the decimal will get too long in outbound shipments
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/common/src/utils/numbers/NumUtils.test.ts
  client/packages/common/src/utils/numbers/NumUtils.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Returns/InboundDetailView/columns.ts
  client/packages/invoices/src/Returns/OutboundDetailView/columns.ts
  client/packages/system/src/Item/Components/PackVariant/PackVariantQuantityCell.tsx
  client/packages/system/src/Item/ListView/ListView.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#4404 4401 reports display available report in report menu
  client/packages/common/src/intl/locales/en/reports.json
  client/packages/common/src/ui/icons/Bar.tsx
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/ui/icons/TrendingDown.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/reports/src/Components/ListView.tsx
  client/packages/reports/src/ListView/AppBarButton.tsx
  client/packages/reports/src/ListView/ListView.tsx
  client/packages/reports/src/ListView/SidePanel.tsx
  client/packages/reports/src/ListView/index.ts
  client/packages/reports/src/ReportService.tsx
  client/packages/reports/src/components/ReportWidget.tsx
  client/packages/reports/src/components/index.ts
  server/graphql/reports/src/reports.rs
  server/repository/src/db_diesel/report_row.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/repository/src/migrations/v2_02_00/report_add_report_context.rs
  server/service/src/sync/translations/report.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#4426 4408 create rnr list view (PT 1)
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/programs.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/config/src/routes.ts
  client/packages/host/src/components/Navigation/ProgramsNav.tsx
  client/packages/host/src/routers/ProgramRouter.tsx
  client/packages/host/src/routers/index.ts
  client/packages/programs/src/ImmunisationProgramDetailView/AppBarButtons.tsx
  client/packages/programs/src/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/programs/src/ImmunisationProgramDetailView/Toolbar.tsx
  client/packages/programs/src/ImmunisationProgramDetailView/index.ts
  client/packages/programs/src/ImmunisationProgramListView/AppBarButtons.tsx
  client/packages/programs/src/ImmunisationProgramListView/ImmunisationProgramCreateModal.tsx
  client/packages/programs/src/ImmunisationProgramListView/ListView.tsx
  client/packages/programs/src/ImmunisationProgramListView/Toolbar.tsx
  client/packages/programs/src/ImmunisationProgramListView/index.ts
  client/packages/programs/src/RnRForms/ListView/AppBarButtons.tsx
  client/packages/programs/src/RnRForms/ListView/ListView.tsx
  client/packages/programs/src/RnRForms/ListView/Toolbar.tsx
  client/packages/programs/src/RnRForms/ListView/index.ts
  client/packages/programs/src/RnRForms/index.ts
  client/packages/programs/src/Service/Service.tsx
  client/packages/programs/src/Service/index.ts
  client/packages/programs/src/VaccineCourseEditModal/DescriptionColumn.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseItemSelect.tsx
  client/packages/programs/src/VaccineCourseEditModal/index.ts
  client/packages/programs/src/api/hooks/index.ts
  client/packages/programs/src/api/hooks/keys.ts
  client/packages/programs/src/api/hooks/types.ts
  client/packages/programs/src/api/hooks/useDeleteSelectedImmunisationPrograms.ts
  client/packages/programs/src/api/hooks/useDeleteSelectedVaccineCourses.ts
  client/packages/programs/src/api/hooks/useImmunisationProgram.ts
  client/packages/programs/src/api/hooks/useImmunisationProgramList.ts
  client/packages/programs/src/api/hooks/useRnRFormList.ts
  client/packages/programs/src/api/hooks/useVaccineCourse.ts
  client/packages/programs/src/api/hooks/useVaccineCourseList.ts
  client/packages/programs/src/api/index.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/programs/src/api/useProgramsGraphQL.ts
  client/packages/programs/src/index.ts
  client/packages/system/src/Immunisation/api/hooks/index.ts
  client/packages/system/src/Immunisation/api/index.ts
  client/packages/system/src/Immunisation/api/operations.generated.ts
  client/packages/system/src/Immunisation/api/operations.graphql
  client/packages/system/src/Immunisation/index.ts
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/queries/mod.rs
  server/graphql/programs/src/queries/r_and_r_form.rs
  server/graphql/programs/src/types/mod.rs
  server/graphql/programs/src/types/r_and_r_form.rs
  server/graphql/types/src/types/program/mod.rs
  server/graphql/types/src/types/program/rnr_form.rs
Labels: enhancement, Team Piwakawaka, feature: R&R

#4432 4408 create rnr list view pt2
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/RnRForms/ListView/ListView.tsx
  client/packages/programs/src/RnRForms/ListView/Toolbar.tsx
  client/packages/programs/src/api/hooks/useRnRFormList.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  server/graphql/programs/src/queries/r_and_r_form.rs
  server/graphql/programs/src/types/r_and_r_form.rs
  server/graphql/types/src/types/permissions.rs
  server/graphql/types/src/types/program/rnr_form.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/rnr_form.rs
  server/repository/src/db_diesel/rnr_form_row.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/repository/src/migrations/v2_02_00/rnr_form.rs
  server/service/src/auth.rs
  server/service/src/lib.rs
  server/service/src/login.rs
  server/service/src/rnr_form/mod.rs
  server/service/src/rnr_form/query.rs
  server/service/src/service_provider.rs
Labels: enhancement, Team Piwakawaka, feature: R&R

#4442 4441 use store pref amc
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Report/components/ReportArgumentsModal.tsx
  server/graphql/core/src/loader/item_stats.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/item_stats.rs
  server/graphql/types/src/types/requisition_line.rs
  server/service/src/item_stats.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#4431 4430 report builder helpers
  client/packages/common/src/hooks/useQueryParams/useQueryParamsStore.tsx
  client/packages/common/src/hooks/useUrlQuery/useUrlQuery.ts
  client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
  client/packages/common/src/types/schema.ts
  client/packages/reports/src/DetailView/AppBarButton.tsx
  client/packages/reports/src/DetailView/DetailView.tsx
  client/packages/reports/src/components/ReportWidget.tsx
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Report/api/hooks/index.ts
  client/packages/system/src/Report/api/hooks/useDisplayReport.ts
  client/packages/system/src/Report/api/hooks/useGenerateReport.ts
  client/packages/system/src/Report/api/hooks/usePrintReport.ts
  client/packages/system/src/Report/api/hooks/useReportStore.ts
  client/packages/system/src/Report/api/operations.generated.ts
  client/packages/system/src/Report/api/operations.graphql
  client/packages/system/src/Report/components/ReportArgumentsModal.tsx
  server/Cargo.lock
  server/cli/src/cli.rs
  server/graphql/core/src/loader/item_stats.rs
  server/graphql/reports/src/lib.rs
  server/graphql/reports/src/print.rs
  server/graphql/tests/permissions.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/item_stats.rs
  server/graphql/types/src/types/requisition_line.rs
  server/report_builder/src/cli.rs
  server/report_builder/src/lib.rs
  server/report_builder/src/print.rs
  server/repository/Cargo.toml
  server/repository/src/db_diesel/form_schema_row.rs
  server/repository/src/db_diesel/report_row.rs
  server/service/src/item_stats.rs
  server/service/src/report/report_service.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#4446 4412 generate blank rows
  server/cli/src/refresh_dates.rs
  server/graphql/programs/src/mutations/rnr_form/insert.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/item_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/rnr_form_line_row.rs
  server/repository/src/migrations/v2_02_00/item_ven.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/repository/src/migrations/v2_02_00/rnr_form.rs
  server/repository/src/mock/full_master_list.rs
  server/repository/src/mock/program.rs
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/insert.rs
  server/service/src/rnr_form/mod.rs
  server/service/src/rnr_form/tests/insert.rs
  server/service/src/rnr_form/validate.rs
  server/service/src/sync/test/test_data/item.rs
  server/service/src/sync/translations/item.rs
Labels: enhancement, Team Piwakawaka, feature: R&R

#4445 4444 Move dispensary reports
  client/packages/common/src/styles/theme.ts
  client/packages/host/src/components/Navigation/DispensaryNav.tsx
  client/packages/host/src/routers/DispensaryRouter.tsx
  client/packages/reports/src/DetailView/DetailView.tsx
  client/packages/reports/src/ListView/ListView.tsx
  client/packages/reports/src/components/ReportWidget.tsx
  client/packages/system/src/Report/ListView/ListView.tsx
  client/packages/system/src/Report/ListView/Toolbar.tsx
  client/packages/system/src/Report/ListView/index.ts
  client/packages/system/src/Report/Service/Service.tsx
  client/packages/system/src/Report/Service/index.ts
  client/packages/system/src/Report/api/hooks/useReport.ts
  client/packages/system/src/Report/index.ts
Labels: enhancement, Team Ruru 🦉, feature: reports

#4452 4451 Print button for report detail view
  client/packages/reports/src/DetailView/AppBarButton.tsx
  client/packages/reports/src/DetailView/DetailView.tsx
Labels: enhancement, Team Ruru 🦉, feature: reports

#4453 4412 populate rows
  server/graphql/programs/src/mutations/rnr_form/insert.rs
  server/repository/src/db_diesel/adjustment.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/replenishment.rs
  server/repository/src/migrations/v2_02_00/consumption_and_replenishment_views.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/repository/src/mock/full_master_list.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/period_and_period_schedule.rs
  server/repository/src/mock/rnr_form.rs
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/insert.rs
  server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/insert.rs
  server/service/src/rnr_form/tests/mod.rs
  server/service/src/rnr_form/tests/schedules_with_periods.rs
  server/service/src/rnr_form/validate.rs
Labels: enhancement, Team Piwakawaka, feature: R&R

#4456 4414 editing/saving R&R progress
  client/packages/common/src/types/schema.ts
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/mutations/rnr_form/mod.rs
  server/graphql/programs/src/mutations/rnr_form/update.rs
  server/graphql/types/src/types/activity_log.rs
  server/graphql/types/src/types/program/rnr_form_line.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/rnr_form_line_row.rs
  server/repository/src/migrations/v2_02_00/rnr_form.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/rnr_form.rs
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/mod.rs
  server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/insert.rs
  server/service/src/rnr_form/tests/mod.rs
  server/service/src/rnr_form/tests/update.rs
  server/service/src/rnr_form/update.rs
Labels: enhancement, Team Piwakawaka, feature: R&R

#4461 4417 finalise R&R
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/RnRForms/DetailView/AppBarButtons.tsx
  client/packages/programs/src/RnRForms/DetailView/DetailView.tsx
  client/packages/programs/src/RnRForms/DetailView/Footer.tsx
  client/packages/programs/src/api/hooks/useRnRForm.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/mutations/rnr_form/finalise.rs
  server/graphql/programs/src/mutations/rnr_form/mod.rs
  server/graphql/types/src/types/activity_log.rs
  server/graphql/types/src/types/program/rnr_form.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/migrations/v2_02_00/rnr_form.rs
  server/service/src/rnr_form/finalise.rs
  server/service/src/rnr_form/mod.rs
  server/service/src/rnr_form/tests/finalise.rs
  server/service/src/rnr_form/tests/mod.rs
  server/service/src/rnr_form/tests/update.rs
Labels: enhancement, Team Piwakawaka, feature: R&R

#4467 Include source site id sync buffer rows after v6 push to OMS Central
  server/service/src/sync/api/common_records.rs
  server/service/src/sync/central_data_synchroniser.rs
  server/service/src/sync/central_data_synchroniser_v6.rs
  server/service/src/sync/remote_data_synchroniser.rs
  server/service/src/sync/sync_on_central/mod.rs
Labels: bug, needs triage, Severity: High, needs daily triage

#4469 4466-integration-test-for-remote-omsupply-data
  server/service/src/sync/test/integration/README.md
  server/service/src/sync/test/integration/central/unit_and_item.rs
  server/service/src/sync/test/integration/omsupply_central/asset.rs
  server/service/src/sync/test/integration/omsupply_central/mod.rs
  server/service/src/sync/test/integration/omsupply_central/test.rs
  server/service/src/sync/test/integration/transfer/mod.rs
  server/service/src/sync/test/integration/transfer/requisition.rs
  server/service/src/sync/test/integration/transfer/returns.rs
  server/service/src/sync/test/integration/transfer/shipments.rs
Labels: bug, needs triage, Severity: High, needs daily triage

#4474 Improve sync messaging
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/common/src/types/schema.ts
  client/packages/host/src/components/Sync/Sync.tsx
  client/packages/system/src/Sync/api/operations.generated.ts
  client/packages/system/src/Sync/api/operations.graphql
  server/graphql/general/src/queries/sync_status.rs
  server/repository/src/db_diesel/sync_log_row.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/repository/src/migrations/v2_02_00/sync.rs
  server/service/src/sync/sync_status/logger.rs
  server/service/src/sync/sync_status/status.rs
  server/service/src/sync/sync_status/test.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
Labels: enhancement, Priority: Should have, make omSupply delightful, Team Piwakawaka

#4478 Remove 1.2 Migration Warning
  server/repository/src/migrations/v1_06_00/is_sync_update.rs
Labels: bug, refactor, Team Piwakawaka
