Repository msupply-foundation/open-msupply, pull requests merged in 2024-08, with the labels that each got.

#4473 4411 detail view edit
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/programs.json
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/RnRForms/DetailView/ContentArea.tsx
  client/packages/programs/src/RnRForms/DetailView/DetailView.tsx
  client/packages/programs/src/RnRForms/DetailView/Footer.tsx
  client/packages/programs/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/programs/src/api/hooks/useRnRForm.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/Item/api/operations.generated.ts
  server/graphql/programs/src/mutations/rnr_form/update.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/program/rnr_form.rs
  server/graphql/types/src/types/program/rnr_form_line.rs
  server/repository/src/db_diesel/rnr_form_line_row.rs
  server/repository/src/migrations/v2_02_00/rnr_form.rs
  server/service/src/rnr_form/finalise.rs
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/mod.rs
  server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/update.rs
  server/service/src/rnr_form/update.rs
  server/service/src/rnr_form/validate.rs
Labels: enhancement, Team Piwakawaka, feature: R&R

#4477 4417 create internal order on rr form submit
  server/repository/src/db_diesel/item_row.rs
  server/service/src/rnr_form/finalise.rs
  server/service/src/rnr_form/tests/finalise.rs
Labels: enhancement, Team Piwakawaka, feature: R&R

#4479 Add min/max for excursions
  server/service/src/cold_chain/query_temperature_breach.rs
Labels: bug, feature: coldchain, Team Piwakawaka, Severity: Normal

#4454 #3098 Excel from html
  cspell.json
  server/Cargo.lock
  server/docs/content/docs/api/patterns.md
  server/graphql/reports/src/lib.rs
  server/report_builder/src/lib.rs
  server/service/Cargo.toml
  server/service/src/report/report_service.rs
Labels: Team Ruru 🦉, feature: reports

#4487 filter report contexts for r&r forms
  client/packages/programs/src/RnRForms/DetailView/AppBarButtons.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/system/src/Report/api/hooks/useReportList.ts
  client/packages/system/src/Report/components/ReportSelector.tsx
Labels: enhancement, Team Piwakawaka, feature: R&R

#4483 Reports - fix infinite re-render
  client/packages/system/src/Report/components/ReportArgumentsModal.tsx
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#4486 4459 Export report to Excel button
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/files/FileUtils.ts
  client/packages/reports/src/DetailView/AppBarButton.tsx
  client/packages/reports/src/DetailView/DetailView.tsx
  client/packages/system/src/Report/api/hooks/useGenerateReport.ts
  client/packages/system/src/Report/api/hooks/usePrintReport.ts
Labels: Team Ruru 🦉, feature: reports

#4489 Fix opening balance for first R&R Form when stock is reserved.
  server/repository/src/db_diesel/stock_on_hand.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/repository/src/migrations/v2_02_00/stock_on_hand_add_total_stock.rs
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/finalise.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
Labels: bug, Team Piwakawaka, feature: R&R

#4495 4161 relocate gender input
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
  client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
  client/packages/system/src/Patient/PatientView/PatientSummary.tsx
  server/graphql/programs/src/mutations/patient/insert.rs
  server/graphql/programs/src/mutations/patient/update.rs
  server/graphql/programs/src/queries/patient_search.rs
  server/graphql/types/src/types/clinician.rs
  server/graphql/types/src/types/name.rs
  server/graphql/types/src/types/program/contact_trace.rs
  server/graphql/types/src/types/program/patient.rs
Labels: Team Ruru 🦉

#4500 4480 default R&R options
  client/packages/common/src/intl/locales/en/programs.json
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/RnRForms/ListView/ListView.tsx
  client/packages/programs/src/RnRForms/ListView/ProgramSearchInput.tsx
  client/packages/programs/src/RnRForms/ListView/RnRFormCreateModal.tsx
  client/packages/programs/src/api/hooks/useCreateRnRForm.ts
  client/packages/programs/src/api/hooks/useRnRFormList.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  server/graphql/programs/src/types/r_and_r_form.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/program/rnr_form.rs
  server/repository/src/mock/rnr_form.rs
  server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/insert.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
Labels: bug, Team Piwakawaka, feature: R&R

#4490 Allow settings to be reset
  client/packages/host/src/components/Login/Login.tsx
  server/graphql/general/src/queries/display_settings.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
Labels: bug, Team Piwakawaka, Severity: Normal

#4498 4497 Report args modal backdrop blackening
  client/packages/reports/src/DetailView/DetailView.tsx
  client/packages/reports/src/ListView/ListView.tsx
  client/packages/reports/src/components/ReportWidget.tsx
  client/packages/system/src/Report/components/ReportArgumentsModal.tsx
  client/packages/system/src/Report/components/ReportSelector.tsx
Labels: bug, Team Ruru 🦉, feature: reports

#4505 4386 Hide program related columns in Requisition
  client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
Labels: enhancement, Priority: Nice to Have, make omSupply delightful

#4491 #3641 Show age in months/days for <1
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
Labels: enhancement, Priority: Must Have, Team Ruru 🦉, feature: dispensing

#4507 allow export of R&R form to excel
  client/packages/programs/src/RnRForms/DetailView/AppBarButtons.tsx
  client/packages/system/src/Report/api/hooks/usePrintReport.ts
Labels: enhancement, Team Piwakawaka, feature: R&R

#4508 4502 rnr requested quantity not saving
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/programs/src/api/hooks/useRnRForm.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  server/graphql/programs/src/mutations/rnr_form/update.rs
  server/graphql/types/src/types/program/rnr_form_line.rs
  server/repository/src/db_diesel/rnr_form_line_row.rs
  server/repository/src/migrations/v2_02_00/rnr_form.rs
  server/service/src/rnr_form/finalise.rs
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/update.rs
  server/service/src/rnr_form/update.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
Labels: bug, Team Piwakawaka, Severity: High, feature: R&R

#4511 Set R&R line stock out duration to 0 if no transactions
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
Labels: bug, Team Piwakawaka, feature: R&R

#4493 4492 fix some warnings
  server/repository/src/migrations/templates/add_data_from_sync_buffer/mod.rs
  server/repository/src/migrations/templates/adding_table/mod.rs
  server/repository/src/migrations/templates/data_and_schema/mod.rs
  server/repository/src/migrations/templates/data_migration/mod.rs
  server/server/src/main.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
Labels: bug, Team Piwakawaka

#4512 Fix initial R&R AMC calculations for frontend
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/RnRForms/DetailView/ContentArea.tsx
  client/packages/programs/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/programs/src/RnRForms/DetailView/getAmc.test.ts
  client/packages/programs/src/RnRForms/DetailView/getAmc.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  server/graphql/types/src/types/program/rnr_form_line.rs
  server/repository/src/db_diesel/rnr_form_line_row.rs
  server/repository/src/migrations/v2_02_00/rnr_form.rs
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/update.rs
  server/service/src/rnr_form/update.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
Labels: bug, Team Piwakawaka, feature: R&R

#4515 4510 add status to rn r form
  client/packages/host/src/components/Navigation/ProgramsNav.tsx
  client/packages/programs/src/RnRForms/ListView/ListView.tsx
  client/packages/programs/src/utils.ts
Labels: enhancement, Team Piwakawaka, feature: R&R

#4521 Change postgres type for name row type enum
  server/repository/src/db_diesel/name_row.rs
Labels: bug, needs triage, needs daily triage

#4518 Add header tooltips
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/programs.json
  client/packages/programs/src/RnRForms/DetailView/ContentArea.tsx
Labels: enhancement, Team Piwakawaka, feature: R&R

#4522 Move the RNR forms to Replenishment menu
  client/packages/common/src/intl/locales/en/programs.json
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/common/src/intl/locales/ru/programs.json
  client/packages/common/src/intl/locales/ru/replenishment.json
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/components/Navigation/ProgramsNav.tsx
  client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
  client/packages/host/src/routers/ReplenishmentRouter.tsx
  client/packages/programs/src/Components/ProgramSearchInput.tsx
  client/packages/programs/src/Components/index.ts
  client/packages/programs/src/Service/Service.tsx
  client/packages/programs/src/api/hooks/index.ts
  client/packages/programs/src/api/hooks/keys.ts
  client/packages/programs/src/api/index.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/programs/src/utils.ts
  client/packages/requisitions/src/RequisitionService.tsx
  client/packages/requisitions/src/RnRForms/DetailView/AppBarButtons.tsx
  client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
  client/packages/requisitions/src/RnRForms/DetailView/DetailView.tsx
  client/packages/requisitions/src/RnRForms/DetailView/Footer.tsx
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/requisitions/src/RnRForms/DetailView/getAmc.test.ts
  client/packages/requisitions/src/RnRForms/DetailView/getAmc.ts
  client/packages/requisitions/src/RnRForms/DetailView/index.ts
  client/packages/requisitions/src/RnRForms/ListView/AppBarButtons.tsx
  client/packages/requisitions/src/RnRForms/ListView/ListView.tsx
  client/packages/requisitions/src/RnRForms/ListView/RnRFormCreateModal.tsx
  client/packages/requisitions/src/RnRForms/ListView/Toolbar.tsx
  client/packages/requisitions/src/RnRForms/ListView/index.ts
  client/packages/requisitions/src/RnRForms/api/hooks/index.ts
  client/packages/requisitions/src/RnRForms/api/hooks/keys.ts
  client/packages/requisitions/src/RnRForms/api/hooks/useCreateRnRForm.ts
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormList.ts
  client/packages/requisitions/src/RnRForms/api/hooks/useSchedulesAndPeriods.ts
  client/packages/requisitions/src/RnRForms/api/index.ts
  client/packages/requisitions/src/RnRForms/api/operations.generated.ts
  client/packages/requisitions/src/RnRForms/api/operations.graphql
  client/packages/requisitions/src/RnRForms/api/useRnRGraphQL.ts
  client/packages/requisitions/src/RnRForms/index.ts
  client/packages/requisitions/src/RnRForms/utils.ts
Labels: enhancement, feature: R&R

#4529 4349 Replenishment -> Inbound Shipment: Locations are not shown properly when the view is grouped by item
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
Labels: bug, Team Ruru 🦉, Severity: Low

#4537 Check for undefined value in NumberCell
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx
Labels: bug, Severity: Hotfix

#4523 Add useDebounce option to text input
  client/packages/programs/src/JsonForms/common/components/Text.tsx
Labels: bug, Team Ruru 🦉, feature: reports

#4530 4506 Reports page is blank if the reports aren't configured
  client/packages/common/src/intl/locales/en/reports.json
  client/packages/reports/src/ListView/ListView.tsx
Labels: bug, Team Ruru 🦉

#4551 4531 fix client build
  client/packages/electron/package.json
  client/packages/electron/src/electron.ts
  client/packages/electron/webpack.main.config.ts
  client/yarn.lock
  package.json
Labels: bug, platform: desktop, Severity: Hotfix

#4550 4534 additional columns
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/icons/Alert.tsx
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/host/src/routers/ReplenishmentRouter.tsx
  client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/requisitions/src/RnRForms/DetailView/getAmc.test.ts
  client/packages/requisitions/src/RnRForms/DetailView/helpers.test.ts
  client/packages/requisitions/src/RnRForms/DetailView/helpers.ts
  client/packages/requisitions/src/RnRForms/ListView/RnRFormCreateModal.tsx
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts
  client/packages/requisitions/src/RnRForms/api/operations.generated.ts
  client/packages/requisitions/src/RnRForms/api/operations.graphql
  server/graphql/programs/src/mutations/rnr_form/update.rs
  server/graphql/types/src/types/program/rnr_form_line.rs
  server/repository/src/db_diesel/rnr_form_line_row.rs
  server/repository/src/migrations/v2_02_00/rnr_form.rs
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/update.rs
  server/service/src/rnr_form/update.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
Labels: enhancement, Team Piwakawaka, docs: external, feature: R&R

#4552 4394 view service charges in more detail such as the types of service charged
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx
Labels: enhancement, Priority: Nice to Have, Migrate Existing Desktop, Team Ruru 🦉

#4556 Reports UI
  client/packages/host/src/CommandK.tsx
  client/packages/reports/src/DetailView/DetailView.tsx
Labels: bug, Priority: Must Have, feature: reports

#4554 3910 Post migration from desktop, previous 'sg' stocktakes have missing lines
  server/service/src/sync/translations/stocktake_line.rs
Labels: bug, Migrate Existing Desktop, Team Tauhou, Severity: High, Needs refinement

#4533 4476 rnr dirty state
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
  client/packages/requisitions/src/RnRForms/DetailView/DetailView.tsx
  client/packages/requisitions/src/RnRForms/DetailView/Footer.tsx
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/requisitions/src/RnRForms/ListView/ListView.tsx
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts
Labels: enhancement, Team Piwakawaka, feature: R&R

#4557 4514 Export to excel crashes server with DEBUG log level
  server/Cargo.lock
  server/service/Cargo.toml
  server/service/src/report/report_service.rs
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#4519 Ability to migrate with fragments
  server/repository/src/db_diesel/migration_fragment_log.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/README.md
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_02_00/add_low_stock_and_requisition_line_id.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/repository/src/migrations/v2_02_00/rnr_form.rs
  server/repository/src/migrations/version.rs
Labels: enhancement, needs architecture/solution

#4573 4555 fix "Unexpected Null" error on Internal Orders page
  server/cli/src/refresh_dates.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/repository/src/migrations/v2_02_00/requisitions_in_period.rs
Labels: bug, Team Piwakawaka, Severity: Hotfix, feature: R&R

#3846 3830 report manifest file
  server/report_builder/README.md
  server/report_builder/example/manifest.json
  server/report_builder/example/template.html
  server/report_builder/src/build.rs
  server/report_builder/src/cli.rs
  server/report_builder/src/lib.rs
  server/report_builder/src/print.rs
  server/repository/src/db_diesel/report_row.rs
  server/service/src/report/definition.rs
  server/service/src/report/report_service.rs
Labels: enhancement, Team Tauhou

#4599 4471 Equipment list not showing properly when reloading the page in browser
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
Labels: bug, Team Ruru 🦉, Severity: Low, feature: CCEI

#4593 4590 Disable export button on Android
  client/packages/reports/src/DetailView/AppBarButton.tsx
Labels: bug, Team Ruru 🦉, feature: reports

#4581 4499 expiring items report UI review
  client/packages/common/src/intl/locales/en/reports.json
  client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
  client/packages/programs/src/JsonForms/common/JsonForm.tsx
  client/packages/programs/src/JsonForms/common/components/Date.tsx
  client/packages/programs/src/JsonForms/common/components/Number.tsx
  client/packages/programs/src/JsonForms/common/components/Text.tsx
  client/packages/system/src/Report/components/ReportArgumentsModal.tsx
Labels: bug, Team Ruru 🦉, feature: reports

#4570 4534 map requisition approved quantities
  client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
  server/graphql/core/src/loader/rnr_form_line.rs
  server/graphql/types/src/types/activity_log.rs
  server/graphql/types/src/types/program/rnr_form_line.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/requisition/requisition_row.rs
  server/repository/src/db_diesel/requisition_line/requisition_line_row.rs
  server/repository/src/db_diesel/rnr_form_line.rs
  server/repository/src/db_diesel/rnr_form_line_row.rs
  server/repository/src/migrations/v2_02_00/add_requisition_approved_activity_type.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/repository/src/migrations/v2_02_00/rnr_form.rs
  server/service/src/processors/transfer/requisition/mod.rs
  server/service/src/processors/transfer/requisition/test.rs
  server/service/src/processors/transfer/requisition/update_request_requisition_approved_quantities.rs
  server/service/src/rnr_form/finalise.rs
  server/service/src/rnr_form/tests/finalise.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/rnr_form.rs
  server/service/src/sync/translations/rnr_form_line.rs
Labels: enhancement, Team Piwakawaka, feature: R&R

#4594 4587 basic reports error shows eternal loading indicator
  client/packages/common/src/intl/locales/en/reports.json
  client/packages/reports/src/DetailView/DetailView.tsx
  client/packages/system/src/Report/api/hooks/useGenerateReport.ts
Labels: bug, feature: reports

#4517 #4224 Drop and recreate Views
  package.json
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/repository/src/migrations/views/mod.rs
Labels: enhancement, Team Piwakawaka, feature: R&R

#4607 R&R Form performance
  client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
  client/packages/requisitions/src/RnRForms/DetailView/DetailView.tsx
  client/packages/requisitions/src/RnRForms/DetailView/Footer.tsx
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts
Labels: bug, Team Piwakawaka, feature: R&R

#4606 Round numbers when displayed in R&R forms
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
Labels: enhancement, Team Piwakawaka, feature: R&R

#4615 4614 update v6 sync version
  server/service/src/sync/settings.rs
  server/service/src/sync/sync_on_central/mod.rs
Labels: enhancement, Team Piwakawaka, docs: external, feature: R&R

#4612 4596 fix R&R form line reference columns
  server/graphql/types/src/types/program/rnr_form_line.rs
  server/repository/src/db_diesel/rnr_form_line.rs
  server/repository/src/db_diesel/rnr_form_line_row.rs
  server/repository/src/migrations/v2_02_00/fix_rnr_form_line_columns.rs
  server/repository/src/migrations/v2_02_00/mod.rs
  server/repository/src/mock/rnr_form.rs
  server/service/src/rnr_form/finalise.rs
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/insert.rs
  server/service/src/rnr_form/tests/update.rs
  server/service/src/rnr_form/update.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
Labels: bug, Team Piwakawaka, feature: R&R

#4609 4541 trying to increase the issue quan in prescription window shows wrong available(packs) and thus can't increase the quan despite the stocks available
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/hooks/useDraftPrescriptionLines.tsx
Labels: bug, Severity: Hotfix

#4613 4574 No need to show 0 lines (deleted lines + issued-out lines) in exported list under View Stocks
  client/packages/common/src/intl/locales/es/distribution.json
  client/packages/common/src/intl/locales/es/replenishment.json
  client/packages/common/src/intl/locales/fr/app.json
  client/packages/common/src/intl/locales/fr/catalogue.json
  client/packages/common/src/intl/locales/fr/coldchain.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/fr/distribution.json
  client/packages/common/src/intl/locales/fr/inventory.json
  client/packages/common/src/intl/locales/fr/plugin.json
  client/packages/common/src/intl/locales/fr/replenishment.json
  client/packages/system/src/Stock/api/hooks/useExportStockList.ts
  package.json
Labels: bug, Team Ruru 🦉, Severity: Normal

#4618 4380 fix contact trace page crashing
  client/packages/system/src/ContactTrace/DetailView/DetailView.tsx
Labels: bug, feature: programs, Team Piwakawaka, Severity: High

#4611 4604 Fix R&R forms not being pulled on initialisation
  server/repository/src/db_diesel/rnr_form_line_row.rs
  server/repository/src/db_diesel/rnr_form_row.rs
Labels: bug, Team Piwakawaka, Severity: High, feature: R&R

#4617 Adjust translation namespace calls
  client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/InboundDetailView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/AppBarButtons.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/RequestRequisition/api/hooks/utils/useAddFromMasterList.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/RnRForms/DetailView/AppBarButtons.tsx
  client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
Labels: bug, Severity: Hotfix, HUNCHY FUNCHY

#4624 4578 Catalogue -> Master List Lines: Code sorting does not work
  client/packages/system/src/MasterList/DetailView/ContentArea.tsx
  client/packages/system/src/MasterList/api/api.ts
Labels: bug, Team Ruru 🦉, Severity: Low

#4626 4437 Add some helpful message under 'Master List' tab of item details window for invisible items
  client/packages/common/src/intl/locales/en/catalogue.json
  client/packages/system/src/Item/DetailView/Tabs/MasterLists.tsx
Labels: bug, Team Ruru 🦉, Severity: Low, docs: external

#4625 4567 Catalogue -> Assets -> the count does not update when deleting assets
  server/repository/src/db_diesel/assets/asset_catalogue_item.rs
Labels: bug, Team Ruru 🦉, Severity: Low

#4619 4559 Total/Available SoH number looks wrong after stocktake for existing lines whose packsize is greater than 1
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#4549 Add test connection binary
  build/windows/omsupply-build.bat
  build/windows/omsupply_server.suf
  server/Cargo.lock
  server/Cargo.toml
  server/cli/Cargo.toml
  server/cli/src/assets/check_outline.png
  server/cli/src/assets/error_circle.png
  server/cli/src/assets/error_outline.png
  server/cli/src/assets/help_outline.png
  server/cli/src/test_connection.rs
  server/service/src/sync/api_v6/core.rs
Labels: enhancement, Tooling

#4632 Add fallback to loading indicator for lazy loads
  client/packages/common/src/ui/layout/skeletons/DetailFormSkeleton.tsx
  client/packages/host/src/Site.tsx
Labels: bug, Team Piwakawaka, Severity: High

#4627 3936 you can finalise a stocktake with only placeholder lines
  client/packages/common/src/intl/locales/en/common.json
  client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx
Labels: bug, Team Ruru 🦉, Severity: Low

#4645 #3641 (2) Fix default patient schema DOB component
  client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
Labels: enhancement, Priority: Must Have, Build Tested: Issues Found, Team Ruru 🦉, feature: dispensing, Tester: Taina

#4643 Populate internal order sent date
  server/service/src/rnr_form/finalise.rs
Labels: bug, Priority: Must Have, Team Piwakawaka, feature: R&R

#4631 4588 Extend pagination on stock lines for reports
  server/service/src/stock_line/query.rs
Labels: bug, Team Ruru 🦉, Severity: Hotfix, Severity: High, feature: reports

#4640 4429 Remove column sorting on ledger
  client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
Labels: bug, Priority: Should have, Team Ruru 🦉

#4637 4601 Expiry dates are not readable in the issue stock window
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#4638 4365 The Decimal will get too long in outbound shipments
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditTable.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#4630 Remove seconds from DatePicker UI
  client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
Labels: bug

#4649 1633 disable actions if invoice/requisition is uneditable
  client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/Toolbar.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/ToolbarActions.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/ToolbarDropDown.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar.tsx
Labels: enhancement, Priority: Nice to Have

#3924 3717 om supply central backup kdd
  decisions/central server backup.md
Labels: enhancement, Priority: Must Have, Team Ruru 🦉

#4636 4592 Add store id to item visibility stock on hand filter
  server/repository/src/db_diesel/item.rs
Labels: bug, Severity: Hotfix

#4651 4647 GAPS: Store Properties are saved but doesn't show up
  client/packages/system/src/Name/ListView/Facilities/FacilityEditModal.tsx
  client/packages/system/src/Name/ListView/Facilities/ListView.tsx
Labels: bug, Team Ruru 🦉, feature: GAPS

#4659 #4233 Fix filter layout ordering
  client/packages/common/src/ui/components/inputs/Filters/FilterMenu.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#4671 4072 add 'invoice number' column to ledger view
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/graphql/general/src/queries/ledger.rs
  server/repository/src/db_diesel/ledger.rs
  server/repository/src/migrations/views/mod.rs
Labels: enhancement, Priority: Should have, Team Ruru 🦉, docs: external

#4670 3767 Cold Chain -> Equipment -> most useful filters not shown by default
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
Labels: enhancement, Priority: Should have, Team Ruru 🦉, feature: CCEI, docs: external

#4648 2389 Carry customer reference field through from requisition to outbound shipment
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
Labels: enhancement, needs architecture/solution, Priority: Nice to Have

#4667 3926 Scrollbar is not fixed in outbound & prescription window
  client/packages/invoices/src/Prescriptions/DetailView/ContentArea.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/ContentArea.tsx
Labels: bug, platform: desktop, Team Ruru 🦉, Severity: Low

#4693 Download excel report export via iframe
  client/packages/common/src/utils/files/FileUtils.ts
  client/packages/reports/src/DetailView/DetailView.tsx
Labels: bug, Team Ruru 🦉, Severity: Hotfix, feature: reports

#4674 4662 om supply backups
  server/Cargo.lock
  server/README.md
  server/android/src/android.rs
  server/cli/Cargo.toml
  server/cli/src/backup/README.md
  server/cli/src/backup/backup.rs
  server/cli/src/backup/mod.rs
  server/cli/src/backup/restore.rs
  server/cli/src/cli.rs
  server/cli/src/lib.rs
  server/configuration/example.yaml
  server/service/src/settings.rs
  server/service/src/test_helpers.rs
Labels: enhancement

#4692 3797 move internal order toolbar content to side panel
  client/packages/common/src/hooks/useDetailPanel/useDetailPanel.tsx
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/host/src/CommandK.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/OrderInfoSection.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/SidePanel.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
Labels: bug, platform: android, Severity: Hotfix, needs design

#4689 4687 hotfix populate changelog store ids
  package.json
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_02_01/add_store_ids_to_existing_rnr_form_changelogs.rs
  server/repository/src/migrations/v2_02_01/mod.rs
  server/repository/src/migrations/v2_03_00/mod.rs
Labels: bug, Severity: Hotfix, feature: R&R

#4695 4694 Enable gzip in reqwest
  server/Cargo.lock
  server/Cargo.toml
Labels: enhancement, sync v5, Severity: Hotfix

#4697 Add backup cleanup to backup script
  server/cli/src/backup/README.md
  server/cli/src/backup/backup.rs
  server/cli/src/backup/mod.rs
  server/cli/src/cli.rs
  server/configuration/example.yaml
  server/service/src/settings.rs
Labels: enhancement, Severity: Hotfix

#4639 4250 Status set as cancelled but pop up for save encountered as visited appears
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
Labels: bug, feature: programs, Team Ruru 🦉, Severity: High

#4666 1404 Add some logging to migrations
  server/Cargo.lock
  server/Cargo.toml
  server/android/Cargo.toml
  server/repository/src/migrations/mod.rs
  server/server/Cargo.toml
  server/server/src/main.rs
Labels: enhancement, Priority: Should have, Team Ruru 🦉

#4708 4652 remove immunisation program oms mutations
  client/packages/common/src/intl/locales/en/programs.json
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/programs/src/ImmunisationProgramDetailView/Toolbar.tsx
  client/packages/programs/src/ImmunisationProgramListView/AppBarButtons.tsx
  client/packages/programs/src/ImmunisationProgramListView/ImmunisationProgramCreateModal.tsx
  client/packages/programs/src/ImmunisationProgramListView/ListView.tsx
  client/packages/programs/src/ImmunisationProgramListView/Toolbar.tsx
  client/packages/programs/src/api/hooks/index.ts
  client/packages/programs/src/api/hooks/useDeleteSelectedImmunisationPrograms.ts
  client/packages/programs/src/api/hooks/useImmunisationProgram.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/mutations/immunisation/delete.rs
  server/graphql/programs/src/mutations/immunisation/insert.rs
  server/graphql/programs/src/mutations/immunisation/mod.rs
  server/graphql/programs/src/mutations/immunisation/update.rs
  server/repository/src/db_diesel/program_requisition/program.rs
  server/repository/src/db_diesel/program_requisition/program_row.rs
  server/repository/src/migrations/v2_03_00/drop_program_deleted_datetime.rs
  server/repository/src/migrations/v2_03_00/mod.rs
  server/repository/src/mock/program.rs
  server/service/src/program/delete_immunisation.rs
  server/service/src/program/insert_immunisation.rs
  server/service/src/program/mod.rs
  server/service/src/program/test/delete.rs
  server/service/src/program/test/insert.rs
  server/service/src/program/test/mod.rs
  server/service/src/program/test/query.rs
  server/service/src/program/update_immunisation.rs
  server/service/src/program/validate.rs
  server/service/src/stock_line/tests/query.rs
  server/service/src/sync/test/test_data/program_requisition_settings.rs
  server/service/src/sync/translations/program_requisition_settings.rs
Labels: Team Piwakawaka, feature: vaccine card
