Repository msupply-foundation/open-msupply, pull requests merged in 2024-05, with the labels that each got.

#3726 3563 Item id isn't being sent to query to display master lists in Item detail view
  client/packages/system/src/Item/DetailView/DetailView.tsx
Labels: bug, Team Tauhou, Severity: High

#3719 3684 pack variant feature flag
  client/packages/config/src/config.ts
  client/packages/host/webpack.config.js
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Returns/InboundDetailView/columns.ts
  client/packages/invoices/src/Returns/OutboundDetailView/columns.ts
  client/packages/invoices/src/Returns/modals/InboundReturn/ReturnQuantitiesTable.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/ReturnQuantitiesTable.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEditForm.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/system/src/Item/DetailView/DetailView.tsx
  client/packages/system/src/Item/context/usePackVariant.ts
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
  server/service/src/pack_variant/query.rs
Labels: enhancement, Priority: Must Have, Team Ruru 🦉, docs: external

#3701 Implement name soft deletes
  server/repository/src/db_diesel/name.rs
  server/repository/src/db_diesel/name_row.rs
  server/repository/src/db_diesel/patient.rs
  server/repository/src/migrations/v2_00_00/mod.rs
  server/repository/src/migrations/v2_00_00/name_created_datetime.rs
  server/service/src/programs/patient/patient_updated.rs
  server/service/src/sync/test/test_data/name.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/name.rs
  server/service/src/sync/translations/special/name_merge.rs
Labels: bug, Priority: Should have, feature: merging, Team Tauhou, Severity: Normal

#3639 #3499 Ledger back end query
  package.json
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/ledger.rs
  server/graphql/general/src/queries/mod.rs
  server/repository/src/db_diesel/ledger.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/stock_movement.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_01_00/ledger.rs
  server/repository/src/migrations/v2_01_00/mod.rs
  server/service/src/ledger.rs
  server/service/src/lib.rs
Labels: Team Ruru 🦉, feature: inventory adjustments

#3588 #3497 Stockline Ledger tab
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/en/inventory.json
  client/packages/common/src/types/schema.ts
  client/packages/host/src/components/Navigation/DispensaryNav.tsx
  client/packages/host/src/components/Navigation/DistributionNav.tsx
  client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
  client/packages/system/src/Stock/Components/Ledger/LedgerForm.tsx
  client/packages/system/src/Stock/Components/Ledger/index.ts
  client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
  client/packages/system/src/Stock/Components/StockLineEditModal.tsx
  client/packages/system/src/Stock/api/hooks/useStockLedger.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/service/src/invoice/inventory_adjustment/insert.rs
Labels: Team Ruru 🦉, feature: inventory adjustments, docs: external

#3732 advance v6 cursor from v6 synchroniser
  server/service/src/sync/central_data_synchroniser_v6.rs
  server/service/src/sync/remote_data_synchroniser.rs
  server/service/src/sync/synchroniser.rs
Labels: bug, Team Ruru 🦉, Severity: High

#3749 3475 restarting server and refreshing causes user login error and potentially blocks user
  client/packages/common/src/authentication/AuthContext.tsx
  client/packages/common/src/authentication/api/api.ts
  client/packages/common/src/authentication/api/hooks/index.ts
  client/packages/common/src/authentication/api/hooks/useAuthApi.ts
  client/packages/common/src/authentication/api/hooks/useLogin.ts
  client/packages/common/src/authentication/api/hooks/useUpdateUser.ts
  client/packages/common/src/authentication/api/hooks/useUserDetails.ts
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.graphql
  client/packages/common/src/authentication/hooks/useUpdateUserInfo.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/host/src/components/Sync/Sync.tsx
  client/packages/system/src/Sync/api/api.ts
  client/packages/system/src/Sync/api/hooks/index.ts
  client/packages/system/src/Sync/api/hooks/sync/index.ts
  client/packages/system/src/Sync/api/hooks/sync/useUpdateUser.ts
  client/packages/system/src/Sync/api/hooks/utils/index.ts
  client/packages/system/src/Sync/api/hooks/utils/useLastSuccessfulUserSync.ts
  client/packages/system/src/Sync/api/hooks/utils/useSyncApi.ts
  client/packages/system/src/Sync/api/operations.generated.ts
  client/packages/system/src/Sync/api/operations.graphql
  server/graphql/general/src/mutations/update_user.rs
  server/graphql/general/src/queries/login.rs
  server/service/src/login.rs
  server/service/src/sync/sync_user.rs
  server/service/src/sync/translations/name.rs
Labels: bug, Priority: Should have, Team Tauhou

#3680 3501 add new stock line mutation
  server/graphql/inventory_adjustment/mutations/insert.rs
  server/graphql/stock_line/src/mutations/insert.rs
  server/repository/src/db_diesel/invoice_line_row.rs
  server/service/src/common_stock.rs
  server/service/src/invoice/inbound_return/insert/generate.rs
  server/service/src/invoice/inbound_return/update_lines/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/insert.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/mod.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/validate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/insert.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/mod.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/validate.rs
  server/service/src/invoice/inventory_adjustment/mod.rs
  server/service/src/invoice/mod.rs
  server/service/src/invoice/validate.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/mod.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
Labels: Team Ruru 🦉, feature: inventory adjustments

#3682 add returns integration tests
  server/service/src/processors/transfer/shipment/test.rs
  server/service/src/sync/test/integration/README.md
  server/service/src/sync/test/integration/errors.rs
  server/service/src/sync/test/integration/transfer/mod.rs
  server/service/src/sync/test/integration/transfer/returns.rs
  server/service/src/sync/test/integration/transfer/shipments.rs
Labels: Team Ruru 🦉, feature: returns

#3735 3704-Fix-fully-issued-lines-dissapearing-in-outbound-shipment
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
Labels: bug, needs architecture/solution, Team Ruru 🦉

#3745 Fix onClick callback handling
  client/packages/system/src/ContactTrace/DetailView/Footer.tsx
Labels: bug, Team Tauhou, Severity: Normal

#3683 Add cli to build
  build/windows/omsupply-build.bat
  build/windows/omsupply_server.suf
  server/cli/src/cli.rs
  server/cli/src/refresh_dates.rs
Labels: enhancement, Team Piwakawaka

#3759 3757 Open mSupply hangs when you order form Dashboard
  client/packages/dashboard/src/widgets/StockWidget.tsx
Labels: bug, Team Tauhou, Severity: High

#3747 #3536 Prescription input quantity fix
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.test.tsx
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/host/src/Admin/LabelPrinterSettings.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
Labels: bug, platform: android, Team Ruru 🦉, Severity: Normal

#3768 3730 disable add batch button on inbound return reason step
  client/packages/invoices/src/Returns/modals/InboundReturn/AddBatch.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/ReturnSteps.tsx
Labels: bug, Team Ruru 🦉, Severity: High, docs: external

#3763 3538 number pad for number inputs
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#3765 only render quantity inputs after item is set
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#3766 Add asset number to equipment filter
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
  client/packages/common/src/intl/locales/en/coldchain.json
Labels: bug, Severity: High, feature: CCEI

#3731 Add home button to error boundary
  client/README.md
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/errors/GenericErrorFallback.tsx
Labels: bug, Severity: Normal, needs design

#3775 prevent duplicates
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
Labels: bug, Severity: Normal, feature: CCEI

#3728 3492 handle inbound batch errors
  client/packages/common/src/hooks/useDeleteConfirmation/useDeleteConfirmation.ts
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/line/useDeleteSelectedLines.ts
Labels: bug, Team Tauhou, Severity: High

#3799 add installation date column
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
Labels: bug, Severity: Normal, feature: CCEI, docs: external

#3812 Coldchain cherry pick for 2.0.0-RC
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/BreachIndicator.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/BreachPopover.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureTooltip.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/types.ts
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureLog/operations.generated.ts
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/ui/components/charts/index.ts
  server/graphql/cold_chain/src/lib.rs
  server/graphql/cold_chain/src/temperature_chart.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/temperature_chart/README.md
  server/repository/src/db_diesel/temperature_chart/mod.rs
  server/repository/src/db_diesel/temperature_chart/temperature_chart.rs
  server/repository/src/db_diesel/temperature_chart/temperature_chart_row.rs
  server/service/src/cold_chain/query_temperature_log.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
  server/service/src/temperature_chart.rs
Labels: refactor, Team Piwakawaka

#3770 3679 simplify cold chain graphing
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/BreachIndicator.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/BreachPopover.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureChart.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/TemperatureTooltip.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/types.ts
  client/packages/coldchain/src/Monitoring/ListView/TemperatureChart/useTemperatureChartData.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureLog/operations.generated.ts
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/ui/components/charts/index.ts
  server/graphql/cold_chain/src/lib.rs
  server/graphql/cold_chain/src/temperature_chart.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/temperature_chart/README.md
  server/repository/src/db_diesel/temperature_chart/mod.rs
  server/repository/src/db_diesel/temperature_chart/temperature_chart.rs
  server/repository/src/db_diesel/temperature_chart/temperature_chart_row.rs
  server/service/src/cold_chain/query_temperature_log.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
  server/service/src/temperature_chart.rs
Labels: refactor, Team Piwakawaka, docs: external

#3809 Update stock line on scan
  client/packages/system/src/Stock/Components/StockLineForm.tsx
Labels: bug, Team Piwakawaka, Severity: Normal

#3804 Handle app crash
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/dashboard/src/api/api.ts
Labels: bug, Team Piwakawaka, Severity: High, feature: CCEI

#3818 Hide required asterisk when inv adj reason is disabled
  client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#3822 Use correct condition for app nav's activeness
  client/packages/host/src/components/Navigation/ColdChainNav.tsx
  client/packages/host/src/components/Navigation/DispensaryNav.tsx
Labels: bug, Team Tauhou, Severity: Low

#3821 3771 Have to click Ok twice if permission is denied
  client/packages/common/src/hooks/useToggle/useToggle.ts
Labels: bug, Team Tauhou, Severity: Normal

#3826 3801 Internal Order Page has misaligned "Filter Items" searchbox and "Actions" drop down
  client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
Labels: bug, front-end, make omSupply delightful, Team Tauhou, Severity: Low, docs: external

#3805 3800 sync assets fails with duplicate asset numbers
  server/repository/src/migrations/v2_00_00/assets/asset.rs
Labels: bug, Team Piwakawaka, Severity: High

#3841 3760 Catalogue -> Assets -> Log Reasons -> swap Reason and Status around
  client/packages/system/src/Asset/AssetLogReasons/ListView.tsx
Labels: enhancement, Priority: Nice to Have, Team Tauhou, Severity: Low, docs: external

#3819 Make the supplier name website look like another, disabled text input
  client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
  client/packages/system/src/Name/DetailModal/DetailModal.tsx
Labels: bug, Team Tauhou, Severity: Low, docs: external

#3814 3736 bug: OS issue expired line value disappears on click
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/StockOut/utils.tsx
Labels: bug, Team Ruru 🦉, Severity: High

#3802 add useKeyboardHeightAdjustment to response line edit modal
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
Labels: bug, Team Ruru 🦉, Severity: High, needs design

#3851 3741 cannot sort the list in equipment table
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  server/graphql/asset/src/types.rs
  server/repository/src/db_diesel/assets/asset.rs
  server/repository/src/db_diesel/assets/asset_log.rs
  server/repository/src/db_diesel/assets/asset_log_row.rs
  server/repository/src/db_diesel/assets/asset_row.rs
Labels: enhancement, Priority: Should have, Severity: Normal, feature: CCEI, docs: external

#3833 3547 new patient breadcrumb
  client/packages/common/src/intl/locales/en/dispensary.json
  client/packages/system/src/Patient/PatientView/PatientSummary.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal, docs: external

#3836 3442 collapse drawers on secondary click
  client/packages/common/src/hooks/useDrawer/useDrawer.ts
Labels: bug, Team Ruru 🦉, Severity: Normal

#3852 Fix encounter updated test
  server/service/src/programs/encounter/encounter_updated.rs
Labels: Priority: Should have, refactor

#3817 3532 issue stock not clearing values
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/PrescriptionLineEditForm.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#3856 2926 Datepicker moves if it is to close to the edge
  client/package.json
  client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
  client/yarn.lock
Labels: bug, Team Tauhou, Severity: Normal, Tester: Taina

#3837 # 3579 Fix Pagination bar side-scrolling
  client/packages/common/src/ui/components/navigation/Tabs/DetailTab.tsx
  client/packages/common/src/ui/layout/tables/DataTable.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
Labels: bug, refactor, Team Ruru 🦉, Severity: Normal

#3842 #3561 Fix Column show/hide behaviour
  client/packages/common/src/ui/layout/tables/DataTable.tsx
  client/packages/common/src/ui/layout/tables/components/Header/ColumnPicker.tsx
  client/packages/common/src/ui/layout/tables/hooks/index.ts
  client/packages/common/src/ui/layout/tables/hooks/useColumnDisplayState.ts
Labels: bug, Team Ruru 🦉, Severity: Normal

#3860 Increase thermometer stroke width
  client/packages/common/src/ui/icons/Thermometer.tsx
Labels: bug, make omSupply delightful, Severity: Low

#3843 Add warnings for fields for fields if they fail to parse
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/ImportReviewDataTable.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/ReviewTab.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
Labels: bug, Priority: Nice to Have, Team Piwakawaka, Severity: Low, feature: CCEI

#3850 Fix the zebra tester 🦓 ✅
  server/server/src/print/label.rs
  server/service/src/print/jetdirect.rs
Labels: bug

#3752 Add component selectors
  client/packages/common/src/ui/components/buttons/FlatButton/FlatButton.tsx
  client/packages/common/src/ui/components/popover/ClickPopover/ClickPopover.tsx
  client/packages/common/src/ui/components/popover/PaperPopover/PaperClickPopover/PaperClickPopover.tsx
  client/packages/host/src/components/Footer/LanguageSelector.tsx
  client/packages/host/src/components/Login/Login.tsx
Labels: enhancement, Team Piwakawaka

#3861 3527 You can confirm outbound shipments with only placeholder lines
  client/packages/common/src/intl/locales/en/replenishment.json
  client/packages/requisitions/src/RequestRequisition/DetailView/Footer/StatusChangeButton.tsx
Labels: bug, Team Tauhou

#3870 3858 CCEI module: No details in error message when creating CCE with duplicate asset numbers
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
Labels: bug, Team Tauhou, feature: CCEI

#3855 Add tooltip to the select/unselect all column header
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/TooltipTextCell/TooltipTextCell.tsx
  client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
  client/packages/common/src/ui/layout/tables/components/tooltipPlacement.ts
Labels: bug, Team Tauhou

#3871 Pagination side scrolling
  client/packages/common/src/ui/components/navigation/Tabs/DetailTab.tsx
  client/packages/common/src/ui/layout/tables/DataTable.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
Labels: bug, Team Piwakawaka, feature: CCEI

#3791 2752 consolidate cold chain filters
  client/packages/coldchain/src/Monitoring/ListView/ListView.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/TemperatureBreachList.tsx
  client/packages/coldchain/src/Monitoring/ListView/TemperatureBreach/Toolbar.tsx
  client/packages/coldchain/src/Monitoring/api/TemperatureBreach/api.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureLog/api.ts
  client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
Labels: enhancement, Priority: Nice to Have, Team Piwakawaka, docs: external

#3879 3877 introduce stock when set straight to verified
  server/service/src/invoice/inbound_return/update/generate.rs
  server/service/src/invoice/inbound_return/update/mod.rs
Labels: bug, Team Ruru 🦉, Severity: High

#3808 Enable hold button for "Shipped" invoices
  client/packages/invoices/src/InboundShipment/DetailView/Footer/OnHoldButton.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/utils/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/utils/useIsInboundHoldable.ts
  client/packages/invoices/src/utils.ts
Labels: bug, Build tested: passed, Team Tauhou, needs design

#3884 3834 clear number inputs to 0
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
  client/packages/system/src/Item/Components/PackVariant/PackVariantEntryCell.tsx
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#3902 3895 Username no longer being displayed in sidepanels
  client/packages/coldchain/src/Equipment/DetailView/Tabs/StatusLogs.tsx
  client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/RelatedDocumentsSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/InboundDetailView/SidePanel/RelatedDocumentsSection.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Returns/OutboundDetailView/SidePanel/RelatedDocumentsSection.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/SidePanel.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/AdditionalInfoSection.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/RelatedDocumentsSection.tsx
  client/packages/system/src/Encounter/DetailView/SidePanel.tsx
Labels: bug, Team Tauhou, docs: external

#3901 3674 assets locations dont show on central server
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
Labels: bug, Team Piwakawaka, Severity: Normal, feature: CCEI

#3896 3739 remove foreign key for user
  server/repository/src/migrations/v2_00_00/assets/asset_log.rs
Labels: bug, Priority: Must Have, Team Piwakawaka, Severity: High, feature: CCEI

#3825 3485 uncounted packs should show uncounted
  client/packages/common/src/intl/number/IntlNumber.ts
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberCell.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal, docs: external

#3899 Adjust QR code command
  server/service/src/print/label.rs
Labels: bug, Team Piwakawaka, Severity: Normal

#3894 3893 correctly map repack times and status
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  server/service/src/sync/translations/invoice.rs
Labels: refactor, Team Tauhou

#3876 3829 inbound delivery date updated when verified
  server/repository/src/mock/invoice.rs
  server/service/src/invoice/inbound_return/update/generate.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
Labels: bug, Team Ruru 🦉, Severity: Low

#3904 Lock changelog table when retrieving changelogs (postgres)
  server/repository/src/db_diesel/changelog/changelog.rs
Labels: Priority: Should have, refactor, Team Tauhou

#3891 Avoid float precision problems when multiplying pack sizes
  client/packages/common/src/utils/numbers/NumUtils.test.ts
  client/packages/common/src/utils/numbers/NumUtils.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/PrescriptionLineEdit/columns.ts
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Returns/InboundDetailView/columns.ts
  client/packages/invoices/src/Returns/OutboundDetailView/columns.ts
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: enhancement, Epic, Priority: Should have, Team Tauhou

#3942 Remove label
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/ru/app.json
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
Labels: enhancement, Team Piwakawaka

#3955 3954 Link to documentation broken
  client/packages/common/src/utils/environment/EnvUtils.ts
Labels: bug, Team Tauhou, Severity: Hotfix

#3920 3914 prevent resyncing line records
  server/repository/src/migrations/v2_00_00/mod.rs
Labels: bug, Team Tauhou, Severity: Hotfix

#3943 3286 remove 'shipment' in invoice log translations
  client/packages/common/src/intl/locales/en/common.json
Labels: enhancement, Team Ruru 🦉, feature: returns, docs: external

#3963 3949 fix taxPercentage mapping for service charges
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/OutboundShipment/api/api.ts
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#3962 make min=0 the default for number input cell
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/Returns/modals/InboundReturn/ReturnQuantitiesTable.tsx
  client/packages/invoices/src/Returns/modals/OutboundReturn/ReturnQuantitiesTable.tsx
  client/packages/invoices/src/StockOut/utils.tsx
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#3958 3111 oms central sync versioning
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Sync/api/api.ts
  server/graphql/general/src/sync_api_error.rs
  server/repository/src/db_diesel/sync_log_row.rs
  server/repository/src/migrations/v2_01_00/mod.rs
  server/repository/src/migrations/v2_01_00/v6_sync_api_error_code.rs
  server/service/src/sync/README.md
  server/service/src/sync/api/core.rs
  server/service/src/sync/api_v6/core.rs
  server/service/src/sync/api_v6/download_file.rs
  server/service/src/sync/api_v6/mod.rs
  server/service/src/sync/api_v6/upload_file.rs
  server/service/src/sync/central_data_synchroniser_v6.rs
  server/service/src/sync/file_synchroniser.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/site_info.rs
  server/service/src/sync/sync_on_central/mod.rs
  server/service/src/sync/sync_status/logger.rs
  server/service/src/sync/synchroniser.rs
Labels: enhancement, Priority: Must Have, Team Ruru 🦉, feature: central server

#3953 3606 sync buffer integration error show when item was ignored
  server/service/src/sync/test/test_data/store.rs
  server/service/src/sync/translation_and_integration.rs
  server/service/src/sync/translations/document_registry.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/master_list_name_join.rs
  server/service/src/sync/translations/report.rs
  server/service/src/sync/translations/requisition.rs
  server/service/src/sync/translations/special/name_to_name_store_join.rs
  server/service/src/sync/translations/stocktake.rs
  server/service/src/sync/translations/store.rs
Labels: enhancement, Priority: Should have, Migrate Existing Desktop, Team Tauhou

#3975 #3968 Stocktake pricing fix
  client/packages/common/src/ui/layout/tables/components/Cells/CurrencyInputCell/CurrencyInputCell.tsx
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#3985 update msupply support email
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/fr/app.json
  client/packages/common/src/intl/locales/ru/app.json
Labels: docs: external

#3990 3981 fix $NaN currency display for outbound shipment placeholder lines
  client/packages/common/src/ui/layout/tables/components/Cells/CurrencyCell.tsx
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#3997 2154 Linter rule for const and warning for indirect external package imports
  client/tsconfig.json
Labels: Priority: Nice to Have, Team Tauhou

#3946 3930 asset properties edit
  client/packages/coldchain/src/Equipment/Components/PropertyInput.tsx
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Details.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetProperties.ts
  client/packages/coldchain/src/Equipment/api/hooks/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/utils/useAssetApi.ts
  client/packages/coldchain/src/Equipment/api/hooks/utils/useAssetPropertiesApi.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
  client/packages/system/src/Asset/api/api.ts
  client/packages/system/src/Asset/api/operations.generated.ts
  client/packages/system/src/Asset/api/operations.graphql
  client/tsconfig.json
  server/graphql/asset/src/mutations/insert.rs
  server/graphql/asset/src/mutations/update.rs
  server/graphql/asset/src/types/asset.rs
  server/graphql/asset/src/types/asset_property.rs
  server/graphql/core/src/generic_filters.rs
  server/repository/src/db_diesel/assets/asset_property.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/migrations/v2_01_00/assets/asset.rs
  server/repository/src/migrations/v2_01_00/assets/asset_property.rs
  server/repository/src/migrations/v2_01_00/assets/mod.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/tests/insert.rs
  server/service/src/asset/tests/update.rs
  server/service/src/asset/update.rs
  server/service/src/sync/test/test_data/asset.rs
Labels: Team Piwakawaka, feature: GAPS

#3960 3948 asset donor field name lookup
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Name/Components/DonorSearchInput/DonorSearchInput.tsx
  client/packages/system/src/Name/Components/DonorSearchInput/index.ts
  client/packages/system/src/Name/Components/index.ts
  client/packages/system/src/Name/api/api.ts
  client/packages/system/src/Name/api/hooks/document/index.ts
  client/packages/system/src/Name/api/hooks/document/useDonors.ts
  client/packages/system/src/Name/api/hooks/index.ts
  client/packages/system/src/Name/api/hooks/utils/useNameApi.ts
  client/packages/system/src/Name/utils.ts
  server/graphql/general/src/queries/names.rs
  server/graphql/general/src/queries/tests/names.rs
  server/repository/src/db_diesel/name.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#3970 3866 add support for registering new cce category cold rooms and freezer rooms
  project-words.txt
  server/cli/src/refresh_dates.rs
  server/repository/src/migrations/v2_01_00/assets/asset_catalogue_data.rs
  server/repository/src/migrations/v2_01_00/assets/asset_property_data.rs
  server/repository/src/migrations/v2_01_00/assets/mod.rs
  server/service/src/catalogue/tests/query_catalogue_item.rs
Labels: Team Piwakawaka, feature: CCEI, feature: GAPS

#3976 3907 gaps add needs replacing property
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/common/src/intl/locales/en/coldchain.json
  client/packages/common/src/types/schema.ts
  server/graphql/asset/src/mutations/insert.rs
  server/graphql/asset/src/mutations/update.rs
  server/graphql/asset/src/types/asset.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/migrations/v2_01_00/assets/asset.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/update.rs
Labels: Team Piwakawaka, feature: GAPS

#3998 3905 facilities list
  client/packages/common/src/intl/locales/en/app.json
  client/packages/common/src/intl/locales/en/manage.json
  client/packages/common/src/intl/locales/index.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/ui/icons/Sliders.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/config/src/routes.ts
  client/packages/host/src/CommandK.tsx
  client/packages/host/src/Site.tsx
  client/packages/host/src/components/AppBar/SectionIcon.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/components/Navigation/ManageNav.tsx
  client/packages/host/src/components/Navigation/index.ts
  client/packages/host/src/routers/ManageRouter.tsx
  client/packages/host/src/routers/index.ts
  client/packages/system/src/Name/ListView/Facilities/ListView.tsx
  client/packages/system/src/Name/ListView/Facilities/Toolbar.tsx
  client/packages/system/src/Name/ListView/ListView.tsx
  client/packages/system/src/Name/Service/Service.tsx
  client/packages/system/src/Name/api/api.ts
  client/packages/system/src/Name/api/hooks/document/index.ts
  client/packages/system/src/Name/api/hooks/document/useFacilities.ts
  client/packages/system/src/Name/api/hooks/document/useNames.ts
  client/packages/system/src/Name/api/hooks/index.ts
  server/graphql/general/src/queries/names.rs
  server/repository/src/db_diesel/name.rs
Labels: Team Piwakawaka, docs: external, feature: GAPS

#4011 Add properties to PQS Items
  server/repository/src/migrations/v2_01_00/assets/asset_property_data.rs
Labels: Team Piwakawaka, feature: GAPS

#4003 dd gaps demographic data storage
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/demographic/Cargo.toml
  server/graphql/demographic/src/lib.rs
  server/graphql/demographic/src/mutations/insert_indicator.rs
  server/graphql/demographic/src/mutations/insert_projection.rs
  server/graphql/demographic/src/mutations/mod.rs
  server/graphql/demographic/src/mutations/update.rs
  server/graphql/demographic/src/mutations/update_indicator.rs
  server/graphql/demographic/src/mutations/update_projection.rs
  server/graphql/demographic/src/types.rs
  server/graphql/lib.rs
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/demographic_indicator.rs
  server/repository/src/db_diesel/demographic_indicator_row.rs
  server/repository/src/db_diesel/demographic_projection.rs
  server/repository/src/db_diesel/demographic_projection_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v2_01_00/demographics.rs
  server/repository/src/migrations/v2_01_00/mod.rs
  server/repository/src/mock/mod.rs
  server/service/src/auth.rs
  server/service/src/demographic/insert_demographic_indicator.rs
  server/service/src/demographic/insert_demographic_projection.rs
  server/service/src/demographic/mod.rs
  server/service/src/demographic/query_demographic_indicator.rs
  server/service/src/demographic/query_demographic_projection.rs
  server/service/src/demographic/tests/insert_indicator.rs
  server/service/src/demographic/tests/insert_projection.rs
  server/service/src/demographic/tests/mod.rs
  server/service/src/demographic/tests/update_indicator.rs
  server/service/src/demographic/tests/update_projection.rs
  server/service/src/demographic/update_demographic_indicator.rs
  server/service/src/demographic/update_demographic_projection.rs
  server/service/src/demographic/validate.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
Labels: Team Piwakawaka, feature: GAPS

#4017 3906 edit custom name data - modal
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Details.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/inputs/PropertyInput/PropertyInput.tsx
  client/packages/common/src/ui/components/inputs/PropertyInput/index.ts
  client/packages/common/src/ui/components/inputs/index.ts
  client/packages/system/src/Name/ListView/Facilities/FacilityEditModal.tsx
  client/packages/system/src/Name/ListView/Facilities/ListView.tsx
  client/packages/system/src/Name/api/api.ts
  client/packages/system/src/Name/api/hooks/document/index.ts
  client/packages/system/src/Name/api/hooks/document/useNameProperties.ts
  client/packages/system/src/Name/api/hooks/index.ts
  client/packages/system/src/Name/api/hooks/utils/index.ts
  client/packages/system/src/Name/api/hooks/utils/useNameApi.ts
  client/packages/system/src/Name/api/hooks/utils/useNextFacilityId.ts
Labels: Team Piwakawaka, feature: GAPS
