Repository msupply-foundation/open-msupply, pull requests merged in 2025-01, with the labels that each got.

#5907 Update column picker
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/intl/utils/DateUtils.test.ts
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/common/src/ui/layout/tables/DataTable.tsx
  client/packages/common/src/ui/layout/tables/columns/CheckboxSelectionColumn.tsx
  client/packages/common/src/ui/layout/tables/components/Header/ColumnPicker.tsx
  client/packages/common/src/ui/layout/tables/hooks/useColumnDisplayState.ts
Labels: bug, good first issue, Severity: Normal

#5906 Item total values
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
  client/packages/common/src/ui/components/navigation/AppNavSection.tsx
  client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/system/src/Item/DetailView/Toolbar/Statistics.tsx
  client/packages/system/src/Item/ListView/ListView.tsx
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Stock/ListView/ListView.tsx
  server/graphql/types/src/types/item_stats.rs
  server/service/src/item_stats.rs
Labels: enhancement

#5891 5665 extra window to show item info
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/navigation/ListOptions/ListOptions.tsx
  client/packages/requisitions/src/PageLayout.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemInformation.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditForm.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/index.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/requisition_item_information.rs
  server/graphql/general/src/queries/item_ledger.rs
  server/graphql/general/src/queries/ledger.rs
  server/graphql/general/src/queries/names.rs
  server/graphql/general/src/queries/tests/names.rs
  server/graphql/invoice_line/src/invoice_line_queries.rs
  server/graphql/programs/src/types/program.rs
  server/graphql/requisition/src/query_tests/requisition.rs
  server/graphql/requisition/src/query_tests/requisitions.rs
  server/graphql/requisition/src/requisition_queries.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/program/program_node.rs
  server/graphql/types/src/types/requisition_item_information.rs
  server/graphql/types/src/types/requisition_line.rs
  server/repository/src/db_diesel/invoice_line.rs
  server/repository/src/db_diesel/ledger.rs
  server/repository/src/db_diesel/name.rs
  server/repository/src/db_diesel/program_requisition/program.rs
  server/repository/src/db_diesel/program_requisition/program_row.rs
  server/repository/src/db_diesel/requisition/mod.rs
  server/repository/src/db_diesel/requisition/requisition.rs
  server/repository/src/migrations/v2_05_00/add_elmis_code_to_program.rs
  server/repository/src/migrations/v2_05_00/mod.rs
  server/repository/src/mock/program.rs
  server/service/src/ledger.rs
  server/service/src/program/test/query.rs
  server/service/src/requisition/mod.rs
  server/service/src/requisition/request_requisition/mod.rs
  server/service/src/requisition/request_requisition/requisition_item_info.rs
  server/service/src/sync/test/test_data/program_requisition_settings.rs
  server/service/src/sync/translations/program_requisition_settings.rs
Labels: enhancement, Team Ruru 🦉, feature: CIV

#5913 bump v6 sync version
  server/service/src/sync/settings.rs
  server/service/src/sync/sync_on_central/mod.rs
Labels: feature: GEDSI, Team Korimako

#5862 5801 dispensing diagnosis selection
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PatientDetails.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/keys.ts
  client/packages/invoices/src/Prescriptions/api/hooks/useDiagnosisOptions.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescription.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionLines.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  server/graphql/batch_mutations/src/batch_prescription.rs
  server/graphql/core/src/loader/diagnosis.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/diagnosis.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/invoice/src/mutations/prescription/insert.rs
  server/graphql/invoice/src/mutations/prescription/update.rs
  server/graphql/types/src/types/diagnosis.rs
  server/graphql/types/src/types/invoice_query.rs
  server/graphql/types/src/types/mod.rs
  server/repository/src/db_diesel/diagnosis.rs
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/migrations/v2_05_00/diagnosis_add_to_invoice.rs
  server/repository/src/migrations/v2_05_00/mod.rs
  server/service/src/auth.rs
  server/service/src/diagnosis.rs
  server/service/src/invoice/customer_return/insert/generate.rs
  server/service/src/invoice/inbound_shipment/insert/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/outbound_shipment/insert/generate.rs
  server/service/src/invoice/prescription/insert/generate.rs
  server/service/src/invoice/prescription/insert/mod.rs
  server/service/src/invoice/prescription/update/generate.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/invoice/supplier_return/insert/generate.rs
  server/service/src/lib.rs
  server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/vaccination/generate.rs
Labels: Team Piwakawaka, feature: dispensing

#5888 Update external docs link
  client/packages/common/src/utils/environment/EnvUtils.ts
Labels: feature: GEDSI, Team Korimako

#5894 5804 PR 1 update actions footer across all detail view tables
  client/packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx
  client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
  client/packages/inventory/src/Stocktake/api/hooks/utils/useSelectedRows.ts
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/Toolbar.tsx
  client/packages/invoices/src/Returns/api/hooks/line/useDeleteSelectedCustomerLines.ts
  client/packages/invoices/src/Returns/api/hooks/line/useDeleteSelectedSupplierLines.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Footer/Footer.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/ToolbarDropDown.tsx
  client/packages/requisitions/src/RequestRequisition/api/hooks/line/useDeleteRequestLines.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar/Toolbar.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar/ToolbarDropDown.tsx
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useDeleteResponseLines.ts
Labels: refactor, feature: GEDSI, Team Korimako

#5916 5804 pr 2 update actions footer across list view tables
  client/packages/coldchain/src/Equipment/ListView/Footer.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetsDelete.ts
  client/packages/common/src/ui/layout/tables/columns/PaginationRow/PaginationRow.tsx
  client/packages/inventory/src/Stocktake/ListView/Footer.tsx
  client/packages/inventory/src/Stocktake/ListView/ListView.tsx
  client/packages/inventory/src/Stocktake/ListView/Toolbar.tsx
  client/packages/inventory/src/Stocktake/api/hooks/document/useStocktakeDeleteSelected.ts
  client/packages/invoices/src/InboundShipment/ListView/Footer.tsx
  client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/InboundShipment/ListView/Toolbar.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/document/useInboundDeleteRows.ts
  client/packages/invoices/src/OutboundShipment/ListView/Footer.tsx
  client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx
  client/packages/invoices/src/OutboundShipment/api/hooks/document/useOutboundDeleteRows.ts
  client/packages/invoices/src/Prescriptions/ListView/Footer.tsx
  client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
  client/packages/invoices/src/Prescriptions/ListView/Toolbar.tsx
  client/packages/invoices/src/Returns/CustomerListView/Footer.tsx
  client/packages/invoices/src/Returns/CustomerListView/ListView.tsx
  client/packages/invoices/src/Returns/CustomerListView/Toolbar.tsx
  client/packages/invoices/src/Returns/SupplierListView/Footer.tsx
  client/packages/invoices/src/Returns/SupplierListView/ListView.tsx
  client/packages/invoices/src/Returns/SupplierListView/Toolbar.tsx
  client/packages/invoices/src/Returns/api/hooks/document/useCustomerDeleteRows.ts
  client/packages/invoices/src/Returns/api/hooks/document/useSupplierDeleteRows.ts
  client/packages/requisitions/src/RequestRequisition/ListView/Footer.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/Toolbar.tsx
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useDeleteSelectedRequisitions.ts
  client/packages/requisitions/src/ResponseRequisition/ListView/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/Toolbar.tsx
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useDeleteSelectedResponseRequisitions.ts
  client/packages/system/src/Asset/AssetLogReasons/Footer.tsx
  client/packages/system/src/Asset/AssetLogReasons/ListView.tsx
  client/packages/system/src/Asset/AssetLogReasons/Toolbar.tsx
  client/packages/system/src/Asset/ListView/Footer.tsx
  client/packages/system/src/Asset/ListView/ListView.tsx
  client/packages/system/src/Asset/ListView/Toolbar.tsx
  client/packages/system/src/Asset/api/hooks/document/useAssetsDelete.ts
  client/packages/system/src/Location/ListView/Footer.tsx
  client/packages/system/src/Location/ListView/ListView.tsx
  client/packages/system/src/Location/ListView/Toolbar.tsx
Labels: refactor, feature: GEDSI, Team Korimako

#5922 5920 prescriptions filter out on hold stock
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/useDraftPrescriptionLines.tsx
Labels: Team Piwakawaka

#5883 5841 gaps item import script is incorrect
  server/gaps/items/create_gaps_item_sql_script.py
  server/gaps/items/gaps_code_creator.py
  server/gaps/items/gaps_insert_functions.py
  server/gaps/items/gaps_item_variants.csv
  server/gaps/items/generated/gaps_item_inserts.sql
  server/gaps/items/helpers.py
  server/gaps/items/id_lookup.json
Labels: bug, Team Piwakawaka, Severity: High

#5915 5821 email sending
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  server/Cargo.lock
  server/README.md
  server/android/src/android.rs
  server/cli/src/refresh_dates.rs
  server/configuration/example.yaml
  server/repository/src/db_diesel/email_queue_row.rs
  server/repository/src/migrations/v2_05_00/add_email_retry_at.rs
  server/repository/src/migrations/v2_05_00/mod.rs
  server/server/src/lib.rs
  server/server/src/scheduled_tasks.rs
  server/service/Cargo.toml
  server/service/src/email/base.html
  server/service/src/email/enqueue.rs
  server/service/src/email/mod.rs
  server/service/src/email/send.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
  server/service/src/settings.rs
  server/service/src/test_helpers.rs
Labels: feature: GEDSI, Team Korimako

#5908 Move sync to a modal
  client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
  client/packages/common/src/ui/components/navigation/Breadcrumbs/Breadcrumbs.tsx
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/config/src/routes.ts
  client/packages/host/src/CommandK.tsx
  client/packages/host/src/Site.tsx
  client/packages/host/src/components/AppBar/SectionIcon.tsx
  client/packages/host/src/components/AppDrawer/SyncNavLink.tsx
  client/packages/host/src/components/Sync/SyncModal.tsx
  client/packages/host/src/components/Sync/SyncModalContext.ts
  client/packages/host/src/components/Sync/SyncModalProvider.tsx
  client/packages/host/src/components/Sync/index.tsx
  client/packages/host/src/components/Sync/useSyncModal.ts
  client/packages/system/src/Sync/api/hooks/utils/useSyncInfo.ts
Labels: enhancement, good first issue, Priority: Should have, make omSupply delightful

#5718 5666 generate indicators for internal orders
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useIndicators.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  server/graphql/core/src/loader/program_indicator_value.rs
  server/graphql/types/src/types/program/program_indicator.rs
  server/repository/src/db_diesel/indicator_value.rs
  server/repository/src/db_diesel/indicator_value_row.rs
  server/service/src/requisition/common.rs
  server/service/src/requisition/indicator_value/update.rs
  server/service/src/requisition/request_requisition/insert_program.rs
  server/service/src/requisition/response_requisition/insert_program.rs
Labels: enhancement, Team Ruru 🦉, feature: CIV

#5927 5780 inbound Shipment table does not show total cost
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
Labels: bug, Severity: High, Team Korimako

#5921 prevent delete on inbound transferred shipment
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/hooks/line/useDeleteSelectedLines.ts
  client/packages/invoices/src/InboundShipment/api/hooks/line/useSaveInboundLines.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/delete.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/mod.rs
  server/repository/src/mock/invoice.rs
  server/repository/src/mock/invoice_line.rs
  server/service/src/invoice/validate.rs
  server/service/src/invoice_line/stock_in_line/delete/mod.rs
  server/service/src/invoice_line/stock_in_line/delete/validate.rs
Labels: bug, Severity: High, Team Korimako

#5909 5750 civ 2.5 add item in page
  client/packages/common/src/intl/locales/en/common.json
  client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/Footer.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/utils.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/utils.ts
  client/packages/requisitions/src/common/PageLayout.tsx
  client/packages/system/src/Item/Components/ListItems/ListItems.tsx
  server/Cargo.lock
Labels: enhancement, Team Ruru 🦉, feature: CIV

#5880 #5779 Stock issuing UI
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/navigation/ListOptions/ListOptions.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/ExpiryDateCell/ExpiryDateCell.tsx
  client/packages/invoices/src/Prescriptions/DetailView/ContentArea.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/NavBar.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PanelSection.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditTable.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/columns.ts
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/useDraftPrescriptionLines.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/usePrescriptionLineEditRows.ts
  client/packages/invoices/src/StockOut/utils.tsx
  client/packages/programs/src/JsonForms/components/Prescription/StockLineTable.tsx
Labels: Team Piwakawaka, feature: dispensing

#5942 Add some safety to version from string conversion
  server/repository/src/migrations/version.rs
Labels: bug, Severity: Normal

#5946 Update button styles
  client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/DetailView/Footer/Footer.tsx
  client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
  client/packages/coldchain/src/Monitoring/ListView/AppBarButtons.tsx
  client/packages/common/src/styles/theme.ts
  client/packages/common/src/ui/components/buttons/FlatButton/FlatButton.tsx
  client/packages/common/src/ui/components/buttons/standard/BaseButton.tsx
  client/packages/common/src/ui/components/buttons/standard/ButtonWithIcon.tsx
  client/packages/common/src/ui/components/buttons/standard/LoadingButton.stories.tsx
  client/packages/common/src/ui/components/buttons/standard/LoadingButton.tsx
  client/packages/common/src/ui/components/buttons/standard/ShrinkableBaseButton.tsx
  client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.tsx
  client/packages/host/src/Admin/ElectronSettings.tsx
  client/packages/host/src/Admin/LabelPrinterSettings.tsx
  client/packages/host/src/Admin/ServerSettings.tsx
  client/packages/host/src/Admin/SyncSettings.tsx
  client/packages/host/src/Help/ContactForm.tsx
  client/packages/host/src/components/Initialise/Initialise.tsx
  client/packages/host/src/components/Login/Login.tsx
  client/packages/host/src/components/Sync/SyncModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx
  client/packages/inventory/src/Stocktake/ListView/AppBarButtons.tsx
  client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/OutboundShipment/ListView/AppBarButtons.tsx
  client/packages/invoices/src/Prescriptions/ListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/SupplierListView/AppBarButtons.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/AppBarButtons.tsx
  client/packages/requisitions/src/RnRForms/DetailView/AppBarButtons.tsx
  client/packages/system/src/Asset/ListView/AppBarButtons.tsx
  client/packages/system/src/ContactTrace/DetailView/Footer.tsx
  client/packages/system/src/Encounter/DetailView/Footer.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/Footer.tsx
  client/packages/system/src/Location/ListView/AppBarButtons.tsx
  client/packages/system/src/MasterList/ListView/AppBarButtons.tsx
  client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
  client/packages/system/src/Patient/ListView/AppBarButtons.tsx
  client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
  client/packages/system/src/Patient/PatientView/Footer.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
  client/packages/system/src/Stock/DetailView/Footer.tsx
  client/packages/system/src/Stock/ListView/AppBarButtons.tsx
Labels: bug

#5947 5873 fix action footer buttons
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/buttons/FlatButton/FlatButton.tsx
  client/packages/common/src/ui/components/footer/ActionsFooter.tsx
  client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Footer/Footer.tsx
Labels: feature: GEDSI, Team Korimako

#5928 5431 when the supplier and the customer have different master list for the same program, you need to display the customer one when creating a manual requisition
  server/service/src/requisition/program_settings/common.rs
  server/service/src/requisition/program_settings/customer_program_settings/map.rs
  server/service/src/requisition/program_settings/customer_program_settings/prepare.rs
  server/service/src/requisition/program_settings/supplier_program_settings/map.rs
  server/service/src/requisition/program_settings/supplier_program_settings/prepare.rs
Labels: bug, Team Ruru 🦉, Severity: High, feature: manual requisition, feature: CIV

#5950 5949 Integration problem when syncing mSupply master lists for programs when no "elmisCode" set
  server/service/src/sync/translations/program_requisition_settings.rs
Labels: bug, Team Ruru 🦉

#5896 inbound shipment cost price is NaN
  client/packages/common/src/utils/arrays/ArrayUtils.test.ts
  client/packages/common/src/utils/arrays/ArrayUtils.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
Labels: bug, Severity: High, Team Korimako

#5940 5938 Move letter behind not android target flag
  server/Cargo.lock
  server/service/Cargo.toml
Labels: bug, platform: android

#5952 #5846 Fix Stock issue quantities for JSON Forms prescription
  client/packages/programs/src/JsonForms/components/Prescription/StockLineTable.tsx
Labels: bug, feature: programs, Team Piwakawaka, Severity: Normal

#5954 Move the ServerInfo component to the settings page
  client/packages/host/src/Admin/ServerInfo.tsx
  client/packages/host/src/Admin/Settings.tsx
  client/packages/host/src/components/AppVersion.tsx
  client/packages/host/src/components/Sync/ServerInfo.tsx
  client/packages/host/src/components/Sync/SyncModal.tsx
Labels: bug, Severity: Normal

#5936 5823 process contact forms to email queue
  server/Cargo.lock
  server/README.md
  server/repository/src/db_diesel/contact_form.rs
  server/repository/src/db_diesel/contact_form_row.rs
  server/repository/src/db_diesel/email_queue_row.rs
  server/repository/src/db_diesel/key_value_store.rs
  server/repository/src/db_diesel/user_row.rs
  server/repository/src/migrations/v2_05_00/mod.rs
  server/repository/src/migrations/v2_05_00/remove_contact_form_user_account_fk.rs
  server/repository/src/mock/contact_form.rs
  server/service/Cargo.toml
  server/service/src/contact_form/insert/generate.rs
  server/service/src/contact_form/insert/mod.rs
  server/service/src/contact_form/insert/validate.rs
  server/service/src/email/enqueue.rs
  server/service/src/email/mod.rs
  server/service/src/processors/contact_form/mod.rs
  server/service/src/processors/contact_form/queue_email.rs
  server/service/src/processors/contact_form/templates/contact.html
  server/service/src/processors/mod.rs
  server/service/src/processors/transfer/invoice/mod.rs
  server/service/src/processors/transfer/mod.rs
  server/service/src/processors/transfer/requisition/mod.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/test/test_data/contact_form.rs
  server/service/src/sync/translations/contact_form.rs
  server/service/src/test_helpers.rs
  server/util/src/constants.rs
Labels: feature: GEDSI, Team Korimako

#5960 5934 fix flatbutton shrink issue
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/buttons/FlatButton/FlatButton.tsx
  client/packages/common/src/ui/components/footer/ActionsFooter.tsx
  client/packages/programs/src/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/programs/src/ImmunisationProgramDetailView/Toolbar.tsx
  client/packages/programs/src/api/hooks/useDeleteSelectedVaccineCourses.ts
Labels: bug, Severity: High, Team Korimako

#5959 #5957 Remove duplicate "New item" link
  client/packages/system/src/Item/Components/ListItems/ListItems.tsx
Labels: bug, Team Piwakawaka, Severity: High, feature: dispensing

#5974 Update to use patientId instead of otherPartyId in dispensing
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
Labels: refactor, Team Piwakawaka

#5980 5979 Item ledger missing label
  client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx
Labels: bug, Team Ruru 🦉

#5976 Restore row expansion in prescription detail view
  client/packages/invoices/src/Prescriptions/DetailView/ContentArea.tsx
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Labels: bug, Severity: Normal, feature: dispensing

#5970 5919 Update app bar button to display disabled buttons clearly
  client/packages/common/src/ui/components/buttons/standard/BaseButton.tsx
  client/packages/common/src/ui/components/buttons/standard/ShrinkableBaseButton.tsx
Labels: bug, Severity: High, Team Korimako

#5958 Add generating with customer_name_id
  server/service/src/requisition/request_requisition/insert_program.rs
Labels: bug, Severity: Hotfix

#5983 create cold storage translation label
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Item/Components/ColdStorageTypeInput/ColdStorageTypeInput.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/Location/ListView/ListView.tsx
Labels: bug, Severity: Normal, Team Korimako

#5972 add confirmation modal for line allocation
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/OutboundShipment/api/hooks/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/useSelectedIds.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/useSelectedLines.ts
Labels: bug, Severity: High, docs: external, Team Korimako

#5988 5987 fix tests
  server/service/src/requisition/program_settings/customer_program_settings/map.rs
  server/service/src/requisition/program_settings/supplier_program_settings/map.rs
Labels: bug, Build Tested: Dev, Team Ruru 🦉

#5996 Query with user customer store name id
  client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
Labels: bug, needs daily triage

#5917 5673 civ 2.5 indicators for ds internal orders
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/strings/IntlStrings.ts
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/columns/types.ts
  client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
  client/packages/common/src/ui/layout/tables/components/index.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/CustomerIndicatorInfo.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/utils.ts
  client/packages/system/src/Name/ListView/ImportProperties/ImportReviewDataTable.tsx
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/program_indicator_value.rs
  server/graphql/core/src/loader/requisition_indicator_information.rs
  server/graphql/requisition/src/program_indicator.rs
  server/graphql/types/src/types/program/mod.rs
  server/graphql/types/src/types/program/program_indicator.rs
  server/graphql/types/src/types/program/requisition_indicator_info.rs
  server/repository/src/db_diesel/indicator_value.rs
  server/service/src/requisition/indicator_value/update.rs
  server/service/src/requisition/mod.rs
  server/service/src/requisition/request_requisition/indicator_information.rs
  server/service/src/requisition/request_requisition/insert_program.rs
  server/service/src/requisition/request_requisition/mod.rs
  server/service/src/sync/translations/indicator_value.rs
Labels: enhancement, Team Ruru 🦉, feature: CIV

#5994 5925 test mail connection
  server/README.md
  server/cli/src/test_connection.rs
  server/service/src/lib.rs
Labels: enhancement, feature: GEDSI, Team Korimako

#5993 5669 Fix patient lookup failure
  client/packages/system/src/Patient/CreatePatientModal/FetchPatientModal.tsx
  client/packages/system/src/Patient/CreatePatientModal/useFetchPatient.ts
Labels: bug, Severity: High, Team Korimako

#5971 5368 Fix ledger with migrated cancelled invoices
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/translations/invoice_line.rs
Labels: bug, Migrate Existing Desktop, Team Ruru 🦉, Severity: High

#5975 5620 Add index to sync buffer
  package.json
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_06_00/add_index_to_sync_buffer.rs
  server/repository/src/migrations/v2_06_00/mod.rs
Labels: bug, Team Ruru 🦉, Severity: High

#6003 5886 improve logout modal
  client/packages/host/src/components/Footer/UserDetails.tsx
Labels: bug, Severity: Low, feature: GEDSI, Effort: small, Team Korimako

#6010 Update cost per unit when items not grouped
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
Labels: bug, good first issue, Severity: Normal, Tester: Alain, Team Korimako

#6017 6016 add pg enum type for contact form processor cursor
  server/repository/src/migrations/v2_05_00/add_contact_form_processor_pg_enum_type.rs
  server/repository/src/migrations/v2_05_00/mod.rs
Labels: bug, Severity: Hotfix, feature: GEDSI, Team Korimako

#6024 #5977 Ability to clear clinician name
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescription.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionLines.ts
  server/graphql/invoice/src/mutations/prescription/update.rs
  server/service/src/invoice/prescription/update/generate.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/invoice/prescription/update/validate.rs
  server/service/src/vaccination/generate.rs
Labels: bug, Team Piwakawaka, Severity: Normal, feature: dispensing

#6026 Update route to navigate to portuguese docs when lang is portuguese
  client/packages/config/src/routes.ts
Labels: bug, Severity: Normal, feature: GEDSI, Team Korimako

#6028 #6014 Handle date change properly
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.tsx
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalProvider.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
Labels: bug, Team Piwakawaka, Severity: Hotfix, feature: dispensing

#6027 5424 Add modifiers to the CMD+K global shortcuts
  client/packages/host/src/CommandK.tsx
Labels: enhancement, good first issue, Priority: Should have, Team Ruru 🦉, docs: external

#5955 5933 update backend crates
  server/Cargo.lock
  server/Cargo.toml
  server/android/Cargo.toml
  server/repository/Cargo.toml
  server/server/Cargo.toml
  server/server/src/logging.rs
  server/service/Cargo.toml
  server/service/src/document/document_service.rs
  server/service/src/programs/contact_trace/upsert.rs
  server/service/src/programs/encounter/insert.rs
  server/service/src/programs/encounter/update.rs
  server/service/src/programs/patient/upsert_program_patient.rs
  server/service/src/programs/program_enrolment/upsert.rs
  server/util/Cargo.toml
Labels: enhancement, back-end, Build Tested: Dev, Team Ruru 🦉

#6022 5582 Add rounding to internal order request edit
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Labels: bug, Severity: Normal, Team Korimako

#6004 Update customer requisition warning to show correct message
  client/packages/common/src/intl/locales/en/common.json
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useDeleteSelectedRequisitions.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useDeleteSelectedResponseRequisitions.ts
Labels: bug, Severity: Low, Effort: small, Team Korimako

#6072 #5696 Add requested to tetum
  client/packages/common/src/intl/locales/tet/common.json
Labels: bug, needs triage, Build Tested: Issues Found, Tester: Maria, Team Ruru 🦉, Team Piwakawaka, Severity: Hotfix, needs daily triage

#6071 6070 Localise ledger date + fix adjustment calculation
  server/service/src/requisition/request_requisition/requisition_item_info.rs
Labels: bug, Team Ruru 🦉

#6099 Remove extra div
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/system/src/Item/Components/ListItems/ListItems.tsx
Labels: bug, Team Ruru 🦉, Severity: High

#6104 #6083 #6090 #6061 #6059 Prescription hotfixes x4
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditTable.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/usePrescriptionLineEditRows.ts
  client/packages/invoices/src/StockOut/utils.tsx
Labels: bug, Team Piwakawaka, Severity: Hotfix, feature: dispensing

#6020 IO extra columns show with use consumption data pref
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Labels: bug, Team Ruru 🦉, feature: CIV

#6117 6100 Log events need standardising
  client/packages/common/src/intl/locales/en/common.json
Labels: bug, Severity: Low, UI tweaks

#6113 6092 Add icon and update shouldShrink
  client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
  client/packages/system/src/Stock/DetailView/Footer.tsx
Labels: bug, Severity: Normal, feature: GEDSI, Team Korimako, UI tweaks

#6089 Get invoice line cost/sell price instead of stock line
  server/repository/src/migrations/views/mod.rs
Labels: bug, Team Ruru 🦉, Severity: High

#6058 Fix error boundary
  client/packages/common/src/ui/components/errors/GenericErrorFallback.tsx
  client/packages/host/src/Host.tsx
Labels: bug, Severity: High, Team Korimako

#6131 6114 adding new asset crashes
  client/packages/system/src/Store/components/StoreSearchInput/StoreSearchInput.tsx
Labels: bug, Severity: Hotfix, Team Korimako

#6127 #6078 Prevent unnecessary scrolling
  client/packages/common/src/ui/components/navigation/ListOptions/ListOptions.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/NavBar.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/Footer.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/Footer.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorEditPage.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/common/ListIndicators.tsx
  client/packages/system/src/Item/Components/ListItems/ListItems.tsx
Labels: bug, Team Piwakawaka, Severity: Hotfix, feature: dispensing

#6133 6128 Internal order editing requested packs does not save changes
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Labels: bug, Team Ruru 🦉, feature: CIV

#5962 Update picked_date when adding or updating lines in prescriptions
  server/service/src/invoice/common.rs
  server/service/src/invoice/mod.rs
  server/service/src/invoice/prescription/update/generate.rs
  server/service/src/invoice/update_picked_date.rs
  server/service/src/invoice_line/stock_out_line/insert/mod.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
  server/service/src/processors/transfer/invoice/update_inbound_invoice.rs
Labels: bug, Team Piwakawaka, Severity: High

#6129 6075 'Invoice Number' column can be clearer
  client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx
  client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
Labels: enhancement, Team Ruru 🦉, Severity: Low, needs design, docs: external, UI tweaks

#6134 5986 Add migration to drop user_account fk constraint
  server/repository/src/migrations/v2_05_00/mod.rs
  server/repository/src/migrations/v2_05_00/remove_vaccination_user_account_fk.rs
Labels: bug, Severity: Hotfix, Team Korimako

#6154 #5977(2) Fix prescription update tests
  server/graphql/invoice/src/mutations/prescription/update.rs
  server/service/src/invoice/prescription/update/mod.rs
Labels: bug, Build Tested: Passed, Tester: Anusha, Team Piwakawaka, Severity: Normal, feature: dispensing

#6143 6088 dispensary directions popover shows batch but unclear this is batch
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Labels: bug, Team Piwakawaka, Severity: High, feature: dispensing, Effort: small, UI tweaks

#6009 5567 add soft delete for programs
  server/repository/src/db_diesel/program_requisition/program.rs
  server/repository/src/db_diesel/program_requisition/program_requisition_settings.rs
  server/repository/src/db_diesel/program_requisition/program_row.rs
  server/repository/src/migrations/v2_06_00/add_program_deleted_datetime.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/repository/src/mock/program.rs
  server/service/src/program/test/query.rs
  server/service/src/sync/test/test_data/program_requisition_settings.rs
  server/service/src/sync/translations/program_requisition_settings.rs
Labels: bug, feature: programs, Severity: High

#6171 5155 patient info update not showing in prescription
  client/packages/host/src/components/Sync/SyncModal.tsx
  client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx
Labels: bug, good first issue, make omSupply delightful, Severity: Normal, Team Korimako

#6120 5102 cannot change servers tablet
  client/packages/host/src/components/SiteInfo.tsx
Labels: bug, Severity: High, Team Korimako

#6195 6147 Indicators details show Nothing here where there is no customer to show. This text should be hidden
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
Labels: bug, Team Ruru 🦉

#6054 4015 Allow filtering "View Stock Page" by master list
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/api/hooks/useStockList.ts
Labels: enhancement, good first issue, Priority: Nice to Have, Build Tested: Issues Found, Tester: Maria, Team Ruru 🦉, needs design, docs: external

#5998 3813 Retry api on connection error or timeout
  server/Cargo.lock
  server/service/src/sync/api/core.rs
  server/service/src/sync/api_v6/core.rs
  server/util/Cargo.toml
  server/util/src/api_helper.rs
  server/util/src/lib.rs
Labels: bug, Severity: High, Needs Investigation

#6198 5818 Creating a new encounter does not take you to a newly created encounter, instead keeps you on a landing page
  client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
Labels: bug, feature: programs, Team Ruru 🦉, Severity: Normal

#6202 6146 for ivory coast, indicators should not be included in emergency orders
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  server/graphql/types/src/types/requisition.rs
  server/repository/src/db_diesel/requisition/requisition_row.rs
  server/repository/src/migrations/v2_05_00/add_requisition_is_emergency.rs
  server/repository/src/migrations/v2_05_00/mod.rs
  server/service/src/processors/transfer/requisition/create_response_requisition.rs
  server/service/src/requisition/request_requisition/insert.rs
  server/service/src/requisition/request_requisition/insert_program.rs
  server/service/src/requisition/response_requisition/insert.rs
  server/service/src/requisition/response_requisition/insert_program.rs
  server/service/src/rnr_form/finalise.rs
  server/service/src/sync/test/test_data/requisition.rs
  server/service/src/sync/translations/requisition.rs
Labels: bug, Team Ruru 🦉

#6207 6199 Able to add items to a non-manual requisition
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#6170 4707 automate android build
  .github/workflows/build-android-apk.yaml
Labels: Priority: Must Have, Tooling, Team Korimako

#6201 Invalidate Graphql Queries After Sync
  client/packages/host/src/components/Sync/SyncModal.tsx
Labels: enhancement, sync v5, Priority: Should have, Team Korimako

#6194 5121 Floor decimal quantity to return
  client/packages/invoices/src/Returns/modals/SupplierReturn/ReturnQuantitiesTable.tsx
Labels: bug, good first issue, Severity: Normal, Team Korimako

#6190 5943 inform users why actions are disabled
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/footer/ActionsFooter.tsx
  client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/Footer/Footer.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Footer/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/Footer.tsx
Labels: enhancement, Priority: Should have, Team Korimako

#6209 Catch panic in discovery
  server/server/src/discovery.rs
Labels: bug, Team Piwakawaka, Severity: High

#6213 Hack: Always use base year 2024 for demographic projections
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/utils.tsx
Labels: bug, Team Piwakawaka, Severity: Hotfix

#6225 Item variants: Packaging tables ordering
  server/repository/src/db_diesel/item_variant/packaging_variant.rs
Labels: bug, Severity: Normal, feature: GAPS, Team Korimako

#6236 6119/6212 Disable next button when adding new item (internal order + manual requisition)
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/hooks.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
Labels: bug, Severity: High, Effort: small, Team Korimako

#6065 5009 mobile modal improvements
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/useDialog/useDialog.tsx
  client/packages/common/src/hooks/useKeyboard/Keyboard.tsx
  client/packages/common/src/hooks/useKeyboard/index.ts
  client/packages/common/src/hooks/useKeyboardHeightAdjustment/index.ts
  client/packages/common/src/hooks/useKeyboardHeightAdjustment/useKeyboardHeightAdjustment.ts
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/utils.tsx
  client/packages/common/src/ui/components/modals/BasicModal/BasicModal.tsx
  client/packages/common/src/ui/components/modals/InputModal/InputModal.tsx
  client/packages/common/src/ui/components/portals/AppFooter/AppFooter.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditModal.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
  client/packages/invoices/src/Returns/modals/CustomerReturn/CustomerReturn.tsx
  client/packages/invoices/src/Returns/modals/SupplierReturn/SupplierReturn.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/requisitions/src/RnRForms/DetailView/Footer.tsx
  client/packages/system/src/Item/Components/ItemOptionRenderer/ItemOptionRenderer.tsx
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/BundledItemModal.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
  client/packages/system/src/Name/ListView/Facilities/FacilityEditModal.tsx
  client/packages/system/src/Name/ListView/ListView.tsx
  client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
  client/packages/system/src/Report/components/ReportArgumentsModal.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
Labels: Priority: Must Have, refactor, Team Korimako

#6232 fix internal order value after backspace
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Labels: bug, Severity: Hotfix, Team Korimako

#6166 6162 in stock and available show wrong numbers once the prescription is saved
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/useDraftPrescriptionLines.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionLines.ts
  client/packages/invoices/src/StockOut/utils.tsx
  client/packages/system/src/Item/api/hooks/useHistoricalStockLines/useHistoricalStockLines.tsx
  client/packages/system/src/Item/api/keys.ts
Labels: bug, Severity: Hotfix, feature: dispensing

#6249 Don't convert dob to naivedate
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
Labels: bug, Team Ruru 🦉, Severity: High

#6025 5079 remove raw graphql error from snacks
  client/packages/common/src/hooks/useNotification/useNotification.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/host/src/QueryErrorHandler.tsx
Labels: bug, Severity: Normal, Team Korimako

#6237 6085 use path in report building cli
  server/cli/src/cli.rs
  server/report_builder/src/build.rs
  server/report_builder/src/lib.rs
Labels: bug, Team Ruru 🦉, Severity: High, feature: reports

#6228 5293 backspace autocomlete
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
  client/packages/system/src/Item/Components/StockItemSearchInputWithStats/StockItemSearchInputWithStats.tsx
  client/packages/system/src/Item/Components/StockItemSearchInputWithStats/index.ts
  client/packages/system/src/Item/Components/StockItemSelectModal/StockItemSelectModal.tsx
  client/packages/system/src/Item/Components/StockItemSelectModal/index.ts
  client/packages/system/src/Item/Components/index.ts
  client/packages/system/src/Item/utils.ts
Labels: bug, Severity: High, Team: Kororā

#5997 Add generate transfer requisition indicator values
  server/service/src/processors/transfer/requisition/create_response_requisition.rs
Labels: bug, Team Ruru 🦉, Severity: High

#6259 6015 sync pull and push tests failing
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/test/test_data/requisition.rs
  server/service/src/sync/translations/program_requisition_settings.rs
Labels: bug, Severity: High, Team: Kororā

#5929 Change amc plugin interface to take item_ids list instead of filter
  server/graphql/core/src/loader/item_stats.rs
  server/service/src/backend_plugin/examples/amc/amc.js
  server/service/src/backend_plugin/types/amc.rs
  server/service/src/dashboard/item_count.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
  server/service/src/item_stats.rs
  server/service/src/requisition/request_requisition/generate.rs
Labels: enhancement, Team Ruru 🦉, feature: plugin

#6276 6272 move status change to footer
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/Footer.tsx
  client/packages/system/src/Encounter/DetailView/SidePanel.tsx
  client/packages/system/src/Encounter/DetailView/StatusChangeButton.tsx
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
Labels: feature: vaccine card, Team: Kororā

#6245 5147 fix on hold items counted towards available stock
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.ts
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/useDraftPrescriptionLines.tsx
  client/packages/invoices/src/StockOut/utils.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#6288 Change the button style (orange text on white) to have black text
  client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx
  client/packages/coldchain/src/Monitoring/ListView/AppBarButtons.tsx
  client/packages/common/src/ui/components/buttons/standard/LoadingButton.tsx
  client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
  client/packages/system/src/Patient/PatientView/AddButton.tsx
Labels: Build Tested: Issues Found, Tester: Maria, feature: GEDSI, Build Tested: Needs Retesting, Team: Kororā

#6211 6144 add check for exceeding max orders
  client/packages/common/src/intl/locales/en/common.json
  client/packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx
  client/packages/requisitions/src/RequestRequisition/api/api.ts
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useInsertProgramRequest.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  client/packages/requisitions/src/ResponseRequisition/ListView/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useInsertProgramResponse.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  server/service/src/requisition/common.rs
  server/service/src/requisition/request_requisition/insert_program.rs
  server/service/src/requisition/response_requisition/insert.rs
  server/service/src/requisition/response_requisition/insert_program.rs
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#6303 update icon color to white on orange buttons
  client/packages/common/src/ui/components/buttons/standard/ShrinkableBaseButton.tsx
Labels: bug, make omSupply delightful, Severity: Low, feature: GEDSI, UI tweaks, Team: Kororā

#6231 5122 fix user can create shipment from requisition without permission set
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/CreateShipmentButton.tsx
  server/graphql/requisition/src/mutations/response_requisition/create_requisition_shipment.rs
  server/graphql/tests/permissions.rs
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v2_06_00/add_create_invoice_from_requisition_permission.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/service/src/auth.rs
  server/service/src/login.rs
Labels: bug, back-end, Severity: Low, Team Korimako

#6325 6287 fix missing item value
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
Labels: Severity: High, Team: Kororā

#5892 5826-Plugin-base
  server/Cargo.lock
  server/Cargo.toml
  server/graphql/core/src/loader/item_stats.rs
  server/graphql/general/src/queries/item_counts.rs
  server/graphql/requisition/src/mutations/request_requisition/add_from_master_list.rs
  server/graphql/requisition/src/mutations/request_requisition/insert_program.rs
  server/graphql/requisition_line/src/mutations/request_requisition_line/insert.rs
  server/repository/src/db_diesel/filter_sort_pagination.rs
  server/repository/src/db_diesel/mod.rs
  server/server/Cargo.toml
  server/server/src/lib.rs
  server/server/src/upload_plugin.rs
  server/service/Cargo.toml
  server/service/src/backend_plugin/boajs/call_plugin.rs
  server/service/src/backend_plugin/boajs/methods/log.rs
  server/service/src/backend_plugin/boajs/methods/mod.rs
  server/service/src/backend_plugin/boajs/methods/sql.rs
  server/service/src/backend_plugin/boajs/methods/sql_type.rs
  server/service/src/backend_plugin/boajs/mod.rs
  server/service/src/backend_plugin/boajs/utils.rs
  server/service/src/backend_plugin/examples/amc/amc.js
  server/service/src/backend_plugin/mod.rs
  server/service/src/backend_plugin/plugin_provider.rs
  server/service/src/backend_plugin/types/amc.rs
  server/service/src/backend_plugin/types/mod.rs
  server/service/src/dashboard/item_count.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
  server/service/src/item_stats.rs
  server/service/src/lib.rs
  server/service/src/requisition/request_requisition/add_from_master_list.rs
  server/service/src/requisition/request_requisition/generate.rs
  server/service/src/requisition/request_requisition/insert_program.rs
  server/service/src/requisition_line/request_requisition_line/insert.rs
Labels: enhancement, Team Ruru 🦉, feature: plugin

#5898 5827-Backend-plugin-table
  server/repository/src/db_diesel/backend_plugin_row.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_06_00/backend_plugins.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/repository/src/mock/mod.rs
  server/server/src/upload_plugin.rs
  server/service/src/backend_plugin/examples/amc/amc.js
  server/service/src/backend_plugin/plugin_provider.rs
  server/service/src/item_stats.rs
  server/service/src/sync/test/test_data/backend_plugin.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/backend_plugin.rs
  server/service/src/sync/translations/mod.rs
Labels: enhancement, Team Ruru 🦉, feature: plugin

#5924 5828.1 Backend provision for uploading and installing plugin
  server/Cargo.lock
  server/cli/Cargo.toml
  server/cli/src/cli.rs
  server/cli/src/plugins.rs
  server/graphql/lib.rs
  server/graphql/plugin/Cargo.toml
  server/graphql/plugin/src/lib.rs
  server/graphql/plugin/src/mutations/install.rs
  server/graphql/plugin/src/mutations/mod.rs
  server/graphql/plugin/src/queries/mod.rs
  server/graphql/plugin/src/queries/uploaded_info.rs
  server/server/src/lib.rs
  server/server/src/upload.rs
  server/server/src/upload_plugin.rs
  server/service/src/auth.rs
  server/service/src/backend_plugin/examples/amc/amc.js
  server/service/src/backend_plugin/examples/amc/plugin_manifest.json
  server/service/src/backend_plugin/plugin_provider.rs
  server/service/src/lib.rs
  server/service/src/plugin/mod.rs
  server/service/src/requisition/request_requisition/insert_program.rs
  server/service/src/service_provider.rs
  server/service/src/test_helpers.rs
Labels: enhancement, Team Ruru 🦉, feature: plugin

#6286 fix confirm on leaving with multiple blockers
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Monitoring/ListView/AppBarButtons.tsx
  client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.stories.tsx
  client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
  client/packages/common/src/ui/components/navigation/Tabs/DetailTabs.tsx
  client/packages/host/src/Site.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/programs/src/JsonForms/useFormActions.tsx
  client/packages/programs/src/JsonForms/useJsonFormsHandler.tsx
  client/packages/requisitions/src/RnRForms/DetailView/DetailView.tsx
Labels: feature: vaccine card, Team: Kororā

#6328 6292 cant backspace/change patient
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx
Labels: bug, Severity: Normal, Team: Kororā

#6326 6159 add filters to prescription list view
  client/packages/common/src/hooks/useUrlQuery/useUrlQueryParams.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
  client/packages/invoices/src/Prescriptions/ListView/Toolbar.tsx
Labels: Team Piwakawaka, feature: dispensing

#6307 6304 translate next of kin id
  server/Cargo.lock
  server/repository/src/db_diesel/name_row.rs
  server/repository/src/migrations/v2_06_00/add_name_next_of_kin_id.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/service/src/programs/patient/patient_updated.rs
  server/service/src/sync/test/test_data/name.rs
  server/service/src/sync/translations/name.rs
Labels: feature: vaccine card, Team: Kororā :penguin:

#6293 6261 mark as visited on change
  client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModal.tsx
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalContext.ts
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalProvider.tsx
  client/packages/common/src/ui/components/modals/ConfirmationModal/useConfirmationModal.ts
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/StatusChangeButton.tsx
  client/packages/system/src/Vaccination/Components/VaccinationCard.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
Labels: feature: vaccine card, Team: Kororā :penguin:

#6296 6262 schdule next encounter modal
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/ScheduleNextEncounterModal.tsx
  client/packages/system/src/Patient/Encounter/CreateEncounterForm.tsx
  client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
  client/packages/system/src/Patient/Encounter/index.ts
Labels: feature: vaccine card, Team: Kororā :penguin:

#6302 6263 suggest next date from vax card
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/ScheduleNextEncounterModal.tsx
  client/packages/system/src/Encounter/DetailView/helpers.test.ts
  client/packages/system/src/Encounter/DetailView/helpers.ts
Labels: feature: vaccine card, Team: Kororā :penguin:

#6309 6305 add next of kin to patient schema
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  server/graphql/types/src/types/program/patient.rs
  server/service/src/programs/patient/patient_schema.rs
  server/service/src/programs/patient/patient_updated.rs
  server/service/src/programs/schemas/patient.json
Labels: feature: vaccine card, Team: Kororā :penguin:

#6348 6338 fix autocompletes
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
Labels: Severity: High, Team: Kororā :penguin:

#6346 6281 add optional path to cli
  server/cli/src/cli.rs
  server/report_builder/README.md
  server/service/src/standard_reports.rs
Labels: enhancement, Severity: Hotfix, feature: reports

#6350 6230 not all periods shows up on first load
  client/packages/common/src/intl/locales/en/common.json
  client/packages/requisitions/src/RequestRequisition/ListView/ProgramRequisitionOptions.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ProgramRequisitionOptions.tsx
  server/service/src/requisition/program_settings/common.rs
Labels: bug, Team Ruru 🦉, Severity: Hotfix

#6269 6177 create patient from prescription window
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/ListView/AppBarButtons.tsx
  client/packages/system/src/Patient/Components/PatientSearchModal/PatientSearchModal.tsx
  client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
  client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Patient/utils.ts
Labels: Team Piwakawaka, feature: dispensing

#6339 6306 add next of kin to patient edit
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/JsonForms/components/PatientSearch.tsx
  client/packages/programs/src/JsonForms/components/index.ts
  client/packages/programs/src/JsonForms/useJsonFormsHandler.tsx
  client/packages/system/src/Patient/PatientView/DefaultPatientSchema.json
  client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  client/packages/system/src/Patient/index.ts
  server/graphql/programs/src/mutations/patient/insert.rs
  server/graphql/programs/src/mutations/patient/update.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/service/src/programs/patient/insert_patient.rs
  server/service/src/programs/patient/update_patient.rs
Labels: feature: vaccine card, Team: Kororā :penguin:

#6351 6251 filter by next of kin name
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Patient/ListView/ListView.tsx
  client/packages/system/src/Patient/ListView/Toolbar.tsx
  server/graphql/types/src/types/program/patient.rs
  server/repository/src/db_diesel/patient.rs
Labels: feature: vaccine card, Team: Kororā :penguin:

#6247 5675.1 pass requisition id on insert inbound
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  server/graphql/invoice/src/mutations/inbound_shipment/insert.rs
  server/service/src/invoice/inbound_shipment/insert/generate.rs
  server/service/src/invoice/inbound_shipment/insert/mod.rs
  server/service/src/invoice/inbound_shipment/insert/validate.rs
Labels: enhancement, Team Ruru 🦉, feature: CIV

#6357 Main to dev
  client/packages/common/src/intl/locales/en/common.json
  client/packages/requisitions/src/RequestRequisition/ListView/ProgramRequisitionOptions.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ProgramRequisitionOptions.tsx
  server/service/src/requisition/program_settings/common.rs
Labels: Build Tested: Dev

#6241 5080 allow manual config of server url in desktop
  client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/discovery/ManualServerConfig.tsx
  client/packages/common/src/ui/discovery/ServerDiscovery.tsx
Labels: enhancement, Team Piwakawaka, Severity: High

#6330 5675.2 link requisition modal
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
  client/packages/invoices/src/InboundShipment/ListView/LinkInternalOrderModal.tsx
  client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/hooks/document/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/document/useListInternalOrders.ts
  client/packages/invoices/src/InboundShipment/api/hooks/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/utils/useInboundApi.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
Labels: enhancement, Team Ruru 🦉, feature: CIV

#6363 Add config option to disable discovery
  server/android/src/android.rs
  server/configuration/base.yaml
  server/configuration/example.yaml
  server/server/src/lib.rs
  server/service/src/settings.rs
  server/service/src/test_helpers.rs
Labels: bug, Team Piwakawaka, Severity: High

#6313 6203 sync and translate for insuranceprovider table
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/insurance_provider_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_06_00/add_insurance_provider.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/service/src/sync/test/test_data/insurance_provider.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/insurance_provider.rs
  server/service/src/sync/translations/mod.rs
Labels: Team Piwakawaka, feature: dispensing
