Repository msupply-foundation/open-msupply, pull requests merged in 2025-05, with the labels that each got.

#7522 7145 prefs refactor
  client/packages/common/src/authentication/api/hooks/index.ts
  client/packages/common/src/authentication/api/hooks/useAuthApi.ts
  client/packages/common/src/authentication/api/hooks/usePreference.ts
  client/packages/common/src/authentication/api/hooks/usePreferences.ts
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.graphql
  client/packages/common/src/intl/locales/ar/common.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/index.ts
  client/packages/config/src/routes.ts
  client/packages/host/src/components/Navigation/ManageNav.tsx
  client/packages/system/src/Manage/Preferences/EditPage/EditField.tsx
  client/packages/system/src/Manage/Preferences/EditPage/EditPreference.tsx
  client/packages/system/src/Manage/Preferences/EditPage/EditPreferencesPage.tsx
  client/packages/system/src/Manage/Preferences/EditPage/LineEditBase.tsx
  client/packages/system/src/Manage/Preferences/api/index.ts
  client/packages/system/src/Manage/Preferences/api/keys.ts
  client/packages/system/src/Manage/Preferences/api/operations.generated.ts
  client/packages/system/src/Manage/Preferences/api/operations.graphql
  client/packages/system/src/Manage/Preferences/api/useAdminPrefsList.ts
  client/packages/system/src/Manage/Preferences/api/useAvailablePreferences.ts
  client/packages/system/src/Manage/Preferences/api/useEditPreference.ts
  client/packages/system/src/Manage/Service/Service.tsx
  client/packages/system/src/Patient/PatientView/AddButton.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  server/Cargo.lock
  server/graphql/preference/Cargo.toml
  server/graphql/preference/src/lib.rs
  server/graphql/preference/src/upsert.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/preferences.rs
  server/service/Cargo.toml
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/README.md
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/preferences/show_contact_tracing.rs
  server/service/src/preference/preferences/types.rs
  server/service/src/preference/query_preference.rs
  server/service/src/preference/types.rs
  server/service/src/preference/upsert.rs
  server/service/src/preference/upsert_helpers.rs
  server/service/src/sync/translations/preference.rs
Labels: refactor, Team Ruru 🦉

#7537 Add VVM status table to server
  package.json
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/lib.rs
  server/graphql/vvm/Cargo.toml
  server/graphql/vvm/src/lib.rs
  server/graphql/vvm/src/queries/mod.rs
  server/graphql/vvm/src/queries/vvm_status.rs
  server/graphql/vvm/src/types/mod.rs
  server/graphql/vvm/src/types/vvm_status.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/vvm_status_row.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_08_00/add_vvm_status_table.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
  server/service/src/vvm/mod.rs
  server/service/src/vvm/vvm_status/mod.rs
  server/service/src/vvm/vvm_status/query.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7536 #7372 Implement "Display population based forecasting" preference
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Manage/Preferences/api/operations.generated.ts
  client/packages/system/src/Manage/Preferences/api/operations.graphql
  server/graphql/preference/src/upsert.rs
  server/graphql/types/src/types/preferences.rs
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/display_population_based_forecasting.rs
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/types.rs
  server/service/src/preference/upsert.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7562 7511 Fix unable to save stocktake line for an item
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useDraftStocktakeLines.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeLines.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts
  server/graphql/stocktake_line/src/stocktake_line_queries.rs
  server/repository/src/db_diesel/stocktake_line.rs
Labels: Team Piwakawaka, Severity: High

#7576 Set isLocal to false for manual server config
  client/packages/common/src/ui/discovery/ManualServerConfig.tsx
Labels: Team Piwakawaka, Severity: High

#7567 5537 supplier return item search autocomplete not scrolling
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditForm.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Returns/modals/SupplierReturn/ItemSelector.tsx
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
  client/packages/system/src/Item/api/api.ts
  client/packages/system/src/Item/api/hooks/useItemStockOnHand/useItemStockOnHand.tsx
  client/packages/system/src/Item/utils.ts
  server/graphql/general/src/queries/item.rs
  server/repository/src/db_diesel/item.rs
Labels: bug, Build Tested: Issues Found, Tester: Maria, Team Ruru 🦉, Severity: High, Build Tested: Needs Retesting

#7550 1169 store pref edit UI
  client/packages/common/src/hooks/useDialog/useDialog.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Manage/Preferences/EditPage/EditPreference.tsx
  client/packages/system/src/Manage/Preferences/EditPage/EditPreferencesPage.tsx
  client/packages/system/src/Manage/Preferences/EditPage/index.ts
  client/packages/system/src/Manage/Preferences/api/index.ts
  client/packages/system/src/Manage/Preferences/api/operations.generated.ts
  client/packages/system/src/Manage/Preferences/api/operations.graphql
  client/packages/system/src/Manage/Preferences/api/useAdminPrefsList.ts
  client/packages/system/src/Manage/Preferences/api/useEditPreference.ts
  client/packages/system/src/Manage/Preferences/index.ts
  client/packages/system/src/Name/ListView/Facilities/EditStorePreferences.tsx
  client/packages/system/src/Name/ListView/Facilities/FacilityEditModal.tsx
  client/packages/system/src/Name/ListView/Facilities/FacilityProperties.tsx
  client/packages/system/src/Name/ListView/Facilities/useDraftFacilityProperties.tsx
  server/graphql/preference/src/lib.rs
  server/graphql/preference/src/upsert.rs
  server/graphql/types/src/types/preferences.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/display_vaccine_in_doses.rs
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/types.rs
  server/service/src/preference/upsert.rs
Labels: enhancement, Priority: Must Have, Team Ruru 🦉, feature: dose management

#7542 7373 population based forecasting store property edit population
  client/packages/common/src/intl/locales/ar/common.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/host/src/Admin/ConfigurationSettings.tsx
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
  client/packages/host/src/api/hooks/settings/namePropertyKeys.ts
  client/packages/host/src/api/hooks/settings/useConfigureNameProperties.ts
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7556 7548 sync vvm status
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/vvm_status.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/vvm_status.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7584 7569 FIx JSON Form telephone field
  client/packages/programs/src/JsonForms/common/components/Text.tsx
  client/packages/programs/src/JsonForms/common/hooks/useJSONFormsCustomError.ts
Labels: Team Piwakawaka, Severity: High

#7623 70 the toggle 'record stock transaction for past vaccination' doesn't work when a stockline is ticked
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/inputs/Switch/Switch.tsx
  client/packages/system/src/Vaccination/Components/SelectBatch.tsx
  client/packages/system/src/Vaccination/Components/SelectItemAndBatch.tsx
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/service/src/vaccination/insert/validate.rs
  server/service/src/vaccination/update/generate.rs
  server/service/src/vaccination/update/validate.rs
Labels: bug, Team Ruru 🦉, Severity: Hotfix, feature: vaccine card

#7407 6705 master list name hidden swap select for autocomplete
  client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
  client/packages/system/src/MasterList/Components/MasterListSearchInput.tsx
  client/packages/system/src/MasterList/Components/index.ts
Labels: Team Ruru 🦉, Severity: Normal

#7523 Update component property
  client/packages/host/src/CommandK.tsx
Labels: Tester: Maria, Severity: Normal, Build Tested: Needs Retesting, UI tweaks, feature: translation

#7626 7604 add doses per unit & vvm type to item variant table
  server/graphql/item_variant/src/mutations/upsert.rs
  server/repository/src/db_diesel/item_variant/item_variant.rs
  server/repository/src/db_diesel/item_variant/item_variant_row.rs
  server/repository/src/db_diesel/item_variant/packaging_variant.rs
  server/repository/src/migrations/v2_08_00/add_doses_columns_to_item_variant.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/repository/src/mock/item_variant.rs
  server/service/src/item/item_variant/upsert.rs
  server/service/src/sync/test/test_data/item_variant.rs
Labels: Build Tested: Dev, Team Ruru 🦉, feature: item variant

#7612 7605 Add fallback to handle undefined value - fix crash on backspace NewStocklineModal
  client/packages/common/src/intl/utils/DateUtils.test.ts
  client/packages/system/src/Stock/Components/StockLineForm.tsx
Labels: Team Ruru 🦉, Severity: Hotfix, feature: inventory adjustments

#7632 Fix french translations not refreshing
  client/packages/common/src/intl/context/IntlContext.tsx
Labels: Team Piwakawaka, Needs Investigation, feature: translation

#7665 7663 show years for display age utils
  client/packages/common/src/intl/utils/DateUtils.ts
Labels: feature: vaccine card

#7621 69 internal rnr search
  client/packages/common/src/ui/components/inputs/SearchBar/SearchBar.tsx
  client/packages/common/src/ui/layout/tables/index.ts
  client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
  client/packages/requisitions/src/RnRForms/DetailView/Footer.tsx
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/requisitions/src/RnRForms/DetailView/Search.tsx
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts
  client/packages/requisitions/src/RnRForms/utils.ts
Labels: enhancement, needs triage, feature: R&R

#7620 7601 Send tab on enter in RnR form on tablet
  client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
  client/packages/common/src/hooks/useNativeClient/types.ts
  client/packages/common/src/hooks/useNativeClient/useNativeClient.ts
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
Labels: enhancement, needs triage, feature: R&R

#7629 7608 Remove confirm, strength and navigate to error when finalising
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/common/src/ui/components/inputs/SearchBar/SearchBar.tsx
  client/packages/requisitions/src/RnRForms/DetailView/ContentArea.tsx
  client/packages/requisitions/src/RnRForms/DetailView/DetailView.tsx
  client/packages/requisitions/src/RnRForms/DetailView/Footer.tsx
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/requisitions/src/RnRForms/DetailView/Search.tsx
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts
Labels: enhancement, needs triage, feature: R&R

#7637 7363 RnR From demo related, search by starts with make adjustment numeric input
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/requisitions/src/RnRForms/DetailView/Search.tsx
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts
  client/packages/requisitions/src/RnRForms/utils.ts
Labels: enhancement, needs triage, feature: R&R

#7571 7348 dose management display doses in inbound and prescriptions
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/layout/tables/columns/DosesPerUnitColumn/DosesPerUnitColumn.test.ts
  client/packages/common/src/ui/layout/tables/columns/DosesPerUnitColumn/DosesPerUnitColumn.tsx
  client/packages/common/src/ui/layout/tables/columns/DosesPerUnitColumn/index.ts
  client/packages/common/src/ui/layout/tables/columns/index.ts
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/invoices/src/DoseQtyColumn.tsx
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/ContentArea.tsx
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/utils.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/line/useInboundRows.ts
  client/packages/invoices/src/InboundShipment/index.ts
  client/packages/invoices/src/OutboundShipment/DetailView/AddFromScannerButton.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/Prescriptions/DetailView/ContentArea.tsx
  client/packages/invoices/src/Prescriptions/DetailView/DetailView.tsx
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditTable.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/columns.ts
  client/packages/invoices/src/Prescriptions/LineEditView/dosesColumns.ts
  client/packages/invoices/src/Prescriptions/api/hooks/utils.tsx
  client/packages/invoices/src/index.ts
  client/packages/invoices/src/types.ts
Labels: enhancement, Team Ruru 🦉, feature: dose management

#7657 7547 off 2.7.2 refactor customer program response requisition
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/ResponseRequisition/ListView/CreateRequisitionModal.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ProgramRequisitionOptions.tsx
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/index.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/utils/index.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/utils/useProgramRequisitionSettingsByCustomer.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/utils/useProgramSettings.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  server/graphql/requisition/src/lib.rs
  server/graphql/requisition/src/mutations/response_requisition/insert_program.rs
  server/graphql/requisition/src/program_settings.rs
  server/repository/src/db_diesel/name_tag.rs
  server/repository/src/db_diesel/program_requisition/requisitions_in_period.rs
  server/service/src/requisition/common.rs
  server/service/src/requisition/mod.rs
  server/service/src/requisition/program_settings/customer_program_settings/map.rs
  server/service/src/requisition/program_settings/customer_program_settings/mod.rs
  server/service/src/requisition/program_settings/customer_program_settings/prepare.rs
  server/service/src/requisition/program_settings/mod.rs
  server/service/src/requisition/response_requisition/insert_program.rs
Labels: Team Piwakawaka, Severity: High, feature: manual requisition, feature: CIV

#7672 Fixes prepare tests
  server/service/src/requisition/program_settings/customer_program_settings/prepare.rs
Labels: Team Piwakawaka

#7673 7547 fix name tag filter
  server/repository/src/db_diesel/name_tag.rs
Labels: Team Piwakawaka, Severity: High, feature: manual requisition, feature: CIV

#7613 7354 implement vvm preferences
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  server/graphql/preference/src/upsert.rs
  server/graphql/types/src/types/preferences.rs
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/manage_vvm_status.rs
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/preferences/sort_by_vvm_status.rs
  server/service/src/preference/types.rs
  server/service/src/preference/upsert.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7651 7606 add doses per unit & vvm type to central server UI
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Item/DetailView/DetailView.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/Item/api/hooks/useItemVariant/useItemVariant.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Name/Components/ManufacturerSearchInput/ManufacturerSearchInput.tsx
  client/packages/system/src/Name/utils.ts
  server/graphql/core/src/simple_generic_errors.rs
  server/graphql/item_variant/src/mutations/upsert.rs
  server/graphql/types/src/types/item_variant.rs
  server/service/src/item/item_variant/test/mod.rs
  server/service/src/item/item_variant/upsert.rs
Labels: Team Ruru 🦉, feature: item variant

#7644 7386 improve on creating initial stocktake
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/errors/NothingHere.tsx
  client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx
  client/packages/inventory/src/Stocktake/DetailView/ChangeLocationModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
  client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx
  client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx
  client/packages/inventory/src/Stocktake/DetailView/Footer/StatusChangeButton.tsx
  client/packages/inventory/src/Stocktake/DetailView/Footer/StocktakeLockButton.tsx
  client/packages/inventory/src/Stocktake/DetailView/ReduceLinesToZeroModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
  client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useDraftStocktakeLines.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts
  client/packages/inventory/src/Stocktake/ListView/AppBarButtons.tsx
  client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
  client/packages/inventory/src/Stocktake/ListView/CreateStocktakeModal.tsx
  client/packages/inventory/src/Stocktake/ListView/Footer.tsx
  client/packages/inventory/src/Stocktake/ListView/ListView.tsx
  client/packages/inventory/src/Stocktake/api/api.ts
  client/packages/inventory/src/Stocktake/api/hooks/document/index.ts
  client/packages/inventory/src/Stocktake/api/hooks/document/useInsertStocktake.ts
  client/packages/inventory/src/Stocktake/api/hooks/index.ts
  client/packages/inventory/src/Stocktake/api/hooks/keys.ts
  client/packages/inventory/src/Stocktake/api/hooks/line/useStocktakeRows.ts
  client/packages/inventory/src/Stocktake/api/hooks/useStocktake.ts
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/inventory/src/Stocktake/api/operations.graphql
  client/packages/inventory/src/Stocktake/api/useStocktakeGraphQL.ts
  client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx
  client/packages/system/src/Location/Components/LocationSearchInput.tsx
  client/packages/system/src/MasterList/Components/MasterListSearchInput.tsx
  server/graphql/stocktake/src/mutations/insert.rs
  server/graphql/tests/permissions.rs
  server/graphql/types/src/types/stocktake.rs
  server/repository/src/db_diesel/stocktake_row.rs
  server/repository/src/migrations/v2_08_00/add_initial_stocktake_field.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/repository/src/mock/stocktake.rs
  server/service/src/invoice_line/stock_in_line/insert/validate.rs
  server/service/src/invoice_line/stock_in_line/update/validate.rs
  server/service/src/lib.rs
  server/service/src/stock_line/update.rs
  server/service/src/stocktake/insert/generate.rs
  server/service/src/stocktake/insert/mod.rs
  server/service/src/stocktake/insert/validate.rs
  server/service/src/stocktake_line/insert/mod.rs
  server/service/src/stocktake_line/insert/validate.rs
  server/service/src/stocktake_line/update/validate.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/test/test_data/stocktake.rs
  server/service/src/sync/translations/stocktake.rs
Labels: enhancement, Team Ruru 🦉, feature: vaccine

#7457 7370 vaccine emergency order notifications
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx
  client/packages/common/src/ui/components/panels/StatusChip.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/StatusCell/StatusCell.tsx
  client/packages/dashboard/src/api/operations.generated.ts
  client/packages/dashboard/src/api/operations.graphql
  client/packages/dashboard/src/widgets/DistributionWidget.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/Toolbar.tsx
  server/graphql/general/src/queries/requisition_counts.rs
  server/graphql/requisition/src/query_tests/requisition.rs
  server/graphql/requisition/src/query_tests/requisitions.rs
  server/graphql/requisition/src/requisition_queries.rs
  server/repository/src/db_diesel/requisition/mod.rs
  server/repository/src/db_diesel/requisition/requisition.rs
  server/service/src/dashboard/requisition_count.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7693 7674 sync vvm status log
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/vvm_status/vvm_status_log_row.rs
  server/repository/src/migrations/v2_08_00/add_vvm_status_log_change_log_table_name.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/vvm_status_log.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/vvm_status_log.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7534 7379 add donor tracking pref
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.graphql
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Manage/Preferences/api/operations.generated.ts
  client/packages/system/src/Manage/Preferences/api/operations.graphql
  server/graphql/preference/src/upsert.rs
  server/graphql/types/src/types/preferences.rs
  server/repository/src/db_diesel/invoice_line_row.rs
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/migrations/v2_08_00/add_donor_id_to_invoice_and_invoice_lines.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/service/src/invoice/customer_return/insert/generate.rs
  server/service/src/invoice/inbound_shipment/generate.rs
  server/service/src/invoice/inbound_shipment/insert/generate.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/outbound_shipment/generate.rs
  server/service/src/invoice/outbound_shipment/insert/generate.rs
  server/service/src/invoice/prescription/insert/generate.rs
  server/service/src/invoice/supplier_return/insert/generate.rs
  server/service/src/invoice_line/inbound_shipment_from_internal_order_lines/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/set_prescribed_quantity/generate.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/allow_tracking_of_received_stock_by_donor.rs
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/types.rs
  server/service/src/preference/upsert.rs
  server/service/src/processors/transfer/invoice/common.rs
  server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/sync/test/integration/remote/invoice.rs
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/test/test_data/stock_line.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/invoice_line.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7730 Fix rebuilding views so it doesn't run on test cases
  server/repository/src/migrations/mod.rs
Labels: Build Tested: Dev

#7724 7723 VVM: Manage VVM status rename
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/Prescriptions/DetailView/DetailView.tsx
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/columns.ts
  client/packages/system/src/Manage/Preferences/api/operations.generated.ts
  client/packages/system/src/Manage/Preferences/api/operations.graphql
  client/packages/system/src/Name/ListView/Facilities/EditStorePreferences.tsx
  server/graphql/preference/src/upsert.rs
  server/graphql/types/src/types/preferences.rs
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/display_vaccines_in_doses.rs
  server/service/src/preference/preferences/manage_vvm_status_for_stock.rs
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/preferences/sort_by_vvm_status_then_expiry.rs
  server/service/src/preference/types.rs
  server/service/src/preference/upsert.rs
Labels: enhancement, Team Ruru 🦉, feature: vaccine

#7742 7702 vvm status log update
  server/graphql/types/src/types/activity_log.rs
  server/graphql/vvm/src/lib.rs
  server/graphql/vvm/src/mutations/vvm_status_log/mod.rs
  server/graphql/vvm/src/mutations/vvm_status_log/update.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/migrations/v2_08_00/add_vvm_status_log_update_to_activity_log.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/service/src/sync/test/test_data/vvm_status_log.rs
  server/service/src/vvm/mod.rs
  server/service/src/vvm/vvm_status_log/insert/validate.rs
  server/service/src/vvm/vvm_status_log/mod.rs
  server/service/src/vvm/vvm_status_log/update/generate.rs
  server/service/src/vvm/vvm_status_log/update/mod.rs
  server/service/src/vvm/vvm_status_log/update/test.rs
  server/service/src/vvm/vvm_status_log/update/validate.rs
  server/service/src/vvm/vvm_status_log/validate.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7758 7749 add from master list refresh
  client/packages/requisitions/src/RequestRequisition/api/hooks/utils/useAddFromMasterList.ts
Labels: Priority: Should Have

#7727 7676 fix expiry date column display
  client/packages/invoices/src/Prescriptions/LineEditView/columns.ts
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: Team Ruru 🦉, Severity: High

#7703 7380 add donor inbound
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Manage/Preferences/api/operations.generated.ts
  client/packages/system/src/Manage/Preferences/api/operations.graphql
  server/Cargo.lock
  server/graphql/invoice/Cargo.toml
  server/graphql/invoice/src/mutations/inbound_shipment/update.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/preference/src/upsert.rs
  server/graphql/types/src/types/preferences.rs
  server/repository/src/db_diesel/stock_line_row.rs
  server/repository/src/migrations/v2_08_00/add_donor_id_to_stock_lines.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/repository/src/mock/invoice.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/name.rs
  server/service/src/invoice/customer_return/insert/generate.rs
  server/service/src/invoice/customer_return/update_lines/generate.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice_line/stock_in_line/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
  server/service/src/invoice_line/stock_in_line/update/mod.rs
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/allow_tracking_of_stock_by_donor.rs
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/types.rs
  server/service/src/preference/upsert.rs
  server/service/src/stock_line/update.rs
  server/service/src/stocktake/insert/generate.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/sync/test/integration/remote/location_movement.rs
  server/service/src/sync/test/integration/remote/stock_line.rs
  server/service/src/sync/test/test_data/stock_line.rs
  server/service/src/sync/translations/stock_line.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7754 7710 (7380 b) add donor select front end
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/Select/Select.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/DonorSection.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/Donor/DonorEditModal.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/Donor/index.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/index.ts
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  server/graphql/invoice/src/mutations/inbound_shipment/update.rs
  server/graphql/types/src/types/invoice_query.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7760 Update text input debounce to more moderate value
  client/packages/common/src/ui/layout/tables/columns/types.ts
  client/packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
Labels: Severity: Normal, Effort: Small

#7681 Add table provider around activity log for rnr form
  client/packages/system/src/ActivityLog/Components/ListView.tsx
Labels: needs triage, Severity: Hotfix, needs daily triage, feature: R&R

#7738 Override tet with en in Intl.NumberFormat
  client/packages/coldchain/src/common/utils.ts
  client/packages/common/src/intl/currency/currency.ts
  client/packages/common/src/intl/number/IntlNumber.ts
Labels: needs triage, needs daily triage

#7741 Add translation number formatting in RnR form
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
  server/graphql/general/src/lib.rs
Labels: enhancement, feature: R&R

#7779 7778 fix failing postgres test
  server/service/src/requisition/program_settings/customer_program_settings/prepare.rs
Labels: bug, Team Ruru 🦉, Bug: development

#7712 7472 outbound shipment edit refactor
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/DataTable.tsx
  client/packages/common/src/utils/arrays/ArrayUtils.ts
  client/packages/common/src/utils/arrays/SortUtils.ts
  client/packages/invoices/src/OutboundShipment/DetailView/AddFromScannerButton.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/Allocation.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/AutoAllocate.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/SelectItem.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/allocateQuantities.test.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/allocateQuantities.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/useAllocationContext.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/utils.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/index.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useDraftOutboundLines.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useOpenedWithBarcode.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/hooks/useOutboundLineEditRows.ts
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/line/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/useOutboundLineEditData.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/useSaveOutboundLines.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/index.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/useGetItemPricing.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/utils/useOutboundApi.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
  client/packages/invoices/src/Prescriptions/api/hooks/utils.tsx
  client/packages/invoices/src/StockOut/Components/StockOutAlerts.tsx
  client/packages/invoices/src/StockOut/hooks/usePackSizeController.test.tsx
  client/packages/invoices/src/StockOut/utils.test.ts
  client/packages/invoices/src/StockOut/utils.tsx
  client/packages/invoices/src/types.ts
  server/Cargo.lock
  server/graphql/invoice_line/Cargo.toml
  server/graphql/invoice_line/src/invoice_line_queries.rs
  server/graphql/invoice_line/src/lib.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/mod.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/save_item_lines.rs
  server/graphql/lib.rs
  server/graphql/types/src/types/draft_outbound_shipment_line.rs
  server/graphql/types/src/types/mod.rs
  server/service/src/invoice_line/get_draft_outbound_lines.rs
  server/service/src/invoice_line/mod.rs
  server/service/src/invoice_line/save_outbound_shipment_item_lines/generate.rs
  server/service/src/invoice_line/save_outbound_shipment_item_lines/mod.rs
  server/service/src/invoice_line/save_outbound_shipment_item_lines/validate.rs
  server/service/src/pricing/item_price.rs
Labels: refactor, Team Ruru 🦉, Needs Refinement

#7759 7722 add item variant dosesPerUnit support to dose calculations
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/columns/DosesPerUnitColumn/DosesPerUnitColumn.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/utils.ts
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/inventory/src/Stocktake/api/operations.graphql
  client/packages/invoices/src/DoseQtyColumn.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/utils.tsx
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/dosesColumns.ts
  client/packages/invoices/src/Prescriptions/api/hooks/utils.tsx
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  client/packages/system/src/Item/Components/ItemVariantSearchInput/ItemVariantInputCell.tsx
  client/packages/system/src/Item/Components/ItemVariantSearchInput/ItemVariantSearchInput.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/BundledItemModal.tsx
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Vaccination/Components/SelectBatch.tsx
  server/graphql/types/src/types/invoice_line.rs
  server/graphql/types/src/types/stock_line.rs
  server/graphql/types/src/types/stocktake_line.rs
Labels: enhancement, Team Ruru 🦉, feature: dose management

#7753 7349 display doses outbound
  client/packages/common/src/intl/locales/ar/common.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/columns/DosesPerUnitColumn/DosesPerUnitColumn.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/ExpandoTable.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/Allocation.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/AutoAllocate.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/allocateQuantities.test.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/allocateQuantities.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/useAllocationContext.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/utils.test.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/utils.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/line/useOutboundRows.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
  server/graphql/types/src/types/draft_outbound_shipment_line.rs
  server/service/src/invoice_line/get_draft_outbound_lines.rs
Labels: enhancement, Team Ruru 🦉, feature: dose management

#7784 7774 edit inbound donor
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/inventory/src/Stocktake/api/operations.graphql
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/DonorSection.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/system/src/Name/Components/DonorSearchInput/DonorSearchInput.tsx
  client/packages/system/src/Name/Components/DonorSearchInput/DonorSelectColumn.tsx
  client/packages/system/src/Name/Components/DonorSearchInput/index.ts
  server/graphql/types/src/types/invoice_line.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
Labels: enhancement, Team Ruru 🦉, feature: vaccine

#7767 7369 vvm stock
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Stock/Components/StatusHistory/StatusHistory.tsx
  client/packages/system/src/Stock/Components/StatusHistory/index.ts
  client/packages/system/src/Stock/Components/StatusHistory/useStatusHistoryColumns.ts
  client/packages/system/src/Stock/DetailView/DetailView.tsx
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/vvm_status_log.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/stock_line.rs
  server/graphql/types/src/types/vvm_status_log.rs
  server/graphql/vvm/src/lib.rs
  server/graphql/vvm/src/mutations/vvm_status_log/insert.rs
  server/graphql/vvm/src/queries/vvm_status_log.rs
  server/graphql/vvm/src/types/mod.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7780 7641 sort by vvms status outbound
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/arrays/SortUtils.test.ts
  client/packages/common/src/utils/arrays/SortUtils.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/Allocation.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/useAllocationContext.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/utils.test.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/utils.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
  server/graphql/types/src/types/draft_outbound_shipment_line.rs
  server/service/src/invoice_line/get_draft_outbound_lines.rs
Labels: enhancement, Team Piwakawaka

#7791 #7388 Store pref for simplifed mobile UI
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/useSimplifiedTabletUI/index.ts
  client/packages/common/src/hooks/useSimplifiedTabletUI/useSimplifiedTabletUI.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/hooks/useColumnDisplayState.ts
  server/graphql/preference/src/upsert.rs
  server/graphql/types/src/types/preferences.rs
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/preferences/use_simplified_mobile_ui.rs
  server/service/src/preference/types.rs
  server/service/src/preference/upsert.rs
Labels: enhancement, feature: simplified tablet UI

#7792 #7397 Simplified mobile columns (for Internal Order)
  client/packages/common/src/hooks/useSimplifiedTabletUI/useSimplifiedTabletUI.ts
  client/packages/common/src/ui/layout/tables/columns/types.ts
  client/packages/common/src/ui/layout/tables/hooks/useColumnDisplayState.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
Labels: enhancement, Team Piwakawaka, feature: simplified tablet UI

#7698 7835 add open vial wastage reasons
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/index.ts
  client/packages/common/src/utils/reasons/ReasonOptionsUtils.ts
  client/packages/common/src/utils/reasons/index.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx
  client/packages/system/src/RequestRequisitionLine/operations.generated.ts
  client/packages/system/src/RequestRequisitionLine/operations.graphql
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
  server/graphql/types/src/types/inventory_adjustment_reason.rs
  server/graphql/types/src/types/reason_option.rs
  server/repository/src/db_diesel/reason_option.rs
  server/repository/src/db_diesel/reason_option_row.rs
  server/repository/src/migrations/v2_08_00/add_open_vial_wastage_to_reason_option_type.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/service/src/stocktake_line/validate.rs
  server/service/src/sync/translations/reason.rs
Labels: enhancement, Team Ruru 🦉, feature: vaccine

#7781 7764 vvm stock logs edit
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Stock/Components/StatusHistory/StatusHistory.tsx
  client/packages/system/src/Stock/Components/StatusHistory/VvmStatusLogModal.tsx
  client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusSearchInput.tsx
  client/packages/system/src/Stock/Components/VVMStatusSearchInput/index.ts
  client/packages/system/src/Stock/api/hooks/index.ts
  client/packages/system/src/Stock/api/hooks/keys.ts
  client/packages/system/src/Stock/api/hooks/useActiveVVMStatuses.ts
  client/packages/system/src/Stock/api/hooks/useVvmStatusLog.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7796 7750 add program id filter to stocktake query
  client/packages/programs/src/JsonForms/components/PeriodSearch.tsx
  client/packages/programs/src/JsonForms/components/ProgramSearch.tsx
  server/graphql/stocktake/src/stocktake_queries.rs
  server/repository/src/db_diesel/stocktake.rs
Labels: enhancement, feature: reports, feature: CIV, UI tweaks

#7812 7790 vvm stock line update status
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/DetailView/DetailView.tsx
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/repository/src/db_diesel/vvm_status/vvm_status_log_row.rs
  server/service/src/sync/translations/vvm_status_log.rs
  server/service/src/vvm/vvm_status_log/insert/mod.rs
  server/service/src/vvm/vvm_status_log/insert/test.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7814 7398 io modal
  client/packages/common/src/intl/locales/ar/common.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/common/src/styles/theme.ts
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/common/src/ui/components/inputs/Select/Select.tsx
  client/packages/common/src/ui/components/inputs/TextArea/BufferedTextArea.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/Footer.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/ConsumptionHistory.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/StockDistribution.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemCharts/StockEvolution.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/Layout/Layout.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/Layout/Panels.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/Layout/index.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditModal.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/index.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/utils.test.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/utils.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/hooks.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/index.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/utils.test.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/utils.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/index.ts
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useRequest.ts
  client/packages/requisitions/src/RequisitionService.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/system/src/Item/Components/ItemOptionRenderer/ItemOptionRenderer.tsx
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
  client/packages/system/src/Item/Components/StockItemSearchInputWithStats/StockItemSearchInputWithStats.tsx
  client/packages/system/src/Item/Components/StockItemSearchInputWithStats/index.ts
  client/packages/system/src/Item/Components/index.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Item/utils.ts
  client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx
Labels: docs: internal, enhancement, Team Ruru 🦉, Team Piwakawaka, feature: simplified tablet UI

#7793 7566 fix pack size issues stocktake
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useNextItem.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/hooks/useStocktakeLineEdit.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/utils.ts
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/inventory/src/Stocktake/api/operations.graphql
  client/packages/inventory/src/types.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
Labels: Team Ruru 🦉, Severity: High, Effort: Small

#7821 7818 Rename "DisplayVaccinesInDoses" to "ManageVaccinesInDoses"
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
  client/packages/invoices/src/OutboundShipment/api/hooks/line/useOutboundRows.ts
  client/packages/invoices/src/Prescriptions/DetailView/DetailView.tsx
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/columns.ts
  server/graphql/preference/src/upsert.rs
  server/graphql/types/src/types/preferences.rs
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/manage_vaccines_in_doses.rs
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/types.rs
  server/service/src/preference/upsert.rs
Labels: enhancement, Team Ruru 🦉, feature: dose management

#7825 7824 locations tab to other
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTabs.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
Labels: Team Ruru 🦉

#7816 7786 auto allocate in packs from outbound shipment
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/layout/tables/components/Cells/CheckCell/CheckCell.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/AllocateInSelector.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/Allocation.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/AutoAllocate.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/allocateQuantities.test.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/allocateQuantities.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/useAllocationContext.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/utils.test.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/allocation/utils.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
Labels: enhancement, Team Ruru 🦉, area: outbound line edit

#7823 7655 rename facilities to stores
  client/packages/common/src/intl/locales/ar/common.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/config/src/routes.ts
  client/packages/host/src/components/Footer/Footer.tsx
  client/packages/host/src/components/Navigation/ManageNav.tsx
  client/packages/host/src/routers/ManageRouter.tsx
  client/packages/system/src/Name/ListView/ImportProperties/UploadTab.tsx
  client/packages/system/src/Name/ListView/Stores/AppBarButtons.tsx
  client/packages/system/src/Name/ListView/Stores/DisplayCoordinates.tsx
  client/packages/system/src/Name/ListView/Stores/EditStorePreferences.tsx
  client/packages/system/src/Name/ListView/Stores/ListView.tsx
  client/packages/system/src/Name/ListView/Stores/StoreEditModal.tsx
  client/packages/system/src/Name/ListView/Stores/StoreProperties.tsx
  client/packages/system/src/Name/ListView/Stores/Toolbar.tsx
  client/packages/system/src/Name/ListView/Stores/useDraftStoreProperties.tsx
  client/packages/system/src/Name/ListView/index.ts
  client/packages/system/src/Name/Service/Service.tsx
  client/packages/system/src/Name/api/api.ts
  client/packages/system/src/Name/api/hooks/document/index.ts
  client/packages/system/src/Name/api/hooks/document/useStores.ts
  client/packages/system/src/Name/api/hooks/document/useStoresAll.ts
  client/packages/system/src/Name/api/hooks/index.ts
  client/packages/system/src/Name/api/hooks/utils/index.ts
  client/packages/system/src/Name/api/hooks/utils/useNextFacilityId.ts
  client/packages/system/src/Name/api/hooks/utils/useNextStoreId.ts
  client/packages/system/src/Name/api/operations.generated.ts
  client/packages/system/src/Name/api/operations.graphql
Labels: enhancement, Team Ruru 🦉, UI tweaks

#7810 #7803 Campaigns back-end
  client/packages/common/src/ui/layout/tables/hooks/useColumnDisplayState.ts
  server/cli/src/refresh_dates.rs
  server/graphql/general/src/campaign/mod.rs
  server/graphql/general/src/campaign/mutations/delete.rs
  server/graphql/general/src/campaign/mutations/mod.rs
  server/graphql/general/src/campaign/mutations/upsert.rs
  server/graphql/general/src/campaign/query.rs
  server/graphql/general/src/lib.rs
  server/graphql/lib.rs
  server/graphql/types/src/types/campaign.rs
  server/graphql/types/src/types/mod.rs
  server/repository/src/db_diesel/campaign/campaign.rs
  server/repository/src/db_diesel/campaign/campaign_row.rs
  server/repository/src/db_diesel/campaign/mod.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_08_00/add_campaign_change_log_table_name.rs
  server/repository/src/migrations/v2_08_00/add_campaign_table.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/service/src/auth.rs
  server/service/src/campaign/delete.rs
  server/service/src/campaign/mod.rs
  server/service/src/campaign/query.rs
  server/service/src/campaign/upsert.rs
  server/service/src/campaign/validate.rs
  server/service/src/lib.rs
  server/service/src/requisition/program_settings/customer_program_settings/prepare.rs
  server/service/src/service_provider.rs
  server/service/src/sync/test/test_data/campaign.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/campaign.rs
  server/service/src/sync/translations/mod.rs
Labels: feature: vaccine

#7820 7797 test vvm status
  server/repository/src/db_diesel/vvm_status/vvm_status_row.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/vvm_status.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
  server/service/src/invoice_line/stock_in_line/delete/mod.rs
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/update/mod.rs
  server/service/src/vvm/vvm_status_log/update/test.rs
Labels: enhancement, Team Ruru 🦉, feature: vaccine

#7785 7616 selecting item variant inbound
  client/packages/common/src/ui/components/popover/PaperPopover/PersistentPaperPopover/PersistentPaperPopover.tsx
  client/packages/common/src/ui/components/popover/PaperPopover/PersistentPaperPopover/index.ts
  client/packages/common/src/ui/components/popover/PaperPopover/index.ts
  client/packages/common/src/ui/layout/tables/columns/types.ts
  client/packages/common/src/ui/layout/tables/components/Cells/RadioCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/index.ts
  client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
  client/packages/common/src/ui/layout/tables/index.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/utils.tsx
  client/packages/invoices/src/Returns/modals/CustomerReturn/ReturnQuantitiesTable.tsx
  client/packages/system/src/Item/Components/ItemVariantSearchInput/ItemVariantInputCellOld.tsx
  client/packages/system/src/Item/Components/ItemVariantSearchInput/ItemVariantSearchInput.tsx
  client/packages/system/src/Item/Components/ItemVariantSearchInput/index.ts
  client/packages/system/src/Item/Components/ItemVariantSelector/ItemVariantInputCell.tsx
  client/packages/system/src/Item/Components/ItemVariantSelector/ItemVariantSelector.tsx
  client/packages/system/src/Item/Components/ItemVariantSelector/columns.tsx
  client/packages/system/src/Item/Components/ItemVariantSelector/index.ts
  client/packages/system/src/Item/Components/index.ts
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
Labels: Team Ruru 🦉, feature: item variant

#7777 7776 Add plugin processor
  client/packages/plugins/backendCommon/generated/ChangelogFilter.ts
  client/packages/plugins/backendCommon/generated/ChangelogRow.ts
  client/packages/plugins/backendCommon/generated/ChangelogTableName.ts
  client/packages/plugins/backendCommon/generated/PluginTypes.ts
  client/packages/plugins/backendCommon/generated/ProcessorInput.ts
  client/packages/plugins/backendCommon/generated/ProcessorOutput.ts
  client/packages/plugins/backendCommon/generated/RowActionType.ts
  client/packages/plugins/backendCommon/types.ts
  package.json
  server/Cargo.lock
  server/repository/src/db_diesel/backend_plugin_row.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/key_value_store.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_07_04/create_dynamic_cursor_key.rs
  server/repository/src/migrations/v2_07_04/mod.rs
  server/service/Cargo.toml
  server/service/src/backend_plugin/plugin_provider.rs
  server/service/src/backend_plugin/types/mod.rs
  server/service/src/backend_plugin/types/processor.rs
  server/service/src/boajs/methods/log.rs
  server/service/src/cursor_controller.rs
  server/service/src/processors/add_central_patient_visibility/add_central_patient_visibility.rs
  server/service/src/processors/assign_requisition_number/assign_requisition_number.rs
  server/service/src/processors/contact_form/queue_email.rs
  server/service/src/processors/general_processor.rs
  server/service/src/processors/load_plugin/load_plugin.rs
  server/service/src/processors/mod.rs
  server/service/src/processors/plugin_processor/mod.rs
  server/service/src/processors/plugin_processor/plugin_processor.rs
  server/service/src/sync/synchroniser.rs
Labels: enhancement, feature: integration

#7718 7374 View for Vaccine course
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/vaccination_course.rs
  server/repository/src/migrations/views/mod.rs
Labels: enhancement, feature: vaccine

#7817 7804 add campaign to stock line schema
  server/graphql/core/src/loader/campaign.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/types/src/types/stock_line.rs
  server/repository/src/db_diesel/stock_line_row.rs
  server/repository/src/migrations/v2_08_00/add_campaign_id_to_stock_line.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice_line/stock_in_line/generate.rs
  server/service/src/stocktake/insert/generate.rs
  server/service/src/sync/test/test_data/stock_line.rs
  server/service/src/sync/translations/stock_line.rs
Labels: Team Piwakawaka, feature: vaccine

#7840 7839 Trigger reasons resync
  server/repository/src/migrations/v2_08_00/mod.rs
  server/repository/src/migrations/v2_08_00/reintegrate_options_sync_buffer_records.rs
Labels: Team Ruru 🦉

#7836 7512 Prevent reasonOptions firing on scroll
  client/packages/inventory/src/Stocktake/DetailView/ReduceLinesToZeroModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/invoices/src/Returns/modals/ReturnReasonsTable.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
  client/packages/system/src/Stock/Components/NewStockLineModal.tsx
Labels: Team Ruru 🦉, Severity: Normal, Effort: Small

#7857 7815 move common components
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/Layout/index.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditModal.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/utils.ts
  client/packages/requisitions/src/common/ModalContentLayout.tsx
  client/packages/requisitions/src/common/ModalContentPanels.ts
  client/packages/requisitions/src/common/index.tsx
  client/packages/requisitions/src/common/utils.test.ts
  client/packages/requisitions/src/common/utils.ts
Labels: enhancement, Team Ruru 🦉, feature: simplified tablet UI

#7826 Add front-end API
  client/packages/system/src/Manage/Campaigns/api/hooks/index.ts
  client/packages/system/src/Manage/Campaigns/api/hooks/keys.ts
  client/packages/system/src/Manage/Campaigns/api/hooks/useCampaigns.ts
  client/packages/system/src/Manage/Campaigns/api/index.ts
  client/packages/system/src/Manage/Campaigns/api/operations.generated.ts
  client/packages/system/src/Manage/Campaigns/api/operations.graphql
  client/packages/system/src/Manage/Campaigns/api/useCampaignGraphQL.ts
Labels: feature: vaccine

#7853 7394 Add MVP simplified mobile UI changes Outbound shipment detail view
  client/packages/common/src/ui/layout/tables/columns/DosesPerUnitColumn/DosesPerUnitColumn.tsx
  client/packages/invoices/src/DoseQtyColumn.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/columns.ts
Labels: enhancement, Team Piwakawaka, feature: simplified tablet UI

#7822 7367 add vvm status to outbound and prescription
  client/packages/common/src/ui/layout/tables/columns/index.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/columns.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7829 #7805 Campaign Editor
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/config/src/routes.ts
  client/packages/host/src/components/Navigation/ManageNav.tsx
  client/packages/system/src/Manage/Campaigns/ListView/AppBarButtons.tsx
  client/packages/system/src/Manage/Campaigns/ListView/CampaignEditModal.tsx
  client/packages/system/src/Manage/Campaigns/ListView/Footer.tsx
  client/packages/system/src/Manage/Campaigns/ListView/ListView.tsx
  client/packages/system/src/Manage/Campaigns/ListView/index.ts
  client/packages/system/src/Manage/Campaigns/api/hooks/useCampaigns.ts
  client/packages/system/src/Manage/Campaigns/api/operations.generated.ts
  client/packages/system/src/Manage/Campaigns/api/operations.graphql
  client/packages/system/src/Manage/Campaigns/index.ts
  client/packages/system/src/Manage/Service/Service.tsx
  server/service/src/campaign/upsert.rs
Labels: Team Piwakawaka, feature: vaccine

#7869 Fix plugin type error
  client/packages/plugins/api/index.ts
Labels: enhancement, Built Tested: Tested in Feature, feature: vaccine

#7813 7809 sync messages
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/message_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_07_04/create_message_table.rs
  server/repository/src/migrations/v2_07_04/mod.rs
  server/service/src/sync/test/test_data/message.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/message.rs
  server/service/src/sync/translations/mod.rs
Labels: enhancement, feature: integration

#7808 7382 donor outbound stock line
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/utils.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/stock_line/src/mutations/insert.rs
  server/graphql/stock_line/src/mutations/update.rs
  server/graphql/types/src/types/draft_outbound_shipment_line.rs
  server/graphql/types/src/types/stock_line.rs
  server/repository/src/db_diesel/name.rs
  server/repository/src/mock/name_store_join.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/insert.rs
  server/service/src/invoice_line/get_draft_outbound_lines.rs
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/insert/validate.rs
  server/service/src/stock_line/tests/update.rs
  server/service/src/stock_line/update.rs
  server/service/src/validate.rs
Labels: enhancement, Team Ruru 🦉, feature: vaccine

#7861 Outbound Shipments Label
  client/packages/common/src/intl/locales/en/common.json
Labels: Team Ruru 🦉, Severity: Low, UI tweaks

#7871 7807 add ability to select campaign inbound shipments
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/system/src/Stock/Components/Campaign/CampaignSelectorColumn.tsx
  client/packages/system/src/Stock/Components/Campaign/index.ts
  client/packages/system/src/Stock/Components/index.ts
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/types/src/types/invoice_line.rs
  server/repository/src/db_diesel/invoice_line_row.rs
  server/repository/src/migrations/v2_08_00/add_campaign_id_to_invoice_line_row.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/service/src/invoice/customer_return/update_lines/generate.rs
  server/service/src/invoice/inbound_shipment/generate.rs
  server/service/src/invoice/outbound_shipment/generate.rs
  server/service/src/invoice_line/inbound_shipment_from_internal_order_lines/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
  server/service/src/invoice_line/stock_in_line/update/mod.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/set_prescribed_quantity/generate.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/processors/transfer/invoice/common.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/translations/invoice_line.rs
Labels: Team Piwakawaka, feature: vaccine

#7830 Add simplified UI
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/layout/tables/columns/CommentPopoverColumn/CommentPopoverColumn.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/inventory/src/Stocktake/DetailView/DetailView.tsx
  client/packages/inventory/src/Stocktake/DetailView/Toolbar.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/ListView/AppBarButtons.tsx
  client/packages/inventory/src/Stocktake/ListView/ListView.tsx
  client/packages/inventory/src/Stocktake/ListView/Toolbar.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/Toolbar.tsx
  client/packages/requisitions/src/RequestRequisition/api/api.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  client/packages/system/src/Stock/DetailView/DetailView.tsx
  client/packages/system/src/Stock/ListView/AppBarButtons.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: enhancement, feature: simplified tablet UI

#7877 #7834 Fix column state error for default mobile hidden columns
  client/packages/common/src/ui/layout/tables/hooks/useColumnDisplayState.ts
Labels: Team Piwakawaka, Severity: High

#7891 7890 added campaign in inbound shipment detail view
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/system/src/Stock/Components/Campaign/CampaignSelectorColumn.tsx
  server/graphql/types/src/types/invoice_line.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7898 7894 update stock line campaign id when inbound shipment updates
  server/service/src/invoice_line/stock_in_line/update/generate.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#7897 null packs received updates units
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Labels: Team Ruru 🦉, Severity: Low, feature: dose management

#7864 7392 Simplified UI Inbound Line Edit MVP
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Labels: enhancement, Team Ruru 🦉, feature: simplified tablet UI

#7906 7899 error when saving new stock without a campaign specified
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
Labels: Team Piwakawaka, Severity: High

#7902 7628 Set Item Variant on Stocktake
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Labels: Team Ruru 🦉, feature: item variant

#7907 7630 new item variant picker in view stock
  client/packages/common/src/ui/components/buttons/standard/TextInputButton.tsx
  client/packages/common/src/ui/components/buttons/standard/index.ts
  client/packages/common/src/ui/components/popover/PaperPopover/PersistentPaperPopover/PersistentPaperPopover.tsx
  client/packages/system/src/Item/Components/ItemVariantSelector/ItemVariantInput.tsx
  client/packages/system/src/Item/Components/ItemVariantSelector/ItemVariantInputCell.tsx
  client/packages/system/src/Item/Components/ItemVariantSelector/ItemVariantSelector.tsx
  client/packages/system/src/Item/Components/ItemVariantSelector/index.ts
  client/packages/system/src/Stock/Components/StockLineForm.tsx
Labels: Team Ruru 🦉, feature: item variant

#7909 filter master list by store id
  client/packages/system/src/Item/DetailView/Tabs/MasterLists.tsx
  client/packages/system/src/MasterList/ListView/ListView.tsx
Labels: Team Piwakawaka, Severity: High

#7923 #7901 Fix JSON forms prescription component
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/useDraftPrescriptionLines.tsx
  client/packages/programs/src/JsonForms/components/Prescription/Prescription.tsx
  client/packages/programs/src/JsonForms/components/Prescription/StockLineTable.tsx
  client/packages/programs/src/JsonForms/components/Prescription/useDraftLines.tsx
Labels: Team Piwakawaka, Severity: High

#7916 Reverse preference buttons
  client/packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx
  client/packages/system/src/Manage/Preferences/EditPage/EditPreferencesPage.tsx
  client/packages/system/src/Name/ListView/Stores/EditStorePreferences.tsx
Labels: Team Piwakawaka, Severity: Normal, UI tweaks

#7945 7915 vvm status field showing incorrectly stock detail view
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/DetailView/DetailView.tsx
Labels: Team Ruru 🦉, feature: vaccine

#7943 7936 prescription units in stock increasing
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/prescription_line/insert.rs
  server/graphql/invoice_line/src/mutations/prescription_line/update.rs
  server/service/src/invoice/update_picked_date.rs
  server/service/src/invoice_line/save_stock_out_item_lines/mod.rs
  server/service/src/invoice_line/stock_out_line/insert/mod.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
Labels: Team Ruru 🦉, feature: dose management

#7911 7868 add running balance total for ledger queries
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/db_diesel/ledger.rs
  server/service/src/ledger.rs
Labels: Team Piwakawaka, Severity: High, Needs Investigation

#7921 7828 line edit table column alignment
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/DeprecatedBasicTextInput.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
Labels: Team Ruru 🦉, Severity: Low, UI tweaks
