Repository msupply-foundation/open-msupply, pull requests merged in 2025-02, with the labels that each got.

#6316 #5756 Dispensing history modal
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
  client/packages/invoices/src/Prescriptions/DetailView/DetailView.tsx
  client/packages/invoices/src/Prescriptions/DetailView/History/HistoryModal.tsx
  client/packages/invoices/src/Prescriptions/DetailView/History/columns.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionList.ts
  client/packages/invoices/src/Prescriptions/api/hooks/utils.ts
  client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
Labels: Team Piwakawaka, feature: dispensing

#6387 6353 prescribed quantity improvements
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionLines.ts
  client/packages/invoices/src/StockOut/utils.test.ts
  client/packages/invoices/src/StockOut/utils.tsx
Labels: Team Piwakawaka, feature: dispensing

#6377 5863 Add overwrite flag to upsert json cli
  server/cli/src/cli.rs
  server/server/src/lib.rs
  server/service/src/standard_reports.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#6371 #6284 Prescriptions per program
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/invoices/src/Prescriptions/DetailView/ContentArea.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescription.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionLines.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  client/packages/programs/src/api/hooks/useProgramList.ts
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
  client/packages/system/src/Item/api/hooks/useItemStockOnHand/useItemStockOnHand.tsx
  client/packages/system/src/Item/utils.ts
  client/packages/system/src/Program/ProgramSearchInput.tsx
  client/packages/system/src/Program/index.ts
  client/packages/system/src/index.ts
  server/graphql/batch_mutations/src/batch_prescription.rs
  server/graphql/general/src/queries/item.rs
  server/graphql/invoice/src/mutations/prescription/insert.rs
  server/graphql/invoice/src/mutations/prescription/update.rs
  server/graphql/types/src/types/invoice_query.rs
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/db_diesel/item.rs
  server/repository/src/migrations/v2_06_00/add_program_id_to_invoice.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/service/src/invoice/customer_return/insert/generate.rs
  server/service/src/invoice/inbound_shipment/insert/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/outbound_shipment/insert/generate.rs
  server/service/src/invoice/prescription/insert/generate.rs
  server/service/src/invoice/prescription/insert/mod.rs
  server/service/src/invoice/prescription/update/generate.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/invoice/supplier_return/insert/generate.rs
  server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/translations/invoice.rs
  server/service/src/vaccination/generate.rs
Labels: Team Piwakawaka, feature: dispensing

#6172 5990(1) Allow custom props for table cells without creating new component.
  client/packages/common/src/ui/layout/tables/columns/types.ts
  client/packages/common/src/ui/layout/tables/components/DataRow/DataRow.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Labels: refactor, Team Piwakawaka

#6394 #6366 Fix patient sorting
  server/repository/src/db_diesel/patient.rs
Labels: Team Piwakawaka, Severity: High, feature: dispensing

#6337 6336 Make central record processor generic
  server/service/src/processors/contact_form/mod.rs
  server/service/src/processors/contact_form/queue_email.rs
  server/service/src/processors/general_processor.rs
  server/service/src/processors/mod.rs
  server/service/src/sync/synchroniser.rs
  server/service/src/sync/test/test_data/invoice.rs
Labels: Team Ruru 🦉, feature: plugin

#6356 6175 prescription price columns
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundServiceLineEdit/useDraftServiceLines.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/StockOut/hooks/usePackSizeController.test.tsx
  client/packages/invoices/src/StockOut/operations.generated.ts
  client/packages/invoices/src/StockOut/operations.graphql
  client/packages/invoices/src/StockOut/utils.test.ts
  client/packages/invoices/src/StockOut/utils.tsx
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
Labels: Team Piwakawaka, feature: dispensing

#6403 Print Labels Button in App Bar
  client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
Labels: enhancement, Team: Kororā :penguin:

#6401 Print Labels Button in Row Actions
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx
Labels: enhancement, Team: Kororā :penguin:

#6408 #6333 item directions gql
  client/packages/common/src/types/schema.ts
  server/graphql/core/src/loader/item_direction.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/item_direction.rs
  server/graphql/types/src/types/mod.rs
  server/repository/src/db_diesel/item_direction.rs
  server/repository/src/db_diesel/item_direction_row.rs
Labels: enhancement, Team: Kororā :penguin:

#6406 5559 add show report to cli
  server/.gitignore
  server/cli/src/cli.rs
  server/cli/src/report_utils.rs
  server/report_builder/README.md
  server/report_builder/src/print.rs
  server/reports/test-config.json
Labels: enhancement, Team Ruru 🦉, feature: reports

#6362 5648 prescriptions directions section
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/getPrescriptionDirections.test.ts
  client/packages/invoices/src/Prescriptions/LineEditView/getPrescriptionDirections.ts
Labels: feature: dispensing, Team: Kororā :penguin:

#6418 6283 Add stock-to-date report name translation
  client/packages/common/src/intl/locales/en/common.json
Labels: enhancement, Team Ruru 🦉, feature: reports, feature: CIV

#6416 #6354 Presribed quantity Store pref
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.graphql
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  server/graphql/types/src/types/store_preference.rs
  server/repository/src/db_diesel/store_preference_row.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/repository/src/migrations/v2_06_00/prescribed_quantity_store_pref.rs
  server/service/src/sync/test/test_data/store_preference.rs
  server/service/src/sync/translations/store_preference.rs
Labels: Team Piwakawaka, feature: dispensing

#6420 Disable pluralisation in prescription line edit view
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
Labels: bug, Team Piwakawaka, Severity: Normal, Needs refinement

#6413 6176 payments modal select insurance
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Payments/PaymentsModal.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Payments/index.ts
Labels: Team Piwakawaka, feature: dispensing

#6383 Update utils.ts
  client/packages/reports/src/utils.ts
Labels: needs triage, feature: reports, needs daily triage

#6426 6410 fix backend patient schema
  client/packages/programs/src/schema_types.ts
  server/service/src/programs/patient/patient_schema.rs
  server/service/src/programs/patient/patient_updated.rs
  server/service/src/programs/schemas/patient.json
Labels: enhancement, feature: vaccine card, Team: Kororā :penguin:

#6395 6204 name insurance join
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/name_insurance_join_row.rs
  server/repository/src/migrations/v2_06_00/add_name_insurance_join.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/service/src/sync/test/test_data/insurance_provider.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/name_insurance_join.rs
  server/service/src/sync/translations/insurance_provider.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/name_insurance_join.rs
Labels: Team Piwakawaka, feature: dispensing

#6414 5999 add references to prescription
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescription.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionLines.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  server/graphql/batch_mutations/src/batch_prescription.rs
  server/graphql/invoice/src/mutations/prescription/insert.rs
  server/graphql/invoice/src/mutations/prescription/update.rs
  server/service/src/invoice/prescription/insert/generate.rs
  server/service/src/invoice/prescription/insert/mod.rs
  server/service/src/invoice/prescription/update/generate.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/vaccination/generate.rs
Labels: enhancement, Team Piwakawaka, feature: dispensing

#6397 Add cli to generate and install plugin bundle
  server/cli/src/cli.rs
  server/cli/src/graphql/auth.rs
  server/cli/src/graphql/mod.rs
  server/cli/src/graphql/queries_mutations.rs
  server/cli/src/lib.rs
  server/cli/src/plugins.rs
  server/service/src/backend_plugin/examples/amc/amc.js
  server/service/src/lib.rs
Labels: enhancement, Team Ruru 🦉, feature: plugin

#6450 restore the border
  client/packages/common/src/ui/components/inputs/TextArea/TextArea.tsx
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/NumberInputCell/NumberInputCell.tsx
  client/packages/host/src/Admin/SettingTextArea.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/StockOut/utils.tsx
Labels: UI tweaks

#6435 add nothing found feedback to new prescription modal
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Patient/Components/PatientSearchModal/PatientSearchModal.tsx
Labels: bug, Team Piwakawaka, Severity: Normal, feature: dispensing

#6399 5829 load plugins via processor
  server/repository/src/db_diesel/key_value_store.rs
  server/repository/src/migrations/v2_06_00/add_load_plugin_processor_pg_enum_type.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/server/src/lib.rs
  server/service/src/plugin/mod.rs
  server/service/src/processors/general_processor.rs
  server/service/src/processors/load_plugin/load_plugin.rs
  server/service/src/processors/load_plugin/mod.rs
  server/service/src/processors/mod.rs
  server/service/src/sync/synchroniser.rs
Labels: enhancement, Team Ruru 🦉, feature: plugin

#6433 #6248 Fix issue quanity resetting to 0 after adding new item
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
Labels: Team Piwakawaka, Severity: High, feature: dispensing

#6429 6411 No translations for program reports
  client/packages/common/src/intl/locales/en/common.json
Labels: Team Ruru 🦉, feature: reports, feature: translation

#6430 Add check exclusive of other customer or supplier stores
  server/service/src/requisition/common.rs
  server/service/src/requisition/request_requisition/insert_program.rs
  server/service/src/requisition/response_requisition/insert_program.rs
Labels: Team Ruru 🦉, Severity: High

#6472 Refine the keyboard shortcuts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/host/src/CommandK.tsx
  client/packages/host/src/Help/Help.tsx
  client/packages/host/src/Help/UserGuide.tsx
Labels: enhancement, make omSupply delightful

#6421 connect abbreviations graphql to ui
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/getPrescriptionDirections.test.ts
  client/packages/invoices/src/Prescriptions/LineEditView/getPrescriptionDirections.ts
  client/packages/invoices/src/Prescriptions/api/hooks/keys.ts
  client/packages/invoices/src/Prescriptions/api/hooks/useAbbreviations.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
Labels: feature: dispensing, Team: Kororā 🐧

#6474 6461 insurance provider loader
  server/graphql/core/src/loader/insurance_provider.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/general/src/queries/insurances.rs
  server/graphql/general/src/types.rs
  server/repository/src/db_diesel/insurance_provider_row.rs
Labels: Team Piwakawaka, feature: dispensing

#6473 Prevent revoked user permissions reverting
  client/packages/host/src/components/Sync/SyncModal.tsx
Labels: bug, Severity: Normal, Severity: High, Needs Investigation, feature: GEDSI, Team: Kororā 🐧

#6454 add patient details
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PatientDetails.tsx
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
Labels: Team Piwakawaka, feature: dispensing

#6509 6455 cancelled prescription status
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/Footer/Footer.tsx
  client/packages/invoices/src/utils.ts
  server/graphql/types/src/types/activity_log.rs
  server/graphql/types/src/types/invoice_query.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/invoice.rs
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/migrations/v2_06_00/add_cancelled_status_to_invoice.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/repository/src/mock/invoice.rs
  server/service/src/activity_log.rs
  server/service/src/dashboard/invoice_count.rs
  server/service/src/sync/translations/invoice.rs
Labels: Team Piwakawaka, feature: dispensing

#6503 #6289 Insurance fields on Invoice
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/migrations/v2_06_00/add_insurance_fields_to_invoice.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/service/src/invoice/customer_return/insert/generate.rs
  server/service/src/invoice/inbound_shipment/insert/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/outbound_shipment/insert/generate.rs
  server/service/src/invoice/prescription/insert/generate.rs
  server/service/src/invoice/supplier_return/insert/generate.rs
  server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/sync/sync_serde.rs
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/translations/invoice.rs
Labels: Team Piwakawaka, feature: dispensing

#5729 Preferences KDD
  decisions/2024-12-03_preferences.md
Labels: KDD, Build Tested: None, Team Piwakawaka

#6477 6452 printer configuration table
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/printer.rs
  server/repository/src/db_diesel/printer_row.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/repository/src/migrations/v2_06_00/printer_create_table.rs
Labels: enhancement, Team: Kororā 🐧

#6516 6499 Cancel verified prescriptions
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/utils.ts
  client/packages/invoices/src/utils.ts
  server/graphql/invoice/src/mutations/prescription/update.rs
  server/repository/src/migrations/v2_06_00/add_cancelled_status_to_invoice.rs
  server/service/src/dashboard/invoice_count.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/invoice/prescription/update/validate.rs
Labels: Team Piwakawaka

#6428 6168 customised reports satisfaction rate per program
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/JsonForms/components/PatientProgramSearch.tsx
  client/packages/programs/src/JsonForms/components/PeriodSearch.tsx
  client/packages/programs/src/JsonForms/components/ProgramSearch.tsx
  client/packages/programs/src/JsonForms/components/index.ts
  client/packages/programs/src/api/hooks/keys.ts
  client/packages/programs/src/api/hooks/usePeriodList.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/reports/src/ListView/ListView.tsx
  client/packages/requisitions/src/index.ts
  client/packages/system/src/Report/components/ReportArgumentsModal.tsx
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/queries/program.rs
  server/graphql/requisition/src/requisition_queries.rs
  server/graphql/types/src/types/period.rs
  server/report_builder/README.md
  server/repository/src/db_diesel/period/period.rs
  server/service/src/program/query.rs
  server/service/src/requisition/request_requisition/requisition_item_info.rs
  server/service/src/rnr_form/schedules_with_periods.rs
  server/service/src/rnr_form/validate.rs
  standard_reports/encounters/2_6/argument_schemas/arguments_ui.json
Labels: enhancement, Team Ruru 🦉, feature: reports, feature: CIV

#6480 6086 Unclear which store's SOH & AMC are shown when clicking on an item in Requisitions
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
Labels: enhancement, Priority: Should have, Team Ruru 🦉, needs design, docs: external, feature: manual requisition

#6476 6459 Can send blank internal orders
  client/packages/common/src/intl/locales/en/common.json
  client/packages/requisitions/src/RequestRequisition/DetailView/Footer/StatusChangeButton.tsx
Labels: Team Ruru 🦉

#6458 6191 customised report stocktake per period
  client/packages/common/src/intl/locales/en/common.json
  client/packages/programs/src/JsonForms/components/PeriodSearch.tsx
  server/graphql/stocktake/src/stocktake_queries.rs
  server/graphql/types/src/types/stocktake.rs
  server/repository/src/db_diesel/period/period.rs
  server/repository/src/db_diesel/stocktake.rs
  server/repository/src/db_diesel/stocktake_row.rs
  server/repository/src/migrations/v2_06_00/add_program_id_on_stocktake.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/service/src/stocktake/insert/generate.rs
  server/service/src/sync/test/test_data/stocktake.rs
  server/service/src/sync/translations/stocktake.rs
Labels: enhancement, Team Ruru 🦉, feature: reports, feature: CIV

#6475 6344 customised report prescription
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  server/graphql/invoice/src/invoice_queries.rs
  server/graphql/types/src/types/invoice_query.rs
  server/repository/src/db_diesel/invoice.rs
Labels: enhancement, Team Ruru 🦉, feature: reports, feature: CIV

#6508 Refactor utils to have overridable name as displaying report name
  client/packages/reports/src/utils.ts
Labels: enhancement, feature: reports

#6384 5675.3 batch create IS lines from IO lines
  server/graphql/batch_mutations/src/batch_inbound_shipment.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert_from_internal_order.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/mod.rs
  server/repository/src/mock/mod.rs
  server/service/src/invoice/inbound_shipment/batch.rs
  server/service/src/invoice_line/inbound_shipment_from_internal_order_lines/generate.rs
  server/service/src/invoice_line/inbound_shipment_from_internal_order_lines/mod.rs
  server/service/src/invoice_line/inbound_shipment_from_internal_order_lines/validate.rs
  server/service/src/invoice_line/mod.rs
  server/service/src/program/query.rs
Labels: enhancement, Build Tested: Dev, Team Ruru 🦉, feature: CIV

#6390 5675.4 frontend
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
  client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
  client/packages/invoices/src/InboundShipment/DetailView/AddButton.tsx
  client/packages/invoices/src/InboundShipment/DetailView/AddFromInternalOrder.tsx
  client/packages/invoices/src/InboundShipment/DetailView/AddFromMasterListButton.tsx
  client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/hooks/document/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/document/useListInternalOrderLines.ts
  client/packages/invoices/src/InboundShipment/api/hooks/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/line/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/line/useLinesFromInternalOrder.ts
  client/packages/invoices/src/InboundShipment/api/hooks/utils/useInboundApi.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  server/graphql/batch_mutations/src/batch_inbound_shipment.rs
Labels: bug, Team Ruru 🦉, Severity: Normal, feature: GEDSI, feature: CIV, UI tweaks

#6415 6267 add toolbar rendered encounter fields
  client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/programs/src/JsonForms/common/JsonForm.tsx
  client/packages/programs/src/JsonForms/common/components/ToolbarLayout.tsx
  client/packages/programs/src/JsonForms/common/components/index.ts
  client/packages/programs/src/JsonForms/common/index.ts
  client/packages/system/src/Encounter/DetailView/AppBarButtons.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
Labels: feature: vaccine card, Team: Kororā 🐧

#6528 6488 printer graphql
  client/packages/common/src/types/schema.ts
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/lib.rs
  server/graphql/printer/Cargo.toml
  server/graphql/printer/lib.rs
  server/graphql/printer/mutations/insert.rs
  server/graphql/printer/mutations/mod.rs
  server/graphql/printer/mutations/update.rs
  server/graphql/printer/query.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/printer.rs
  server/repository/src/db_diesel/printer.rs
  server/repository/src/db_diesel/printer_row.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/printer.rs
  server/service/src/lib.rs
  server/service/src/printer/insert.rs
  server/service/src/printer/mod.rs
  server/service/src/printer/query.rs
  server/service/src/printer/tests/insert.rs
  server/service/src/printer/tests/mod.rs
  server/service/src/printer/tests/query.rs
  server/service/src/printer/tests/update.rs
  server/service/src/printer/update.rs
  server/service/src/printer/validate.rs
  server/service/src/service_provider.rs
Labels: enhancement, Jobcode: Yes, Team: Kororā 🐧

#6548 Refactor plugin data structure
  client/packages/common/src/plugins/usePluginEvents.ts
  client/packages/common/src/types/schema.ts
  server/graphql/plugin/src/lib.rs
  server/graphql/plugin/src/plugin_data/mutations/insert.rs
  server/graphql/plugin/src/plugin_data/mutations/mod.rs
  server/graphql/plugin/src/plugin_data/mutations/update.rs
  server/graphql/plugin/src/plugin_data/query.rs
  server/graphql/plugin/src/types.rs
  server/repository/src/db_diesel/plugin_data.rs
  server/repository/src/db_diesel/plugin_data_row.rs
  server/repository/src/migrations/v2_06_00/plugin_data.rs
  server/service/src/auth.rs
  server/service/src/plugin/mod.rs
  server/service/src/plugin_data/insert.rs
  server/service/src/plugin_data/update.rs
Labels: Team Piwakawaka, feature: plugin

#6479 5516 i can delete a requisition line for which stock has been allocated in a outbound shipment
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RequestRequisition/api/hooks/line/useDeleteRequestLines.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useDeleteResponseLines.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  client/packages/requisitions/src/ResponseRequisition/context/responseRequisitionLineError.tsx
  server/graphql/core/src/simple_generic_errors.rs
  server/graphql/requisition_line/src/mutations/response_requisition_line/delete.rs
  server/service/src/requisition_line/response_requisition_line/delete.rs
Labels: bug, Team Ruru 🦉, Severity: Normal

#6513 6471 insurance graphql service layer mutation
  server/graphql/general/src/lib.rs
  server/graphql/general/src/mutations/insert_insurance.rs
  server/graphql/general/src/mutations/mod.rs
  server/graphql/general/src/mutations/update_insurance.rs
  server/graphql/general/src/queries/insurances.rs
  server/graphql/general/src/types.rs
  server/graphql/types/src/types/mod.rs
  server/service/src/insurance/insert/generate.rs
  server/service/src/insurance/insert/mod.rs
  server/service/src/insurance/insert/test.rs
  server/service/src/insurance/insert/validate.rs
  server/service/src/insurance/mod.rs
  server/service/src/insurance/query.rs
  server/service/src/insurance/tests/mod.rs
  server/service/src/insurance/tests/query.rs
  server/service/src/insurance/update/generate.rs
  server/service/src/insurance/update/mod.rs
  server/service/src/insurance/update/test.rs
  server/service/src/insurance/update/validate.rs
  server/service/src/service_provider.rs
Labels: Team Piwakawaka, feature: dispensing, Jobcode: Yes

#6425 6406 update report readme
  server/report_builder/README.md
  standard_reports/README.md
Labels: Team Ruru 🦉

#6541 6510 add fields to prescription more panel
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/SidePanel.tsx
Labels: Team Piwakawaka, feature: dispensing

#6550 6547 insurance scheme in payments modal
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/DetailView/Payments/PaymentsModal.tsx
Labels: Team Piwakawaka, feature: dispensing

#6514 6343 Add datetime filter to itemledger endpoint for customised stockouts report
  server/graphql/general/src/queries/ledger.rs
Labels: enhancement, Team Ruru 🦉, feature: reports, feature: CIV

#6546 6205 patient insurance editing
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/Payments/PaymentsModal.tsx
  client/packages/programs/src/hooks/usePatientModalStore.ts
  client/packages/system/src/Patient/Insurance/InsuranceModal.tsx
  client/packages/system/src/Patient/Insurance/InsurancePolicySelect.tsx
  client/packages/system/src/Patient/Insurance/InsuranceProvidersSelect.tsx
  client/packages/system/src/Patient/Insurance/InsuranceStatusToggle.tsx
  client/packages/system/src/Patient/Insurance/ListView.tsx
  client/packages/system/src/Patient/Insurance/columns.ts
  client/packages/system/src/Patient/Insurance/index.ts
  client/packages/system/src/Patient/PatientView/AddButton.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Patient/api/api.ts
  client/packages/system/src/Patient/api/hooks/document/index.ts
  client/packages/system/src/Patient/api/hooks/document/useInsurances.ts
  client/packages/system/src/Patient/api/hooks/index.ts
  client/packages/system/src/Patient/api/hooks/utils/usePatientApi.ts
  client/packages/system/src/Patient/api/operations.generated.ts
  client/packages/system/src/Patient/api/operations.graphql
  client/packages/system/src/Patient/apiModern/hooks/index.ts
  client/packages/system/src/Patient/apiModern/hooks/keys.ts
  client/packages/system/src/Patient/apiModern/hooks/useInsuranceProviders.ts
  client/packages/system/src/Patient/apiModern/hooks/useInsurances.ts
  client/packages/system/src/Patient/apiModern/index.ts
  client/packages/system/src/Patient/apiModern/operations.generated.ts
  client/packages/system/src/Patient/apiModern/operations.graphql
  client/packages/system/src/Patient/apiModern/usePatientGraphQL.ts
  client/packages/system/src/Patient/index.ts
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/insurance_providers.rs
  server/graphql/general/src/queries/mod.rs
  server/repository/src/db_diesel/insurance_provider_row.rs
  server/service/src/insurance_provider/mod.rs
  server/service/src/insurance_provider/query.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
Labels: Team Piwakawaka, feature: dispensing

#6565 #6542 dispensary label printing
  server/server/src/print/label.rs
  server/server/src/print/mod.rs
  server/service/src/auth_data.rs
  server/service/src/print/label.rs
  server/service/src/token_bucket.rs
Labels: enhancement, Team: Kororā 🐧

#6577 Prescription Creation with more fields!
  server/graphql/batch_mutations/src/batch_prescription.rs
  server/graphql/invoice/src/mutations/prescription/insert.rs
  server/service/src/invoice/prescription/insert/generate.rs
  server/service/src/invoice/prescription/insert/mod.rs
  server/service/src/invoice/prescription/invoice_date_utils.rs
  server/service/src/invoice/prescription/mod.rs
  server/service/src/invoice/prescription/update/generate.rs
  server/service/src/vaccination/generate.rs
Labels: enhancement, Team Piwakawaka, feature: dispensing

#6562 6290 payment plugin
  .gitignore
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/plugins/prescriptionTypes.ts
  client/packages/common/src/plugins/types.ts
  client/packages/invoices/src/Prescriptions/DetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Payments/PaymentsModal.tsx
  client/packages/plugins/backendTypes/types.ts
Labels: Team Piwakawaka, feature: dispensing

#6554 6533 pagination for period
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/JsonForms/components/PeriodSearch.tsx
  client/packages/programs/src/api/hooks/usePeriodList.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/queries/program.rs
  server/graphql/types/src/types/period.rs
  server/repository/src/db_diesel/period/period.rs
  server/service/src/program/query.rs
  server/service/src/rnr_form/schedules_with_periods.rs
Labels: Team Ruru 🦉

#6584 Remove datetime filter from ledger.rs
  server/graphql/general/src/queries/ledger.rs
Labels: enhancement, Team Ruru 🦉, feature: reports, feature: CIV

#6590 #6545 New Create Prescription modal
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/ListView/AppBarButtons.tsx
  client/packages/invoices/src/Prescriptions/ListView/NewPrescriptionModal.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescription.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx
  client/packages/system/src/Patient/Components/PatientSearchModal/PatientSearchModal.tsx
  client/packages/system/src/Patient/Components/PatientSearchModal/index.ts
  client/packages/system/src/Patient/Components/index.ts
  client/packages/system/src/Patient/Components/utils.ts
  client/packages/system/src/Patient/utils.ts
  server/graphql/invoice/src/mutations/prescription/insert.rs
  server/repository/src/migrations/v2_06_00/add_cancellation_fields_to_invoice.rs
  server/repository/src/migrations/v2_06_00/add_cancelled_status_to_invoice.rs
  server/repository/src/migrations/v2_06_00/mod.rs
Labels: enhancement, Team Piwakawaka, feature: dispensing

#6586 6517 App crashes when I click on disabled Reason dropdown Supplier return edit modal
  client/packages/system/src/ReturnReason/Components/ReturnReasonSearchInput.tsx
Labels: Team Ruru 🦉, Severity: High, feature: returns

#6537 Add migration changes for reports
  server/cli/src/cli.rs
  server/cli/src/report_utils.rs
  server/graphql/reports/src/reports.rs
  server/repository/src/db_diesel/report.rs
  server/repository/src/db_diesel/report_row.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/repository/src/migrations/v2_06_00/reinitialise_reports.rs
  server/service/src/report/report_service.rs
  server/service/src/standard_reports.rs
  server/service/src/sync/test/integration/central/report.rs
  server/service/src/sync/test/test_data/om_report.rs
Labels: enhancement, Team Ruru 🦉, feature: reports

#6627 Add a checklist to PR template
  .github/pull_request_template.md
Labels: Priority: Must Have

#6622 6612 prescribed quantity gets overriden
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/utils.tsx
Labels: bug, Team Piwakawaka, Severity: High, feature: dispensing

#6611 6398 display existing doses from deleted vaccine courses
  client/packages/common/src/types/schema.ts
  server/graphql/core/src/loader/vaccine_course.rs
  server/graphql/types/src/types/vaccine_course_dose.rs
  server/graphql/vaccine_course/src/vaccine_course_queries.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course.rs
Labels: Severity: High, feature: vaccine card, Team: Kororā 🐧

#6626 Prevent needing to double-click 'Next' when adding items to Internal Orders
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
Labels: bug, Severity: Normal, UI tweaks, Team: Kororā 🐧

#6633 6615 fix vaccine course age cells
  client/packages/common/src/ui/layout/tables/components/Cells/MultiNumberInputCell/MultiNumberInputCell.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
Labels: Severity: High, feature: vaccine card, Team: Kororā 🐧

#6610 5812 vaccinated children report
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
  client/packages/invoices/src/Prescriptions/ListView/NewPrescriptionModal.tsx
  client/packages/programs/src/Components/ProgramSearchInput.tsx
  client/packages/programs/src/JsonForms/components/ProgramSearch.tsx
  client/packages/programs/src/api/hooks/useProgramList.ts
  client/packages/reports/src/ListView/ListView.tsx
Labels: enhancement, feature: vaccine card, Team: Kororā 🐧

#6519 Update kbar and add manual button
  client/packages/common/src/intl/locales/en/common.json
  client/packages/host/src/CommandK.tsx
Labels: Severity: Low, UI tweaks

#6623 6521 Remove whitespace from username input
  client/packages/host/src/components/Login/hooks.ts
Labels: Team Ruru 🦉, Severity: High

#6672 6605 fix time picker crash
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
Labels: feature: programs, Severity: Normal, Team: Kororā 🐧

#6675 6441 fix add item variant
  client/packages/common/src/ui/components/errors/NothingHere.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
Labels: Team Piwakawaka, Severity: Hotfix, feature: GAPS

#6591 6563 rename masterlist to masterlists in stock line node and move to item node
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/JsonForms/components/ProgramSearch.tsx
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/graphql/requisition/src/requisition_queries.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/stock_line.rs
Labels: refactor, Team Ruru 🦉

#6636 6332 location/autocomplete mui fixes
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
  client/packages/common/src/ui/components/inputs/Select/Select.tsx
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
Labels: UI tweaks, Team: Kororā 🐧

#6625 6174 prescription insurance details
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/index.ts
  client/packages/invoices/src/Prescriptions/api/hooks/keys.ts
  client/packages/invoices/src/Prescriptions/api/hooks/useInsurance.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/insurances.rs
  server/graphql/lib.rs
  server/service/src/insurance/mod.rs
  server/service/src/insurance/query.rs
Labels: Team Piwakawaka, feature: dispensing

#6671 6668 fix context type in report migration
  server/repository/src/db_diesel/report_row.rs
  server/repository/src/migrations/v2_06_00/reinitialise_reports.rs
Labels: Team Ruru 🦉, feature: reports

#6618 6530 gender options are in english
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/programs/src/hooks/usePatientStore.ts
  client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
  client/packages/system/src/Patient/PatientView/PatientSummary.tsx
  client/packages/system/src/Patient/PatientView/utils.ts
Labels: Severity: High, feature: dispensing, Team: Kororā 🐧

#6608 Translate labels
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/CustomerIndicatorInfo.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
  client/packages/requisitions/src/utils.ts
Labels: needs triage, Severity: Low, Effort: small

#6678 6592 clearable json form fields
  client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx
  client/packages/programs/src/JsonForms/common/components/Group.tsx
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
Labels: Severity: Normal, feature: dispensing, feature: vaccine card, Team: Kororā 🐧

#6681 6594 link program patients as next of kin
  client/packages/programs/src/JsonForms/components/Search/usePatientSearchQuery.tsx
Labels: Severity: Normal, feature: vaccine card, Team: Kororā 🐧

#6658 6597 navigate after not scheduling encounter
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalContext.ts
  client/packages/common/src/ui/components/modals/ConfirmationModal/ConfirmationModalProvider.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/UseSuggestedQuantityButton.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/SupplyRequestedQuantityButton.tsx
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/ScheduleNextEncounterModal.tsx
  client/packages/system/src/Encounter/DetailView/useSaveWithStatusChange.tsx
Labels: feature: programs, Severity: High, Team: Kororā 🐧

#6664 6657 Misc prescription/insurance fixes
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
  client/packages/invoices/src/Prescriptions/DetailView/DetailView.tsx
  client/packages/invoices/src/Prescriptions/DetailView/History/HistoryModal.tsx
  client/packages/system/src/Patient/Insurance/InsuranceModal.tsx
  client/packages/system/src/Patient/Insurance/InsuranceStatusToggle.tsx
Labels: Team Piwakawaka

#6686 Set is dirty state when updating quantity
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEdit.tsx
Labels: Team Ruru 🦉, Severity: High

#6638 5032 add siteName to OG login v4 requests
  server/cli/src/cli.rs
  server/cli/src/test_connection.rs
  server/service/src/apis/login_v4.rs
  server/service/src/login.rs
  server/service/src/sync/sync_user.rs
Labels: bug, Severity: High, Team: Kororā 🐧

#6717 Tell the browser to use UTF-8
  client/packages/host/public/index.html
Labels: Team Ruru 🦉, Severity: High, Needs Investigation

#6701 6582 Update save button to stay disabled if no changes made
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
Labels: Team Ruru 🦉, Severity: High

#6667 Remove Deleted Items from Vaccine List
  client/packages/system/src/Item/api/api.ts
Labels: bug, Team Piwakawaka, Severity: High, feature: GAPS, feature: vaccine card

#6688 6653 prescription sidepanel styling
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PricingSection.tsx
Labels: enhancement, Team Piwakawaka, Severity: Normal

#6718 #6689 Always clear directions abbreviation field
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
Labels: Team Piwakawaka, Severity: High, feature: dispensing

#6738 Remove conditional
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
Labels: Team Piwakawaka, feature: dispensing

#6721 #6677 Don't show expired or inactive insurances in Prescription payment
  client/packages/common/src/intl/utils/DateUtils.ts
  client/packages/invoices/src/Prescriptions/DetailView/Payments/PaymentsModal.tsx
  client/packages/system/src/Patient/apiModern/hooks/useInsurances.ts
Labels: bug, Team Piwakawaka, feature: dispensing

#6728 6716 fix encounter report description
  client/packages/common/src/intl/locales/en/common.json
Labels: feature: programs, Severity: Normal, feature: reports, Team: Kororā 🐧

#6734 6257 fix encounter filter date
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx
  client/packages/invoices/src/InboundShipment/ListView/Toolbar.tsx
Labels: Severity: High, Team: Kororā 🐧, area: date picker

#6735 6578 add back JSON date picker ok button
  client/packages/programs/src/JsonForms/common/components/DateTime.tsx
Labels: Severity: Normal, feature: reports, Team: Kororā 🐧, area: date picker

#6699 6630 prevent saving empty vaccine courses
  client/packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
Labels: Severity: Normal, feature: vaccine card, Team: Kororā 🐧

#6727 6719 insurance loader
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/Payments/PaymentsModal.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/index.ts
  client/packages/invoices/src/Prescriptions/api/hooks/useInsurance.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  client/packages/system/src/Patient/Insurance/InsuranceModal.tsx
  client/packages/system/src/Patient/Insurance/ListView.tsx
  client/packages/system/src/Patient/apiModern/hooks/index.ts
  client/packages/system/src/Patient/apiModern/hooks/keys.ts
  client/packages/system/src/Patient/apiModern/hooks/useInsurancesPolicies.ts
  client/packages/system/src/Patient/apiModern/operations.generated.ts
  client/packages/system/src/Patient/apiModern/operations.graphql
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/name_insurance_join.rs
  server/graphql/general/src/lib.rs
  server/graphql/general/src/mutations/insert_insurance.rs
  server/graphql/general/src/mutations/update_insurance.rs
  server/graphql/general/src/queries/insurance_policies.rs
  server/graphql/general/src/queries/mod.rs
  server/graphql/general/src/types.rs
  server/graphql/types/src/types/insurance_policy.rs
  server/graphql/types/src/types/insurance_provider.rs
  server/graphql/types/src/types/invoice_query.rs
  server/graphql/types/src/types/mod.rs
  server/repository/src/db_diesel/name_insurance_join_row.rs
Labels: Team Piwakawaka, feature: dispensing

#6730 4884 vaccine age range fixes
  client/packages/common/src/intl/locales/en/common.json
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
Labels: bug, Build Tested: Issues Found, Tester: Maria, Severity: Normal, feature: vaccine card, Build Tested: Needs Retesting, Team: Kororā 🐧

#6679 6165 disable directions if cant add item
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
Labels: bug, Severity: Normal, feature: dispensing, Team: Kororā 🐧

#6739 #6504 Sync Prescription is_cancellation and cancelled_datetime fields
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/translations/invoice.rs
Labels: Team Piwakawaka, feature: dispensing

#6751 Wording updates & fr translations
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
Labels: Team Piwakawaka, feature: dispensing

#6742 6637 fix date translations
  client/packages/common/src/intl/context/IntlContext.tsx
  client/packages/electron/src/home.tsx
  client/packages/host/src/Host.tsx
Labels: Severity: High, Team: Kororā 🐧

#6743 Clear selected option
  client/packages/common/src/ui/components/footer/ActionsFooter.tsx
Labels: enhancement, make omSupply delightful, Team Ruru 🦉, Effort: small

#6741 6733 changing insurance doesnt correctly change
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/DetailView/Payments/PaymentsModal.tsx
Labels: Team Piwakawaka, feature: dispensing
