Repository msupply-foundation/open-msupply, pull requests merged in 2025-04, with the labels that each got.

#7012 Automatically create a location for new CCE assets
  server/repository/src/db_diesel/assets/asset_internal_location_row.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/tests/insert.rs
  server/service/src/asset/tests/update.rs
Labels: Team Piwakawaka, feature: GAPS

#7015 6849 restrict ability to manually add cce to admin users onlyfacility users can only add cce by scanning 2d datamatrix
  client/packages/coldchain/src/Equipment/ListView/AddFromScannerButton.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v2_07_00/asset_data_matrix_permission.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/service/src/apis/permissions.rs
  server/service/src/auth.rs
  server/service/src/login.rs
Labels: Team Piwakawaka, feature: GAPS

#7123 6849 Prevent no admin users from editing GS1 (Data matrix) provided data
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/operations.generated.ts
  client/packages/coldchain/src/Equipment/api/operations.graphql
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  server/graphql/asset/Cargo.toml
  server/graphql/asset/src/mutations/insert.rs
  server/graphql/asset/src/types/asset.rs
  server/repository/src/db_diesel/assets/asset_row.rs
  server/repository/src/migrations/v2_07_00/asset_data_matrix_locked_fields.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/service/src/asset/insert.rs
  server/service/src/asset/parse.rs
Labels: Team Piwakawaka, feature: GAPS

#7132 Fix typo in gql errors for document registry
  server/graphql/programs/src/mutations/contact_trace/insert.rs
  server/graphql/programs/src/mutations/contact_trace/update.rs
  server/graphql/programs/src/mutations/program_enrolment/insert.rs
  server/graphql/programs/src/mutations/program_enrolment/update.rs
  server/graphql/programs/src/mutations/program_patient/insert.rs
  server/graphql/programs/src/mutations/program_patient/update.rs
  server/service/src/programs/contact_trace/upsert.rs
  server/service/src/programs/patient/upsert_program_patient.rs
  server/service/src/programs/program_enrolment/upsert.rs
Labels: bug, Team Ruru 🦉, Severity: Low, UI tweaks

#7112 7096 add patient id to vaccination records
  server/repository/src/db_diesel/vaccination_row.rs
  server/repository/src/migrations/v2_07_00/add_patient_link_id_to_vaccination.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/service/src/sync/test/test_data/vaccination.rs
  server/service/src/vaccination/insert/generate.rs
  server/service/src/vaccination/update/generate.rs
Labels: enhancement, Build Tested: Dev, Team Ruru 🦉, feature: vaccine card

#7115 6137 Update on hold - delete error message
  client/packages/common/src/intl/locales/en/common.json
  client/packages/inventory/src/Stocktake/api/hooks/document/useStocktakeDeleteSelected.ts
  client/packages/inventory/src/utils.ts
Labels: bug, Team Ruru 🦉, Severity: Low, UI tweaks

#7150 Add find_all_active pattern
  server/repository/src/db_diesel/insurance_provider_row.rs
  server/service/src/insurance_provider/query.rs
Labels: Build Tested: Issues Found, Tester: Maria, Team Piwakawaka, Severity: High, feature: dispensing, Build Tested: Needs Retesting

#7139 7122 fix permission error on cold chain equipment
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
Labels: Team Piwakawaka

#7154 show insurance status on patient details
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PatientDetails.tsx
Labels: enhancement, Team Piwakawaka, feature: dispensing

#7119 7007 central server UI for manage assets cce
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/ListView/columns.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/usePathnameIncludes/index.ts
  client/packages/common/src/hooks/usePathnameIncludes/usePathnameIncludes.tsx
  client/packages/common/src/types/schema.ts
  client/packages/host/src/components/Navigation/ManageNav.tsx
  client/packages/host/src/routers/ManageRouter.tsx
  server/graphql/asset/src/mutations/insert.rs
  server/graphql/asset/src/types/asset.rs
  server/repository/src/db_diesel/assets/asset.rs
Labels: enhancement, Team Piwakawaka, feature: GAPS

#7169 7155 move program to main window
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ProgramInfoSection.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Toolbar/Toolbar.tsx
Labels: enhancement, Priority: Must Have, Team Ruru 🦉, feature: CIV

#7166 6142 Update rnr adjusted description
  client/packages/common/src/intl/locales/en/common.json
Labels: bug, Build Tested: Issues Found, Tester: Maria, Team Ruru 🦉, Severity: Normal, feature: R&R, Build Tested: Needs Retesting

#7175 7167 fix permission denied on prefs page
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Manage/Preferences/api/operations.generated.ts
  client/packages/system/src/Manage/Preferences/api/operations.graphql
  client/packages/system/src/Manage/Preferences/api/useAvailablePreferences.ts
  server/graphql/preference/src/lib.rs
Labels: Team Ruru 🦉, Severity: High, feature: preferences

#7144 2528.1 refactor hooks to use new hook pattern
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/coldchain/src/Mobile/Equipment/DetailView/LogCardListView.tsx
  client/packages/common/src/utils/globalConst.ts
  client/packages/system/src/ActivityLog/Components/ListView.tsx
  client/packages/system/src/ActivityLog/api/api.ts
  client/packages/system/src/ActivityLog/api/hooks/document/index.ts
  client/packages/system/src/ActivityLog/api/hooks/document/useActivityLogsByRecord.ts
  client/packages/system/src/ActivityLog/api/hooks/index.ts
  client/packages/system/src/ActivityLog/api/hooks/keys.ts
  client/packages/system/src/ActivityLog/api/hooks/useActivityLog.ts
  client/packages/system/src/ActivityLog/api/hooks/utils/index.ts
  client/packages/system/src/ActivityLog/api/hooks/utils/useActivityLogApi.ts
  client/packages/system/src/ActivityLog/api/useActivityLogGraphQL.ts
  client/packages/system/src/Asset/ImportCatalogueItem/CatalogueItemImportModal.tsx
  client/packages/system/src/Asset/ListView/AppBarButtons.tsx
  client/packages/system/src/Asset/ListView/ListView.tsx
  client/packages/system/src/Asset/api/hooks/document/index.ts
  client/packages/system/src/Asset/api/hooks/document/useAssetItemInsert.ts
  client/packages/system/src/Asset/api/hooks/document/useAssets.ts
  client/packages/system/src/Asset/api/hooks/document/useAssetsAll.ts
  client/packages/system/src/Asset/api/hooks/document/useAssetsDelete.ts
  client/packages/system/src/Asset/api/hooks/index.ts
  client/packages/system/src/Asset/api/hooks/keys.ts
  client/packages/system/src/Asset/api/hooks/useAsset.ts
  client/packages/system/src/Asset/api/hooks/useAssetList.ts
  client/packages/system/src/Asset/api/useAssetGraphQL.ts
  client/packages/system/src/Asset/index.ts
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
Labels: enhancement, front-end, needs architecture/solution, Priority: Nice to Have, refactor

#7174 Prevents render of too many years
  client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx
Labels: bug, Team Piwakawaka, Severity: High, Needs Investigation

#7148 5776 Show available stock in Inventory
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal

#7170 #7105 Improve prescription payment error
  client/packages/common/src/plugins/prescriptionTypes.ts
  client/packages/invoices/src/Prescriptions/DetailView/Payments/PaymentsModal.tsx
Labels: Team Piwakawaka, feature: CIV

#7173 7172 remove reference constraints from vaccination migration
  server/repository/src/migrations/v2_06_01/change_vaccination_date_to_nullable.rs
Labels: Team Ruru 🦉, Severity: Hotfix, feature: vaccine card

#7178 Fix error in deserializing sql date for plugins
  client/packages/plugins/backendCommon/utils.ts
Labels: Team Ruru 🦉, Severity: Hotfix, Severity: High, Needs Investigation, feature: CIV

#7125 6994 outbound shipment expected delivery date
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/TransportSection.tsx
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/invoices/src/OutboundShipment/DetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/TransportSection.tsx
  client/packages/invoices/src/OutboundShipment/api/api.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
  client/packages/system/src/Clinician/ClinicianSearchInput.tsx
  server/cli/src/refresh_dates.rs
  server/graphql/invoice/src/mutations/outbound_shipment/error.rs
  server/graphql/invoice/src/mutations/outbound_shipment/update.rs
  server/graphql/types/src/types/invoice_query.rs
  server/repository/src/db_diesel/invoice_row.rs
  server/repository/src/migrations/v2_07_00/add_expected_delivery_date_to_invoice.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/service/src/invoice/customer_return/insert/generate.rs
  server/service/src/invoice/inbound_shipment/insert/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/outbound_shipment/insert/generate.rs
  server/service/src/invoice/outbound_shipment/update/generate.rs
  server/service/src/invoice/outbound_shipment/update/mod.rs
  server/service/src/invoice/outbound_shipment/update/validate.rs
  server/service/src/invoice/prescription/insert/generate.rs
  server/service/src/invoice/supplier_return/insert/generate.rs
  server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
  server/service/src/processors/transfer/invoice/update_inbound_invoice.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/translations/invoice.rs
Labels: enhancement, Team Ruru 🦉, docs: external

#7204 7203 furx terst
  server/service/src/sync/test/test_data/invoice_line.rs
Labels: Team Ruru 🦉, Severity: Hotfix, needs daily triage

#7163 6312 Align placeholder row packSize column
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
Labels: Team Ruru 🦉, Severity: Normal, Effort: small, UI tweaks

#7201 7196 sync http request timeout
  server/util/src/api_helper.rs
Labels: Team Ruru 🦉, Severity: Hotfix

#7192 6930 Revert to use average days in a month for most calculations
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  server/repository/src/mock/test_item_stats.rs
  server/service/src/item_stats.rs
  server/service/src/requisition_line/chart/historic_consumption.rs
  server/service/src/requisition_line/chart/mod.rs
  server/service/src/requisition_line/chart/stock_evolution.rs
Labels: Severity: Hotfix, Needs refinement

#7205 2528.3
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Details.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
  client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/api/hooks/document/index.ts
  client/packages/coldchain/src/Equipment/api/hooks/index.ts
  client/packages/common/src/hooks/useQueryParams/types.ts
  client/packages/system/src/Asset/ImportCatalogueItem/CatalogueItemImportModal.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
  client/packages/system/src/Asset/ListView/Toolbar.tsx
  client/packages/system/src/Asset/api/api.ts
  client/packages/system/src/Asset/api/hooks/index.ts
  client/packages/system/src/Asset/api/hooks/useAssetCategories.ts
  client/packages/system/src/Asset/api/hooks/useAssetClasses.ts
  client/packages/system/src/Asset/api/hooks/useAssetProperties.ts
  client/packages/system/src/Asset/api/hooks/useAssetTypes.ts
  client/packages/system/src/Asset/api/hooks/utils/index.ts
  client/packages/system/src/Asset/api/hooks/utils/useAssetApi.ts
  client/packages/system/src/Asset/api/hooks/utils/useAssetCategories.ts
  client/packages/system/src/Asset/api/hooks/utils/useAssetClasses.ts
  client/packages/system/src/Asset/api/hooks/utils/useAssetProperties.ts
  client/packages/system/src/Asset/api/hooks/utils/useAssetTypes.ts
  client/packages/system/src/Asset/index.ts
Labels: enhancement, front-end, needs architecture/solution, Priority: Nice to Have, refactor, Team Ruru 🦉

#7135 6696 Add required indicator
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
Labels: Team Ruru 🦉, Severity: Low, needs design, Effort: small

#6906 Integration test fix
  server/service/src/processors/transfer/invoice/test.rs
  server/service/src/processors/transfer/requisition/test.rs
  server/service/src/sync/sync_status/logger.rs
  server/service/src/sync/test/integration/central/mod.rs
  server/service/src/sync/test/integration/central/report.rs
  server/service/src/sync/test/integration/central/test.rs
  server/service/src/sync/test/integration/omsupply_central/mod.rs
  server/service/src/sync/test/integration/omsupply_central/test.rs
  server/service/src/sync/test/integration/remote/invoice.rs
  server/service/src/sync/test/integration/remote/stocktake.rs
  server/service/src/sync/translations/invoice_line.rs
Labels: Priority: Must Have, Team Ruru 🦉

#7165 7099 name store join filter on v6 sync
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/vaccination_row.rs
  server/repository/src/migrations/v2_07_00/add_patient_link_id_to_vaccination.rs
  server/repository/src/mock/vaccination.rs
  server/service/src/sync/test/test_data/vaccination.rs
Labels: enhancement, Team Ruru 🦉, feature: vaccine card

#7214 7198 fix test builds failing
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Labels: Team Piwakawaka, needs daily triage

#7216 6941 fix stock quantity rounding
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: Team Piwakawaka, Severity: Normal

#7226 #7113 Outbound alerts layout
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditForm.tsx
Labels: Team Piwakawaka, Severity: High

#7233 7208 fix import asset and equipment csv error
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/system/src/Asset/ListView/Footer.tsx
  client/packages/system/src/Asset/api/hooks/index.ts
  client/packages/system/src/Asset/api/hooks/useAssetDelete.ts
  client/packages/system/src/Asset/api/hooks/useAssetList.ts
Labels: bug, Severity: High

#7244 6715 hide contact tracing
  client/packages/common/src/authentication/api/hooks/index.ts
  client/packages/common/src/authentication/api/hooks/useAuthApi.ts
  client/packages/common/src/authentication/api/hooks/usePreferences.ts
  client/packages/common/src/authentication/api/operations.generated.ts
  client/packages/common/src/authentication/api/operations.graphql
  client/packages/system/src/Manage/Preferences/EditPage/EditPreference.tsx
  client/packages/system/src/Manage/Preferences/api/usePreferences.ts
  client/packages/system/src/Patient/PatientView/AddButton.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
Labels: enhancement, Team Ruru 🦉, feature: vaccine card

#7212 7195 add correct id in build route
  client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
Labels: Team Piwakawaka, Severity: High

#7210 2528.4.coldchain part 1
  client/packages/coldchain/src/ColdchainNotification.tsx
  client/packages/coldchain/src/Monitoring/api/TemperatureBreach/hooks/document/useUpdateTemperatureBreach.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureNotification/api.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureNotification/hooks/document/index.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureNotification/hooks/document/useTemperatureNotifications.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureNotification/hooks/index.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureNotification/hooks/keys.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureNotification/hooks/useTemperatureNotificationList.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureNotification/hooks/utils/index.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureNotification/hooks/utils/useTemperatureNotificationApi.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureNotification/useTemperatureNotificationGraphQL.ts
  client/packages/coldchain/src/Sensor/Components/SensorEditModal.tsx
  client/packages/coldchain/src/Sensor/ListView/ListView.tsx
  client/packages/coldchain/src/Sensor/api/api.ts
  client/packages/coldchain/src/Sensor/api/hooks/document/index.ts
  client/packages/coldchain/src/Sensor/api/hooks/document/useSensorUpdate.ts
  client/packages/coldchain/src/Sensor/api/hooks/document/useSensors.ts
  client/packages/coldchain/src/Sensor/api/hooks/index.ts
  client/packages/coldchain/src/Sensor/api/hooks/keys.ts
  client/packages/coldchain/src/Sensor/api/hooks/useSensorList.ts
  client/packages/coldchain/src/Sensor/api/hooks/useSensorUpdate.ts
  client/packages/coldchain/src/Sensor/api/hooks/utils/index.ts
  client/packages/coldchain/src/Sensor/api/hooks/utils/useSensorApi.ts
  client/packages/coldchain/src/Sensor/api/useSensorGraphQL.ts
  client/packages/coldchain/src/common/ImportFridgeTag.tsx
Labels: enhancement, front-end, needs architecture/solution, Priority: Nice to Have, refactor, Team Ruru 🦉

#7240 #6900 Error when both policy number fields empty for new Insurance
  client/packages/system/src/Patient/Insurance/InsuranceModal.tsx
Labels: Team Piwakawaka, Severity: High

#7252 Translations: datepicker's buttons show in English #7241
  client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
Labels: Team Ruru 🦉, Severity: High, feature: translation

#7238 5889 Make reference field multi-lined in inbound shipment detail view
  client/packages/common/src/ui/components/inputs/TextArea/BufferedTextArea.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Toolbar.tsx
Labels: bug, good first issue, Team Ruru 🦉, Severity: Normal, needs design

#7197 7023 Remove mos from soh column
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
Labels: Priority: Nice to Have, Team Ruru 🦉, UI tweaks

#7257 7249 2.6.2 migration reintegrate store, skip transfers on linked_invoice_id.is_some()
  package.json
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_06_02/mod.rs
  server/repository/src/migrations/v2_06_02/store_reintegrate_for_created_date.rs
  server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
  server/service/src/processors/transfer/invoice/mod.rs
  server/util/src/api_helper.rs
Labels: Team Ruru 🦉, Severity: Hotfix

#7218 7100 show vax card in non home store
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Vaccination/Components/FacilitySearchInput.tsx
  client/packages/system/src/Vaccination/Components/SelectItemAndBatch.tsx
  client/packages/system/src/Vaccination/Components/VaccinationCard.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/service/src/vaccination/update/validate.rs
Labels: enhancement, Team Ruru 🦉, feature: vaccine card

#7220 6666 Make age column width relative vaccination card
  client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
Labels: Team Ruru 🦉, Severity: Low, feature: vaccine card, UI tweaks, area: tables

#7250 2528.5
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Monitoring/api/TemperatureNotification/hooks/useTemperatureNotificationList.ts
  client/packages/coldchain/src/Sensor/api/hooks/useSensorList.ts
  client/packages/common/src/utils/globalConst.ts
  client/packages/inventory/src/Stocktake/DetailView/ReduceLinesToZeroModal.tsx
  client/packages/inventory/src/Stocktake/ListView/CreateStocktakeButton.tsx
  client/packages/system/src/Asset/api/hooks/useAssetList.ts
  client/packages/system/src/Asset/api/hooks/useAssetLogReasonList.ts
  client/packages/system/src/Currency/Components/CurrencySearchInput.tsx
  client/packages/system/src/Currency/api/api.ts
  client/packages/system/src/Currency/api/hooks/document/index.ts
  client/packages/system/src/Currency/api/hooks/document/useCurrencies.ts
  client/packages/system/src/Currency/api/hooks/index.ts
  client/packages/system/src/Currency/api/hooks/keys.ts
  client/packages/system/src/Currency/api/hooks/useCurrencyList.ts
  client/packages/system/src/Currency/api/hooks/utils/index.ts
  client/packages/system/src/Currency/api/hooks/utils/useCurrencyApi.ts
  client/packages/system/src/Currency/api/useCurrencyGraphQL.ts
  client/packages/system/src/InventoryAdjustmentReason/Components/InventoryAdjustmentReasonSearchInput.tsx
  client/packages/system/src/InventoryAdjustmentReason/api/api.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/document/index.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/document/useInventoryAdjustmentReason.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/index.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/keys.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/useInventoryAdjustmentReasonList.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/utils/index.ts
  client/packages/system/src/InventoryAdjustmentReason/api/hooks/utils/useInventoryAdjustmentReasonApi.ts
  client/packages/system/src/InventoryAdjustmentReason/api/useInventoryAdjustmentReasonGraphQL.ts
  client/packages/system/src/Location/Components/LocationSearchInput.tsx
  client/packages/system/src/Location/ListView/AppBarButtons.tsx
  client/packages/system/src/Location/ListView/ListView.tsx
  client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx
  client/packages/system/src/Location/api/api.ts
  client/packages/system/src/Location/api/hooks/document/index.ts
  client/packages/system/src/Location/api/hooks/document/useLocations.ts
  client/packages/system/src/Location/api/hooks/document/useLocationsAll.ts
  client/packages/system/src/Location/api/hooks/document/useNextLocation.ts
  client/packages/system/src/Location/api/hooks/index.ts
  client/packages/system/src/Location/api/hooks/keys.ts
  client/packages/system/src/Location/api/hooks/useLocationList.ts
  client/packages/system/src/Location/api/hooks/utils/useLocationApi.ts
  client/packages/system/src/Location/api/useLocationGraphQL.ts
Labels: enhancement, front-end, needs architecture/solution, Priority: Nice to Have, refactor, Team Ruru 🦉

#7266 2528.6
  client/packages/system/src/Item/Components/index.ts
  client/packages/system/src/Location/ListView/Footer.tsx
  client/packages/system/src/Location/ListView/LocationEditModal/LocationEditModal.tsx
  client/packages/system/src/Location/api/api.ts
  client/packages/system/src/Location/api/hooks/document/index.ts
  client/packages/system/src/Location/api/hooks/document/useLocationInsert.ts
  client/packages/system/src/Location/api/hooks/document/useLocationUpdate.ts
  client/packages/system/src/Location/api/hooks/index.ts
  client/packages/system/src/Location/api/hooks/useLocation.ts
Labels: enhancement, front-end, needs architecture/solution, Priority: Nice to Have, refactor, Team Ruru 🦉

#7209 Adds appending of intial data to new data patch before mutation
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
Labels: Severity: High, feature: dispensing

#7253 7187 record not given vaccination date
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/Components/VaccineCardTable.tsx
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/graphql/programs/src/mutations/vaccination/update.rs
  server/graphql/types/src/types/program/vaccination.rs
  server/repository/src/db_diesel/vaccination_row.rs
  server/repository/src/migrations/v2_07_00/change_vaccination_date_to_not_nullable.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/service/src/sync/test/test_data/vaccination.rs
  server/service/src/vaccination/insert/generate.rs
  server/service/src/vaccination/update/generate.rs
  server/service/src/vaccination/update/mod.rs
Labels: Team Piwakawaka, Severity: High, feature: vaccine card

#7256 Patient schema changes
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
Labels: Epic

#7269 Recursion limit
  server/Cargo.lock
  server/android/src/android.rs
  server/android/src/lib.rs
  server/server/src/main.rs
  server/windows/Cargo.toml
  server/windows/src/windows.rs
Labels: Severity: Hotfix

#7281 7273 always assign serial number
  server/repository/src/db_diesel/key_value_store.rs
  server/repository/src/migrations/v2_06_02/add_assign_requisition_number_processor_pg_enum_type.rs
  server/repository/src/migrations/v2_06_02/mod.rs
  server/service/src/processors/assign_requisition_number/assign_requisition_number.rs
  server/service/src/processors/assign_requisition_number/mod.rs
  server/service/src/processors/assign_requisition_number/test.rs
  server/service/src/processors/general_processor.rs
  server/service/src/processors/mod.rs
  server/service/src/processors/transfer/requisition/assign_requisition_number.rs
  server/service/src/processors/transfer/requisition/mod.rs
  server/service/src/sync/synchroniser.rs
Labels: Team Ruru 🦉, Severity: Hotfix

#7287 Add translation changes for insurance
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/system/src/Patient/Insurance/InsuranceModal.tsx
Labels: Epic

#7292 7228 cant access encounter if clinician not visible
  server/graphql/types/src/types/program/encounter.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/repository/src/migrations/v2_07_00/remove_encounter_clinician_constraint.rs
Labels: feature: programs, Team Ruru 🦉, Severity: High

#7283 7232 unable to access linked prescription from vax card from another store
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  client/packages/programs/src/JsonForms/components/Prescription/PrescriptionInfo.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
Labels: Team Ruru 🦉, Severity: High, docs: external, feature: vaccine card

#7264 7160.2 patient record sync v6 part 2
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/vaccination_card.rs
  server/repository/src/db_diesel/vaccination_row.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/repository/src/migrations/v2_07_00/remove_name_store_join_constraint.rs
  server/service/src/sync/translations/name.rs
  server/service/src/sync/translations/name_store_join.rs
  server/service/src/vaccination/update/mod.rs
Labels: enhancement, Team Ruru 🦉, feature: vaccine card

#7271 7160.4 Add integration tests for multi site vaccination
  server/repository/src/db_diesel/name_store_join.rs
  server/repository/src/db_diesel/vaccination_row.rs
  server/service/src/apis/api_on_central/mod.rs
  server/service/src/programs/patient/insert_patient.rs
  server/service/src/programs/patient/patient_updated.rs
  server/service/src/programs/patient/upsert_program_patient.rs
  server/service/src/sync/test/integration/README.md
  server/service/src/sync/test/integration/central/mod.rs
  server/service/src/sync/test/integration/errors.rs
  server/service/src/sync/test/integration/mod.rs
  server/service/src/sync/test/integration/omsupply_central/mod.rs
  server/service/src/sync/test/integration/omsupply_central/test.rs
  server/service/src/sync/test/integration/omsupply_central/vaccine_card.rs
  server/service/src/sync/test/integration/remote/invoice.rs
  server/service/src/sync/test/integration/remote/mod.rs
  server/service/src/sync/test/integration/remote/stocktake.rs
  server/service/src/sync/test/integration/site_info.rs
  server/service/src/sync/test/integration/transfer/mod.rs
  server/service/src/sync/test/integration/transfer/requisition.rs
  server/service/src/sync/test/integration/transfer/returns.rs
  server/service/src/sync/test/integration/transfer/shipments.rs
  server/service/src/sync/test/mod.rs
Labels: enhancement, Team Ruru 🦉, feature: vaccine card

#7261 Make print errors translatable and add translations
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/system/src/Report/api/hooks/usePrintReport.ts
Labels: needs triage, Team Piwakawaka, Severity: High, feature: reports, feature: translation

#7294 7225 add prescription column changes
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Labels: Epic

#7295 #7106 Restrict Android phone to Portrait screen orientation
  client/packages/android/README.MD
  client/packages/android/app/capacitor.build.gradle
  client/packages/android/app/src/main/assets/capacitor.plugins.json
  client/packages/android/app/src/main/java/org/openmsupply/client/ExtendedWebViewClient.java
  client/packages/android/capacitor.settings.gradle
  client/packages/android/package.json
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/host/src/Host.tsx
  client/yarn.lock
Labels: Team Piwakawaka, feature: GAPS

#7280 7242 enable saving items even issue quantity is zero
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescriptionLines.ts
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/translations/invoice_line.rs
Labels: Team Piwakawaka, Severity: High, feature: dispensing, feature: CIV

#7255 6188-6407-5035 Add debounced value callback for prescription comment field
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
Labels: bug, Team Ruru 🦉, Severity: High

#7302 7300 unable to create log reason
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Asset/AssetLogReasons/LogReasonCreateModal/LogReasonCreateModal.tsx
  client/packages/system/src/Asset/api/hooks/useAssetLogReason.ts
  client/packages/system/src/Asset/utils.ts
Labels: Team Ruru 🦉, feature: GAPS

#7251 6767 sync item warnings
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/hooks/utils.test.tsx
  client/packages/invoices/src/Prescriptions/DetailView/hooks/utils.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/utils.test.ts
  client/packages/invoices/src/Prescriptions/api/hooks/utils.tsx
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/warning.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/warning.rs
  server/repository/src/db_diesel/item.rs
  server/repository/src/db_diesel/item_warning_join.rs
  server/repository/src/db_diesel/item_warning_join_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/warning.rs
  server/repository/src/db_diesel/warning_row.rs
  server/repository/src/migrations/v2_07_00/add_item_warning_join_table.rs
  server/repository/src/migrations/v2_07_00/add_warning_table.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/service/src/item_warning_join.rs
  server/service/src/lib.rs
  server/service/src/print/label.rs
  server/service/src/sync/test/test_data/item_warning_join.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/warning.rs
  server/service/src/sync/translations/item_warning_join.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/warning.rs
  server/service/src/warning.rs
Labels: Priority: Should have, Build Tested: Blocked, Team Ruru 🦉

#7268 Add report translation via code
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/index.ts
  client/packages/common/src/intl/utils/IntlUtils.ts
  client/packages/common/src/types/schema.ts
  client/packages/reports/src/DetailView/DetailView.tsx
  client/packages/reports/src/components/ReportWidget.tsx
  client/packages/reports/src/utils.ts
  client/packages/system/src/Report/api/operations.generated.ts
  client/packages/system/src/Report/api/operations.graphql
  client/packages/system/src/Report/components/ReportSelector.tsx
  server/graphql/reports/src/reports.rs
  standard_reports/README.md
Labels: Severity: High, feature: translation

#7321 7241 Translate datetime picker
  client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
Labels: Team Ruru 🦉, Severity: High, feature: translation

#7259 7097 approval status to pending if item is in a program
  server/service/src/processors/transfer/requisition/create_response_requisition.rs
Labels: Severity: High, Needs Investigation, Needs refinement

#7325 Fix yarn compilation/item warnings graphql
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/api/operations.generated.ts
  client/packages/invoices/src/Prescriptions/api/operations.graphql
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Vaccination/api/operations.generated.ts
Labels: Priority: Should have, Build Tested: Blocked, Team Ruru 🦉

#7303 refactor: use enum for valid vaccination actions
  server/repository/src/db_diesel/vaccination_row.rs
  server/service/src/vaccination/update/generate.rs
  server/service/src/vaccination/update/mod.rs
  server/service/src/vaccination/update/validate.rs
Labels: Team Ruru 🦉, Severity: High, feature: vaccine card

#7308 7186 Add confirmation on leaving modal when navigating with unsaved changes - View stock
  client/packages/system/src/Stock/DetailView/DetailView.tsx
Labels: Team Ruru 🦉, Severity: High

#7346 7342 navigate via id
  client/packages/invoices/src/Returns/SupplierListView/AppBarButtons.tsx
Labels: Team Piwakawaka

#7340 7339 Timeout on get_site_status v6 api call
  server/service/src/sync/api_v6/core.rs
Labels: sync, Severity: Hotfix

#6329 Add github sort action
  .github/workflows/sort-json.sh
  .github/workflows/sort-json.yaml
Labels: enhancement, Priority: Should have, feature: translation

#7357 7268 add fix to 2.7 branch
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/index.ts
  client/packages/common/src/intl/utils/IntlUtils.ts
  client/packages/common/src/types/schema.ts
  client/packages/reports/src/DetailView/DetailView.tsx
  client/packages/reports/src/components/ReportWidget.tsx
  client/packages/reports/src/utils.ts
  client/packages/system/src/Report/api/operations.generated.ts
  client/packages/system/src/Report/api/operations.graphql
  client/packages/system/src/Report/components/ReportSelector.tsx
  server/graphql/reports/src/reports.rs
  standard_reports/README.md
Labels: Severity: High

#7336 Android readme update
  client/packages/android/README.MD
Labels: enhancement, Team Ruru 🦉, feature: GAPS

#7361 Split button drop down now clickable across entire component
  client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
Labels: Severity: High

#7378 7341 add navigate via
  client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx
Labels: Severity: Hotfix

#7375 7164 add name id into insurance policies query keys
  client/packages/system/src/Patient/apiModern/hooks/useInsurancesPolicies.ts
Labels: Team Piwakawaka, Severity: High

#7381 7320 Reflect User-Made Changes to Preferences Without Leaving the Preferences Page
  client/packages/system/src/Manage/Preferences/api/useEditPreference.ts
Labels: bug, Team Piwakawaka, Severity: High

#7312 7217 add all compatible android build
  .github/workflows/build-android-apk.yaml
  client/packages/android/README.MD
  client/packages/android/app/build.gradle
  client/packages/android/app/src/main/jniLibs/armeabi-v7a/.gitignore
  client/packages/android/build_remote_server_libs.sh
  client/packages/android/package.json
  server/Cargo.lock
  server/android/.cargo/config.toml
  server/service/src/report/definition.rs
Labels: enhancement, Team Ruru 🦉, feature: GAPS

#7391 #7327 Prescription loading fix
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescription.ts
  client/packages/programs/src/JsonForms/components/Prescription/Prescription.tsx
Labels: feature: programs, Team Piwakawaka, Severity: High

#7338 7272 ensure patients are visible on oms central
  server/graphql/programs/src/queries/link_patient_to_store.rs
  server/repository/src/migrations/v2_07_00/add_patient_link_id_to_vaccination.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/repository/src/migrations/v2_07_00/trigger_patient_visibility_sync.rs
  server/service/src/apis/api_on_central/mod.rs
  server/service/src/apis/api_on_central/patient_name_store_join.rs
  server/service/src/programs/patient/README.md
  server/service/src/programs/patient/search_central.rs
  server/service/src/sync/translations/vaccination.rs
Labels: enhancement, sync, Team Ruru 🦉, Severity: High, feature: vaccine card, deployment gotchas

#7323 7285 prevent ungiving vaccinations from another store
  client/packages/common/src/intl/locales/ar/common.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Vaccination/Components/FacilitySearchInput.tsx
  client/packages/system/src/Vaccination/Components/SelectBatch.tsx
  client/packages/system/src/Vaccination/Components/SelectItem.tsx
  client/packages/system/src/Vaccination/Components/SelectItemAndBatch.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/Components/getSwitchReason.test.ts
  client/packages/system/src/Vaccination/Components/getSwitchReason.ts
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/graphql/programs/src/mutations/vaccination/insert.rs
  server/graphql/programs/src/mutations/vaccination/update.rs
  server/graphql/types/src/types/program/vaccination.rs
  server/repository/src/db_diesel/item_link_row.rs
  server/repository/src/db_diesel/item_row.rs
  server/repository/src/db_diesel/vaccination.rs
  server/repository/src/db_diesel/vaccination_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_dose_row.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_item.rs
  server/repository/src/migrations/v2_07_00/add_given_store_id_to_vaccination.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/repository/src/mock/vaccination.rs
  server/service/src/sync/test/test_data/vaccination.rs
  server/service/src/vaccination/insert/generate.rs
  server/service/src/vaccination/insert/mod.rs
  server/service/src/vaccination/insert/validate.rs
  server/service/src/vaccination/update/generate.rs
  server/service/src/vaccination/update/mod.rs
  server/service/src/vaccination/update/validate.rs
  server/service/src/vaccination/validate.rs
Labels: Team Ruru 🦉, Severity: High, feature: vaccine card

#7431 7347 patients accessible on central without related records
  server/repository/src/db_diesel/key_value_store.rs
  server/repository/src/migrations/v2_07_00/add_central_patient_visibility_processor_pg_enum_type.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/service/src/apis/api_on_central/patient_name_store_join.rs
  server/service/src/apis/oms_central.rs
  server/service/src/apis/patient_v4.rs
  server/service/src/processors/add_central_patient_visibility/add_central_patient_visibility.rs
  server/service/src/processors/add_central_patient_visibility/mod.rs
  server/service/src/processors/add_central_patient_visibility/test.rs
  server/service/src/processors/assign_requisition_number/assign_requisition_number.rs
  server/service/src/processors/contact_form/queue_email.rs
  server/service/src/processors/general_processor.rs
  server/service/src/processors/load_plugin/load_plugin.rs
  server/service/src/processors/mod.rs
  server/service/src/programs/patient/search_central.rs
  server/service/src/sync/mod.rs
  server/service/src/sync/sync_on_central/mod.rs
Labels: Priority: Must Have, Team Ruru 🦉, feature: vaccine card, deployment gotchas

#7359 7337 pending encounter reports are broken
  client/packages/reports/src/DetailView/DetailView.tsx
  server/service/src/report/report_service.rs
  standard_forms/generated/standard_forms.json
  standard_reports/encounters/latest/report-manifest.json
  standard_reports/generated/standard_reports.json
Labels: Team Ruru 🦉, Severity: Hotfix

#7409 Delete records with null vaccination dates and their changelogs
  server/repository/src/migrations/v2_06_02/mod.rs
  server/repository/src/migrations/v2_07_00/change_vaccination_date_to_not_nullable.rs
  server/repository/src/migrations/v2_07_00/mod.rs
Labels: Team Piwakawaka, Severity: High, feature: vaccine card

#7447 7443 assigned requisition number is 0
  package.json
  server/service/src/number.rs
Labels: Team Ruru 🦉

#7448 7149 Always overwrite cli and tester executables when installing/updating omSupply server
  build/windows/omsupply_server.suf
Labels: Severity: Hotfix, feature: server cli

#7462 7455 Infinite loading in requisition when clicking on Next item
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
Labels: Team Ruru 🦉, Severity: High

#7439 Add can add when no internal orders exist
  client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
  client/packages/invoices/src/InboundShipment/ListView/LinkInternalOrderModal.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/document/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/document/useListInternalOrders.ts
  client/packages/invoices/src/InboundShipment/api/hooks/index.ts
Labels: needs triage, Severity: High

#7436 Update verifying functions
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/InboundShipment/DetailView/AddButton.tsx
  client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/utils/useAddFromMasterList.ts
  server/service/src/invoice/inbound_shipment/add_from_master_list.rs
Labels: Team Piwakawaka, Severity: Hotfix

#7467 7410 Extend total timeout in sync api
  server/util/src/api_helper.rs
Labels: sync, Severity: High, Needs Investigation

#7437 7284 assign value to initial_stock_on_hand_units in translation
  client/packages/requisitions/src/RequestRequisition/api/api.ts
  server/service/src/sync/test/test_data/requisition_line.rs
  server/service/src/sync/translations/requisition_line.rs
Labels: Team Piwakawaka, Severity: High, Effort: small

#7466 7356 cant edit date filter
  client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx
  client/packages/common/src/ui/components/inputs/Filters/dateFilter.test.tsx
Labels: bug, feature: coldchain, Team Ruru 🦉, Severity: High, feature: fridge-tag, area: date picker

#7464 6966 warn on early vaccinations
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/Footer.tsx
  client/packages/system/src/Encounter/DetailView/ScheduleNextEncounterModal.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
Labels: enhancement, Team Ruru 🦉, feature: vaccine card

#7441 7433 remove drag and drop from tablets
  client/packages/coldchain/src/Equipment/DetailView/StatusForm.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Documents.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
  client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/src/ui/components/inputs/Upload/UploadButton.tsx
  client/packages/common/src/ui/components/inputs/Upload/UploadDragAndDrop.tsx
  client/packages/common/src/ui/components/inputs/Upload/UploadFile.tsx
  client/packages/common/src/ui/components/inputs/Upload/index.ts
  client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
  client/packages/system/src/Name/ListView/ImportProperties/UploadTab.tsx
Labels: make omSupply delightful, feature: coldchain, Team Piwakawaka, area: cold chain import/export

#7468 7421 breadcrumbs show uuids
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/hooks/useDraftPrescriptionLines.tsx
Labels: Team Ruru 🦉, Severity: Normal, feature: dispensing

#7449 add Open_mSupply prefix to APK zip files
  .github/workflows/build-android-apk.yaml
Labels: enhancement

#7495 7480 prescription breadcrumb shows uuid on new item
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
Labels: Team Ruru 🦉, Severity: High

#7500 #7476 Fix log re-opening bug
  client/packages/host/src/Admin/AndroidLogFileModal.tsx
  client/packages/host/src/Admin/DisplaySettings.tsx
  client/packages/host/src/Admin/WebAppLogFileModal.tsx
Labels: needs triage, Severity: High, Needs Investigation

#7499 7498 translate pending encounter to fr
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr-DJ/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/utils/IntlUtils.ts
  server/repository/src/migrations/v2_07_00/drop_encounters_report.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  standard_forms/generated/standard_forms.json
  standard_reports/encounters/latest/report-manifest.json
  standard_reports/generated/standard_reports.json
Labels: Severity: Low, feature: translation

#7503 Prevent simultaneous installs by removing application id suffix
  client/packages/android/app/build.gradle
Labels: Severity: Hotfix

#7502 7501 cant edit vaccine given at other store
  client/packages/system/src/Vaccination/Components/useConfirmNoStockLineSelected.ts
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/service/src/programs/patient/README.md
Labels: Team Ruru 🦉, Severity: High, feature: vaccine

#7509 Translation keys for standard reports
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
Labels: feature: translation

#7516 remove unused hook
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
Labels: bug

#7510 Remove db triggers in version 2.0 instead of version 2.2
  server/repository/src/migrations/v2_00_00/mod.rs
  server/repository/src/migrations/v2_00_00/remove_changelog_triggers.rs
Labels: Severity: Hotfix

#7194 Upgrade AutocompleteWithPagination styling
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
Labels: bug, good first issue, Team Piwakawaka, Severity: Normal, Severity: Low

#7527 7456 skip and log bad fridge tag records
  server/service/src/sensor/berlinger.rs
Labels: Team Piwakawaka, Severity: Hotfix

#7525 7242 enable saving when number of packs is zero
  client/packages/invoices/src/Prescriptions/api/hooks/utils.test.ts
  client/packages/invoices/src/Prescriptions/api/hooks/utils.tsx
Labels: Team Piwakawaka, Severity: High, feature: dispensing, feature: CIV

#7533 7531 fix borken postgres tests in 2.6.4
  server/repository/src/migrations/v2_00_00/remove_changelog_triggers.rs
  server/service/src/sync/translations/special/name_merge.rs
Labels: Severity: Hotfix

#7408 7131 refactor useIsScreen now uses useMediaQuery
  client/packages/coldchain/src/common/ImportFridgeTag.tsx
  client/packages/coldchain/src/common/Monitoring/TemperatureChart/Chart.tsx
  client/packages/coldchain/src/common/Monitoring/TemperatureChart/TemperatureChart.tsx
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/useIsGapsStoreOnly/useIsGapsStoreOnly.ts
  client/packages/common/src/hooks/useIsScreen/index.ts
  client/packages/common/src/hooks/useIsScreen/useIsExtraLargeScreen.test.ts
  client/packages/common/src/hooks/useIsScreen/useIsExtraLargeScreen.ts
  client/packages/common/src/hooks/useIsScreen/useIsExtraSmallScreen.spec.ts
  client/packages/common/src/hooks/useIsScreen/useIsExtraSmallScreen.ts
  client/packages/common/src/hooks/useIsScreen/useIsLargeScreen.test.ts
  client/packages/common/src/hooks/useIsScreen/useIsLargeScreen.ts
  client/packages/common/src/hooks/useIsScreen/useIsMediumScreen.test.ts
  client/packages/common/src/hooks/useIsScreen/useIsMediumScreen.tsx
  client/packages/common/src/hooks/useIsScreen/useIsScreen.stories.tsx
  client/packages/common/src/hooks/useIsScreen/useIsScreen.ts
  client/packages/common/src/hooks/useIsScreen/useIsSmallScreen.test.ts
  client/packages/common/src/hooks/useIsScreen/useIsSmallScreen.ts
  client/packages/common/src/styles/index.ts
  client/packages/common/src/styles/theme.ts
  client/packages/common/src/ui/components/buttons/FlatButton/FlatButton.tsx
  client/packages/common/src/ui/components/buttons/standard/ShrinkableBaseButton.tsx
  client/packages/common/src/ui/components/domain/StatusCrumbs/StatusCrumbs.tsx
  client/packages/common/src/ui/components/inputs/Upload/UploadDragAndDrop.tsx
  client/packages/common/src/ui/components/portals/DetailPanel/DetailPanel.tsx
  client/packages/host/src/components/AppDrawer/AppDrawer.tsx
  client/packages/host/src/components/Footer/Footer.tsx
  client/packages/host/src/components/Initialise/InitialiseLayout.tsx
  client/packages/host/src/components/Login/LoginIcon.tsx
  client/packages/host/src/components/Sync/SyncModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
Labels: refactor, Team Piwakawaka

#7358 7254 generate typescript types for plugins
  server/cli/src/cli.rs
  server/cli/src/generate_typescript_types.rs
  server/cli/src/lib.rs
  server/service/src/backend_plugin/types/mod.rs
Labels: Severity: Normal, Devops

#7538 7530 save prescription even when line items issued quantity zero
  server/service/src/invoice/prescription/update/generate.rs
  server/service/src/invoice/prescription/update/mod.rs
Labels: Team Piwakawaka, feature: dispensing

#7406 7093 add sort toggle to prevent report filter dropdowns overlapping
  client/packages/programs/src/JsonForms/common/JsonForm.tsx
  client/packages/programs/src/JsonForms/common/components/SortToggle.tsx
  client/packages/programs/src/JsonForms/common/components/index.ts
  standard_reports/expiring-items/latest/argument_schemas/arguments.json
  standard_reports/expiring-items/latest/argument_schemas/arguments_ui.json
  standard_reports/item-usage/latest/argument_schemas/arguments.json
  standard_reports/item-usage/latest/argument_schemas/arguments_ui.json
  standard_reports/stock-detail/latest/argument_schemas/arguments.json
  standard_reports/stock-detail/latest/argument_schemas/arguments_ui.json
  standard_reports/stock-status/latest/argument_schemas/arguments.json
  standard_reports/stock-status/latest/argument_schemas/arguments_ui.json
Labels: platform: android, Team Ruru 🦉, Severity: Normal, Needs Investigation, feature: reports
