Repository msupply-foundation/open-msupply, pull requests merged in 2025-06, with the labels that each got.

#7994 7968 be able to assign campaign on remote site
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Manage/Campaigns/api/hooks/useCampaigns.ts
  client/packages/system/src/Manage/Campaigns/api/operations.generated.ts
  client/packages/system/src/Manage/Campaigns/api/operations.graphql
  server/graphql/lib.rs
Labels: Team Piwakawaka, Severity: High, feature: vaccine

#7990 7910 Show campaign in Outbound Shipment
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
  client/packages/invoices/src/OutboundShipment/api/hooks/useSaveOutboundLines.ts
  client/packages/invoices/src/StockOut/api/operations.generated.ts
  client/packages/invoices/src/StockOut/api/operations.graphql
  client/packages/system/src/Manage/Campaigns/api/hooks/useCampaigns.ts
  project-words.txt
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/save_item_lines.rs
  server/graphql/invoice_line/src/mutations/prescription_line/insert.rs
  server/graphql/invoice_line/src/mutations/prescription_line/save_item_lines.rs
  server/graphql/invoice_line/src/mutations/prescription_line/update.rs
  server/graphql/types/src/types/draft_stock_out_line.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/supplier_return/insert/generate.rs
  server/service/src/invoice/supplier_return/update_lines/generate.rs
  server/service/src/invoice_line/get_draft_outbound_lines.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/allocate/generate.rs
  server/service/src/invoice_line/save_stock_out_item_lines/generate.rs
  server/service/src/invoice_line/save_stock_out_item_lines/mod.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/insert/mod.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/vaccination/generate.rs
Labels: Team Piwakawaka, Severity: High

#7918 7844 add context menu to desktop app
  client/packages/common/src/hooks/useNativeClient/types.ts
  client/packages/common/src/intl/locales/en/desktop.json
  client/packages/common/src/intl/locales/es/desktop.json
  client/packages/common/src/intl/locales/fr/desktop.json
  client/packages/electron/src/electron.ts
Labels: enhancement, platform: desktop, Team Ruru 🦉, Severity: High

#7885 7815 requisition modal
  client/packages/common/src/hooks/useDialog/useDialog.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx
  client/packages/common/src/ui/components/inputs/TextInput/NumericTextInput.tsx
  client/packages/common/src/ui/components/modals/BasicModal/BasicModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/ReduceLinesToZeroModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/invoices/src/Returns/modals/ReturnReasonsTable.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ModalContentPanels.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditModal.tsx
  client/packages/requisitions/src/RequisitionService.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditModal.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/SupplySelection.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/index.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/utils.test.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/utils.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/index.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/utils.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/RequestStoreStats.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/ResponseStoreStats.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/utils.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/index.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/utils.tsx
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useResponse.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/index.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/index.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useDeleteResponseLine.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useInsertResponseLines.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useResponseLineStatsData.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useSaveResponseLines.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useUpdateLine.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  client/packages/requisitions/src/ResponseRequisition/utils.ts
  client/packages/requisitions/src/common/ModalContentLayout.tsx
  client/packages/requisitions/src/common/index.tsx
  client/packages/requisitions/src/common/utils.test.ts
  client/packages/requisitions/src/common/utils.ts
  client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
  client/packages/system/src/Stock/Components/NewStockLineModal.tsx
  server/service/src/item_stats.rs
  server/service/src/processors/transfer/requisition/create_response_requisition.rs
  server/service/src/requisition_line/response_line_stats/response_line_stats.rs
Labels: enhancement, Team Ruru 🦉, feature: simplified tablet UI

#7976 New status for og migrated inbound shipment to be considered as shipped
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/translations/invoice.rs
Labels: Migrating Existing Mobile, Migrate Existing Desktop, Severity: High

#7988 7617 Display item variant detail in outbound shipment
  client/packages/common/src/ui/layout/tables/components/Cells/RadioCell.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
  client/packages/invoices/src/StockOut/api/operations.generated.ts
  client/packages/invoices/src/StockOut/api/operations.graphql
  client/packages/system/src/Item/Components/ItemVariantSelector/ItemVariantInfoIcon.tsx
  client/packages/system/src/Item/Components/ItemVariantSelector/ItemVariantSelector.tsx
  client/packages/system/src/Item/Components/ItemVariantSelector/index.ts
Labels: Team Ruru 🦉, feature: item variant

#7756 7755 creating sites on OG
  server/cli/src/cli.rs
  server/cli/src/lib.rs
  server/cli/src/load_test.rs
Labels: enhancement, Team Ruru 🦉

#8012 7996 change prescribed quan between doses and units
  client/packages/common/src/ui/components/loading/BasicSpinner/BasicSpinner.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/AutoAllocatePrescribedQuantityField.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/NavBar.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/useSavePrescriptionItemLineData.ts
  client/packages/invoices/src/StockOut/useAllocationContext.ts
Labels: Team Ruru 🦉, Severity: High

#7946 #7915(2) Prefs key invalidation fix
  client/packages/common/src/authentication/api/hooks/useAuthApi.ts
  client/packages/common/src/authentication/api/hooks/usePreference.ts
  client/packages/system/src/Manage/Preferences/api/keys.ts
  client/packages/system/src/Manage/Preferences/api/useAdminPrefsList.ts
  client/packages/system/src/Manage/Preferences/api/useEditPreference.ts
  client/packages/system/src/Manage/Preferences/api/usePreferencesGraphQL.ts
Labels: Team Ruru 🦉, feature: vaccine

#7967 7590 Translate GAPS Store properties into French
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/host/src/Admin/ConfigurationSettings.tsx
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
Labels: enhancement, Team Piwakawaka, feature: GAPS, feature: translation

#7962 7951 update stock line donor on stock take insert or update
  server/service/src/stocktake_line/insert/mod.rs
  server/service/src/stocktake_line/update/mod.rs
Labels: Team Piwakawaka, Bug: development

#8028 7970 increase simplified ui breakpoint threshold
  client/packages/common/src/hooks/useSimplifiedTabletUI/useSimplifiedTabletUI.ts
Labels: Team Ruru 🦉, Severity: High, feature: simplified tablet UI

#7995 7986 entry times broken
  server/service/src/sync/translations/invoice.rs
  server/service/src/sync/translations/location_movement.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/sensor.rs
  server/service/src/sync/translations/stocktake.rs
  server/service/src/sync/translations/sync_message.rs
  server/service/src/sync/translations/temperature_breach.rs
  server/service/src/sync/translations/temperature_log.rs
Labels: Team Ruru 🦉, Severity: Hotfix

#8001 7992 Add population percentage to demographic table
  server/repository/src/db_diesel/demographic_row.rs
  server/repository/src/migrations/v2_08_00/add_population_percentage_to_demographic.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/repository/src/migrations/views/mod.rs
  server/repository/src/mock/demographic.rs
  server/service/src/demographic/insert_demographic_indicator.rs
  server/service/src/demographic/update_demographic_indicator.rs
  server/service/src/sync/test/test_data/demographic.rs
Labels: Team Piwakawaka

#8030 7926 add from master list refresh
  client/packages/requisitions/src/RequestRequisition/api/hooks/utils/useAddFromMasterList.ts
Labels: Team Piwakawaka

#8003 7997 keeps selected campaign when inbound shipment status updates
  server/service/src/invoice/customer_return/update/generate.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice_line/inbound_shipment_from_internal_order_lines/generate.rs
  server/service/src/invoice_line/stock_in_line/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/processors/transfer/invoice/common.rs
  server/service/src/stocktake/update/generate.rs
Labels: Team Piwakawaka, Severity: High

#7847 Add MVP simplified UI
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
Labels: enhancement, Tester: Maria, Team Ruru 🦉, Team Piwakawaka, Built Tested: Tested in Feature, feature: dose management, feature: simplified tablet UI

#8031 7999 rename vaccine course is active
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/VaccineCourseEditModal/VaccineCourseEditModal.tsx
  client/packages/programs/src/api/hooks/useVaccineCourse.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  server/graphql/types/src/types/vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/insert_vaccine_course.rs
  server/graphql/vaccine_course/src/mutations/update_vaccine_course.rs
  server/repository/src/db_diesel/vaccine_course/vaccine_course_row.rs
  server/repository/src/migrations/v2_08_00/mod.rs
  server/repository/src/migrations/v2_08_00/rename_vaccine_course_is_active_to_use_in_gaps.rs
  server/repository/src/migrations/views/mod.rs
  server/service/src/sync/test/test_data/vaccine_course.rs
  server/service/src/vaccine_course/insert.rs
  server/service/src/vaccine_course/test/delete.rs
  server/service/src/vaccine_course/test/insert.rs
  server/service/src/vaccine_course/test/query.rs
  server/service/src/vaccine_course/test/update.rs
  server/service/src/vaccine_course/update.rs
Labels: Team Ruru 🦉

#8010 #7993 Change Forecasting field to match new UI
  client/packages/common/src/plugins/types.ts
  client/packages/plugins/api/hooks/index.ts
  client/packages/plugins/api/hooks/usePluginData.ts
  client/packages/plugins/index.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/common/ModalContentLayout.tsx
Labels: Team Piwakawaka

#7920 7876 add report list view
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/host/src/components/Navigation/ManageNav.tsx
  client/packages/system/src/Manage/Reports/ListView/AppBarButtons.tsx
  client/packages/system/src/Manage/Reports/ListView/ListView.tsx
  client/packages/system/src/Manage/Reports/ListView/index.ts
  client/packages/system/src/Manage/Reports/api/hooks/index.ts
  client/packages/system/src/Manage/Reports/api/hooks/keys.ts
  client/packages/system/src/Manage/Reports/api/hooks/useAllReportVersionsList.ts
  client/packages/system/src/Manage/Reports/api/index.ts
  client/packages/system/src/Manage/Reports/api/operations.generated.ts
  client/packages/system/src/Manage/Reports/api/operations.graphql
  client/packages/system/src/Manage/Reports/api/useReportsGraphQL.ts
  client/packages/system/src/Manage/Reports/index.ts
  client/packages/system/src/Manage/Service/Service.tsx
  client/packages/system/src/Report/api/operations.generated.ts
  client/packages/system/src/Report/api/operations.graphql
  server/graphql/reports/src/lib.rs
  server/graphql/reports/src/reports.rs
  server/repository/src/db_diesel/report.rs
  server/service/src/report/report_service.rs
Labels: enhancement, needs triage, feature: reports

#8043 #7969 Forecasting UI tweaks
  client/packages/common/src/intl/locales/en/common.json
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
Labels: Team Piwakawaka, Severity: High, feature: vaccine

#8009 7882 replace campaign id with generic oms fields
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/test/test_data/stock_line.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/stock_line.rs
Labels: enhancement, Team Piwakawaka, feature: vaccine

#8008 7343 dose management display doses in internal order & requisition
  client/packages/common/src/intl/locales/en/common.json
  client/packages/requisitions/src/RequestRequisition/DetailView/ContentArea.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ModalContentPanels.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditModal.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/hooks.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
  client/packages/requisitions/src/RequestRequisition/api/hooks/line/useRequestLines.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/ContentArea.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditModal.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/SupplySelection.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/RequestStoreStats.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/ResponseStoreStats.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/columns.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useResponseLines.ts
  client/packages/requisitions/src/common/ModalContentLayout.tsx
  client/packages/requisitions/src/common/utils.test.ts
  client/packages/requisitions/src/common/utils.ts
  client/packages/requisitions/src/utils.ts
  server/service/src/sync/test/test_data/store_preference.rs
  server/service/src/sync/translations/store_preference.rs
Labels: enhancement, Team Ruru 🦉, feature: dose management

#8047 #7752 Display nothing here message when no log entries to display
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/ActivityLog/Components/ListView.tsx
Labels: Team Ruru 🦉, Severity: Low, UI tweaks

#8054 8052 requisitions full screen modal x not behaving like cancel
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditModal.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditModal.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/SupplySelection.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/ResponseStoreStats.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseStats/utils.tsx
  client/packages/requisitions/src/common/ModalContentLayout.tsx
  client/packages/requisitions/src/common/utils.ts
Labels: Team Ruru 🦉

#8039 #7881 Inbound Shipment - round up to next whole packs
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Labels: Team Ruru 🦉, Severity: Low, feature: dose management

#8075 #8059 Fix errors when changing customer in Outbound Shipment
  client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
Labels: Team Piwakawaka, Severity: High

#8079 Hide doses if 0 units
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/SupplySelection.tsx
  client/packages/requisitions/src/common/ModalContentLayout.tsx
Labels: Team Ruru 🦉

#8041 7950 When turning on the preference to track donor, the donor of existing stockline in OG doesn't sync to the corresponding stock line in omSupply
  server/repository/src/migrations/v2_08_00/mod.rs
  server/repository/src/migrations/v2_08_00/sync_donor_id_to_existing_stock_and_invoice_lines.rs
Labels: Team Piwakawaka

#8077 8066 Update report translation codes
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
Labels: enhancement, Team Ruru 🦉, feature: CIV, UAT

#8050 #6167 Reorder cold storage types to appear in desc order
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  server/graphql/general/src/queries/cold_storage_type.rs
  server/repository/src/db_diesel/cold_storage_type.rs
Labels: enhancement, feature: cold chain, Team Ruru 🦉, Effort: Small, UI tweaks

#8115 7956 invisible clinicians still show up in my store
  package.json
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/clinician_store_join_row.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_09_00/mod.rs
  server/repository/src/migrations/v2_09_00/process_clinician_store_join_deletes.rs
  server/service/src/sync/test/test_data/clinician.rs
  server/service/src/sync/test/test_data/clinician_store_join.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/clinician.rs
  server/service/src/sync/translations/clinician_store_join.rs
Labels: back-end, Priority: Must Have, Team Ruru 🦉, feature: dispensing, feature: CIV, UAT

#8098 #8067 Possible duplicate manual program requisition warning
  client/packages/common/src/intl/locales/en/common.json
  client/packages/requisitions/src/ResponseRequisition/ListView/ProgramRequisitionOptions.tsx
Labels: enhancement, Team Ruru 🦉, feature: CIV, UAT

#8107 #8070 French translation: Stock adjustment and Internal Order
  client/packages/common/src/intl/locales/fr/common.json
Labels: enhancement, Team Ruru 🦉, feature: CIV, UAT

#8117 #8116 Sync clinician mutate permission to OMS
  client/packages/common/src/types/schema.ts
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v2_09_00/add_mutate_clinician_permission.rs
  server/repository/src/migrations/v2_09_00/mod.rs
  server/service/src/auth.rs
  server/service/src/login.rs
Labels: Team Ruru 🦉, feature: CIV, UAT

#8146 8017 expose insert clinician mutation via graphql
  server/Cargo.lock
  server/graphql/clinician/Cargo.toml
  server/graphql/clinician/src/lib.rs
  server/graphql/clinician/src/mutations/insert.rs
  server/graphql/clinician/src/mutations/mod.rs
  server/graphql/lib.rs
  server/service/src/clinician/mod.rs
Labels: enhancement, back-end, Priority: Must Have, Build Tested: Dev, Team Ruru 🦉, feature: dispensing, feature: CIV, UAT

#8134 #8133 Purchase order front-end boilerplate
  client/packages/common/src/intl/locales/en/common.json
  client/packages/config/src/routes.ts
  client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
  client/packages/host/src/routers/ReplenishmentRouter.tsx
  client/packages/purchase_orders/README.md
  client/packages/purchase_orders/package.json
  client/packages/purchase_orders/src/DetailView/DetailView.tsx
  client/packages/purchase_orders/src/DetailView/index.ts
  client/packages/purchase_orders/src/ListView/ListView.tsx
  client/packages/purchase_orders/src/ListView/index.ts
  client/packages/purchase_orders/src/PurchaseOrderService.tsx
  client/packages/purchase_orders/src/index.ts
  client/packages/purchase_orders/tsconfig.json
Labels: Team Piwakawaka, Purchase Orders

#8148 8017 sync clinician store join
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/clinician_store_join_row.rs
  server/service/src/sync/test/test_data/clinician_store_join.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/clinician.rs
  server/service/src/sync/translations/clinician_store_join.rs
Labels: enhancement, back-end, Priority: Must Have, Build Tested: Dev, Team Ruru 🦉, feature: dispensing, feature: CIV, UAT

#8154 8142 stock line import issue
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/test/test_data/stock_line.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/stock_line.rs
Labels: Team Piwakawaka, Severity: Hotfix, Bug: production

#8136 8106 additional properties for suppliers
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Name/DetailModal/DetailModal.tsx
  client/packages/system/src/Name/ListView/ListView.tsx
  client/packages/system/src/Name/api/operations.generated.ts
  client/packages/system/src/Name/api/operations.graphql
  server/graphql/reports/src/reports.rs
  server/graphql/types/src/types/name.rs
  server/repository/src/db_diesel/name_row.rs
  server/repository/src/migrations/v2_09_00/extend_name_table_fields.rs
  server/repository/src/migrations/v2_09_00/mod.rs
  server/service/src/programs/patient/patient_updated.rs
  server/service/src/sync/test/test_data/name.rs
  server/service/src/sync/test/test_data/special/name_to_name_store_join.rs
  server/service/src/sync/translations/name.rs
Labels: enhancement, Team Piwakawaka, Purchase Orders

#8153 8108 move suppliers edit modal to a new page
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Name/DetailModal/DetailModal.tsx
  client/packages/system/src/Name/DetailModal/index.ts
  client/packages/system/src/Name/Details/Details.tsx
  client/packages/system/src/Name/Details/index.ts
  client/packages/system/src/Name/ListView/ListView.tsx
  client/packages/system/src/Name/Service/Service.tsx
  client/packages/system/src/Name/SupplierDetailView/SupplierDetailView.tsx
  client/packages/system/src/Name/SupplierDetailView/index.ts
Labels: enhancement, Team Piwakawaka, Purchase Orders

#8163 #8064 stocktake sorting enhancements (snapshot packs, counted packs, & reason)
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  server/graphql/stocktake_line/src/mutations/insert.rs
  server/graphql/stocktake_line/src/mutations/update.rs
  server/graphql/stocktake_line/src/stocktake_line_queries.rs
  server/repository/src/db_diesel/reason_option_row.rs
  server/repository/src/db_diesel/stocktake_line.rs
  server/repository/src/db_diesel/stocktake_line_row.rs
  server/service/src/stocktake/update/mod.rs
Labels: enhancement, Team Ruru 🦉, feature: CIV, UAT

#8166 8065 clinician list view
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/config/src/routes.ts
  client/packages/host/src/components/Navigation/DispensaryNav.tsx
  client/packages/host/src/routers/DispensaryRouter.tsx
  client/packages/programs/src/api/api.ts
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/Clinician/ListView/ListView.tsx
  client/packages/system/src/Clinician/ListView/columns.ts
  client/packages/system/src/Clinician/ListView/index.ts
  client/packages/system/src/Clinician/Service/Service.tsx
  client/packages/system/src/Clinician/Service/index.ts
  client/packages/system/src/Clinician/index.ts
  client/packages/system/src/Patient/index.ts
Labels: enhancement, Team Ruru 🦉, feature: CIV, UAT

#8176 8061 clinician gender input
  client/README.md
  client/packages/common/src/ui/components/inputs/GenderInput/GenderInput.tsx
  client/packages/common/src/ui/components/inputs/GenderInput/index.ts
  client/packages/common/src/ui/components/inputs/index.ts
  client/packages/common/src/utils/index.ts
  client/packages/common/src/utils/mappers/gender.ts
  client/packages/common/src/utils/mappers/index.ts
  client/packages/requisitions/src/RnRForms/DetailView/SidePanel.tsx
  client/packages/system/src/Clinician/ListView/ListView.tsx
  client/packages/system/src/Clinician/ListView/columns.ts
  client/packages/system/src/Clinician/NewClinicianModal.tsx
  client/packages/system/src/Clinician/api/useInsertClinician.ts
  client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
  client/packages/system/src/Patient/PatientView/PatientSummary.tsx
  client/packages/system/src/Patient/PatientView/index.ts
  client/packages/system/src/Patient/index.ts
Labels: enhancement, Team Ruru 🦉, feature: CIV, UAT

#8173 #8167 Fix forecasting store properties initialisation
  client/packages/host/src/Admin/ConfigurationSettings.tsx
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
  client/packages/host/src/api/hooks/settings/namePropertyKeys.ts
  client/packages/host/src/api/hooks/settings/useConfigureNameProperties.ts
Labels: Priority: Should Have, Team Piwakawaka, feature: vaccine

#8171 8100 add backend purchase order queries
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/purchase_order_line.rs
  server/graphql/lib.rs
  server/graphql/purchase_order/Cargo.toml
  server/graphql/purchase_order/src/lib.rs
  server/graphql/purchase_order/src/purchase_order_queries.rs
  server/graphql/purchase_order_line/Cargo.toml
  server/graphql/purchase_order_line/src/lib.rs
  server/graphql/purchase_order_line/src/purchase_order_line_queries.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/purchase_order.rs
  server/graphql/types/src/types/purchase_order_line.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/purchase_order.rs
  server/repository/src/db_diesel/purchase_order_line.rs
  server/repository/src/db_diesel/purchase_order_line_row.rs
  server/repository/src/db_diesel/purchase_order_row.rs
  server/repository/src/migrations/v2_09_00/add_purchase_order_tables.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/purchase_order.rs
  server/repository/src/mock/purchase_order_line.rs
  server/service/src/lib.rs
  server/service/src/purchase_order/mod.rs
  server/service/src/purchase_order/query.rs
  server/service/src/purchase_order_line/mod.rs
  server/service/src/purchase_order_line/query.rs
  server/service/src/service_provider.rs
Labels: Team Piwakawaka, Purchase Orders

#8162 8160 supplier tab skeleton
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Name/SupplierDetailView/Contacts.tsx
  client/packages/system/src/Name/SupplierDetailView/PurchaseOrder.tsx
  client/packages/system/src/Name/SupplierDetailView/SupplierDetailView.tsx
Labels: enhancement, Team Piwakawaka, Purchase Orders

#8185 #8085 Fix error when going back after changing customer
  client/packages/invoices/src/OutboundShipment/DetailView/Toolbar.tsx
Labels: Severity: High

#8186 8179 add sorting and filtering to purchase order queries
  client/packages/common/src/types/schema.ts
  server/cli/src/cli.rs
  server/graphql/purchase_order/src/purchase_order_queries.rs
  server/graphql/purchase_order_line/src/purchase_order_line_queries.rs
  server/graphql/types/src/types/purchase_order.rs
  server/graphql/types/src/types/purchase_order_line.rs
  server/repository/src/db_diesel/purchase_order.rs
  server/repository/src/db_diesel/purchase_order_line.rs
  server/repository/src/db_diesel/purchase_order_line_row.rs
  server/repository/src/db_diesel/purchase_order_row.rs
  server/repository/src/migrations/v2_09_00/add_purchase_order_tables.rs
  server/repository/src/mock/purchase_order.rs
Labels: enhancement, Team Piwakawaka, Purchase Orders

#8190 #8101 #8102 Purchase order list view front-end basics
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/purchase_orders/src/ListView/AppBarButtons.tsx
  client/packages/purchase_orders/src/ListView/Footer.tsx
  client/packages/purchase_orders/src/ListView/ListView.tsx
  client/packages/purchase_orders/src/ListView/Toolbar.tsx
  client/packages/purchase_orders/src/ListView/index.ts
  client/packages/purchase_orders/src/api/hooks/index.ts
  client/packages/purchase_orders/src/api/hooks/keys.ts
  client/packages/purchase_orders/src/api/hooks/usePurchaseOrderList.ts
  client/packages/purchase_orders/src/api/index.ts
  client/packages/purchase_orders/src/api/operations.generated.ts
  client/packages/purchase_orders/src/api/operations.graphql
  client/packages/purchase_orders/src/api/usePurchaseOrderGraphQL.ts
  client/packages/purchase_orders/src/utils.ts
  server/graphql/types/src/types/purchase_order.rs
Labels: Team Piwakawaka, Purchase Orders

#8196 8164 purchase order insert mutation and service
  server/graphql/lib.rs
  server/graphql/purchase_order/src/lib.rs
  server/graphql/purchase_order/src/mutations/insert.rs
  server/graphql/purchase_order/src/mutations/mod.rs
  server/repository/src/db_diesel/number_row.rs
  server/repository/src/db_diesel/purchase_order_row.rs
  server/repository/src/migrations/v2_09_00/add_purchase_order_to_number_type.rs
  server/repository/src/migrations/v2_09_00/mod.rs
  server/service/src/number.rs
  server/service/src/purchase_order/insert/generate.rs
  server/service/src/purchase_order/insert/mod.rs
  server/service/src/purchase_order/insert/test.rs
  server/service/src/purchase_order/insert/validate.rs
  server/service/src/purchase_order/mod.rs
Labels: Team Piwakawaka, Purchase Orders

#8200 7905 refactor item ledger query
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx
  client/packages/system/src/Item/ListView/ListView.tsx
  client/packages/system/src/Item/api/api.ts
  client/packages/system/src/Item/api/hooks/useItemApi/useItemApi.ts
  client/packages/system/src/Item/api/hooks/useItemLedger/useItemLedger.ts
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  server/graphql/general/src/lib.rs
  server/graphql/general/src/queries/item_ledger.rs
  server/graphql/invoice/src/invoice_queries.rs
  server/graphql/invoice_line/src/invoice_line_queries.rs
  server/graphql/types/src/types/invoice_query.rs
  server/repository/src/db_diesel/item_ledger.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/views/mod.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/ledger.rs
Labels: refactor, Team Ruru 🦉, feature: CIV, UAT

#8212 #8165 Create Purchase order UI
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/purchase_orders/src/DetailView/DetailView.tsx
  client/packages/purchase_orders/src/ListView/AppBarButtons.tsx
  client/packages/purchase_orders/src/ListView/ListView.tsx
  client/packages/purchase_orders/src/PurchaseOrderService.tsx
  client/packages/purchase_orders/src/api/hooks/usePurchaseOrder.ts
  client/packages/purchase_orders/src/api/operations.generated.ts
  client/packages/purchase_orders/src/api/operations.graphql
Labels: enhancement, Team Piwakawaka, Purchase Orders

#8226 8225 queries for purchase order lines always return nothing
  server/graphql/core/src/loader/purchase_order_line.rs
  server/graphql/purchase_order_line/src/purchase_order_line_queries.rs
  server/service/src/purchase_order_line/mod.rs
  server/service/src/purchase_order_line/query.rs
Labels: Team Piwakawaka

#8213 8193 side panel modal should only slide over its parent modal
  client/packages/common/src/hooks/useDialog/useDialog.tsx
  client/packages/common/src/ui/components/inputs/Select/Select.tsx
  client/packages/common/src/ui/components/panels/SlidePanel/SlidePanel.tsx
  client/packages/common/src/ui/components/panels/SlidePanel/index.ts
  client/packages/common/src/ui/components/panels/index.ts
  client/packages/invoices/src/Prescriptions/ListView/NewPrescriptionModal.tsx
  client/packages/system/src/Clinician/ClinicianSearchInput.tsx
  client/packages/system/src/Clinician/CreateClinicianForm.tsx
  client/packages/system/src/Clinician/CreateClinicianModal.tsx
  client/packages/system/src/Clinician/CreateClinicianSlider.tsx
  client/packages/system/src/Clinician/NewClinicianModal.tsx
Labels: enhancement, Team Ruru 🦉, feature: CIV

#8223 #8143 Edit patient details in prescription detail view
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx
  client/packages/system/src/Patient/EditPatientModal/EditPatientModal.tsx
  client/packages/system/src/Patient/EditPatientModal/index.ts
  client/packages/system/src/Patient/EditPatientModal/usePatientEditForm.tsx
  client/packages/system/src/Patient/Insurance/ListView.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
  client/packages/system/src/Patient/PatientView/PatientDetailView.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
  client/packages/system/src/Patient/index.ts
Labels: enhancement, Team Ruru 🦉, feature: CIV, UAT

#8251 8237 add oms fields deserialiser
  server/repository/src/mock/campaign.rs
  server/repository/src/mock/mod.rs
  server/service/src/sync/sync_serde.rs
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/test/test_data/stock_line.rs
  server/service/src/sync/translations/invoice_line.rs
  server/service/src/sync/translations/name.rs
  server/service/src/sync/translations/program_requisition_settings.rs
  server/service/src/sync/translations/stock_line.rs
Labels: Severity: Hotfix

#8254 #8194 Initial Detail View for Purchase Order
  client/packages/common/src/intl/locales/en/common.json
  client/packages/purchase_orders/src/DetailView/AppBarButtons/AddFromMasterListButton.tsx
  client/packages/purchase_orders/src/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/purchase_orders/src/DetailView/AppBarButtons/index.ts
  client/packages/purchase_orders/src/DetailView/ContentArea.tsx
  client/packages/purchase_orders/src/DetailView/DetailView.tsx
  client/packages/purchase_orders/src/DetailView/Footer/Footer.tsx
  client/packages/purchase_orders/src/DetailView/Footer/index.ts
  client/packages/purchase_orders/src/DetailView/Toolbar.tsx
  client/packages/purchase_orders/src/DetailView/columns.ts
  client/packages/purchase_orders/src/api/hooks/usePurchaseOrder.ts
  client/packages/purchase_orders/src/api/operations.generated.ts
  client/packages/purchase_orders/src/api/operations.graphql
  server/graphql/types/src/types/purchase_order_line.rs
Labels: Team Piwakawaka, Purchase Orders

#8267 Use Default packsize for new lines in stocktake if not entered
  client/packages/inventory/src/Stocktake/api/api.ts
Labels: Team Piwakawaka

#8261 Remove ReasonOptionLoader from stocktake_line #8169
  server/graphql/types/src/types/stocktake_line.rs
Labels: refactor, Team Ruru 🦉, Severity: High, feature: CIV, UAT

#8266 #8259 fix/ Adding a reason in stocktake not always possible until clicking on Ok
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx
Labels: Team Ruru 🦉

#8271 Default to allocating in packs if there's only one packsize
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/Allocation.tsx
Labels: Team Piwakawaka, Severity: High

#8268 #8243 Purchase order detail view -- sort and filter lines
  client/packages/purchase_orders/src/DetailView/DetailView.tsx
  client/packages/purchase_orders/src/DetailView/Toolbar.tsx
  client/packages/purchase_orders/src/DetailView/columns.ts
  client/packages/purchase_orders/src/api/hooks/usePurchaseOrder.ts
Labels: Team Piwakawaka, Purchase Orders

#8273 #7085 invoice shipped number of packs
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/prescription_line/update.rs
  server/graphql/types/src/types/invoice_line.rs
  server/repository/src/db_diesel/invoice_line_row.rs
  server/repository/src/migrations/v2_09_00/add_shipped_number_of_packs_to_invoice_line.rs
  server/repository/src/migrations/v2_09_00/mod.rs
  server/repository/src/mock/invoice_line.rs
  server/service/src/invoice/customer_return/insert/generate.rs
  server/service/src/invoice/customer_return/update_lines/generate.rs
  server/service/src/invoice/inbound_shipment/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/outbound_shipment/generate.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/invoice_line/inbound_shipment_from_internal_order_lines/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
  server/service/src/invoice_line/save_stock_out_item_lines/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
  server/service/src/invoice_line/stock_in_line/update/mod.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/insert/mod.rs
  server/service/src/invoice_line/stock_out_line/set_prescribed_quantity/generate.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/invoice_line/stock_out_line/update/mod.rs
  server/service/src/processors/transfer/invoice/common.rs
  server/service/src/processors/transfer/invoice/mod.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/translations/invoice_line.rs
Labels: enhancement, Team Ruru 🦉, Liberia

#8277 7800 internal order/requisition prompt reasons error when user inserts/updates a requisition line
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/Footer/Footer.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditModal.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/hooks.tsx
  client/packages/requisitions/src/RequestRequisition/api/api.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditModal.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useDeleteResponseLines.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.generated.ts
  client/packages/requisitions/src/ResponseRequisition/api/operations.graphql
  client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx
  server/graphql/requisition_line/src/mutations/request_requisition_line/update.rs
  server/graphql/requisition_line/src/mutations/response_requisition_line/update.rs
  server/repository/src/mock/reason_option.rs
  server/service/src/requisition_line/request_requisition_line/update.rs
  server/service/src/requisition_line/response_requisition_line/update.rs
Labels: Team Ruru 🦉, feature: CIV, UAT

#8255 8143 create patient details in prescription detail
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/ListView/AppBarButtons.tsx
  client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx
  client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
  client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
  client/packages/system/src/Patient/EditPatientModal/EditPatientModal.tsx
  client/packages/system/src/Patient/EditPatientModal/useUpsertPatient.tsx
  client/packages/system/src/Patient/ListView/AppBarButtons.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
  client/packages/system/src/Patient/PatientView/PatientDetailView.tsx
Labels: enhancement, Team Ruru 🦉, feature: CIV, UAT

#8283 8211 Create Clinician From Within Search
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/system/src/Clinician/ClinicianSearchInput.tsx
Labels: enhancement, Team Ruru 🦉, feature: CIV

#8032 7874 add report upload back end end point
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Manage/Reports/ListView/AppBarButtons.tsx
  client/packages/system/src/Manage/Reports/ListView/ListView.tsx
  client/packages/system/src/Manage/Reports/ListView/ReportUploadModal.tsx
  client/packages/system/src/Manage/Reports/api/hooks/useAllReportVersionsList.ts
  client/packages/system/src/Manage/Reports/api/operations.generated.ts
  client/packages/system/src/Manage/Reports/api/operations.graphql
  server/graphql/lib.rs
  server/graphql/reports/src/lib.rs
  server/graphql/reports/src/mutations/install.rs
  server/graphql/reports/src/mutations/mod.rs
  server/repository/src/db_diesel/report_row.rs
  server/service/src/report/report_service.rs
  server/service/src/standard_reports.rs
Labels: enhancement, feature: reports

#8307 8291 Default simplified UI pref to be off
  server/service/src/preference/preferences/use_simplified_mobile_ui.rs
Labels: Team Ruru 🦉, feature: preferences

#8317 #8316 Fix Graphql generate schema
  client/packages/system/src/Manage/Reports/api/operations.graphql
Labels: needs triage, Severity: High, Tooling, needs daily triage

#8256 8182 print purchase orders
  client/packages/common/src/intl/locales/en/common.json
  server/graphql/reports/src/reports.rs
  server/repository/src/db_diesel/report_row.rs
  server/repository/src/migrations/v2_09_00/add_purchase_order_report_context.rs
  server/repository/src/migrations/v2_09_00/mod.rs
  standard_forms/generated/standard_forms.json
  standard_forms/purchase-order/latest/report-manifest.json
  standard_forms/purchase-order/latest/src/header.html
  standard_forms/purchase-order/latest/src/query.graphql
  standard_forms/purchase-order/latest/src/style.css
  standard_forms/purchase-order/latest/src/template.html
  standard_reports/generated/standard_reports.json
  standard_reports/test-config.json
Labels: enhancement, Team Piwakawaka

#8305 8292 add clinician mobile number
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Clinician/CreateClinicianForm.tsx
  client/packages/system/src/Clinician/ListView/columns.ts
  client/packages/system/src/Clinician/useCreateClinician.ts
  server/graphql/clinician/src/mutations/insert.rs
  server/service/src/clinician/insert/generate.rs
  server/service/src/clinician/insert/mod.rs
  server/service/src/clinician/insert/validate.rs
Labels: enhancement, Team Ruru 🦉, feature: CIV

#8329 8280 prescriptions cant input correct amount of units
  client/packages/invoices/src/Prescriptions/LineEditView/columns.tsx
Labels: Team Piwakawaka, Severity: Hotfix, Bug: production
