Repository msupply-foundation/open-msupply, pull requests merged in 2025-10, with the labels that each got.

#9406 9355 update sub nav sort order
  client/packages/host/src/components/Navigation/DistributionNav.tsx
  client/packages/host/src/components/Navigation/InventoryNav.tsx
  client/packages/host/src/components/Navigation/ManageNav.tsx
  client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
Labels: enhancement, Team Piwakawaka, feature: usability, area: navigation

#9428 9407 stocktake final usability fixes
  client/packages/common/src/hooks/useDialog/useDialog.tsx
  client/packages/common/src/hooks/useFeatureFlags/useFeatureFlags.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/styles/theme.ts
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/ListView/AppBarButtons.tsx
  client/packages/inventory/src/Stocktake/ListView/CreateStocktakeModal.tsx
  client/packages/inventory/src/Stocktake/ListView/FullStocktakeOnHandSelector.tsx
  client/packages/inventory/src/Stocktake/ListView/NewCreateStocktakeModal.tsx
  client/packages/inventory/src/Stocktake/ListView/StocktakeFilters.tsx
  client/packages/inventory/src/Stocktake/ListView/types.ts
  client/packages/inventory/src/Stocktake/ListView/useGenerateComment.ts
  client/packages/inventory/src/Stocktake/api/hooks/useStocktake.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ModalContentPanels.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/system/src/Location/Components/LocationSearchInput.tsx
  client/packages/system/src/MasterList/Components/MasterListSearchInput.tsx
  client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusSearchInput.tsx
  client/packages/system/src/Stock/index.ts
  server/graphql/stocktake/src/mutations/insert.rs
  server/service/src/stocktake/insert/generate.rs
  server/service/src/stocktake/insert/mod.rs
Labels: enhancement, Team Piwakawaka, feature: usability, area: stocktake

#9438 9402 purchase order modal export columns should match import columns
  client/packages/purchasing/src/purchase_order/DetailView/utils.ts
Labels: enhancement, Team Ruru 🦉, Purchase Orders

#9463 #9374 Fix future encounter creation
  client/packages/system/src/Patient/Encounter/CreateEncounterModal.tsx
Labels: Team Piwakawaka, Severity: High, Bug: development

#9384 Table developer documentation
  client/packages/common/src/ui/layout/tables/material-react-table/README.md
Labels: Team Piwakawaka

#9376 4840 invoice translate legacy finalised date/time
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/translations/invoice.rs
Labels: enhancement, sync, Priority: Should Have, Team Ruru 🦉, let's keep this 💌

#9442 3959 fix controlled currency input
  client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.stories.tsx
  client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/CurrencyInputCell/CurrencyInputCell.tsx
  client/packages/system/src/Stock/DetailView/Footer.tsx
Labels: bug, Priority: Nice to Have, refactor, Team Piwakawaka, let's keep this 💌

#9471 7444 Sort by pack cost on stock line
  client/packages/common/src/types/schema.ts
  client/packages/purchasing/src/purchase_order/api/operations.generated.ts
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/api/hooks/useStockList.ts
  server/graphql/stock_line/src/lib.rs
  server/repository/src/db_diesel/stock_line.rs
Labels: Team Ruru 🦉, Severity: Normal, Needs Refinement, UI tweaks

#9474 8844 Add sort value to mos column
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.tsx
Labels: Team Ruru 🦉, Severity: Low, UI tweaks

#9468 8524 Fix Item Ledger Navigation
  client/packages/system/src/Item/DetailView/DetailView.tsx
Labels: Team Ruru 🦉, Severity: Normal, area: navigation

#9454 9369 replace stocktake edit tables
  client/packages/common/src/ui/layout/tables/components/Cells/CheckboxCell/CheckboxCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/CheckboxCell/EnabledCheckboxCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/CheckboxCell/ReadOnlyCheckboxCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/CheckboxCell/index.ts
  client/packages/common/src/ui/layout/tables/components/Cells/index.ts
  client/packages/common/src/ui/layout/tables/material-react-table/components/CheckBoxCell.tsx
  client/packages/common/src/ui/layout/tables/material-react-table/components/CurrencyInputCell.tsx
  client/packages/common/src/ui/layout/tables/material-react-table/components/NumberInputCell.tsx
  client/packages/common/src/ui/layout/tables/material-react-table/components/RequiredNumberInputCell.tsx
  client/packages/common/src/ui/layout/tables/material-react-table/components/TextInputCell.tsx
  client/packages/common/src/ui/layout/tables/material-react-table/components/index.ts
  client/packages/common/src/ui/layout/tables/material-react-table/tableState/useColumnPinning.ts
  client/packages/common/src/ui/layout/tables/material-react-table/useBaseMaterialTable.tsx
  client/packages/common/src/ui/layout/tables/material-react-table/useMaterialTableColumns.tsx
  client/packages/common/src/ui/layout/tables/material-react-table/useSimpleMaterialTable.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTabs.tsx
  client/packages/system/src/Item/api/hooks/useItemVariant/useIsItemVariantsEnabled.ts
  client/packages/system/src/Stock/Components/Campaign/CampaignOrProgramSelector.tsx
  client/packages/system/src/Stock/Components/Campaign/CampaignOrProgramSelectorColumn.tsx
Labels: Team Piwakawaka, feature: usability, area: tables

#9477 7716 removing is program from a master list doesn't reflect correctly in oms
  server/repository/src/db_diesel/item.rs
  server/repository/src/db_diesel/master_list.rs
  server/service/src/sync/translations/program_requisition_settings.rs
Labels: sync, Team Ruru 🦉, Severity: Normal

#9479 8374 can't handle special characters in postgres credentials during db connection
  server/Cargo.lock
  server/repository/Cargo.toml
  server/repository/src/database_settings.rs
Labels: Team Ruru 🦉, Severity: Normal, area: server config

#9470 #9372 JsonForm error handler fix
  client/packages/programs/src/JsonForms/common/JsonForm.tsx
Labels: Team Piwakawaka, Severity: High

#9482 9369 `manage` list view tables
  client/packages/coldchain/src/Equipment/ListView/Footer.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/ListView/columns.tsx
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssetsDelete.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/layout/tables/material-react-table/types.ts
  client/packages/common/src/ui/layout/tables/material-react-table/useGetColumnDefDefaults.tsx
  client/packages/common/src/ui/layout/tables/material-react-table/useTableFiltering.ts
  client/packages/system/src/Manage/Campaigns/ListView/Footer.tsx
  client/packages/system/src/Manage/Campaigns/ListView/ListView.tsx
  client/packages/system/src/Manage/Campaigns/api/hooks/useCampaigns.ts
  client/packages/system/src/Manage/Reports/ListView/ListView.tsx
  client/packages/system/src/Manage/Reports/api/hooks/useAllReportVersionsList.ts
  client/packages/system/src/Name/ListView/Stores/ListView.tsx
  client/packages/system/src/Name/ListView/Stores/Toolbar.tsx
  client/packages/system/src/Name/api/hooks/document/useStores.ts
Labels: Team Piwakawaka, feature: usability, area: tables

#9490 9139 SOH term being used in internal order to designate available stock
  client/packages/common/src/intl/locales/en/common.json
Labels: Tester: Maria, Team Ruru 🦉, Severity: Normal, Bug: production, area: internal order, translation/terms/naming

#9509 9507 Link internal order to Inbound Shipment doesn't work
  server/service/src/sync/test/test_data/store_preference.rs
  server/service/src/sync/translations/store_preference.rs
Labels: Team Ruru 🦉, Severity: Hotfix
