Repository msupply-foundation/open-msupply, pull requests merged in 2025-03, with the labels that each got.

#6757 6527 change test config default search location
  server/cli/src/cli.rs
Labels: needs triage, feature: reports

#6753 6349 fix double confirm
  client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json
  client/packages/system/src/Patient/PatientView/Footer.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
Labels: Severity: Normal, Team: Kororā 🐧

#6756 6160 disable patient save while fields required
  client/packages/system/src/Patient/PatientView/PatientView.tsx
Labels: bug, feature: programs, Severity: High, Team: Kororā 🐧

#6775 #6706 Make prescription date filtering consistent with date shown in table
  client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
  client/packages/invoices/src/Prescriptions/ListView/Toolbar.tsx
  server/graphql/invoice/src/invoice_queries.rs
  server/repository/src/db_diesel/invoice.rs
Labels: bug, Team Piwakawaka

#6750 Disable asset type when creating non-catalogue asset
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
Labels: bug, Severity: Low, feature: CCEI, area: cold chain import/export

#6781 Hide on backdrop click
  client/packages/common/src/ui/components/popover/PaperPopover/PaperClickPopover/PaperClickPopover.tsx
Labels: make omSupply delightful, Team Ruru 🦉, Severity: Normal

#6778 6765 Hide printer config accordion
  client/packages/config/src/config.ts
  client/packages/host/src/Admin/Settings.tsx
  client/packages/host/webpack.config.js
Labels: Team: Kororā 🐧

#6773 4970 - Back button prevent navigation back to new item
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
Labels: bug, good first issue, Tester: Maria, Severity: Normal, Build Tested: Needs Retesting, Team: Kororā 🐧

#6759 6631 Make demographic clearable in vaccine course
  server/service/src/vaccine_course/update.rs
Labels: Severity: Normal, feature: vaccine card, Team: Kororā 🐧

#6776 6768 labels undefined clinician and trunc
  client/packages/invoices/src/Prescriptions/DetailView/hooks/utils.tsx
  server/service/src/print/label.rs
Labels: Team: Kororā 🐧

#6770 6656 prescription reference filter
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
  client/packages/invoices/src/Prescriptions/ListView/Toolbar.tsx
  server/graphql/invoice/src/invoice_queries.rs
  server/repository/src/db_diesel/invoice.rs
Labels: enhancement, Team Piwakawaka

#6670 Add functionality to disable reports
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Report/api/hooks/useReportList.ts
  server/cli/src/cli.rs
  server/graphql/reports/src/reports.rs
  server/repository/src/db_diesel/report.rs
  server/repository/src/db_diesel/report_row.rs
  server/repository/src/migrations/v2_06_00/add_report_is_active.rs
  server/repository/src/migrations/v2_06_00/mod.rs
  server/service/src/report/report_service.rs
  server/service/src/standard_reports.rs
  server/service/src/sync/test/test_data/om_report.rs
  standard_reports/README.md
Labels: enhancement, Team Ruru 🦉, feature: reports

#6799 6772 Save changes on patient
  client/packages/system/src/Patient/PatientView/PatientView.tsx
Labels: needs triage, Severity: High, feature: dispensing, Team: Kororā 🐧

#6777 6604 dispensing fixes
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
  client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
  client/packages/system/src/Patient/Insurance/InsuranceModal.tsx
  client/packages/system/src/Patient/Insurance/InsurancePolicySelect.tsx
  client/packages/system/src/Patient/Insurance/InsuranceProvidersSelect.tsx
  client/packages/system/src/Patient/apiModern/hooks/useInsurancesPolicies.ts
Labels: Team Piwakawaka, feature: dispensing

#6791 6784 report arguments selected program is not repopulated
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
  client/packages/programs/src/Components/PatientProgramSearchInput.tsx
  client/packages/programs/src/JsonForms/components/PatientProgramSearch.tsx
  client/packages/programs/src/JsonForms/components/PeriodSearch.tsx
  client/packages/programs/src/JsonForms/components/ProgramSearch.tsx
  client/packages/programs/src/api/hooks/usePeriodList.ts
Labels: Team Ruru 🦉, Severity: High

#6786 6234 Don't fix width item info/indicator info table
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
Labels: enhancement, Priority: Should have, Team Ruru 🦉, feature: CIV, UI tweaks

#6803 6779 translate default patient UI schema
  client/packages/common/src/intl/locales/en/common.json
  client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx
  client/packages/programs/src/JsonForms/common/components/Boolean.tsx
  client/packages/programs/src/JsonForms/common/components/ConditionalSelect.tsx
  client/packages/programs/src/JsonForms/common/components/Date.tsx
  client/packages/programs/src/JsonForms/common/components/DateTime.tsx
  client/packages/programs/src/JsonForms/common/components/Group.tsx
  client/packages/programs/src/JsonForms/common/components/Number.tsx
  client/packages/programs/src/JsonForms/common/components/Select.tsx
  client/packages/programs/src/JsonForms/common/components/Text.tsx
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
  client/packages/programs/src/JsonForms/components/IdGenerator.tsx
  client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
  client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json
  client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
Labels: Severity: High, feature: dispensing, Team: Kororā 🐧, feature: translation

#6749 6616 Update disabled action button workflow
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/footer/ActionsFooter.tsx
  client/packages/inventory/src/Stocktake/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/line/useDeleteSelectedLines.ts
  client/packages/invoices/src/OutboundShipment/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/Footer/Footer.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/Footer/Footer.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Footer/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/DetailView.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useDeleteResponseLines.ts
Labels: make omSupply delightful, Team Ruru 🦉, Severity: Normal

#6804 #5825 Fix contraception method/prescription selection reset
  client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
Labels: bug, feature: programs, Team Piwakawaka, Severity: High

#6797 6048 fix tooltip misplacement
  client/packages/system/src/Item/Components/ListItems/ListItems.tsx
Labels: bug, Team Piwakawaka, Severity: Normal, feature: dispensing, UI tweaks

#6761 Dispensing keyboard usability
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/useKeyboardShortcut.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/styles/theme.ts
  client/packages/common/src/ui/components/buttons/standard/AddButton.tsx
  client/packages/common/src/ui/components/buttons/standard/DialogButton.tsx
  client/packages/common/src/ui/components/buttons/standard/index.ts
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/host/src/CommandK.tsx
  client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/Footer.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PanelSection.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditTable.tsx
  client/packages/invoices/src/Prescriptions/ListView/NewPrescriptionModal.tsx
  client/packages/system/src/Patient/Components/PatientSearchInput/PatientSearchInput.tsx
  client/packages/system/src/Patient/utils.ts
  client/packages/system/src/Stock/Components/StockLineForm.tsx
Labels: enhancement, Priority: Should have, feature: dispensing

#6827 Remove report changelogs
  server/repository/src/migrations/v2_06_00/report_fix_prescriptions_report_code.rs
Labels: Team Piwakawaka, Needs Investigation

#6822 #6792 #6815 Re-shuffle Prescription Toolbar and Sidebar items
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
Labels: enhancement, feature: dispensing

#6833 #6829 Fix for Kbar context error
  client/packages/host/src/CommandK.tsx
  client/packages/host/src/Host.tsx
Labels: Team Piwakawaka, Severity: High

#6830 6764 internal orders review
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/CustomerIndicatorInfo.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemLedger.tsx
  server/repository/src/db_diesel/indicator_value.rs
  server/service/src/requisition/common.rs
  server/service/src/requisition/request_requisition/indicator_information.rs
  server/service/src/requisition/request_requisition/insert_program.rs
  server/service/src/requisition/response_requisition/insert_program.rs
Labels: enhancement, Team Ruru 🦉, docs: external

#6844 6712 safely deserialise invoice_line.item_variant_id
  server/service/src/sync/translations/invoice_line.rs
Labels: Severity: Hotfix, Needs Investigation

#6868 6828 add reference column to prescriptions
  client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
Labels: enhancement, needs triage, Team Piwakawaka, Severity: Normal, feature: dispensing

#6860 6069 fix suggested quantities replacing requested quantities - internal order
  client/packages/common/src/intl/locales/en/common.json
  client/packages/host/src/components/Sync/SyncModal.tsx
  server/service/src/requisition/request_requisition/use_suggested_quantity.rs
Labels: bug, Team Ruru 🦉, Severity: Normal

#6854 6364 Fix siteInfo alignment Android
  client/packages/host/src/components/SiteInfo.tsx
Labels: Team Ruru 🦉, Severity: Normal, UI tweaks

#6873 Fix test for pr #6860
  server/service/src/requisition/request_requisition/use_suggested_quantity.rs
Labels: bug, Team Ruru 🦉, Severity: Normal

#6754 6731 Handle error when no reason provided for adding/adjusting stock
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
  client/packages/system/src/Stock/Components/NewStockLineModal.tsx
  client/packages/system/src/Stock/api/hooks/useInventoryAdjustment.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/graphql/inventory_adjustment/mutations/insert.rs
  server/graphql/stock_line/src/mutations/insert.rs
  server/graphql/stocktake_line/src/mutations/insert.rs
  server/graphql/stocktake_line/src/mutations/mod.rs
  server/graphql/stocktake_line/src/mutations/update.rs
  server/graphql/types/src/types/inventory_adjustment_reason.rs
Labels: Team Ruru 🦉, Severity: High

#6876 6819 The confirm delivered option of customer returns is greyed out when it has been created from returning stock from another store
  client/packages/invoices/src/Returns/CustomerDetailView/Footer/StatusChangeButton.tsx
Labels: Team Ruru 🦉, Severity: High

#6865 6810 Inbound shipment: when change status to 'Delivered', the 'Add item' button keeps disabled, until you click on it
  client/packages/invoices/src/InboundShipment/DetailView/AddButton.tsx
Labels: Team Ruru 🦉, Severity: High

#6877 6837 Add prefs table migration
  package.json
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_07_00/add_preference_table.rs
  server/repository/src/migrations/v2_07_00/mod.rs
Labels: Priority: Should have, Team Ruru 🦉, feature: preferences

#6789 Add insert returns as shipped when inserting from shipments
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/SupplierListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/api/api.ts
  client/packages/invoices/src/Returns/api/operations.generated.ts
  client/packages/invoices/src/Returns/api/operations.graphql
  client/packages/invoices/src/Returns/modals/CustomerReturn/CustomerReturn.tsx
  client/packages/invoices/src/Returns/modals/CustomerReturn/useDraftCustomerReturnLines.ts
  client/packages/invoices/src/Returns/modals/SupplierReturn/SupplierReturn.tsx
  client/packages/invoices/src/Returns/modals/SupplierReturn/useDraftSupplierReturnLines.ts
  server/graphql/invoice/src/mutations/customer_return/insert.rs
  server/graphql/invoice/src/mutations/supplier_return/insert.rs
  server/service/src/invoice/customer_return/insert/mod.rs
  server/service/src/invoice/customer_return/update/mod.rs
  server/service/src/invoice/supplier_return/insert/mod.rs
  server/service/src/invoice/supplier_return/update/mod.rs
Labels: Priority: Should have, Team Ruru 🦉, feature: CIV

#6520 Implement android splash page
  client/packages/android/app/src/main/java/org/openmsupply/client/AppState.java
  client/packages/android/app/src/main/java/org/openmsupply/client/MainActivity.java
  client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
  client/packages/android/app/src/main/java/org/openmsupply/client/SplashPage.java
  client/packages/android/app/src/main/res/drawable-land-hdpi/splash.png
  client/packages/android/app/src/main/res/drawable-land-mdpi/splash.png
  client/packages/android/app/src/main/res/drawable-land-xhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-land-xxhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-land-xxxhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-port-hdpi/splash.png
  client/packages/android/app/src/main/res/drawable-port-mdpi/splash.png
  client/packages/android/app/src/main/res/drawable-port-xhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-port-xxhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-port-xxxhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  client/packages/android/app/src/main/res/drawable/ic_launcher_background.xml
  client/packages/android/app/src/main/res/drawable/splash.png
  client/packages/android/app/src/main/res/values/styles.xml
  client/packages/common/src/intl/locales/ar/common.json
  client/packages/common/src/intl/locales/fr-DJ/common.json
Labels: enhancement, feature: GAPS, UI tweaks

#6878 Update namePropertyData.ts
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
Labels: bug, Team Piwakawaka, Severity: Normal, feature: GAPS

#6892 6818 Fix autocomplete appearance on Android
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
Labels: platform: android, Severity: High

#6857 6850 display full facility name
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Equipment/api/hooks/document/useAssets.ts
  client/packages/common/src/types/schema.ts
  server/graphql/asset/src/types/asset.rs
  server/repository/src/db_diesel/assets/asset.rs
Labels: Team Piwakawaka, feature: GAPS

#6826 6825 update front end plugin interfaces names
  client/packages/common/src/plugins/types.ts
  client/packages/plugins/backendTypes/generated/TransformRequestRequisitionLineContext.ts
  client/packages/plugins/backendTypes/generated/TransformRequestRequisitionLineInput.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/ContentArea.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/columns.ts
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
  server/graphql/plugin/src/queries/uploaded_info.rs
  server/service/src/backend_plugin/types/transform_request_requisition_lines.rs
Labels: enhancement, feature: plugin

#6871 6273 add age to encounter header
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
Labels: Team Ruru 🦉, feature: vaccine card

#6859 6651 display approved quantity in requisition, update chart calculations
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditPage.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  server/service/src/requisition_line/response_line_stats/mod.rs
  server/service/src/requisition_line/response_line_stats/response_line_stats.rs
Labels: Team Ruru 🦉, Severity: Hotfix

#6884 Add soft delete translations
  server/repository/src/db_diesel/assets/asset_row.rs
  server/service/src/asset/delete.rs
Labels: bug, Priority: Must Have, Team Piwakawaka, Severity: Normal

#6796 6746 Client Code Checks
  .github/workflows/client-code-checks.yaml
  .github/workflows/server-tests.yaml
  client/.eslintrc.js
  client/.husky/pre-commit
  client/README.md
  client/package.json
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/api/api.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureBreach/api.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureBreach/operations.generated.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureBreach/operations.graphql
  client/packages/coldchain/src/Monitoring/api/TemperatureLog/api.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureLog/operations.generated.ts
  client/packages/coldchain/src/Monitoring/api/TemperatureLog/operations.graphql
  client/packages/common/src/intl/strings/IntlStrings.ts
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteMulti.tsx
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
  client/packages/common/src/ui/components/steppers/VerticalStepper/VerticalStepper.test.tsx
  client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
  client/packages/common/src/ui/layout/tables/components/index.tsx
  client/packages/electron/package.json
  client/packages/host/src/Admin/Printers.tsx
  client/packages/host/src/components/Sync/SyncModal.tsx
  client/packages/host/src/useInitPlugins.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/PricingSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/hooks/usePrinter.tsx
  client/packages/invoices/src/Prescriptions/DetailView/hooks/utils.test.tsx
  client/packages/invoices/src/Prescriptions/DetailView/hooks/utils.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/invoices/src/Prescriptions/api/hooks/useLabelPrinterSettings.ts
  client/packages/invoices/src/Prescriptions/api/hooks/utils.tsx
  client/packages/invoices/src/Returns/modals/CustomerReturn/ReturnQuantitiesTable.tsx
  client/packages/invoices/src/StockOut/utils.tsx
  client/packages/reports/src/utils.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/hooks.tsx
  client/packages/requisitions/src/ResponseRequisition/api/api.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/document/useDeleteSelectedResponseRequisitions.ts
  client/packages/requisitions/src/ResponseRequisition/api/hooks/line/useDeleteResponseLines.ts
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRForm.ts
  client/packages/system/src/Item/Components/ListItems/ListItems.tsx
  client/packages/system/src/Item/Components/PackSize/PackSizeEntryCell.tsx
  client/packages/system/src/Name/Components/CustomerSearchModal/CustomerSearchModal.tsx
  client/packages/system/src/Name/ListView/ImportProperties/ImportReviewDataTable.tsx
  client/packages/system/src/Report/api/hooks/useReport.ts
  client/packages/system/src/Vaccination/Components/SelectItemAndBatch.tsx
  client/packages/system/src/utils.ts
  client/yarn.lock
  server/service/src/contact_form/mod.rs
Labels: refactor

#6872 6635 Add clinicians is_active filter
  client/packages/common/src/types/schema.ts
  client/packages/programs/src/api/api.ts
  server/graphql/clinician/src/query.rs
  server/repository/src/db_diesel/clinician.rs
Labels: Team Piwakawaka, Severity: High, feature: dispensing

#6901 6617 Floor calculated population count
  client/packages/system/src/IndicatorsDemographics/DetailView/PopulationColumn.tsx
Labels: Team Ruru 🦉, Severity: Low, feature: GAPS, UI tweaks

#6909 6895 don't round displayed prescribed quantity
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
Labels: Team Piwakawaka, Severity: Normal, feature: dispensing

#6893 6224 create dummy users on sync
  server/service/src/sync/test/test_data/invoice.rs
  server/service/src/sync/translations/invoice.rs
Labels: bug, Team Piwakawaka, Severity: High

#6885 6838 add prefs repo layer
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/preference.rs
  server/repository/src/db_diesel/preference_row.rs
Labels: Priority: Should have, Team Ruru 🦉, feature: preferences

#6903 6891 stocktake line edit move expiry date column to right of batch column
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
Labels: enhancement, Team Ruru 🦉

#6501 Cold Chain for GAPS mobile features
  client/packages/android/app/src/main/java/org/openmsupply/client/AppState.java
  client/packages/android/app/src/main/java/org/openmsupply/client/MainActivity.java
  client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
  client/packages/android/app/src/main/java/org/openmsupply/client/SplashPage.java
  client/packages/android/app/src/main/res/drawable-land-hdpi/splash.png
  client/packages/android/app/src/main/res/drawable-land-mdpi/splash.png
  client/packages/android/app/src/main/res/drawable-land-xhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-land-xxhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-land-xxxhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-port-hdpi/splash.png
  client/packages/android/app/src/main/res/drawable-port-mdpi/splash.png
  client/packages/android/app/src/main/res/drawable-port-xhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-port-xxhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-port-xxxhdpi/splash.png
  client/packages/android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  client/packages/android/app/src/main/res/drawable/ic_launcher_background.xml
  client/packages/android/app/src/main/res/drawable/splash.png
  client/packages/android/app/src/main/res/values/styles.xml
  client/packages/coldchain/src/ColdchainService.tsx
  client/packages/coldchain/src/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Equipment/DetailView/StatusTab.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Details.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Documents.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/StatusLogs.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/Summary.tsx
  client/packages/coldchain/src/Equipment/DetailView/Tabs/index.ts
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/coldchain/src/Equipment/ListView/AddFromScannerButton.tsx
  client/packages/coldchain/src/Equipment/ListView/Toolbar.tsx
  client/packages/coldchain/src/Mobile/Components/SimpleLabelDisplay.tsx
  client/packages/coldchain/src/Mobile/Equipment/CardListView.tsx
  client/packages/coldchain/src/Mobile/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Mobile/Equipment/DetailView/Footer.tsx
  client/packages/coldchain/src/Mobile/Equipment/LogCardListView.tsx
  client/packages/common/src/hooks/index.ts
  client/packages/common/src/hooks/useIsGapsStoreOnly/index.ts
  client/packages/common/src/hooks/useIsGapsStoreOnly/useIsGapsStoreOnly.ts
  client/packages/common/src/ui/components/inputs/Filters/FilterMenu.tsx
  client/packages/common/src/ui/components/inputs/TextInput/InputWithLabelRow.tsx
  client/packages/common/src/ui/components/inputs/Upload/Upload.tsx
  client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
  client/packages/common/src/ui/discovery/DiscoveredServers.tsx
  client/packages/common/src/ui/discovery/ServerDiscovery.tsx
  client/packages/common/src/ui/icons/QrCodeScanner.tsx
  client/packages/common/src/ui/icons/Tune.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/host/src/Admin/Settings.tsx
  client/packages/host/src/Site.tsx
  client/packages/host/src/components/Android.tsx
  client/packages/host/src/components/AppVersion.tsx
  client/packages/host/src/components/Initialise/InitialiseLayout.tsx
  client/packages/host/src/components/Login/Login.tsx
  client/packages/host/src/components/Login/LoginLayout.tsx
  client/packages/host/src/components/Login/hooks.ts
  client/packages/host/src/components/MobileNavBar/MobileNavBar.tsx
  client/packages/host/src/components/MobileNavBar/index.ts
  client/packages/host/src/components/Navigation/ColdChainNav.tsx
  client/packages/host/src/components/Sync/SyncModal.tsx
  client/packages/host/src/components/index.ts
  client/packages/system/src/Name/ListView/Facilities/FacilityEditModal.tsx
Labels: feature: GAPS

#6894 2687 update nothing here svg 6724 standardise patient nothing here views
  client/packages/common/src/intl/locales/ar/common.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr-DJ/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/common/src/ui/components/errors/NothingHere.tsx
  client/packages/common/src/ui/components/errors/NothingHereIcon.tsx
  client/packages/common/src/ui/components/errors/nothing-here.gif
  client/packages/invoices/src/Returns/SupplierDetailView/ContentArea.tsx
  client/packages/programs/src/ImmunisationProgramDetailView/ImmunisationProgramDetailView.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/ContentArea.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ContentArea.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/RnRForms/ListView/ListView.tsx
  client/packages/system/src/Asset/AssetLogReasons/ListView.tsx
  client/packages/system/src/Asset/ListView/ListView.tsx
  client/packages/system/src/Encounter/ListView/ListView.tsx
  client/packages/system/src/Item/ListView/ListView.tsx
  client/packages/system/src/Name/ListView/Facilities/ListView.tsx
  client/packages/system/src/Name/ListView/ListView.tsx
  client/packages/system/src/Patient/ContactTrace/Components/ListView.tsx
  client/packages/system/src/Patient/Encounter/ListView.tsx
  client/packages/system/src/Patient/Insurance/ListView.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
  client/packages/system/src/Patient/VaccinationCard/ListView.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
Labels: enhancement, Team Ruru 🦉, UI tweaks

#6913 6714 toast message if vax stock has updated
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/operations.graphql
  client/packages/system/src/Vaccination/api/useVaccination.ts
Labels: enhancement, Team Ruru 🦉, feature: vaccine card

#6927 6863 patient list view gender & deceased fields are not translated to respective languages
  client/packages/system/src/Patient/CreatePatientModal/PatientResultsTab.tsx
  client/packages/system/src/Patient/ListView/ListView.tsx
  client/packages/system/src/Patient/PatientView/index.ts
Labels: Severity: High, feature: dispensing, Effort: small

#6921 6793 Add icon for create/save button patientView
  client/packages/system/src/Patient/PatientView/Footer.tsx
Labels: Team Ruru 🦉, UI tweaks

#6932 #6391 Fix missing Cold chain nav items
  client/packages/host/src/components/Navigation/ColdChainNav.tsx
Labels: Team Piwakawaka, Severity: High

#6910 6889 enable insurance tab even when program module off
  client/packages/system/src/Patient/PatientView/AddButton.tsx
  client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
  client/packages/system/src/Patient/PatientView/PatientDetailView.tsx
  client/packages/system/src/Patient/PatientView/PatientView.tsx
Labels: Team Piwakawaka, feature: dispensing

#6935 Fix filtering gender
  client/packages/system/src/Patient/ListView/Toolbar.tsx
Labels: Tester: Maria, Severity: High, feature: dispensing, Effort: small

#6925 6729 fix remove option when no location selected
  client/packages/common/src/ui/components/errors/NothingHere.tsx
  client/packages/system/src/Location/Components/LocationSearchInput.tsx
Labels: Team Ruru 🦉, Severity: Low, UI tweaks

#6934 conditionally hide clinicians from encounters
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
  client/packages/system/src/Patient/Encounter/CreateEncounterForm.tsx
  client/packages/system/src/Vaccination/Components/VaccinationModal.tsx
Labels: enhancement, Team Ruru 🦉, feature: vaccine card

#6937 6795 prescription sidebar styling
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/AdditionalInfoSection.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PatientDetails.tsx
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/PrescriptionDetailsSection.tsx
  client/packages/system/src/Program/ProgramSearchInput.tsx
Labels: Build Tested: Issues Found, Tester: Maria, Team Piwakawaka, feature: dispensing, Build Tested: Needs Retesting

#6918 6758 Vaccine dose UI updates
  client/packages/system/src/Vaccination/Components/SelectBatch.tsx
Labels: Team Ruru 🦉, Severity: Low, feature: dispensing, feature: vaccine card, UI tweaks

#6917 6391 date given does not update when vaccine is changed to not given
  client/packages/common/src/types/schema.ts
  client/packages/plugins/backendTypes/generated/TransformRequestRequisitionLineContext.ts
  client/packages/system/src/Vaccination/api/operations.generated.ts
  client/packages/system/src/Vaccination/api/useVaccination.ts
  server/graphql/programs/src/mutations/vaccination/update.rs
  server/graphql/types/src/types/program/vaccination.rs
  server/repository/src/db_diesel/vaccination_row.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_06_01/change_vaccination_date_to_nullable.rs
  server/repository/src/migrations/v2_06_01/mod.rs
  server/service/src/sync/test/test_data/vaccination.rs
  server/service/src/vaccination/get_vaccination_card.rs
  server/service/src/vaccination/insert/generate.rs
  server/service/src/vaccination/update/generate.rs
  server/service/src/vaccination/update/mod.rs
Labels: feature: programs, Severity: High, feature: vaccine card

#6926 6915 Target MOS is slightly different after migration
  server/service/src/sync/translations/requisition.rs
  server/util/src/constants.rs
Labels: Migrate Existing Desktop, Team Ruru 🦉, Severity: High, Effort: small, feature: CIV

#6942 6600 Able to link yourself as a patient in Next of Kin
  client/packages/programs/src/JsonForms/components/Search/SearchWithUserSource.tsx
Labels: Epic, Build Tested: Issues Found, Tester: Anusha, Tester: Maria, Team Ruru 🦉, Team Piwakawaka, Severity: Normal, feature: dispensing, feature: vaccine card

#6951 6896 Deleting an immunization program master list in OG is not reflected in OMS
  server/service/src/sync/translations/program_requisition_settings.rs
Labels: Team Ruru 🦉, Severity: High, feature: GAPS, feature: vaccine card

#6953 6779 default patient page should be translatable into other languages
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/programs/src/JsonForms/common/components/Select.tsx
  client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json
  client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
  client/packages/system/src/Patient/PatientView/Footer.tsx
Labels: Build Tested: Issues Found, Tester: Maria, Team Ruru 🦉, Severity: High, feature: dispensing, Build Tested: Needs Retesting, feature: translation

#6964 6959 translations encounters filter options are not translated
  client/packages/system/src/Encounter/ListView/Toolbar.tsx
Labels: Team Ruru 🦉, Severity: High, feature: translation

#6976 6955 translations datepicker's buttons show in english
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/styles/ThemeProvider.tsx
  client/packages/common/src/ui/components/inputs/DatePickers/BaseDatePickerInput/BaseDatePickerInput.tsx
  client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
Labels: Team Ruru 🦉, feature: translation

#6956 5713 empty inbound shipment sent to oms site
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/translations/invoice_line.rs
Labels: bug, Team Ruru 🦉, Severity: High

#6978 6970 translations 'no options' text when no options are shown needs to be translatable
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/programs/src/JsonForms/common/components/Autocomplete.tsx
  client/packages/system/src/Patient/ContactTrace/Components/ContactTraceSearchInput.tsx
Labels: Team Ruru 🦉, Severity: High, feature: translation

#6979 6374 datepicker options for patient dob
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
  client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
Labels: Team Ruru 🦉, Severity: Low, feature: dispensing, UI tweaks

#6986 Default no options translation
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteMulti.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
Labels: Team Ruru 🦉, Severity: High, feature: translation

#6990 #6954 #6981 #6967 #6983 Various localisation fixes
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/strings/IntlStrings.ts
  client/packages/common/src/intl/utils/IntlUtils.ts
  client/packages/common/src/ui/components/inputs/Autocomplete/Autocomplete.tsx
  client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
  client/packages/invoices/src/InboundShipment/DetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/SidePanel/SidePanel.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/SidePanel/SidePanel.tsx
  client/packages/programs/package.json
  client/packages/programs/src/JsonForms/common/JsonForm.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/SidePanel.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/SidePanel.tsx
  client/packages/system/src/IndicatorsDemographics/DetailView/IndicatorsDemographics.tsx
  client/yarn.lock
Labels: Severity: High, feature: translation

#6985 6939 use callback permission hook for import button click
  client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
  client/packages/coldchain/src/Equipment/ListView/ListView.tsx
  client/packages/common/src/intl/locales/en/common.json
Labels: feature: coldchain, Team Piwakawaka, Severity: Normal

#6936 6370 fix double scroll
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/ContentArea.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/ContentArea.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/ContentArea.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/ContentArea.tsx
Labels: Team Ruru 🦉, UI tweaks

#6938 6700 Update column arrangement encounters
  client/packages/system/src/Encounter/ListView/columns.ts
Labels: feature: programs, Team Ruru 🦉, Severity: Low, UI tweaks, area: tables

#6946 6855 display gps coordinates in settings
  client/packages/android/app/build.gradle
  client/packages/android/app/capacitor.build.gradle
  client/packages/android/app/src/main/AndroidManifest.xml
  client/packages/android/app/src/main/assets/capacitor.plugins.json
  client/packages/android/app/src/main/java/org/openmsupply/client/ExtendedWebViewClient.java
  client/packages/android/capacitor-cordova-android-plugins/build.gradle
  client/packages/android/capacitor.settings.gradle
  client/packages/android/package.json
  client/packages/android/variables.gradle
  client/packages/common/src/hooks/useDialog/useDialog.tsx
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/ui/icons/Location.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/host/src/Help/Help.tsx
  client/packages/host/src/api/hooks/settings/namePropertyData.ts
  client/packages/host/src/components/Footer/Footer.tsx
  client/packages/system/package.json
  client/packages/system/src/Name/ListView/Facilities/DisplayCoordinates.tsx
  client/packages/system/src/Name/ListView/Facilities/FacilityEditModal.tsx
  client/yarn.lock
Labels: Team Piwakawaka, needs design, feature: GAPS

#6984 #3940 Open files on Android
  client/packages/android/app/capacitor.build.gradle
  client/packages/android/app/src/main/assets/capacitor.plugins.json
  client/packages/android/app/src/main/java/org/openmsupply/client/ExtendedWebViewClient.java
  client/packages/android/app/src/main/res/xml/file_paths.xml
  client/packages/android/build.gradle
  client/packages/android/capacitor.settings.gradle
  client/packages/android/gradle/wrapper/gradle-wrapper.properties
  client/packages/android/package.json
  client/packages/coldchain/src/Equipment/Components/FileList.tsx
  client/packages/common/src/utils/files/FileUtils.ts
  client/packages/config/src/config.ts
  client/yarn.lock
Labels: bug, platform: android, Priority: Must Have, Team Piwakawaka, Severity: High, feature: CCEI, feature: GAPS

#6988 6745 - Allow decimal places in stock adjustment
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
  client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
Labels: Team Ruru 🦉, Severity: Normal, UI tweaks

#6923 Program Internal Orders Fixes
  client/packages/requisitions/src/RequestRequisition/ListView/ProgramRequisitionOptions.tsx
Labels: bug, Team Ruru 🦉, Severity: High, Needs Investigation, feature: CIV

#6991 change comment to popover column
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/columns.tsx
  client/packages/inventory/src/Stocktake/ListView/ListView.tsx
  client/packages/invoices/src/InboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/Prescriptions/ListView/ListView.tsx
  client/packages/invoices/src/Returns/CustomerListView/ListView.tsx
  client/packages/invoices/src/Returns/SupplierListView/ListView.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/ListView.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/ListView.tsx
Labels: bug, platform: android, Team Ruru 🦉, Severity: Low, needs design, area: tables

#7006 revert gradle version
  client/packages/android/build.gradle
Labels: refactor

#7002 6445 Add Pluralization
  client/package.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr-DJ/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/intl/utils/IntlUtils.ts
  client/packages/invoices/package.json
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/yarn.lock
Labels: Team Ruru 🦉, UI tweaks

#7029 #6920 Correct rounding for Currency input
  client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
Labels: Team Piwakawaka, Severity: Normal

#7005 Hide indicator customer info if not exist
  client/packages/requisitions/src/RequestRequisition/DetailView/IndicatorEdit/IndicatorLineEdit.tsx
Labels: Team Ruru 🦉

#7010 3406 Reduce site password field width in sync settings
  client/packages/host/src/Admin/SyncSettings.tsx
Labels: bug, good first issue, front-end, Team Ruru 🦉, Severity: Low, UI tweaks

#7042 6999 import fridge tags mobile view
  client/packages/coldchain/src/ColdchainService.tsx
  client/packages/coldchain/src/Mobile/Equipment/DetailView/DetailView.tsx
  client/packages/coldchain/src/Mobile/Equipment/DetailView/LogCardListView.tsx
  client/packages/coldchain/src/Mobile/Monitoring/MobileTemperatureChart.tsx
  client/packages/coldchain/src/Monitoring/ListView/ListView.tsx
  client/packages/coldchain/src/common/ImportFridgeTag.tsx
  client/packages/coldchain/src/common/Monitoring/TemperatureChart/BreachIndicator.tsx
  client/packages/coldchain/src/common/Monitoring/TemperatureChart/BreachPopover.tsx
  client/packages/coldchain/src/common/Monitoring/TemperatureChart/Chart.tsx
  client/packages/coldchain/src/common/Monitoring/TemperatureChart/TemperatureChart.tsx
  client/packages/coldchain/src/common/Monitoring/TemperatureChart/Tooltip.tsx
  client/packages/coldchain/src/common/Monitoring/TemperatureChart/index.ts
  client/packages/coldchain/src/common/Monitoring/TemperatureChart/types.ts
  client/packages/coldchain/src/common/Monitoring/TemperatureChart/utils.ts
  client/packages/coldchain/src/common/Monitoring/index.ts
  client/packages/common/src/hooks/useIsScreen/index.ts
  client/packages/common/src/hooks/useIsScreen/useIsExtraSmallScreen.spec.ts
  client/packages/common/src/hooks/useIsScreen/useIsExtraSmallScreen.ts
  client/packages/host/src/components/Footer/Footer.tsx
  server/service/src/sensor/berlinger.rs
Labels: Team Piwakawaka, needs design, feature: GAPS

#7040 #6997 #7014 Multiple file upload
  server/server/src/static_files.rs
  server/server/src/upload.rs
  server/server/src/upload_fridge_tag.rs
  server/service/src/static_files.rs
  server/service/src/sync/sync_on_central/mod.rs
Labels: enhancement, Priority: Nice to Have, Team Piwakawaka

#7051 7050 add discountPercentage field value in invoiceLines endpoint
  server/graphql/types/src/types/master_list.rs
Labels: enhancement, needs triage, Severity: High, feature: reports

#7052 7030 release testing feedback
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/ui/components/inputs/DatePickers/DateTimePickerInput/DateTimePickerInput.tsx
  client/packages/common/src/ui/components/inputs/Filters/DateFilter.tsx
  client/packages/invoices/src/OutboundShipment/ListView/ListView.tsx
  client/packages/invoices/src/OutboundShipment/ListView/Toolbar.tsx
  client/packages/system/src/Patient/PatientView/DefaultPatientSchema.json
  client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
Labels: Priority: Must Have, Team Ruru 🦉, docs: external, feature: CIV

#7054 6981 (replacments) Additional translations for loading
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteList.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteMulti.tsx
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
Labels: Build Tested: Issues Found, Tester: Maria, Team Piwakawaka, Severity: High, Build Tested: Needs Retesting, feature: translation

#6972 6839 preference table sync
  server/repository/src/db_diesel/preference_row.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/preference.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/preference.rs
Labels: Priority: Should have, Team Ruru 🦉, feature: preferences

#6875 Allow setting config file via command line argument
  server/README.md
  server/cli/src/cli.rs
  server/cli/src/test_connection.rs
  server/server/src/configuration.rs
  server/server/src/main.rs
  server/windows/src/windows.rs
Labels: enhancement, Team Ruru 🦉, feature: server cli

#7038 7037 Fix plugin sync when backend and frontend plugins have the same code
  server/cli/src/plugins.rs
  server/repository/src/migrations/v2_06_01/mod.rs
  server/repository/src/migrations/v2_06_01/remove_plugins.rs
Labels: Severity: Hotfix

#7047 7044 prescribed qty column
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
Labels: Team Piwakawaka, feature: dispensing

#7019 4754 android report UI
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/icons/Icon.stories.tsx
  client/packages/common/src/ui/icons/Swipe.tsx
  client/packages/common/src/ui/icons/index.ts
  client/packages/reports/src/DetailView/AppBarButton.tsx
  standard_reports/item-usage/latest/src/style.css
Labels: platform: android, Team Ruru 🦉, feature: reports

#7056 6856 Auto-generated comment field is not relevant for all (and is unclear)
  client/packages/requisitions/src/RequestRequisition/DetailView/Footer/StatusChangeButton.tsx
Labels: Team Ruru 🦉, Severity: Normal

#6933 6848 upgrade asset labels
  client/packages/android/README.MD
  client/packages/android/doc/choosing_OMS_Android_Gradle_JDK.png
  client/packages/android/doc/omSupply_android_gradle_jdk.png
  client/packages/android/doc/omSupply_android_ndk.png
  client/packages/coldchain/src/Equipment/DetailView/AppBarButtons.tsx
  client/packages/common/src/intl/locales/en/common.json
  server/server/src/print/label.rs
  server/server/src/print/mod.rs
  server/service/src/print/label.rs
Labels: Team Piwakawaka, feature: GAPS

#7036 6840 prefs query
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/lib.rs
  server/graphql/preference/Cargo.toml
  server/graphql/preference/src/lib.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/preferences.rs
  server/repository/src/db_diesel/preference.rs
  server/repository/src/db_diesel/preference_row.rs
  server/service/src/lib.rs
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/README.md
  server/service/src/preference/preferences/complex_pref.rs
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/preferences/use_payments_in_prescriptions.rs
  server/service/src/service_provider.rs
  server/service/src/store_preference.rs
Labels: Priority: Should have, Team Ruru 🦉, feature: preferences

#7058 Make print button multi select
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
  client/packages/inventory/src/Stocktake/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/InboundShipment/DetailView/AddButton.tsx
  client/packages/invoices/src/InboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/AppBarButtons.tsx
  client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
  client/packages/invoices/src/Returns/CustomerDetailView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/SupplierDetailView/AppBarButtons.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/RnRForms/DetailView/AppBarButtons.tsx
  client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
  client/packages/system/src/Report/components/ReportSelector.tsx
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
Labels: enhancement, Team Ruru 🦉, UI tweaks

#7060 6280 fix exporting and importing coldchain equipment
  client/packages/coldchain/src/Equipment/DetailView/Footer/Footer.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
  client/packages/coldchain/src/Equipment/utils.ts
Labels: Team Piwakawaka, Severity: High, feature: CCEI

#7068 7057 create new inbound shipment firing twice and creates two shipments
  client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
Labels: Team Ruru 🦉, Severity: Hotfix, Needs Investigation

#7008 4998 Hide time tab from datepicker
  client/packages/invoices/src/Prescriptions/ListView/NewPrescriptionModal.tsx
  client/packages/system/src/Patient/Encounter/CreateEncounterForm.tsx
Labels: bug, good first issue, front-end, Team Ruru 🦉, Severity: Low, area: date picker

#7013 6851 add photo with mobile
  client/package.json
  client/packages/android/app/capacitor.build.gradle
  client/packages/android/app/src/main/assets/capacitor.plugins.json
  client/packages/android/app/src/main/java/org/openmsupply/client/ExtendedWebViewClient.java
  client/packages/android/capacitor.settings.gradle
  client/packages/android/package.json
  client/packages/coldchain/src/Equipment/Components/AssetLogPanel.tsx
  client/packages/coldchain/src/Equipment/Components/index.ts
  client/packages/coldchain/src/Equipment/DetailView/StatusForm.tsx
  client/packages/coldchain/src/Equipment/DetailView/TakePhotoButton.tsx
  client/packages/coldchain/src/Equipment/DetailView/UpdateStatusButton.tsx
  client/packages/coldchain/src/Equipment/DetailView/UploadButton.tsx
  client/packages/coldchain/src/Equipment/DetailView/UploadTab.tsx
  client/packages/coldchain/src/Equipment/utils.ts
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/icons/Camera.tsx
  client/packages/common/src/ui/icons/index.ts
  client/yarn.lock
Labels: Team Piwakawaka, needs design, feature: GAPS

#7088 Use a new translation key
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/coldchain/src/Equipment/ListView/AddFromScannerButton.tsx
  client/packages/coldchain/src/Equipment/ListView/CreateAssetModal.tsx
  client/packages/common/src/intl/locales/en/common.json
Labels: Team Piwakawaka, feature: CCEI, feature: translation

#7061 6995 stocktake add a performed by field
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/SidePanel.tsx
  client/packages/inventory/src/Stocktake/api/api.ts
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/inventory/src/Stocktake/api/operations.graphql
  server/graphql/stocktake/src/mutations/update.rs
  server/graphql/types/src/types/stocktake.rs
  server/repository/src/db_diesel/stocktake_row.rs
  server/repository/src/migrations/v2_07_00/mod.rs
  server/repository/src/migrations/v2_07_00/new_stocktake_fields.rs
  server/service/src/stocktake/insert/generate.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/stocktake/update/mod.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/sync_on_central/mod.rs
  server/service/src/sync/test/test_data/stocktake.rs
  server/service/src/sync/translations/stocktake.rs
Labels: enhancement, Priority: Should have, Team Ruru 🦉

#7067 6321 block prescription line edit refresh
  client/packages/common/src/hooks/useConfirmOnLeaving/useConfirmOnLeaving.ts
  client/packages/invoices/src/Prescriptions/LineEditView/LineEditView.tsx
Labels: Build Tested: Issues Found, Tester: Maria, Team Ruru 🦉, feature: vaccine card, Build Tested: Needs Retesting

#7094 Add logo instructions
  server/service/src/print/label.rs
Labels: Team Piwakawaka, feature: GAPS

#7095 6977 Import facilities modal improvements
  client/packages/common/src/intl/locales/en/common.json
  client/packages/system/src/Name/ListView/ImportProperties/ImportReviewDataTable.tsx
  client/packages/system/src/Name/ListView/ImportProperties/PropertiesImportModal.tsx
Labels: Team Ruru 🦉, Severity: Low, UI tweaks

#7102 Possible fix for electron discovery missing translations
  client/packages/electron/webpack.plugins.ts
Labels: bug, platform: desktop, Severity: Normal, Needs Investigation, feature: translation

#7103 7063 use plugin for aggregated item info in request line edit
  client/packages/common/src/plugins/types.ts
  client/packages/common/src/types/schema.ts
  client/packages/plugins/backendCommon/types.ts
  client/packages/plugins/backendCommon/utils.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ItemInformation.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestEditPage.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/api/api.ts
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useRequest.ts
  client/packages/requisitions/src/RequestRequisition/api/hooks/document/useRequestFields.ts
  client/packages/requisitions/src/RequestRequisition/api/index.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.generated.ts
  client/packages/requisitions/src/RequestRequisition/api/operations.graphql
  client/packages/system/src/RequestRequisitionLine/index.ts
  client/packages/system/src/RequestRequisitionLine/operations.generated.ts
  client/packages/system/src/RequestRequisitionLine/operations.graphql
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/core/src/loader/requisition_item_information.rs
  server/graphql/types/src/types/mod.rs
  server/graphql/types/src/types/requisition_item_information.rs
  server/graphql/types/src/types/requisition_line.rs
  server/service/src/requisition/mod.rs
  server/service/src/requisition/request_requisition/mod.rs
  server/service/src/requisition/request_requisition/requisition_item_info.rs
Labels: enhancement, feature: plugin, feature: CIV

#7111 6138 Add "New (On Hold)" status display in stocktake list view
  client/packages/common/src/intl/locales/ar/common.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/intl/locales/tet/common.json
  client/packages/inventory/src/Stocktake/DetailView/Footer/StocktakeLockButton.tsx
  client/packages/inventory/src/Stocktake/ListView/ListView.tsx
Labels: enhancement, Priority: Nice to Have, Team Ruru 🦉, UI tweaks

#7124 7104 translation fixes
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/invoices/src/utils.ts
  client/packages/system/src/Patient/CreatePatientModal/CreatePatientModal.tsx
Labels: Team Piwakawaka, feature: CIV, feature: translation
