Repository msupply-foundation/open-msupply, pull requests merged in 2025-07, with the labels that each got.

#8332 8299 distributed quantity field gets automatically replaced by minimum pack size before the user finishes typing
  client/packages/invoices/src/StockOut/Components/AutoAllocateIssueField.tsx
Labels: needs triage, Team Piwakawaka

#8334 89 internal: negative R&R balances
  client/packages/requisitions/src/RnRForms/DetailView/RnRFormLine.tsx
  client/packages/requisitions/src/RnRForms/DetailView/helpers.test.ts
  client/packages/requisitions/src/RnRForms/DetailView/helpers.ts
  client/packages/requisitions/src/RnRForms/api/hooks/useRnRFormContext.ts
  package.json
  server/Cargo.lock
  server/graphql/programs/Cargo.toml
  server/graphql/programs/src/mutations/rnr_form/finalise.rs
  server/graphql/programs/src/mutations/rnr_form/update.rs
  server/service/src/rnr_form/finalise.rs
  server/service/src/rnr_form/tests/finalise.rs
  server/service/src/rnr_form/tests/update.rs
  server/service/src/rnr_form/update.rs
Labels: Team Ruru 🦉, feature: R&R

#8272 8056 nightly automate builds gh action create tags
  .github/workflows/create-nightly-tags.sh
  .github/workflows/nightly-automated-builds.yaml
Labels: enhancement, Team Piwakawaka

#8333 8235 Internal order Ok & Next does not add item
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEditModal.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestedSelection/RequestedSelection.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseEditModal.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/SuppliedSelection/SupplySelection.tsx
Labels: Team Ruru 🦉, Severity: High

#8342 Fix migration
  server/repository/src/migrations/v2_08_03/invoice_received_status.rs
Labels: bug, Priority: Must Have, Team Piwakawaka

#8330 #8297 Fix for Electron build
  client/packages/electron/forge.config.ts
  client/packages/electron/package.json
  client/packages/electron/webpack.rules.ts
  client/yarn.lock
Labels: Team Piwakawaka, Severity: High

#8304 Add pagination to stockWithStats query
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
  client/packages/system/src/Item/Components/StockItemSearchInputWithStats/StockItemSearchInputWithStats.tsx
  client/packages/system/src/Item/api/hooks/useStockItemsWithStats/useStockItemsWithStats.tsx
  client/packages/system/src/Item/utils.ts
Labels: Team Piwakawaka, Severity: High

#8349 8192 android export CSV/Excel files
  client/packages/android/app/src/main/java/org/openmsupply/client/FileManager.java
  client/packages/android/app/src/main/java/org/openmsupply/client/MainActivity.java
  client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
  client/packages/coldchain/src/Equipment/ImportAsset/EquipmentImportModal.tsx
  client/packages/coldchain/src/Equipment/ImportAsset/UploadTab.tsx
  client/packages/coldchain/src/Equipment/ListView/AppBarButtons.tsx
  client/packages/common/src/hooks/useNativeClient/types.ts
  client/packages/common/src/intl/locales/ar/common.json
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/intl/locales/ru/common.json
  client/packages/common/src/utils/files/FileUtils.ts
  client/packages/inventory/src/Stocktake/ListView/AppBarButtons.tsx
  client/packages/invoices/src/InboundShipment/ListView/AppBarButtons.tsx
  client/packages/invoices/src/OutboundShipment/ListView/AppBarButtons.tsx
  client/packages/invoices/src/Prescriptions/ListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/CustomerListView/AppBarButtons.tsx
  client/packages/invoices/src/Returns/SupplierListView/AppBarButtons.tsx
  client/packages/reports/src/DetailView/AppBarButton.tsx
  client/packages/reports/src/DetailView/DetailView.tsx
  client/packages/requisitions/src/RequestRequisition/ListView/AppBarButtons.tsx
  client/packages/requisitions/src/ResponseRequisition/ListView/AppBarButtons.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/CatalogueItemImportModal.tsx
  client/packages/system/src/Asset/ImportCatalogueItem/UploadTab.tsx
  client/packages/system/src/Asset/ListView/AppBarButtons.tsx
  client/packages/system/src/Location/ListView/AppBarButtons.tsx
  client/packages/system/src/MasterList/ListView/AppBarButtons.tsx
  client/packages/system/src/Name/ListView/ImportProperties/UploadTab.tsx
  client/packages/system/src/Patient/ListView/AppBarButtons.tsx
  client/packages/system/src/Report/api/hooks/usePrintReport.ts
  client/packages/system/src/Report/components/SelectReportModal.tsx
  client/packages/system/src/Stock/ListView/AppBarButtons.tsx
Labels: enhancement, platform: android, Team Ruru 🦉, Liberia

#8352 8351 add purchase order feature flag
  client/packages/config/src/config.ts
  client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
  client/packages/host/webpack.config.js
  client/packages/purchase_orders/README.md
Labels: enhancement, Team Piwakawaka, Purchase Orders

#8358 7899 no easy way to delete a batch line in inbound shipments
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/api/hooks/index.ts
  client/packages/invoices/src/InboundShipment/api/hooks/useDraftInboundLines.tsx
Labels: enhancement, Priority: Should Have, Team Piwakawaka

#8356 Remove filter that masterList exists on store
  client/packages/system/src/Stock/api/hooks/useStockList.ts
Labels: Severity: Normal

#8361 7721 inform user that batch is on hold when making inventory adjustment
  client/packages/system/src/Stock/Components/InventoryAdjustment/InventoryAdjustmentModal.tsx
Labels: enhancement, Team Piwakawaka

#8359 8201 switch store preference and properties tab
  client/packages/system/src/Name/ListView/Stores/StoreEditModal.tsx
Labels: enhancement, Priority: Must Have, Team Piwakawaka, Effort: Small, UI tweaks

#8386 7565 restrict permission cancelling to users with can cancel finalised invoices user permission
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/Prescriptions/DetailView/SidePanel/SidePanel.tsx
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v2_09_00/add_can_cancel_finalised_invoices_user_permission.rs
  server/repository/src/migrations/v2_09_00/mod.rs
  server/service/src/login.rs
Labels: Priority: Should Have, Team Piwakawaka, feature: dispensing

#8379 7084 Program input background colour consistency
  client/packages/system/src/Program/ProgramSearchInput.tsx
Labels: Team Ruru 🦉, Severity: High, feature: dispensing

#8366 8378 Remove delivered lines from item ledger (+ add running balance to stock line ledger)
  client/packages/common/src/intl/README.md
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Stock/Components/Ledger/useLedgerColumns.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/graphql/general/src/queries/ledger.rs
  server/repository/src/db_diesel/item_ledger.rs
  server/repository/src/db_diesel/ledger.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/db_diesel/stock_line_ledger.rs
  server/repository/src/db_diesel/stock_movement.rs
  server/repository/src/migrations/views/mod.rs
  server/repository/src/mock/ledger.rs
  server/repository/src/mock/mod.rs
  server/service/src/ledger.rs
  server/service/src/programs/patient/README.md
  server/service/src/report/convert_to_excel.rs
Labels: Team Ruru 🦉, Severity: High

#8383 8151 stock line details layout
  client/packages/system/src/Item/Components/PackSize/PackSizeNumberInput.tsx
  client/packages/system/src/Item/Components/PackSize/index.ts
  client/packages/system/src/Stock/Components/NewStockLineModal.tsx
  client/packages/system/src/Stock/Components/StockLineForm.tsx
Labels: Team Ruru 🦉, Severity: Normal, docs: external, UI tweaks

#8397 7843 In Store Preferences clicking the Cancel button doesn't prevent your change to be saved
  client/packages/system/src/Name/ListView/Stores/StoreEditModal.tsx
Labels: Team Ruru 🦉, Severity: Normal, docs: external

#8413 reorder view drop
  server/repository/src/migrations/views/mod.rs
Labels: Severity: High, Bug: development

#8409 8394 Prevent negative placeholders after Outbound Shipment autoallocation
  client/packages/invoices/src/StockOut/allocateQuantities.test.ts
  client/packages/invoices/src/StockOut/allocateQuantities.ts
  package.json
Labels: Team Ruru 🦉, Team Piwakawaka, Severity: Hotfix, Bug: production

#8424 8403 donor not visible
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/insert/validate.rs
Labels: Team Piwakawaka

#8418 8137 Move HTTP logs to debug level, add graphql logs
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/lib.rs
  server/graphql/logger.rs
  server/server/Cargo.toml
  server/server/src/middleware/mod.rs
Labels: Team Ruru 🦉, Needs Investigation

#8427 8407 exf78 civ fiche d'inventaire des ppi a master list filter is missing
  server/graphql/invoice_line/src/invoice_line_queries.rs
  server/repository/src/db_diesel/invoice_line.rs
  server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
Labels: enhancement, Team Ruru 🦉, feature: reports, feature: CIV

#8433 Add no_equal_to_or_null filter option & use in central server sync
  server/graphql/core/src/generic_filters.rs
  server/graphql/core/src/lib.rs
  server/graphql/general/src/queries/inventory_adjustment_reason.rs
  server/graphql/general/src/queries/return_reason.rs
  server/repository/src/db_diesel/activity_log.rs
  server/repository/src/db_diesel/document_registry.rs
  server/repository/src/db_diesel/filter_sort_pagination.rs
  server/repository/src/db_diesel/name_row.rs
  server/repository/src/diesel_macros.rs
  server/service/src/programs/patient/search.rs
  server/service/src/sync/mod.rs
Labels: Team Piwakawaka, Severity: High

#8438 8420 on tablet when creating a new patient some fields go outside the modal when virtual keyboard is up
  client/packages/common/src/ui/components/inputs/TextInput/BasicTextInput.tsx
  client/packages/common/src/ui/components/panels/SlidePanel/SlidePanel.tsx
  client/packages/common/src/ui/components/steppers/HorizontalStepper/HorizontalStepper.tsx
  client/packages/common/src/ui/components/steppers/WizardStepper/WizardStepper.tsx
  client/packages/common/src/ui/forms/Detail/InputWithLabelRow.tsx
  client/packages/programs/src/JsonForms/common/components/Text.tsx
  client/packages/system/src/Clinician/CreateClinicianForm.tsx
  client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json
  client/packages/system/src/Patient/CreatePatientModal/PatientFormTab.tsx
Labels: Team Ruru 🦉, Severity: High

#8436 8025 show auto allocation error reasons
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/line/useOutboundAllocate.test.ts
  client/packages/invoices/src/OutboundShipment/api/hooks/line/useOutboundAllocateSelectedLines.ts
  client/packages/invoices/src/OutboundShipment/api/operations.generated.ts
  client/packages/invoices/src/OutboundShipment/api/operations.graphql
Labels: Priority: Must Have, Team Ruru 🦉

#8456 8345 make the confirm finalise button in requisitions smaller users are complaining clicking it and making errors
  client/packages/common/src/ui/components/buttons/standard/SplitButton.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/Footer.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/StatusChangeButton.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/Footer/useCreateShipment.ts
  client/packages/requisitions/src/utils.ts
Labels: Team Ruru 🦉, Severity: High, docs: external, area: requisition

#8461 8460 catch print report errors
  client/packages/system/src/Report/components/ReportSelector.tsx
Labels: Team Ruru 🦉, Severity: Hotfix

#8472 8042 UI tweaks Part 1
  client/packages/common/src/utils/environment/EnvUtils.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/utils.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/AllocationSection.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditForm.tsx
  client/packages/system/src/Name/Components/DonorSearchInput/DonorSelectColumn.tsx
Labels: Priority: Must Have, Team Ruru 🦉, UI tweaks

#8469 8335 json forms dynamic gender component
  client/packages/programs/src/JsonForms/common/components/Select.tsx
  client/packages/programs/src/JsonForms/common/components/tests/Select.test.tsx
  client/packages/system/src/Patient/CreatePatientModal/DefaultCreatePatientUISchema.json
  client/packages/system/src/Patient/PatientView/DefaultPatientUISchema.json
Labels: enhancement, feature: programs, Priority: Should Have, Team Ruru 🦉, feature: dispensing

#8422 gh action integrate rc to develop
  .github/scripts/create-nightly-tags.sh
  .github/scripts/integrate-rc-to-develop.sh
  .github/scripts/mac_backblaze_upload.sh
  .github/scripts/send-telegram-notification.py
  .github/scripts/send-telegram-notification.sh
  .github/scripts/sort-json.sh
  .github/workflows/build-android-apk.yaml
  .github/workflows/integrate-rc-to-develop.yaml
  .github/workflows/nightly-automated-builds.yaml
  .github/workflows/send-telegram-notification.sh
  .github/workflows/sort-json.yaml
Labels: Build Tested: Dev

#8464 8457 cant delete inbound shipment batches
  client/packages/invoices/src/InboundShipment/api/hooks/line/useDeleteSelectedLines.ts
  client/packages/invoices/src/InboundShipment/api/hooks/mapErrorToMessageAndSetContext.ts
  client/packages/invoices/src/InboundShipment/api/hooks/useDraftInboundLines.tsx
Labels: Team Ruru 🦉, Severity: High

#8455 8453 excel exports are invalid files on android
  client/packages/android/app/src/main/java/org/openmsupply/client/FileManager.java
  client/packages/android/app/src/main/java/org/openmsupply/client/MainActivity.java
  client/packages/android/app/src/main/java/org/openmsupply/client/NativeApi.java
  client/packages/common/src/hooks/useNativeClient/types.ts
  client/packages/common/src/utils/files/FileUtils.ts
Labels: Team Ruru 🦉, Severity: High, feature: reports

#8400 Column header
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/es/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/intl/locales/pt/common.json
  client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
  client/packages/invoices/src/InboundShipment/DetailView/AddButton.tsx
  client/packages/purchase_orders/src/DetailView/AppBarButtons/AddFromMasterListButton.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddButton.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddFromMasterListButton.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AddFromMasterListModal.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/AppBarButtons/AppBarButtons.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/OrderInfoSection.tsx
  client/packages/requisitions/src/RequestRequisition/DetailView/Toolbar/Toolbar.tsx
Labels: Priority: Should Have, Team Ruru 🦉, UI tweaks, table: alignment

#8477 8476 update dependencies
  client/packages/common/package.json
  client/packages/common/src/ui/components/inputs/TextInput/DeprecatedBasicTextInput.tsx
  client/packages/common/src/ui/components/inputs/TextInput/index.ts
  client/packages/common/tsconfig.json
  client/packages/programs/src/JsonForms/common/components/tests/Select.test.tsx
  client/yarn.lock
  server/Cargo.lock
  server/Cargo.toml
  server/android/Cargo.toml
  server/cli/Cargo.toml
  server/cli/src/test_connection.rs
  server/repository/Cargo.toml
  server/server/src/certs.rs
  server/service/Cargo.toml
  server/service/src/report/html_printing.rs
  server/windows/Cargo.toml
Labels: enhancement, Team Ruru 🦉

#8473 7743 prescription detail view is grouping by item and shouldn't
  client/packages/invoices/src/Prescriptions/DetailView/ContentArea.tsx
  client/packages/invoices/src/Prescriptions/DetailView/DetailView.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Footer/Footer.tsx
  client/packages/invoices/src/Prescriptions/DetailView/Toolbar.tsx
  client/packages/invoices/src/Prescriptions/DetailView/columns.ts
  client/packages/invoices/src/Prescriptions/api/hooks/usePrescription.ts
Labels: enhancement, Team Ruru 🦉, feature: dispensing, docs: external

#8480 8441 clinician gender sync fix
  server/repository/src/db_diesel/name_row.rs
  server/repository/src/migrations/v2_09_00/mod.rs
  server/repository/src/migrations/v2_09_00/reintegrate_clinician_gender.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/sync_serde.rs
  server/service/src/sync/test/test_data/clinician.rs
  server/service/src/sync/translations/clinician.rs
Labels: Team Ruru 🦉, feature: dispensing, Effort: Small, Bug: development

#8388 8109 contact tab
  .github/workflows/generate-schema.yml
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Name/SupplierDetailView/Contacts.tsx
  client/packages/system/src/Name/SupplierDetailView/SupplierDetailView.tsx
  client/packages/system/src/Name/apiModern/hooks/index.ts
  client/packages/system/src/Name/apiModern/hooks/keys.ts
  client/packages/system/src/Name/apiModern/hooks/useContacts.ts
  client/packages/system/src/Name/apiModern/index.ts
  client/packages/system/src/Name/apiModern/operations.generated.ts
  client/packages/system/src/Name/apiModern/operations.graphql
  client/packages/system/src/Name/apiModern/useContactsGraphQL.ts
  package.json
  server/Cargo.lock
  server/graphql/Cargo.toml
  server/graphql/contact/Cargo.toml
  server/graphql/contact/src/lib.rs
  server/graphql/contact/src/query.rs
  server/graphql/contact/src/types/contact.rs
  server/graphql/contact/src/types/mod.rs
  server/graphql/lib.rs
  server/repository/src/db_diesel/contact_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_10_00/add_contact_table.rs
  server/repository/src/migrations/v2_10_00/mod.rs
  server/service/src/auth.rs
  server/service/src/contact/mod.rs
  server/service/src/contact/query.rs
  server/service/src/lib.rs
  server/service/src/service_provider.rs
  server/service/src/sync/test/test_data/contact.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/contact.rs
  server/service/src/sync/translations/mod.rs
Labels: enhancement, Team Piwakawaka, Purchase Orders

#8437 Remove disabled option from report selector
  client/packages/invoices/src/Prescriptions/DetailView/AppBarButton.tsx
  client/packages/system/src/Patient/PatientView/AppBarButtons.tsx
  client/packages/system/src/Report/components/ReportSelector.tsx
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
Labels: Severity: High

#8502 8497 Internal Orders: Doses shouldn't be displayed for MOS
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/ModalContentPanels.ts
  client/packages/requisitions/src/RequestRequisition/DetailView/RequestLineEdit/RequestLineEdit.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ContentLayout.tsx
  client/packages/requisitions/src/ResponseRequisition/DetailView/ResponseLineEdit/ResponseLineEdit.tsx
Labels: Team Ruru 🦉, Severity: Normal, feature: vaccine, area: internal order

#8508 8487 VVM status set to first status level by default on an Inbound Shipment
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/utils.tsx
  client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusInputCell.tsx
  client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusSearchInput.tsx
Labels: enhancement, Team Ruru 🦉, feature: vaccine

#8488 8384 mark stock lines with unusable vvm status
  client/packages/common/src/ui/layout/tables/components/Cells/VvmStatusCell/VvmStatusCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/VvmStatusCell/index.ts
  client/packages/common/src/ui/layout/tables/components/Cells/index.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/OutboundLineEditTable.tsx
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEditTable.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/columns.tsx
  client/packages/invoices/src/useDisableVvmRows.tsx
Labels: enhancement, Team Piwakawaka, UI tweaks, area: outbound shipment, area: vvm status, area: prescription

#8523 5061 custom translations configure pref
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/system/src/Manage/Preferences/EditPage/EditPreference.tsx
  server/Cargo.lock
  server/graphql/preference/Cargo.toml
  server/graphql/preference/src/upsert.rs
  server/graphql/types/src/types/preferences.rs
  server/service/src/localisations.rs
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/custom_translations.rs
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/types.rs
  server/service/src/preference/upsert.rs
Labels: enhancement, Team Ruru 🦉, Severity: High, feature: translation

#8516 8415 improve report excel export performance
  server/service/src/report/convert_to_excel.rs
Labels: Team Ruru 🦉, Severity: High, Needs Investigation

#8459 7841 cannot verify inbound shipment with lines with 0 quantity
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/InboundShipment/DetailView/ContentArea/columns.ts
  client/packages/invoices/src/InboundShipment/DetailView/DetailView.tsx
  client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.test.ts
  client/packages/invoices/src/InboundShipment/DetailView/Footer/StatusChangeButton.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/InboundLineEdit.tsx
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/utils.test.ts
  client/packages/invoices/src/utils.ts
  server/graphql/logger.rs
  server/service/src/invoice/inbound_shipment/update/generate.rs
  server/service/src/invoice/inbound_shipment/update/mod.rs
Labels: Team Ruru 🦉, Severity: Normal, area: inbound shipment

#8511 8489 doses in stock
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/domain/Dashboard/StatsPanel.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/UnitsAndDoses.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/index.ts
  client/packages/common/src/utils/quantities/quantities.test.ts
  client/packages/common/src/utils/quantities/quantities.ts
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/columns.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/columnsDoses.tsx
  client/packages/invoices/src/StockOut/utils.ts
  client/packages/system/src/Item/DetailView/Toolbar/Statistics.tsx
  client/packages/system/src/Item/ListView/ListView.tsx
  client/packages/system/src/Stock/Components/NewStockLineModal.tsx
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/DetailView/DetailView.tsx
  client/packages/system/src/Stock/ListView/ListView.tsx
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
  client/packages/system/src/Stock/api/hooks/useStockList.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
Labels: enhancement, Team Ruru 🦉, feature: vaccine

#8554 Add Clinician to encounters
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
  client/packages/system/src/Patient/Encounter/CreateEncounterForm.tsx
Labels: Team Ruru 🦉, Severity: High

#8350 Add navigate to encounter tab
  client/packages/system/src/Encounter/DetailView/SidePanel.tsx
Labels: bug, feature: programs, Severity: Normal, UI tweaks

#8509 #8505 Add "Enrolment info" button to Encounter
  client/packages/common/src/intl/locales/en/common.json
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
Labels: enhancement, Priority: Should Have, Team Piwakawaka

#8572 5061 invalidate translations on update
  client/packages/common/src/intl/README.md
  client/packages/common/src/intl/context/IntlContext.tsx
  client/packages/common/src/intl/strings/IntlStrings.ts
  client/packages/host/src/components/Sync/SyncModal.tsx
  client/packages/system/src/Manage/Preferences/EditPage/EditPreference.tsx
  client/packages/system/src/Name/ListView/Stores/EditStorePreferences.tsx
Labels: enhancement, Team Ruru 🦉, Severity: High, feature: translation

#8582 Tweak purchase order columns and add derived delivery status
  client/packages/common/src/intl/locales/en/common.json
  client/packages/host/src/components/Navigation/ReplenishmentNav.tsx
  client/packages/purchase_orders/src/ListView/ListView.tsx
  client/packages/purchase_orders/src/api/operations.generated.ts
  client/packages/purchase_orders/src/api/operations.graphql
  client/packages/purchase_orders/src/utils.ts
Labels: Team Piwakawaka, Purchase Orders

#8558 8520 delete draft rnr
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RnRForms/DetailView/SidePanel.tsx
  client/packages/requisitions/src/RnRForms/ListView/Footer.tsx
  client/packages/requisitions/src/RnRForms/ListView/ListView.tsx
  client/packages/requisitions/src/RnRForms/api/hooks/useDeleteRnRForm.ts
  client/packages/requisitions/src/RnRForms/api/operations.generated.ts
  client/packages/requisitions/src/RnRForms/api/operations.graphql
  server/graphql/programs/src/lib.rs
  server/graphql/programs/src/mutations/rnr_form/delete.rs
  server/graphql/programs/src/mutations/rnr_form/mod.rs
  server/graphql/types/src/types/activity_log.rs
  server/repository/src/db_diesel/activity_log_row.rs
  server/repository/src/db_diesel/rnr_form_line_row.rs
  server/repository/src/db_diesel/rnr_form_row.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_09_01/add_delete_rnr_form_activity_log_enum.rs
  server/repository/src/migrations/v2_09_01/mod.rs
  server/service/src/rnr_form/delete.rs
  server/service/src/rnr_form/mod.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/rnr_form.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
  server/service/src/sync/translations/rnr_form.rs
  server/service/src/sync/translations/rnr_form_line.rs
Labels: enhancement, Team Ruru 🦉, feature: R&R

#8585 Assign label and milestone
  .github/scripts/get_team_assign_label_milestone.py
  .github/workflows/get_team_assign_label_milestone.yaml
Labels: Build Tested: Dev, Team Ruru 🦉, Tooling

#8583 Git ignore config files
  .gitignore
  client/packages/android/.gitignore
  client/packages/android/README.MD
  client/packages/android/app/src/main/assets/capacitor.config.json
  client/packages/android/capacitor.config.local.example.json
  client/packages/android/capacitor.config.ts
  client/packages/android/package.json
  server/cli/src/report_utils.rs
  standard_reports/.gitignore
  standard_reports/README.md
  standard_reports/test-config.example.json
  standard_reports/test-config.json
Labels: Build Tested: Dev, Team Ruru 🦉, Tooling

#8609 8007 can't select vvm status when adding new stock line
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/Components/StyledInputRow.tsx
  client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusInputCell.tsx
  client/packages/system/src/Stock/Components/VVMStatusSearchInput/VVMStatusSearchInput.tsx
  client/packages/system/src/Stock/api/hooks/useStockLine.ts
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/insert.rs
Labels: enhancement, Priority: Should Have, Team Ruru 🦉, needs design, feature: vaccine, area: vvm status

#8110 8092 add purchase order permissions
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  server/graphql/types/src/types/permissions.rs
  server/repository/src/db_diesel/user_permission_row.rs
  server/repository/src/migrations/v2_10_00/add_purchase_order_permission_enum_values.rs
  server/repository/src/migrations/v2_10_00/mod.rs
  server/service/src/login.rs
Labels: Team Piwakawaka, Purchase Orders

#8618 6139 stocktake page performance improvement
  client/packages/common/src/ui/layout/tables/DataTable.tsx
  client/packages/inventory/src/Stocktake/DetailView/ContentArea/ContentArea.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
Labels: bug, Team Ruru 🦉, Severity: Normal, Needs Investigation, UI tweaks

#8622 5061 custom translation overrides pt2
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/layout/tables/components/Cells/TextInputCell/TextInputCell.tsx
  client/packages/common/src/ui/layout/tables/components/Cells/TooltipTextCell/TooltipTextCell.tsx
  client/packages/common/src/ui/layout/tables/components/DataRow/CellContentWrapper.tsx
  client/packages/system/src/Manage/Preferences/Components/CustomTranslations/CustomTranslationsModal.tsx
  client/packages/system/src/Manage/Preferences/Components/CustomTranslations/TranslationSearchInput.tsx
  client/packages/system/src/Manage/Preferences/Components/CustomTranslations/TranslationsInputTable.tsx
  client/packages/system/src/Manage/Preferences/Components/CustomTranslations/helpers.test.ts
  client/packages/system/src/Manage/Preferences/Components/CustomTranslations/helpers.ts
Labels: enhancement, Team Ruru 🦉, Severity: High, docs: external, feature: translation

#8617 8584 store specific item properties
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/inputs/CurrencyInput/CurrencyInput.tsx
  client/packages/system/src/Item/DetailView/DetailView.tsx
  client/packages/system/src/Item/DetailView/Tabs/General.tsx
  client/packages/system/src/Item/DetailView/Tabs/Store.tsx
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  server/graphql/core/src/loader/item_store_join.rs
  server/graphql/core/src/loader/loader_registry.rs
  server/graphql/core/src/loader/mod.rs
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/item_store_join.rs
  server/graphql/types/src/types/mod.rs
  server/repository/src/db_diesel/item_store_join.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_10_00/add_item_store_join.rs
  server/repository/src/migrations/v2_10_00/mod.rs
  server/repository/src/mock/item_store_join.rs
  server/repository/src/mock/mod.rs
  server/service/src/sync/test/test_data/item_store_join.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/item_store_join.rs
  server/service/src/sync/translations/mod.rs
Labels: enhancement, Team Ruru 🦉, docs: external

#8550 8504 map rnr fields values to requisition line fields
  server/repository/src/db_diesel/rnr_form_line.rs
  server/service/src/rnr_form/finalise.rs
  server/service/src/sync/settings.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/requisition_line.rs
  server/service/src/sync/test/test_data/rnr_form_line.rs
  server/service/src/sync/translations/requisition_line.rs
Labels: enhancement, feature: R&R, area: remote authorisation

#8269 8123 add purchase order and line sync
  client/packages/common/src/types/schema.ts
  client/packages/purchase_orders/src/api/operations.generated.ts
  client/packages/purchase_orders/src/api/operations.graphql
  client/packages/system/src/Name/apiModern/operations.generated.ts
  client/packages/system/src/Name/apiModern/operations.graphql
  server/cli/src/refresh_dates.rs
  server/graphql/purchase_order/src/purchase_order_queries.rs
  server/graphql/purchase_order_line/src/purchase_order_line_queries.rs
  server/graphql/types/src/types/purchase_order.rs
  server/graphql/types/src/types/purchase_order_line.rs
  server/repository/src/db_diesel/purchase_order.rs
  server/repository/src/db_diesel/purchase_order_line.rs
  server/repository/src/db_diesel/purchase_order_line_row.rs
  server/repository/src/db_diesel/purchase_order_row.rs
  server/repository/src/migrations/v2_10_00/add_purchase_order_tables.rs
  server/repository/src/mock/mod.rs
  server/repository/src/mock/name.rs
  server/repository/src/mock/purchase_order.rs
  server/repository/src/mock/purchase_order_line.rs
  server/service/src/purchase_order/insert/generate.rs
  server/service/src/purchase_order/insert/test.rs
  server/service/src/purchase_order/query.rs
  server/service/src/purchase_order_line/query.rs
  server/service/src/sync/mod.rs
  server/service/src/sync/sync_utils.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/test/test_data/purchase_order.rs
  server/service/src/sync/test/test_data/purchase_order_line.rs
  server/service/src/sync/translations/mod.rs
  server/service/src/sync/translations/name.rs
  server/service/src/sync/translations/purchase_order.rs
  server/service/src/sync/translations/purchase_order_line.rs
  server/util/src/sync_serde.rs
Labels: Team Piwakawaka, Purchase Orders

#8629 8624 Add permission mapping to resource
  server/graphql/purchase_order/src/mutations/insert.rs
  server/graphql/purchase_order/src/purchase_order_queries.rs
  server/graphql/purchase_order_line/src/purchase_order_line_queries.rs
  server/service/src/auth.rs
Labels: enhancement, Team Piwakawaka

#8628 8593 move edit into store popper & move packaging level from gaps initialisation
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/ui/components/inputs/PropertyInput/PropertyInput.tsx
  client/packages/host/src/components/Footer/Footer.tsx
  client/packages/host/src/components/Footer/StoreSelector.tsx
  client/packages/system/src/Name/ListView/Stores/EditStorePreferences.tsx
  client/packages/system/src/Name/ListView/Stores/StoreProperties.tsx
  server/graphql/preference/src/lib.rs
  server/repository/src/migrations/v2_10_00/add_supply_level_to_name_properties.rs
  server/repository/src/migrations/v2_10_00/mod.rs
  server/service/src/auth.rs
Labels: enhancement, Team Ruru 🦉, docs: external, feature: preferences, area: stock

#8521 8490 insert lines back end mutations
  client/packages/common/src/types/schema.ts
  client/packages/purchase_orders/src/DetailView/ContentArea.tsx
  client/packages/purchase_orders/src/DetailView/columns.ts
  client/packages/purchase_orders/src/ListView/ListView.tsx
  client/packages/purchase_orders/src/api/operations.generated.ts
  client/packages/purchase_orders/src/api/operations.graphql
  client/packages/system/src/Name/SupplierDetailView/PurchaseOrder.tsx
  server/graphql/invoice/src/lib.rs
  server/graphql/lib.rs
  server/graphql/purchase_order_line/src/lib.rs
  server/graphql/purchase_order_line/src/mutations/insert.rs
  server/graphql/purchase_order_line/src/mutations/mod.rs
  server/repository/src/db_diesel/number_row.rs
  server/repository/src/db_diesel/purchase_order_line_row.rs
  server/repository/src/migrations/v2_10_00/delete_unused_number_type.rs
  server/repository/src/migrations/v2_10_00/mod.rs
  server/service/src/number.rs
  server/service/src/purchase_order_line/insert/generate.rs
  server/service/src/purchase_order_line/insert/mod.rs
  server/service/src/purchase_order_line/insert/test.rs
  server/service/src/purchase_order_line/insert/validate.rs
  server/service/src/purchase_order_line/mod.rs
Labels: Team Piwakawaka, Purchase Orders

#8652 #8634 Sync badge updates
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/components/navigation/AppNavLink/AppNavLink.tsx
  client/packages/host/src/components/AppDrawer/SyncNavLink.tsx
  client/packages/system/src/Manage/Preferences/EditPage/EditPreference.tsx
  server/graphql/preference/src/upsert.rs
  server/graphql/types/src/types/preferences.rs
  server/service/src/preference/mod.rs
  server/service/src/preference/preferences/mod.rs
  server/service/src/preference/preferences/sync_records_display_threshold.rs
  server/service/src/preference/types.rs
  server/service/src/preference/upsert.rs
Labels: sync, Priority: Must Have, Team Piwakawaka

#8643 8640 & 8641 rnr default values not on internal order
  server/service/src/rnr_form/finalise.rs
  server/service/src/rnr_form/tests/finalise.rs
Labels: Team Ruru 🦉, Severity: Hotfix, Severity: High

#8621 8589 record default sell price on incoming / introduced stock
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/utils.ts
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/inventory/src/Stocktake/api/operations.graphql
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/utils.ts
  client/packages/invoices/src/InboundShipment/api/hooks/useDraftInboundLines.tsx
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/system/src/Item/Components/ServiceItemSearchInput/ServiceItemSearchInput.tsx
  client/packages/system/src/Item/Components/StockItemSearchInput/StockItemSearchInput.tsx
  client/packages/system/src/Item/DetailView/Tabs/Store.tsx
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Stock/Components/NewStockLineModal.tsx
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/item_store_join.rs
  server/repository/src/db_diesel/item_store_join.rs
  server/repository/src/mock/mod.rs
  server/service/src/processors/general_processor.rs
  server/service/src/processors/transfer/invoice/common.rs
  server/service/src/processors/transfer/invoice/create_inbound_invoice.rs
  server/service/src/processors/transfer/invoice/test.rs
  server/service/src/processors/transfer/invoice/update_inbound_invoice.rs
Labels: enhancement, Team Ruru 🦉, docs: external, area: inbound shipment, area: stock, area: stocktake

#8660 8623 query programs by item
  client/packages/common/src/types/schema.ts
  server/graphql/programs/src/types/program.rs
  server/repository/src/db_diesel/program_requisition/program.rs
  server/repository/src/db_diesel/program_requisition/program_row.rs
Labels: enhancement, feature: programs, Team Ruru 🦉, area: campaign

#8650 8552 Assign location type to an item - part 1
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/types/schema.ts
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEdit.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/utils.ts
  client/packages/inventory/src/Stocktake/api/operations.generated.ts
  client/packages/inventory/src/Stocktake/api/operations.graphql
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabLayout.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/system/src/Item/Components/LocationTypeInput/LocationTypeInput.tsx
  client/packages/system/src/Item/DetailView/Tabs/General.tsx
  client/packages/system/src/Item/api/operations.generated.ts
  client/packages/system/src/Item/api/operations.graphql
  client/packages/system/src/Item/utils.ts
  client/packages/system/src/Location/Components/LocationInputColumn.tsx
  client/packages/system/src/Location/Components/LocationSearchInput.tsx
  client/packages/system/src/Stock/Components/Repack/RepackEditForm.tsx
  client/packages/system/src/Stock/Components/Repack/RepackModal.tsx
  client/packages/system/src/Stock/Components/StockLineForm.tsx
  client/packages/system/src/Stock/api/operations.generated.ts
  client/packages/system/src/Stock/api/operations.graphql
  client/packages/system/src/Stock/types.ts
  server/graphql/types/src/types/item.rs
  server/graphql/types/src/types/location.rs
  server/repository/src/db_diesel/item_row.rs
  server/repository/src/db_diesel/location.rs
  server/repository/src/migrations/v2_10_00/add_restricted_location_type_id_to_item.rs
  server/repository/src/migrations/v2_10_00/mod.rs
  server/service/src/sync/test/test_data/item.rs
  server/service/src/sync/translations/item.rs
Labels: enhancement, Team Ruru 🦉, docs: external, area: location

#8607 8522 rnr skip periods
  client/packages/common/src/types/schema.ts
  client/packages/requisitions/src/RnRForms/ListView/RnRFormCreateModal.tsx
  client/packages/requisitions/src/RnRForms/api/operations.generated.ts
  client/packages/requisitions/src/RnRForms/api/operations.graphql
  server/cli/src/load_test.rs
  server/graphql/programs/src/mutations/rnr_form/insert.rs
  server/graphql/types/src/types/program/rnr_form.rs
  server/repository/src/migrations/v2_09_01/mod.rs
  server/repository/src/migrations/v2_09_01/remove_rnr_form_line_entered_losses_default.rs
  server/repository/src/mock/period_and_period_schedule.rs
  server/repository/src/mock/rnr_form.rs
  server/service/src/report/convert_to_excel.rs
  server/service/src/rnr_form/generate_rnr_form_lines.rs
  server/service/src/rnr_form/insert.rs
  server/service/src/rnr_form/tests/generate_rnr_form_lines.rs
  server/service/src/rnr_form/tests/insert.rs
  server/service/src/rnr_form/tests/schedules_with_periods.rs
Labels: enhancement, Team Ruru 🦉, docs: external, feature: R&R

#8683 8682 inbound shipment swap shipped and received columns
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
Labels: Team Ruru 🦉, docs: external

#8680 #8537 JSON Forms DatePicker "OK" button fix
  client/packages/programs/src/JsonForms/common/components/Date.tsx
  client/packages/programs/src/JsonForms/common/components/DateTime.tsx
Labels: platform: android, Team Piwakawaka, feature: dispensing, UI tweaks, area: date picker

#8666 DJI Family planning customisations to 2.9.1
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr-DJ/common.json
  client/packages/programs/src/JsonForms/common/JsonForm.tsx
  client/packages/programs/src/JsonForms/common/components/Array/common.tsx
  client/packages/programs/src/JsonForms/common/components/Select.tsx
  client/packages/programs/src/JsonForms/common/components/Text.tsx
  client/packages/programs/src/JsonForms/common/hooks/usePrevious.tsx
  client/packages/programs/src/JsonForms/common/utilityComponents/PreviousValueDisplay.tsx
  client/packages/programs/src/JsonForms/common/utilityComponents/index.ts
  client/packages/programs/src/JsonForms/components/DateOfBirth.tsx
  client/packages/programs/src/JsonForms/components/PreviousEncounterField.tsx
  client/packages/programs/src/JsonForms/components/index.ts
  client/packages/programs/src/JsonForms/useJsonFormsHandler.tsx
  client/packages/programs/src/JsonForms/usePreviousEncounter.tsx
  client/packages/programs/src/api/operations.generated.ts
  client/packages/programs/src/api/operations.graphql
  client/packages/system/src/Encounter/DetailView/DetailView.tsx
  client/packages/system/src/Encounter/DetailView/Toolbar.tsx
  client/packages/system/src/Patient/ProgramEnrolment/Components/DetailModal.tsx
Labels: enhancement, Priority: Should Have, Team Piwakawaka

#8687 8668 auto allocate placeholders on open
  client/packages/common/src/intl/locales/en/common.json
  client/packages/invoices/src/OutboundShipment/DetailView/OutboundLineEdit/Allocation.tsx
  client/packages/invoices/src/Prescriptions/LineEditView/PrescriptionLineEdit.tsx
  client/packages/invoices/src/StockOut/Components/AllocateInSelector.tsx
  client/packages/invoices/src/StockOut/useAllocationContext.ts
  client/packages/invoices/src/StockOut/utils.test.ts
  client/packages/invoices/src/StockOut/utils.ts
Labels: Team Ruru 🦉, Severity: High, area: outbound shipment

#8620 8042 pt 4
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/ui/components/inputs/Autocomplete/AutocompleteWithPagination.tsx
  client/packages/common/src/ui/layout/tables/DataTable.tsx
  client/packages/common/src/ui/layout/tables/components/Header/Header.tsx
  client/packages/common/src/ui/layout/tables/types.ts
  client/packages/inventory/src/Stocktake/DetailView/ReduceLinesToZeroModal.tsx
  client/packages/inventory/src/Stocktake/DetailView/modal/StocktakeLineEdit/StocktakeLineEditTables.tsx
  client/packages/system/src/Item/Components/StockItemSearchInputWithStats/StockItemSearchInputWithStats.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/BundledItemVariants.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemPackagingVariantsTable.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantForm.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantModal.tsx
  client/packages/system/src/Item/DetailView/Tabs/ItemVariants/ItemVariantsTab.tsx
  client/packages/system/src/ReasonOption/Components/ReasonOptionsSearchInput.tsx
Labels: Priority: Must Have, Team Ruru 🦉, UI tweaks

#8542 Fix vaccine card returns that were over-ridding stock and packsize
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/vaccination/insert/mod.rs
  server/service/src/vaccination/update/generate.rs
  server/service/src/vaccination/update/mod.rs
  server/service/src/vaccination/update/validate.rs
Labels: Team Piwakawaka, Severity: Hotfix, Severity: High

#8631 8124 goods recieving table
  server/cli/src/refresh_dates.rs
  server/repository/src/db_diesel/changelog/changelog.rs
  server/repository/src/db_diesel/goods_received_row.rs
  server/repository/src/db_diesel/mod.rs
  server/repository/src/migrations/v2_10_00/add_goods_received_table.rs
  server/repository/src/migrations/v2_10_00/mod.rs
  server/service/src/sync/test/pull_and_push.rs
  server/service/src/sync/test/test_data/goods_received.rs
  server/service/src/sync/test/test_data/mod.rs
  server/service/src/sync/translations/goods_received.rs
  server/service/src/sync/translations/mod.rs
Labels: Team Piwakawaka, Purchase Orders

#8697 8685 shipment add invoiced pack size
  client/packages/common/src/intl/locales/en/common.json
  client/packages/common/src/intl/locales/fr/common.json
  client/packages/common/src/types/schema.ts
  client/packages/common/src/ui/layout/tables/utils/ColumnDefinitionSetBuilder.ts
  client/packages/invoices/src/InboundShipment/DetailView/modals/InboundLineEdit/TabTables.tsx
  client/packages/invoices/src/InboundShipment/DetailView/modals/utils.ts
  client/packages/invoices/src/InboundShipment/api/api.ts
  client/packages/invoices/src/InboundShipment/api/operations.generated.ts
  client/packages/invoices/src/InboundShipment/api/operations.graphql
  client/packages/requisitions/src/RnRForms/api/operations.generated.ts
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/insert.rs
  server/graphql/invoice_line/src/mutations/inbound_shipment_line/line/update.rs
  server/graphql/invoice_line/src/mutations/outbound_shipment_line/line/update.rs
  server/graphql/types/src/types/invoice_line.rs
  server/repository/src/db_diesel/invoice_line_row.rs
  server/repository/src/migrations/mod.rs
  server/repository/src/migrations/v2_09_01/add_invoice_line_shipped_pack_size.rs
  server/repository/src/migrations/v2_09_01/invoice_line_shipped_pack_size_sync_buffer.rs
  server/repository/src/migrations/v2_09_01/mod.rs
  server/repository/src/mock/invoice_line.rs
  server/repository/src/test_db/mod.rs
  server/service/src/invoice/customer_return/insert/generate.rs
  server/service/src/invoice/customer_return/update_lines/generate.rs
  server/service/src/invoice/inbound_shipment/generate.rs
  server/service/src/invoice/inventory_adjustment/add_new_stock_line/generate.rs
  server/service/src/invoice/inventory_adjustment/adjust_existing_stock/generate.rs
  server/service/src/invoice/outbound_shipment/generate.rs
  server/service/src/invoice/prescription/update/mod.rs
  server/service/src/invoice_line/inbound_shipment_from_internal_order_lines/generate.rs
  server/service/src/invoice_line/inbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_service_line/insert/generate.rs
  server/service/src/invoice_line/outbound_shipment_unallocated_line/insert.rs
  server/service/src/invoice_line/stock_in_line/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/generate.rs
  server/service/src/invoice_line/stock_in_line/insert/mod.rs
  server/service/src/invoice_line/stock_in_line/update/generate.rs
  server/service/src/invoice_line/stock_in_line/update/mod.rs
  server/service/src/invoice_line/stock_out_line/insert/generate.rs
  server/service/src/invoice_line/stock_out_line/set_prescribed_quantity/generate.rs
  server/service/src/invoice_line/stock_out_line/update/generate.rs
  server/service/src/processors/transfer/invoice/common.rs
  server/service/src/requisition/response_requisition/create_requisition_shipment/generate.rs
  server/service/src/stocktake/update/generate.rs
  server/service/src/sync/test/test_data/invoice_line.rs
  server/service/src/sync/translations/invoice_line.rs
Labels: enhancement, Team Ruru 🦉, docs: external, area: outbound shipment, area: inbound shipment
